/* Generated from scripts/_course-labels.cjs. */
window.CourseStrings={
  "en": {
    "toc": "On this page",
    "browse": "Browse this section",
    "intro": "Read the lesson, then practise at your own pace. All explanations and examples are on this page.",
    "check": "Check answers",
    "reset": "Try again",
    "correct": "Correct.",
    "retry": "Review the answer below.",
    "missing": "Choose an answer first.",
    "score": "{correct} of {total} correct. {remaining} unanswered.",
    "answer": "Answer",
    "listen": "Listen",
    "vocabLink": "Open the vocabulary lesson",
    "toolIntro": "The complete word bank is in the vocabulary lesson. Use this tool to browse or practise saved words.",
    "skip": "Skip to content",
    "lesson": "Full lesson",
    "practice": "Practice",
    "topics": "Lesson topics",
    "build": "Build a syllable",
    "guides": "Study guides"
  },
  "ja": {
    "toc": "このページの内容",
    "browse": "この分野のページ",
    "intro": "解説と例文を読み、自分のペースで練習しましょう。教材はすべてこのページにあります。",
    "check": "解答を確認",
    "reset": "もう一度",
    "correct": "正解です。",
    "retry": "下の解答を確認してください。",
    "missing": "先に答えを選んでください。",
    "score": "{total}問中{correct}問正解。未回答：{remaining}問。",
    "answer": "解答",
    "listen": "聞く",
    "vocabLink": "語彙レッスンを開く",
    "toolIntro": "単語一覧は語彙レッスンにあります。このツールでは単語の閲覧や保存した単語の練習ができます。",
    "skip": "本文へ",
    "lesson": "レッスン全文",
    "practice": "練習",
    "topics": "学習項目",
    "build": "音節を組み立てる",
    "guides": "学習ガイド"
  },
  "zh-tw": {
    "toc": "本頁內容",
    "browse": "瀏覽此分類",
    "intro": "閱讀解說和例句，再依自己的步調練習。完整教材都在這一頁。",
    "check": "檢查答案",
    "reset": "再試一次",
    "correct": "答對了。",
    "retry": "請參考下方答案。",
    "missing": "請先選擇答案。",
    "score": "答對{correct}／{total}題。未作答：{remaining}題。",
    "answer": "答案",
    "listen": "聆聽",
    "vocabLink": "開啟詞彙課程",
    "toolIntro": "完整單字庫位於詞彙課程。此工具可瀏覽單字或練習已儲存的單字。",
    "skip": "跳至內容",
    "lesson": "完整課程",
    "practice": "練習",
    "topics": "學習主題",
    "build": "組合音節",
    "guides": "學習指南"
  },
  "es": {
    "toc": "En esta página",
    "browse": "Explorar esta sección",
    "intro": "Lee las explicaciones y los ejemplos, y practica a tu ritmo. Todo el material está en esta página.",
    "check": "Comprobar respuestas",
    "reset": "Intentar de nuevo",
    "correct": "Correcto.",
    "retry": "Revisa la respuesta de abajo.",
    "missing": "Elige primero una respuesta.",
    "score": "{correct} de {total} correctas. {remaining} sin responder.",
    "answer": "Respuesta",
    "listen": "Escuchar",
    "vocabLink": "Abrir la lección de vocabulario",
    "toolIntro": "El banco completo está en la lección de vocabulario. Esta herramienta permite explorar palabras o practicar las guardadas.",
    "skip": "Saltar al contenido",
    "lesson": "Lección completa",
    "practice": "Práctica",
    "topics": "Temas de estudio",
    "build": "Construir una sílaba",
    "guides": "Guías de estudio"
  },
  "fr": {
    "toc": "Sur cette page",
    "browse": "Explorer cette rubrique",
    "intro": "Lisez les explications et les exemples, puis pratiquez à votre rythme. Tout le cours est sur cette page.",
    "check": "Vérifier les réponses",
    "reset": "Réessayer",
    "correct": "Bonne réponse.",
    "retry": "Consultez la réponse ci-dessous.",
    "missing": "Choisissez d’abord une réponse.",
    "score": "{correct} bonnes réponses sur {total}. {remaining} sans réponse.",
    "answer": "Réponse",
    "listen": "Écouter",
    "vocabLink": "Ouvrir le cours de vocabulaire",
    "toolIntro": "La liste complète se trouve dans le cours de vocabulaire. Cet outil sert à parcourir les mots ou à pratiquer les mots enregistrés.",
    "skip": "Aller au contenu",
    "lesson": "Cours complet",
    "practice": "Exercices",
    "topics": "Sujets du cours",
    "build": "Construire une syllabe",
    "guides": "Guides d’étude"
  },
  "de": {
    "toc": "Auf dieser Seite",
    "browse": "Diesen Bereich durchsuchen",
    "intro": "Lies die Erklärungen und Beispiele und übe in deinem Tempo. Der gesamte Lernstoff steht auf dieser Seite.",
    "check": "Antworten prüfen",
    "reset": "Noch einmal",
    "correct": "Richtig.",
    "retry": "Sieh dir die Antwort unten an.",
    "missing": "Wähle zuerst eine Antwort.",
    "score": "{correct} von {total} richtig. {remaining} unbeantwortet.",
    "answer": "Antwort",
    "listen": "Anhören",
    "vocabLink": "Wortschatzlektion öffnen",
    "toolIntro": "Die vollständige Wortliste steht in der Wortschatzlektion. Mit diesem Werkzeug kannst du Wörter ansehen oder gespeicherte Wörter üben.",
    "skip": "Zum Inhalt",
    "lesson": "Ganze Lektion",
    "practice": "Übung",
    "topics": "Lektionsthemen",
    "build": "Eine Silbe bilden",
    "guides": "Lernhilfen"
  },
  "vi": {
    "toc": "Nội dung trang",
    "browse": "Xem các trang trong mục",
    "intro": "Đọc giải thích và ví dụ, rồi luyện theo nhịp độ của bạn. Toàn bộ nội dung nằm trên trang này.",
    "check": "Kiểm tra đáp án",
    "reset": "Thử lại",
    "correct": "Đúng.",
    "retry": "Xem đáp án bên dưới.",
    "missing": "Hãy chọn đáp án trước.",
    "score": "Đúng {correct}/{total}. Còn {remaining} câu chưa trả lời.",
    "answer": "Đáp án",
    "listen": "Nghe",
    "vocabLink": "Mở bài từ vựng",
    "toolIntro": "Toàn bộ kho từ nằm trong bài từ vựng. Công cụ này giúp xem từ hoặc luyện các từ đã lưu.",
    "skip": "Đến nội dung",
    "lesson": "Toàn bộ bài học",
    "practice": "Luyện tập",
    "topics": "Chủ đề bài học",
    "build": "Ghép âm tiết",
    "guides": "Hướng dẫn học"
  },
  "th": {
    "toc": "เนื้อหาในหน้านี้",
    "browse": "ดูหน้าในหมวดนี้",
    "intro": "อ่านคำอธิบายและตัวอย่าง แล้วฝึกตามจังหวะของคุณ เนื้อหาทั้งหมดอยู่ในหน้านี้",
    "check": "ตรวจคำตอบ",
    "reset": "ลองอีกครั้ง",
    "correct": "ถูกต้อง",
    "retry": "ดูคำตอบด้านล่าง",
    "missing": "เลือกคำตอบก่อน",
    "score": "ถูก {correct} จาก {total} ข้อ ยังไม่ตอบ {remaining} ข้อ",
    "answer": "คำตอบ",
    "listen": "ฟัง",
    "vocabLink": "เปิดบทเรียนคำศัพท์",
    "toolIntro": "คลังคำทั้งหมดอยู่ในบทเรียนคำศัพท์ ใช้เครื่องมือนี้ดูคำหรือฝึกคำที่บันทึกไว้",
    "skip": "ข้ามไปเนื้อหา",
    "lesson": "บทเรียนฉบับเต็ม",
    "practice": "ฝึกฝน",
    "topics": "หัวข้อบทเรียน",
    "build": "ประกอบพยางค์",
    "guides": "คู่มือการเรียน"
  },
  "id": {
    "toc": "Di halaman ini",
    "browse": "Jelajahi bagian ini",
    "intro": "Baca penjelasan dan contoh, lalu berlatih sesuai kecepatan Anda. Semua materi ada di halaman ini.",
    "check": "Periksa jawaban",
    "reset": "Coba lagi",
    "correct": "Benar.",
    "retry": "Lihat jawaban di bawah.",
    "missing": "Pilih jawaban terlebih dahulu.",
    "score": "{correct} dari {total} benar. {remaining} belum dijawab.",
    "answer": "Jawaban",
    "listen": "Dengarkan",
    "vocabLink": "Buka pelajaran kosakata",
    "toolIntro": "Bank kata lengkap ada di pelajaran kosakata. Gunakan alat ini untuk melihat kata atau melatih kata tersimpan.",
    "skip": "Ke konten",
    "lesson": "Pelajaran lengkap",
    "practice": "Latihan",
    "topics": "Topik pelajaran",
    "build": "Susun suku kata",
    "guides": "Panduan belajar"
  },
  "pt-br": {
    "toc": "Nesta página",
    "browse": "Explorar esta seção",
    "intro": "Leia as explicações e os exemplos e pratique no seu ritmo. Todo o material está nesta página.",
    "check": "Conferir respostas",
    "reset": "Tentar de novo",
    "correct": "Correto.",
    "retry": "Veja a resposta abaixo.",
    "missing": "Escolha uma resposta primeiro.",
    "score": "{correct} de {total} corretas. {remaining} sem resposta.",
    "answer": "Resposta",
    "listen": "Ouvir",
    "vocabLink": "Abrir a aula de vocabulário",
    "toolIntro": "O banco completo está na aula de vocabulário. Use esta ferramenta para ver palavras ou praticar as salvas.",
    "skip": "Ir para o conteúdo",
    "lesson": "Aula completa",
    "practice": "Prática",
    "topics": "Temas da aula",
    "build": "Montar uma sílaba",
    "guides": "Guias de estudo"
  }
};
