'use strict';
// Original teaching scenarios. Reference facts are linked at the point of use;
// neither the conversations nor the practice journeys are eyewitness accounts.
module.exports = ({section, table, question, practice, dictionary}) => [
  {
    slug:'restaurant-confidence', title:'Understand your first Korean restaurant visit', category:'Culture in practice', time:'15 minute study',
    description:'Read a Korean restaurant situation, distinguish shared side dishes from your own meal, and practise requests with explained answers and official references.',
    intro:'A restaurant visit combines language with small decisions: where to get water, how to ask for help, and what the dishes on the table are for. This guide gives you a flexible way to observe, ask, and respond. Its dialogue is a constructed learning example; it does not describe a restaurant we visited.',
    sections:[
      section('notice','Read the setting before choosing a phrase', '<p>Imagine entering a small restaurant with a friend. You see a water dispenser, a menu, and small dishes already on the table. Start by looking for instructions rather than assuming every restaurant works the same way. <span lang="ko">셀프</span> on a sign usually means that you serve yourself for the item named there. <span lang="ko">물은 셀프입니다</span> means “Water is self-service.” It does not mean you must collect your entire meal.</p><p>The Korea Tourism Organization describes both self-service arrangements and places where staff help diners in its <a href="https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=229195">restaurant introduction</a>. Use that as background, then follow the instructions at the actual restaurant. A bell may be provided to call staff; its presence is a useful cue, not a rule that every table has one.</p>'),
      section('table','Give the food and the words different jobs',table(['Word','Meaning here','A useful distinction'],[
        ['<span lang="ko">밥</span>','Cooked rice; also a meal in many expressions','<span lang="ko">밥 먹었어요?</span> asks whether someone has eaten, not necessarily whether they ate rice.'],
        ['<span lang="ko">반찬</span>','Side dishes accompanying a meal','The small dishes are not necessarily separate main orders for each person.'],
        ['<span lang="ko">국 / 찌개</span>','Soup / stew','Presentation and portions vary; check what you ordered rather than identifying the arrangement from its English name alone.'],
        ['<span lang="ko">추가</span>','An addition or extra order','Ask whether an extra item costs money rather than assuming that every extra is free.']
      ])+'<p>The <a href="https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=229195">official food introduction</a> explains 반찬 and the arrangement of a Korean meal. Our learning task is to use those distinctions: point to your rice, the shared items, and the main dish, then name each. If sharing is unclear, ask your companion or staff. Do not infer someone’s preferences from their nationality.</p>'),
      section('dialogue','Ask for one thing clearly',table(['Role','Korean','Meaning'],[
        ['Guest','<span lang="ko">저기요. 물 좀 주세요.</span>','Excuse me. Please give us some water.'],
        ['Staff','<span lang="ko">물은 셀프예요.</span>','Water is self-service.'],
        ['Guest','<span lang="ko">아, 네. 감사합니다.</span>','Oh, okay. Thank you.'],
        ['Guest, later','<span lang="ko">반찬을 더 받을 수 있어요?</span>','Could we have more side dishes?']
      ])+'<p><span lang="ko">주세요</span> makes a request. <span lang="ko">좀</span> literally relates to a small amount, but in a request like 물 좀 주세요 it can also soften the wording. It is not a substitute for a polite ending. <span lang="ko">더</span> means “more,” so 반찬을 더 받을 수 있어요? asks about an additional serving.</p><p>Now replace 물 with 냅킨 (“napkin”). Then replace the direct request with <span lang="ko">물은 어디에 있어요?</span> (“Where is the water?”). The second question fits a self-service setting better because you are asking for the location instead of asking staff to bring it. Both are learning patterns, not a guarantee of the reply you will hear.</p>'),
      section('repair','Handle a reply you did not expect','<p>If you miss an instruction, say <span lang="ko">다시 말해 주세요.</span> (“Please say it again.”). If the person points somewhere, you can confirm <span lang="ko">저기예요?</span> (“Is it over there?”). A brief clarification is more useful than guessing which counter or machine they mean.</p><p>For an extra order, <span lang="ko">추가하면 얼마예요?</span> means “How much is it if we add that?” Point to the item or name it first. This avoids assuming that a menu item and a side-dish refill follow the same pricing rule. Prices, refill policies, and payment procedures belong to the particular business.</p><p>Before finishing, <span lang="ko">계산은 어디에서 해요?</span> asks where to pay. After a meal, <span lang="ko">잘 먹었습니다.</span> expresses appreciation for the meal. It describes a completed meal; compare <span lang="ko">잘 먹겠습니다.</span> before eating. Neither phrase requires pretending you enjoyed something you did not want to eat.</p>'),
      section('practice','Choose a response for the setting',practice('restaurant',[
        question('restaurant-self','1. The sign says 물은 셀프입니다. What does it tell you?',['You collect your own water.','Every part of the meal is self-service.'],0,'물 names the item covered by the instruction. Do not extend that instruction to the whole meal.'),
        question('restaurant-location','2. You understand that water is self-service. Which question fits?',['물은 어디에 있어요?','잘 먹었습니다.'],0,'Ask where the water is. 잘 먹었습니다 expresses appreciation after eating.'),
        question('restaurant-price','3. You want an additional menu item, but do not know its price. What helps?',['Assume every extra is free.','Ask 추가하면 얼마예요?'],1,'An extra order can differ from a refill. Ask about this item before agreeing.'),
        question('restaurant-after','4. You have finished the meal. Which expression fits the time?',['잘 먹겠습니다.','잘 먹었습니다.'],1,'먹었습니다 refers to a completed action. 먹겠습니다 is the conventional before-meal expression.')
      ])+'<h3>Make it yours</h3><p>Write a three-line scene: ask where a self-service item is, confirm the location, and thank the staff. Tomorrow, change the item without looking at the model. Check whether you are asking for a thing or asking where that thing is.</p>'),
      section('sources','What the references support',`<p><a href="https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=229195">Korea Tourism Organization: About Korean Food</a> supports the background on side dishes, meal arrangements, and differing restaurant service systems. Accessed 2 October 2026. It is not a source for our constructed conversation and does not establish the policy of a specific restaurant.</p><p>Use ${dictionary} to look up <span lang="ko">반찬, 셀프, 추가, 계산, 더</span>. These are lookup resources for meanings and pronunciation, not a claim that a dictionary has endorsed this guide. Continue with <a href="/guides/order-at-a-cafe.html">café ordering</a> for quantities and <a href="/culture/kfood.html">the food overview</a> for more dishes.</p>`)
    ], related:['order-at-a-cafe','first-conversation','korean-numbers']
  },
  {
    slug:'subway-first-journey', title:'Plan and explain your first Seoul subway journey', category:'Travel in practice', time:'15 minute study',
    description:'Practise reading a subway journey, distinguishing a transfer from an exit, asking for help, and checking current information with official Seoul and tourism sources.',
    intro:'A station name is only one part of a useful journey plan. You also need the direction, any transfer, and the exit at the destination. This guide teaches a checking routine and a few Korean questions. It does not provide a live route, fare, timetable, or accessibility guarantee.',
    sections:[
      section('plan','Write a journey you can check','<p>Choose two stations for a practice trip. In a current journey planner, record the departure station, destination station, line or lines, transfer station if any, and destination exit. Check the direction shown for the platform against the next stations in the route. A line’s color is useful, but the line number and station names give you another way to confirm the route.</p><p>For example, a note might read “depart: [station A] → transfer: [station B] → arrive: [station C] → exit: 2.” The brackets deliberately leave the journey open: fill them from the route you actually checked. A static lesson cannot confirm the best route today, a last train, a closed exit, or whether an elevator is operating. Use the <a href="https://english.seoul.go.kr/policy/transportation/modes-of-transport/subway/">Seoul Metropolitan Government subway page</a> as an official starting point for network information.</p>'),
      section('signs','Separate three decisions',table(['Word on a sign','What it helps you decide','Question to ask yourself'],[
        ['<span lang="ko">방면</span>','Direction toward a named place','Does this platform go toward the stations in my route?'],
        ['<span lang="ko">환승</span>','Transfer to another service or line','Am I changing lines here, or leaving the station?'],
        ['<span lang="ko">출구</span>','An exit from the station','Which exit gets me closer to my destination outside?'],
        ['<span lang="ko">충전</span>','Adding stored value, in the card context','Do I need to top up this card before travelling?']
      ])+'<p>A destination and an exit are different pieces of information. <span lang="ko">서울역</span> identifies Seoul Station; <span lang="ko">2번 출구</span> identifies Exit 2. Reaching the correct station does not tell you which street you will emerge on. If you need step-free access, check an appropriate elevator route as a separate requirement rather than assuming the nearest exit works.</p>'),
      section('card','Understand what tapping is for','<p>Seoul’s <a href="https://english.seoul.go.kr/policy/transportation/modes-of-transport/subway/">official subway guidance</a> explains that its integrated fare calculation depends on tapping when boarding and leaving each mode of transport. Build the habit of following the entry and exit readers rather than assuming one tap covers the entire journey. A successful tap and the route you planned are separate checks: payment alone does not confirm that you chose the correct platform.</p><p>The Korea Tourism Organization’s <a href="https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140663">transportation-card guide</a> describes rechargeable cards and where they can be obtained. Before buying a card or pass, check its current coverage, recharge methods, and restrictions. A stored-value card and a time-limited pass are different products; this lesson does not select one for your budget. It intentionally avoids quoting a fare that may have changed.</p>'),
      section('dialogue','Ask a question that someone can answer',table(['Constructed scene','Korean','Meaning'],[
        ['Checking a train','<span lang="ko">이 열차는 서울역에 가요?</span>','Does this train go to Seoul Station?'],
        ['Checking a transfer','<span lang="ko">어디에서 갈아타요?</span>','Where do I transfer?'],
        ['Finding an exit','<span lang="ko">2번 출구는 어디에 있어요?</span>','Where is Exit 2?'],
        ['Requesting a repeat','<span lang="ko">다시 말해 주세요.</span>','Please say it again.']
      ])+'<p>In <span lang="ko">서울역에 가요</span>, 에 marks the destination. In <span lang="ko">어디에서 갈아타요?</span>, 에서 marks the place where the transfer action happens. You are giving the location two different grammatical jobs. Practise with <span lang="ko">부산역에 가요</span> to change the destination while keeping the pattern.</p><p>If you are unsure, show the written destination and route rather than trying to guess from a fast reply. Ask staff before passing a gate you do not understand. This example does not describe a particular train service: confirm the actual route before boarding.</p>'),
      section('mistakes','Use a recovery routine','<p>If the next station does not match the route, check the direction and stop to re-plan. A simple question is <span lang="ko">반대 방향이에요?</span> (“Is it the opposite direction?”). Avoid rushing through a gate to chase a train while you are still uncertain about the route. Check the station signs and ask staff how to reach the other platform.</p><p>For a low card balance, <span lang="ko">어디에서 충전해요?</span> asks where to top up. The answer may name a machine or another location, so keep the repeat phrase ready. Do not infer that a failed tap always means a low balance; a reader or card issue may require staff assistance.</p><p>Before a late journey, check a current service timetable. Before a journey with luggage or mobility needs, check a usable elevator route. Before buying an airport or intercity ticket, check that service’s own rules. Those are separate decisions that the city subway vocabulary does not settle.</p>'),
      section('practice','Check the decision behind the sign',practice('subway',[
        question('subway-transfer','1. Your route changes lines inside the station. Which sign are you looking for?',['환승','출구'],0,'환승 means transfer. 출구 points toward an exit; leaving may take you away from an internal transfer route.'),
        question('subway-destination','2. Complete 서울역___ 가요, with Seoul Station as the destination.',['에서','에'],1,'에 marks the destination in this pattern. 에서 would describe where an action happens.'),
        question('subway-exit','3. You reached the right station. What still needs checking?',['The exit and any access requirements.','Nothing; all exits lead to the same street.'],0,'Station arrival and the route outside are separate. Exit numbers and elevator locations can matter.'),
        question('subway-timetable','4. Can this static lesson confirm the last train tonight?',['Yes, because it has a revision date.','No; check a current service timetable.'],1,'The revision date records this lesson’s content work. It is not a live transport feed.')
      ])+'<h3>Make it yours</h3><p>Write down a real journey from a current planner and label the departure, direction, transfer, and exit. Then say two help questions aloud. Check that your note still makes sense without the map open. This is a planning exercise; do the current service checks before travelling.</p>'),
      section('sources','Reference scope and freshness',`<p><a href="https://english.seoul.go.kr/policy/transportation/modes-of-transport/subway/">Seoul Metropolitan Government: Subway</a> supports the network reference and entry/exit tapping explanation. <a href="https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=140663">Korea Tourism Organization: Transportation Cards</a> supports the rechargeable-card background. Both were accessed on 2 October 2026. Their operational details may change.</p><p>Use ${dictionary} for <span lang="ko">방면, 환승, 출구, 충전, 갈아타다</span>. The route-note exercise, dialogue, and feedback are original learning examples. Continue with <a href="/guides/particles.html">particles in context</a> and the <a href="/travel/index.html">travel section</a>.</p>`)
    ], related:['particles','first-conversation','korean-numbers']
  }
];
