'use strict';
// New course chrome lives separately from the existing translated lesson data.
const rows = {
  en:['On this page','Browse this section','Read the lesson, then practise at your own pace. All explanations and examples are on this page.','Check answers','Try again','Correct.','Review the answer below.','Choose an answer first.','{correct} of {total} correct. {remaining} unanswered.','Answer','Listen','Open the vocabulary lesson','The complete word bank is in the vocabulary lesson. Use this tool to browse or practise saved words.','Skip to content','Full lesson','Practice','Lesson topics','Build a syllable','Study guides'],
  ja:['このページの内容','この分野のページ','解説と例文を読み、自分のペースで練習しましょう。教材はすべてこのページにあります。','解答を確認','もう一度','正解です。','下の解答を確認してください。','先に答えを選んでください。','{total}問中{correct}問正解。未回答：{remaining}問。','解答','聞く','語彙レッスンを開く','単語一覧は語彙レッスンにあります。このツールでは単語の閲覧や保存した単語の練習ができます。','本文へ','レッスン全文','練習','学習項目','音節を組み立てる','学習ガイド'],
  'zh-tw':['本頁內容','瀏覽此分類','閱讀解說和例句，再依自己的步調練習。完整教材都在這一頁。','檢查答案','再試一次','答對了。','請參考下方答案。','請先選擇答案。','答對{correct}／{total}題。未作答：{remaining}題。','答案','聆聽','開啟詞彙課程','完整單字庫位於詞彙課程。此工具可瀏覽單字或練習已儲存的單字。','跳至內容','完整課程','練習','學習主題','組合音節','學習指南'],
  es:['En esta página','Explorar esta sección','Lee las explicaciones y los ejemplos, y practica a tu ritmo. Todo el material está en esta página.','Comprobar respuestas','Intentar de nuevo','Correcto.','Revisa la respuesta de abajo.','Elige primero una respuesta.','{correct} de {total} correctas. {remaining} sin responder.','Respuesta','Escuchar','Abrir la lección de vocabulario','El banco completo está en la lección de vocabulario. Esta herramienta permite explorar palabras o practicar las guardadas.','Saltar al contenido','Lección completa','Práctica','Temas de estudio','Construir una sílaba','Guías de estudio'],
  fr:['Sur cette page','Explorer cette rubrique','Lisez les explications et les exemples, puis pratiquez à votre rythme. Tout le cours est sur cette page.','Vérifier les réponses','Réessayer','Bonne réponse.','Consultez la réponse ci-dessous.','Choisissez d’abord une réponse.','{correct} bonnes réponses sur {total}. {remaining} sans réponse.','Réponse','Écouter','Ouvrir le cours de vocabulaire','La liste complète se trouve dans le cours de vocabulaire. Cet outil sert à parcourir les mots ou à pratiquer les mots enregistrés.','Aller au contenu','Cours complet','Exercices','Sujets du cours','Construire une syllabe','Guides d’étude'],
  de:['Auf dieser Seite','Diesen Bereich durchsuchen','Lies die Erklärungen und Beispiele und übe in deinem Tempo. Der gesamte Lernstoff steht auf dieser Seite.','Antworten prüfen','Noch einmal','Richtig.','Sieh dir die Antwort unten an.','Wähle zuerst eine Antwort.','{correct} von {total} richtig. {remaining} unbeantwortet.','Antwort','Anhören','Wortschatzlektion öffnen','Die vollständige Wortliste steht in der Wortschatzlektion. Mit diesem Werkzeug kannst du Wörter ansehen oder gespeicherte Wörter üben.','Zum Inhalt','Ganze Lektion','Übung','Lektionsthemen','Eine Silbe bilden','Lernhilfen'],
  vi:['Nội dung trang','Xem các trang trong mục','Đọc giải thích và ví dụ, rồi luyện theo nhịp độ của bạn. Toàn bộ nội dung nằm trên trang này.','Kiểm tra đáp án','Thử lại','Đúng.','Xem đáp án bên dưới.','Hãy chọn đáp án trước.','Đúng {correct}/{total}. Còn {remaining} câu chưa trả lời.','Đáp án','Nghe','Mở bài từ vựng','Toàn bộ kho từ nằm trong bài từ vựng. Công cụ này giúp xem từ hoặc luyện các từ đã lưu.','Đến nội dung','Toàn bộ bài học','Luyện tập','Chủ đề bài học','Ghép âm tiết','Hướng dẫn học'],
  th:['เนื้อหาในหน้านี้','ดูหน้าในหมวดนี้','อ่านคำอธิบายและตัวอย่าง แล้วฝึกตามจังหวะของคุณ เนื้อหาทั้งหมดอยู่ในหน้านี้','ตรวจคำตอบ','ลองอีกครั้ง','ถูกต้อง','ดูคำตอบด้านล่าง','เลือกคำตอบก่อน','ถูก {correct} จาก {total} ข้อ ยังไม่ตอบ {remaining} ข้อ','คำตอบ','ฟัง','เปิดบทเรียนคำศัพท์','คลังคำทั้งหมดอยู่ในบทเรียนคำศัพท์ ใช้เครื่องมือนี้ดูคำหรือฝึกคำที่บันทึกไว้','ข้ามไปเนื้อหา','บทเรียนฉบับเต็ม','ฝึกฝน','หัวข้อบทเรียน','ประกอบพยางค์','คู่มือการเรียน'],
  id:['Di halaman ini','Jelajahi bagian ini','Baca penjelasan dan contoh, lalu berlatih sesuai kecepatan Anda. Semua materi ada di halaman ini.','Periksa jawaban','Coba lagi','Benar.','Lihat jawaban di bawah.','Pilih jawaban terlebih dahulu.','{correct} dari {total} benar. {remaining} belum dijawab.','Jawaban','Dengarkan','Buka pelajaran kosakata','Bank kata lengkap ada di pelajaran kosakata. Gunakan alat ini untuk melihat kata atau melatih kata tersimpan.','Ke konten','Pelajaran lengkap','Latihan','Topik pelajaran','Susun suku kata','Panduan belajar'],
  'pt-br':['Nesta página','Explorar esta seção','Leia as explicações e os exemplos e pratique no seu ritmo. Todo o material está nesta página.','Conferir respostas','Tentar de novo','Correto.','Veja a resposta abaixo.','Escolha uma resposta primeiro.','{correct} de {total} corretas. {remaining} sem resposta.','Resposta','Ouvir','Abrir a aula de vocabulário','O banco completo está na aula de vocabulário. Use esta ferramenta para ver palavras ou praticar as salvas.','Ir para o conteúdo','Aula completa','Prática','Temas da aula','Montar uma sílaba','Guias de estudo']
};
const keys=['toc','browse','intro','check','reset','correct','retry','missing','score','answer','listen','vocabLink','toolIntro','skip','lesson','practice','topics','build','guides'];
module.exports=Object.fromEntries(Object.entries(rows).map(([code,row])=>[code,Object.fromEntries(keys.map((k,i)=>[k,row[i]]))]));
