'use strict';
// Interface copy only. Lesson prose and the Korean being taught remain untouched.
const keys = ['library','intro','all','foundations','sentences','conversation','tools','search','clear','results','empty','save','saved','mark','done','local','unavailable','resume','next','choose','review','showAll','answered','perfect','back','path','quizIntro','cultureIntro','travelIntro'];
const rows = {
 en:['Your Korean starts here.','Start with the alphabet. Build a sentence. Use it in real life. Choose a lesson and learn at your own pace.','All topics','First steps','Words & grammar','Everyday Korean','Practice tools','Find a topic','Clear filters','{n} topics','No matches. Try another word or clear the filters.','Save for later','Saved','Mark as studied','Studied','Saved only in this browser.','Storage unavailable. Progress lasts for this visit.','Continue learning','Up next','Choose your practice','Review missed answers','Show all questions','{n} of {total} answered','All correct. Choose another set when you are ready.','Back to topics','A good place to begin','Choose one topic, answer at your own pace, then review what you missed. No timer. No pressure.','Follow your curiosity. Learn the Korean behind the food, music, and everyday moments you love.','Choose a destination, learn a few useful phrases, and make a plan that feels like you.'],
 ja:['ここから始める韓国語。','文字から単語、文、日常会話へ。レッスンを選び、自分のペースで学びましょう。','すべて','はじめの一歩','単語と文法','日常の韓国語','練習ツール','トピックを検索','絞り込みを解除','{n}件のトピック','該当なし。別の言葉で検索するか、絞り込みを解除してください。','あとで読む','保存済み','学習済みにする','学習済み','このブラウザにのみ保存されます。','保存できません。この訪問中のみ記録します。','学習を続ける','次に学ぶ','練習を選ぶ','間違えた問題を復習','全問を表示','{total}問中{n}問回答済み','全問正解です。準備ができたら別のセットへ。','トピックに戻る','ここから始めよう','テーマを選び、自分のペースで解いて復習しましょう。時間制限はありません。','好きな食べ物、音楽、日常の場面から韓国語を学びましょう。','行き先を選び、役立つ表現を覚えて、自分らしい旅を計画しましょう。'],
 'zh-tw':['從這裡開始學韓語。','從字母、單字到句子和日常對話。選一堂課，按照自己的步調學習。','全部主題','入門','單字與文法','日常韓語','練習工具','搜尋主題','清除篩選','{n} 個主題','沒有符合的結果。請更換關鍵字或清除篩選。','稍後閱讀','已儲存','標記為已學習','已學習','僅儲存在此瀏覽器中。','無法儲存，進度僅保留於本次瀏覽。','繼續學習','接著學','選擇練習','複習答錯的題目','顯示所有題目','已回答 {n}／{total} 題','全部答對！準備好後可以選擇其他題組。','返回主題','從這裡開始','選擇主題，依自己的步調作答，再複習錯誤。沒有時間限制。','從喜愛的美食、音樂和日常生活中探索韓語。','選擇目的地，學幾句實用表達，規劃屬於你的旅程。'],
 es:['Tu coreano empieza aquí.','Empieza por el alfabeto, construye frases y úsalas en la vida real. Elige una lección y aprende a tu ritmo.','Todos los temas','Primeros pasos','Palabras y gramática','Coreano cotidiano','Herramientas','Buscar un tema','Borrar filtros','{n} temas','Sin resultados. Prueba otra palabra o borra los filtros.','Guardar para después','Guardado','Marcar como estudiado','Estudiado','Guardado solo en este navegador.','No se puede guardar. El progreso dura esta visita.','Seguir aprendiendo','Siguiente paso','Elige tu práctica','Repasar errores','Ver todas las preguntas','{n} de {total} respondidas','Todo correcto. Elige otro grupo cuando quieras.','Volver a los temas','Un buen punto de partida','Elige un tema, responde a tu ritmo y repasa los errores. Sin límite de tiempo.','Sigue tu curiosidad y aprende el coreano de la comida, la música y la vida cotidiana.','Elige un destino, aprende frases útiles y diseña un viaje a tu medida.'],
 fr:['Votre coréen commence ici.','Commencez par l’alphabet, formez des phrases et utilisez-les au quotidien. Choisissez un cours et avancez à votre rythme.','Tous les sujets','Premiers pas','Mots et grammaire','Coréen au quotidien','Outils de pratique','Chercher un sujet','Effacer les filtres','{n} sujets','Aucun résultat. Essayez un autre mot ou effacez les filtres.','Garder pour plus tard','Enregistré','Marquer comme étudié','Étudié','Enregistré uniquement dans ce navigateur.','Stockage indisponible. Progrès conservés pour cette visite.','Continuer à apprendre','La suite','Choisissez un exercice','Revoir les erreurs','Afficher toutes les questions','{n} réponses sur {total}','Tout est correct. Choisissez une autre série quand vous le souhaitez.','Retour aux sujets','Un bon point de départ','Choisissez un sujet, répondez à votre rythme et revoyez vos erreurs. Sans chronomètre.','Suivez votre curiosité et découvrez le coréen à travers la cuisine, la musique et le quotidien.','Choisissez une destination, apprenez quelques expressions et préparez un voyage à votre image.'],
 de:['Hier beginnt dein Koreanisch.','Beginne mit dem Alphabet, bilde Sätze und nutze sie im Alltag. Wähle eine Lektion und lerne in deinem Tempo.','Alle Themen','Erste Schritte','Wörter & Grammatik','Koreanisch im Alltag','Übungswerkzeuge','Thema suchen','Filter zurücksetzen','{n} Themen','Keine Treffer. Suche nach einem anderen Wort oder setze die Filter zurück.','Für später speichern','Gespeichert','Als gelernt markieren','Gelernt','Nur in diesem Browser gespeichert.','Speichern nicht möglich. Fortschritt gilt für diesen Besuch.','Weiterlernen','Als Nächstes','Wähle deine Übung','Fehler wiederholen','Alle Fragen anzeigen','{n} von {total} beantwortet','Alles richtig. Wähle eine weitere Übung, wenn du bereit bist.','Zurück zu den Themen','Ein guter Einstieg','Wähle ein Thema, antworte in deinem Tempo und wiederhole Fehler. Ohne Zeitlimit.','Entdecke Koreanisch durch Essen, Musik und die Alltagsmomente, die dich interessieren.','Wähle ein Ziel, lerne nützliche Wendungen und plane deine eigene Reise.'],
 vi:['Bắt đầu học tiếng Hàn tại đây.','Bắt đầu với bảng chữ cái, ghép câu và dùng trong cuộc sống. Chọn bài học và học theo nhịp độ của bạn.','Tất cả chủ đề','Bước đầu tiên','Từ vựng và ngữ pháp','Tiếng Hàn hằng ngày','Công cụ luyện tập','Tìm chủ đề','Xóa bộ lọc','{n} chủ đề','Không tìm thấy. Hãy thử từ khác hoặc xóa bộ lọc.','Lưu để đọc sau','Đã lưu','Đánh dấu đã học','Đã học','Chỉ lưu trong trình duyệt này.','Không thể lưu. Tiến độ chỉ giữ trong lần truy cập này.','Tiếp tục học','Học tiếp','Chọn bài luyện tập','Ôn câu trả lời sai','Hiện tất cả câu hỏi','Đã trả lời {n}/{total} câu','Đúng tất cả. Hãy chọn bài khác khi sẵn sàng.','Về danh sách chủ đề','Bắt đầu từ đây','Chọn chủ đề, trả lời theo nhịp độ của bạn rồi ôn lại câu sai. Không giới hạn thời gian.','Khám phá tiếng Hàn qua món ăn, âm nhạc và những khoảnh khắc đời thường bạn yêu thích.','Chọn điểm đến, học vài câu hữu ích và lên kế hoạch cho chuyến đi của bạn.'],
 th:['เริ่มเรียนภาษาเกาหลีที่นี่','เริ่มจากตัวอักษร สร้างประโยค แล้วใช้ในชีวิตจริง เลือกบทเรียนและเรียนตามจังหวะของคุณ','ทุกหัวข้อ','เริ่มต้น','คำศัพท์และไวยากรณ์','ภาษาเกาหลีในชีวิตประจำวัน','เครื่องมือฝึกฝน','ค้นหาหัวข้อ','ล้างตัวกรอง','{n} หัวข้อ','ไม่พบผลลัพธ์ ลองคำอื่นหรือล้างตัวกรอง','บันทึกไว้อ่านทีหลัง','บันทึกแล้ว','ทำเครื่องหมายว่าเรียนแล้ว','เรียนแล้ว','บันทึกเฉพาะในเบราว์เซอร์นี้','บันทึกไม่ได้ ความคืบหน้าจะอยู่เฉพาะการเข้าชมครั้งนี้','เรียนต่อ','เรียนถัดไป','เลือกแบบฝึกหัด','ทบทวนข้อที่ผิด','แสดงทุกคำถาม','ตอบแล้ว {n} จาก {total} ข้อ','ถูกทุกข้อแล้ว เลือกชุดอื่นเมื่อพร้อม','กลับไปที่หัวข้อ','จุดเริ่มต้นที่ดี','เลือกหัวข้อ ตอบตามจังหวะของคุณ แล้วทบทวนข้อที่ผิด ไม่มีการจับเวลา','เรียนภาษาเกาหลีผ่านอาหาร ดนตรี และช่วงเวลาในชีวิตประจำวันที่คุณชอบ','เลือกจุดหมาย เรียนวลีที่มีประโยชน์ แล้ววางแผนการเดินทางในแบบของคุณ'],
 id:['Bahasa Korea dimulai di sini.','Mulai dari alfabet, susun kalimat, lalu gunakan sehari-hari. Pilih pelajaran dan belajar sesuai ritme Anda.','Semua topik','Langkah awal','Kata & tata bahasa','Bahasa Korea sehari-hari','Alat latihan','Cari topik','Hapus filter','{n} topik','Tidak ditemukan. Coba kata lain atau hapus filter.','Simpan untuk nanti','Tersimpan','Tandai sudah dipelajari','Sudah dipelajari','Hanya disimpan di browser ini.','Penyimpanan tidak tersedia. Progres berlaku selama kunjungan ini.','Lanjutkan belajar','Selanjutnya','Pilih latihan','Tinjau jawaban salah','Tampilkan semua soal','{n} dari {total} terjawab','Semua benar. Pilih set lain saat Anda siap.','Kembali ke topik','Tempat yang tepat untuk mulai','Pilih topik, jawab sesuai ritme Anda, lalu tinjau kesalahan. Tanpa batas waktu.','Ikuti rasa ingin tahu dan pelajari bahasa Korea melalui makanan, musik, dan kehidupan sehari-hari.','Pilih tujuan, pelajari ungkapan berguna, dan rencanakan perjalanan sesuai keinginan Anda.'],
 'pt-br':['Seu coreano começa aqui.','Comece pelo alfabeto, forme frases e use no dia a dia. Escolha uma aula e aprenda no seu ritmo.','Todos os temas','Primeiros passos','Palavras e gramática','Coreano cotidiano','Ferramentas de prática','Buscar um tema','Limpar filtros','{n} temas','Nenhum resultado. Tente outra palavra ou limpe os filtros.','Salvar para depois','Salvo','Marcar como estudado','Estudado','Salvo apenas neste navegador.','Armazenamento indisponível. O progresso dura esta visita.','Continuar aprendendo','Próximo passo','Escolha sua prática','Revisar respostas erradas','Mostrar todas as perguntas','{n} de {total} respondidas','Tudo certo. Escolha outro conjunto quando quiser.','Voltar aos temas','Um bom lugar para começar','Escolha um tema, responda no seu ritmo e revise os erros. Sem cronômetro.','Siga sua curiosidade e aprenda coreano por meio da comida, da música e da vida cotidiana.','Escolha um destino, aprenda frases úteis e planeje uma viagem com a sua cara.']
};
const counts={en:['Topics','Questions'],ja:['テーマ','問題'], 'zh-tw':['主題','題目'],es:['Temas','Preguntas'],fr:['Sujets','Questions'],de:['Themen','Fragen'],vi:['Chủ đề','Câu hỏi'],th:['หัวข้อ','คำถาม'],id:['Topik','Soal'],'pt-br':['Temas','Perguntas']};
module.exports=Object.fromEntries(Object.entries(rows).map(([locale,row])=>{
 if(row.length!==keys.length)throw new Error('Missing experience copy: '+locale);
 return [locale,{...Object.fromEntries(keys.map((key,i)=>[key,row[i]])),sets:counts[locale][0],questions:counts[locale][1]}];
}));
