'use strict';
// Editorial disclosures are translated. New teaching companions are linked as
// English resources rather than silently inserting English into local prose.
module.exports = {
 en: ['About this material','Publisher','Editorial standards','Report a correction','AI assists with content and translations. Independent review of every example is not certified. See our standards for sources and limitations.','Practise this situation (English)','Review and sources','Korean School is an independent project operated by 해본놈RK (Haebonnom RK). The existing operator profile identifies him as a native Korean speaker living in South Korea, working in international sales and administration. This background is not a teaching accreditation.','AI tools assist with development, drafting, exercises, illustrations, and translations. We do not certify that the operator or a qualified teacher has independently reviewed every published sentence. Sample learning conversations are constructed unless their source is identified.','Translations can contain errors or remaining English. Completion checks do not certify natural language quality. Report a page URL and the exact issue; substantial corrections belong in the update log.','Advertising and analytics scripts are paused in this revision. If enabled later, Google and other vendors may use cookies based on visits to this and other sites to serve, personalise, and measure ads. The privacy controls below explain your choices. Advertising activation requires the applicable consent configuration.','Saved words can be reviewed sequentially or shuffled. This tool does not schedule spaced reviews.'],
 ja: ['この教材について','発行者','編集方針','訂正を報告','内容と翻訳にはAIを使用しています。すべての例文の独立した確認は保証していません。情報源と制限は編集方針をご覧ください。','場面で練習する（英語）','確認と情報源','Korean Schoolは해본놈RK (Haebonnom RK)が運営する独立したプロジェクトです。既存の紹介では、韓国在住の韓国語母語話者で、国際営業と事務に従事しています。この経歴は教員資格を示すものではありません。','開発、草稿、練習、画像、翻訳にはAIを使用しています。運営者や有資格の教師が公開文をすべて独立して確認したとは保証していません。出典が明記されていない学習会話は作例です。','翻訳には誤りや英語の残存があり得ます。完了チェックは自然な表現を保証しません。訂正はURLと該当箇所をお知らせください。重要な訂正は更新記録に残します。','この版では広告とアクセス解析のスクリプトを停止しています。後日有効にした場合、Google等は当サイトや他サイトへの訪問に基づくCookieで広告の表示、個別化、測定を行うことがあります。下のプライバシー設定で選択肢を確認できます。広告の開始には適用される同意設定が必要です。','保存した単語を順番またはシャッフルで復習できます。このツールは間隔を空けた復習を自動予約しません。'],
 'zh-tw': ['關於這份教材','發布者','編輯方針','回報更正','內容與翻譯使用AI協助，並未保證每個例句皆經獨立審閱。來源與限制請參閱編輯方針。','情境練習（英文）','審閱與來源','Korean School是由해본놈RK (Haebonnom RK)營運的獨立計畫。既有簡介說明他是居住韓國的韓語母語者，從事國際業務與行政工作。這項背景並非教師資格。','開發、草稿、練習、插圖與翻譯使用AI協助。我們不保證營運者或合格教師已獨立審閱每個公開句子。未註明來源的學習對話均為編寫的範例。','翻譯可能有錯誤或仍包含英文。完整性檢查不代表語言自然度認證。請提供頁面網址與確切問題；重要更正應記錄於更新紀錄。','此版本暫停載入廣告與分析腳本。若日後啟用，Google等供應商可能依據您造訪本站及其他網站的紀錄，使用Cookie顯示、個人化及衡量廣告。下方隱私控制提供選擇方式。啟用廣告前須完成適用的同意設定。','儲存的單字可依序或隨機複習。本工具不會自動安排間隔複習。'],
 es: ['Sobre este material','Editor','Criterios editoriales','Informar de un error','La IA ayuda con el contenido y las traducciones. No certificamos una revisión independiente de cada ejemplo. Consulta las fuentes y limitaciones en nuestros criterios.','Practica esta situación (inglés)','Revisión y fuentes','Korean School es un proyecto independiente de 해본놈RK (Haebonnom RK). Su perfil existente lo describe como hablante nativo de coreano residente en Corea del Sur, dedicado a ventas internacionales y administración. Esta experiencia no es una acreditación docente.','La IA ayuda con desarrollo, borradores, ejercicios, ilustraciones y traducciones. No certificamos que el operador o un profesor cualificado haya revisado independientemente cada frase publicada. Los diálogos son ejemplos creados salvo que se identifique otra fuente.','Las traducciones pueden contener errores o texto en inglés. Los controles de integridad no certifican la naturalidad del idioma. Envía la URL y el problema concreto; las correcciones importantes deben figurar en el registro de cambios.','En esta versión se ha pausado la carga de publicidad y analítica. Si se activan después, Google y otros proveedores pueden usar cookies basadas en visitas a este y otros sitios para mostrar, personalizar y medir anuncios. Los controles de privacidad siguientes explican tus opciones. La activación requiere la configuración de consentimiento aplicable.','Repasa las palabras guardadas en orden o de forma aleatoria. Esta herramienta no programa repasos espaciados.'],
 de: ['Über dieses Material','Herausgeber','Redaktionelle Standards','Fehler melden','KI unterstützt Inhalte und Übersetzungen. Eine unabhängige Prüfung jedes Beispiels wird nicht bestätigt. Quellen und Grenzen stehen in unseren Standards.','Diese Situation üben (Englisch)','Prüfung und Quellen','Korean School ist ein unabhängiges Projekt von 해본놈RK (Haebonnom RK). Das vorhandene Profil beschreibt ihn als koreanischen Muttersprachler in Südkorea, der im internationalen Vertrieb und in der Verwaltung arbeitet. Das ist keine Lehrqualifikation.','KI unterstützt Entwicklung, Entwürfe, Übungen, Illustrationen und Übersetzungen. Wir bestätigen nicht, dass der Betreiber oder eine qualifizierte Lehrkraft jeden veröffentlichten Satz unabhängig geprüft hat. Lerndialoge sind konstruierte Beispiele, sofern keine Quelle genannt wird.','Übersetzungen können Fehler oder englische Reste enthalten. Vollständigkeitsprüfungen bestätigen keine natürliche Sprache. Melde die URL und die konkrete Stelle; wesentliche Korrekturen gehören ins Änderungsprotokoll.','Werbe- und Analyseskripte sind in dieser Version pausiert. Bei späterer Aktivierung können Google und andere Anbieter Cookies aufgrund von Besuchen auf dieser und anderen Seiten zum Anzeigen, Personalisieren und Messen von Werbung nutzen. Die Datenschutzlinks unten erläutern deine Optionen. Die Aktivierung erfordert die zutreffende Einwilligungskonfiguration.','Gespeicherte Wörter lassen sich der Reihe nach oder gemischt wiederholen. Dieses Werkzeug plant keine zeitlich verteilten Wiederholungen.'],
 fr: ['À propos de ce contenu','Éditeur','Règles éditoriales','Signaler une erreur','L’IA aide à créer les contenus et traductions. La vérification indépendante de chaque exemple n’est pas certifiée. Nos règles précisent les sources et limites.','Pratiquer cette situation (anglais)','Vérification et sources','Korean School est un projet indépendant de 해본놈RK (Haebonnom RK). Son profil existant le présente comme un locuteur natif du coréen vivant en Corée du Sud, travaillant dans la vente internationale et l’administration. Ce parcours ne constitue pas une qualification d’enseignant.','L’IA aide au développement, à la rédaction, aux exercices, aux illustrations et aux traductions. Nous ne certifions pas que l’opérateur ou un enseignant qualifié a vérifié indépendamment chaque phrase publiée. Les dialogues pédagogiques sont construits sauf mention d’une source.','Les traductions peuvent comporter des erreurs ou de l’anglais. Les contrôles de complétude ne certifient pas le naturel de la langue. Envoyez l’URL et le problème précis ; les corrections importantes doivent figurer dans le journal des mises à jour.','Les scripts publicitaires et analytiques sont suspendus dans cette version. S’ils sont activés ultérieurement, Google et d’autres fournisseurs peuvent utiliser des cookies liés aux visites de ce site et d’autres sites pour afficher, personnaliser et mesurer les annonces. Les liens de confidentialité ci-dessous expliquent vos choix. L’activation exige la configuration de consentement applicable.','Révisez les mots enregistrés dans l’ordre ou aléatoirement. Cet outil ne programme pas de révisions espacées.'],
 vi: ['Về tài liệu này','Đơn vị xuất bản','Tiêu chuẩn biên tập','Báo lỗi cần sửa','AI hỗ trợ nội dung và bản dịch. Không chứng nhận rằng mọi ví dụ đã được kiểm tra độc lập. Xem tiêu chuẩn để biết nguồn và giới hạn.','Luyện tình huống này (tiếng Anh)','Kiểm tra và nguồn','Korean School là dự án độc lập do 해본놈RK (Haebonnom RK) vận hành. Hồ sơ hiện có giới thiệu ông là người nói tiếng Hàn bản ngữ sống tại Hàn Quốc, làm việc trong lĩnh vực kinh doanh quốc tế và hành chính. Kinh nghiệm này không phải chứng chỉ giảng dạy.','AI hỗ trợ phát triển, soạn thảo, bài tập, hình minh họa và dịch thuật. Chúng tôi không chứng nhận rằng người vận hành hoặc giáo viên có bằng cấp đã kiểm tra độc lập mọi câu được xuất bản. Hội thoại học tập là ví dụ được biên soạn trừ khi có nguồn rõ ràng.','Bản dịch có thể có lỗi hoặc còn tiếng Anh. Kiểm tra độ đầy đủ không chứng nhận cách diễn đạt tự nhiên. Hãy gửi URL và vấn đề cụ thể; sửa đổi quan trọng cần có trong nhật ký cập nhật.','Phiên bản này tạm dừng tải quảng cáo và mã phân tích. Nếu bật sau này, Google và nhà cung cấp khác có thể dùng cookie dựa trên lượt ghé trang này và trang khác để hiển thị, cá nhân hóa và đo lường quảng cáo. Các liên kết quyền riêng tư bên dưới giải thích lựa chọn. Việc bật quảng cáo cần cấu hình đồng ý phù hợp.','Ôn từ đã lưu theo thứ tự hoặc ngẫu nhiên. Công cụ này không tự lên lịch ôn cách quãng.'],
 th: ['เกี่ยวกับเนื้อหานี้','ผู้เผยแพร่','มาตรฐานเนื้อหา','แจ้งข้อผิดพลาด','AI ช่วยจัดทำเนื้อหาและคำแปล ไม่รับรองว่าทุกตัวอย่างผ่านการตรวจอิสระ ดูแหล่งข้อมูลและข้อจำกัดในมาตรฐานของเรา','ฝึกสถานการณ์นี้ (ภาษาอังกฤษ)','การตรวจและแหล่งข้อมูล','Korean School เป็นโครงการอิสระของ 해본놈RK (Haebonnom RK) ประวัติเดิมระบุว่าเขาเป็นเจ้าของภาษาเกาหลีที่อาศัยในเกาหลีใต้ ทำงานด้านการขายระหว่างประเทศและธุรการ ประสบการณ์นี้ไม่ใช่คุณวุฒิครู','AI ช่วยพัฒนา ร่างเนื้อหา แบบฝึก ภาพประกอบ และคำแปล เราไม่รับรองว่าผู้ดูแลหรือครูที่มีคุณวุฒิได้ตรวจทุกประโยคที่เผยแพร่อย่างอิสระ บทสนทนาสำหรับเรียนเป็นตัวอย่างที่แต่งขึ้น เว้นแต่ระบุแหล่งที่มา','คำแปลอาจมีข้อผิดพลาดหรือมีภาษาอังกฤษหลงเหลือ การตรวจความครบถ้วนไม่รับรองความเป็นธรรมชาติของภาษา โปรดส่ง URL และปัญหาที่ชัดเจน การแก้ไขสำคัญควรอยู่ในบันทึกอัปเดต','เวอร์ชันนี้หยุดโหลดสคริปต์โฆษณาและการวิเคราะห์ชั่วคราว หากเปิดในภายหลัง Google และผู้ให้บริการอื่นอาจใช้คุกกี้จากการเยี่ยมชมเว็บไซต์นี้และเว็บไซต์อื่นเพื่อแสดง ปรับแต่ง และวัดผลโฆษณา ลิงก์ความเป็นส่วนตัวด้านล่างอธิบายทางเลือก การเปิดโฆษณาต้องตั้งค่าความยินยอมที่เกี่ยวข้อง','ทบทวนคำที่บันทึกตามลำดับหรือสุ่มได้ เครื่องมือนี้ไม่จัดตารางทบทวนแบบเว้นระยะ'],
 id: ['Tentang materi ini','Penerbit','Standar editorial','Laporkan koreksi','AI membantu konten dan terjemahan. Pemeriksaan independen setiap contoh tidak disertifikasi. Lihat standar kami untuk sumber dan keterbatasan.','Latih situasi ini (bahasa Inggris)','Pemeriksaan dan sumber','Korean School adalah proyek independen yang dikelola 해본놈RK (Haebonnom RK). Profil yang ada menyebutnya penutur asli Korea yang tinggal di Korea Selatan dan bekerja dalam penjualan internasional serta administrasi. Latar belakang ini bukan kualifikasi mengajar.','AI membantu pengembangan, draf, latihan, ilustrasi, dan terjemahan. Kami tidak menyatakan bahwa pengelola atau guru berkualifikasi telah memeriksa secara independen setiap kalimat yang diterbitkan. Dialog belajar adalah contoh yang disusun kecuali sumbernya disebutkan.','Terjemahan dapat mengandung kesalahan atau sisa bahasa Inggris. Pemeriksaan kelengkapan tidak menjamin kewajaran bahasa. Kirim URL dan masalah yang tepat; koreksi penting perlu dicatat dalam log pembaruan.','Skrip iklan dan analitik dihentikan sementara dalam versi ini. Jika diaktifkan nanti, Google dan penyedia lain dapat menggunakan cookie berdasarkan kunjungan ke situs ini dan situs lain untuk menayangkan, mempersonalisasi, dan mengukur iklan. Kontrol privasi di bawah menjelaskan pilihan Anda. Aktivasi memerlukan konfigurasi persetujuan yang sesuai.','Tinjau kata tersimpan secara berurutan atau acak. Alat ini tidak menjadwalkan pengulangan berjarak.'],
 'pt-br': ['Sobre este material','Editor','Critérios editoriais','Informar uma correção','A IA auxilia o conteúdo e as traduções. Não certificamos a revisão independente de cada exemplo. Consulte os critérios para fontes e limitações.','Praticar esta situação (inglês)','Revisão e fontes','Korean School é um projeto independente de 해본놈RK (Haebonnom RK). O perfil existente o descreve como falante nativo de coreano residente na Coreia do Sul, trabalhando em vendas internacionais e administração. Essa experiência não é uma qualificação docente.','A IA auxilia o desenvolvimento, rascunhos, exercícios, ilustrações e traduções. Não certificamos que o operador ou um professor qualificado tenha revisado de forma independente cada frase publicada. Os diálogos são exemplos criados, salvo quando uma fonte é identificada.','As traduções podem conter erros ou trechos em inglês. As verificações de completude não certificam a naturalidade do idioma. Envie a URL e o problema exato; correções importantes devem constar no registro de atualizações.','Os scripts de anúncios e análise estão pausados nesta versão. Se forem ativados depois, Google e outros fornecedores podem usar cookies baseados em visitas a este e outros sites para exibir, personalizar e medir anúncios. Os controles de privacidade abaixo explicam suas opções. A ativação exige a configuração de consentimento aplicável.','Revise as palavras salvas em ordem ou aleatoriamente. Esta ferramenta não agenda revisões espaçadas.']
};
const imageNotes={
 en:'AI-generated illustrations depict representative or fictional scenes. The images do not document firsthand visits, real performers, or product tests.',
 ja:'AI生成の画像は、代表的な場面や架空の場面を描いています。実際の訪問、出演者の撮影、製品テストの記録ではありません。',
 'zh-tw':'AI生成插圖呈現示意或虛構場景，並非親自到訪、拍攝真實藝人或測試產品的紀錄。',
 es:'Las ilustraciones generadas con IA muestran escenas representativas o ficticias. No documentan visitas personales, artistas reales ni pruebas de productos.',
 de:'KI-generierte Illustrationen zeigen beispielhafte oder fiktive Szenen. Sie dokumentieren keine eigenen Besuche, tatsächlichen Künstleraufnahmen oder Produkttests.',
 fr:'Les illustrations générées par IA représentent des scènes indicatives ou fictives. Elles ne documentent pas des visites personnelles, des artistes réels ou des tests de produits.',
 vi:'Hình minh họa do AI tạo thể hiện cảnh đại diện hoặc hư cấu, không phải ghi chép chuyến thăm thực tế, ảnh nghệ sĩ thật hay thử nghiệm sản phẩm.',
 th:'ภาพที่ AI สร้างแสดงฉากตัวอย่างหรือฉากสมมติ ไม่ใช่บันทึกการไปเยือนจริง ภาพศิลปินจริง หรือการทดสอบผลิตภัณฑ์',
 id:'Ilustrasi buatan AI menggambarkan adegan representatif atau fiktif. Gambar tersebut bukan dokumentasi kunjungan langsung, artis nyata, atau pengujian produk.',
 'pt-br':'As ilustrações geradas por IA mostram cenas representativas ou fictícias. Não documentam visitas pessoais, artistas reais nem testes de produtos.'
};
for(const [code,note] of Object.entries(imageNotes))module.exports[code][12]=note;
