'use strict';
(function() {
  const ES = {
    // ── Navigation & Global UI ─────────────────────────
    'Learn': 'Aprender', 'Quiz': 'Cuestionario', 'K-Culture': 'K-Cultura', 'Travel': 'Viajes',
    'Search...': 'Buscar...', 'Search lessons, vocabulary…': 'Buscar lecciones, vocabulario…', 'Search lessons...': 'Buscar lecciones...',
    'Loading lesson…': 'Cargando lección…', 'Previous': 'Anterior', 'Next': 'Siguiente', '📚 Lesson 4 · vocabulary': '📚 Lección 4 · Vocabulario',
    'Search Results': 'Resultados de búsqueda', '← Back to Home': '← Volver al inicio',
    '🇰🇷 · Free · For Every Level': '🇰🇷 · Gratis · Para todos los niveles',
    'Learn Korean': 'Aprender coreano', 'Start Learning': 'Empezar a aprender', 'Explore K-Culture': 'Explorar K-Cultura',
    'Vocabulary Words': 'Palabras de vocabulario', 'Lessons': 'Lecciones', 'Active Learners': 'Estudiantes activos', '% Free': '% Gratis',
    'FEATURES': 'CARACTERÍSTICAS', 'Everything You Need to Learn Korean': 'Todo lo que necesitas para aprender coreano',
    'Start with 한글': 'Empieza con 한글', 'Learn Hangul Now →': 'Aprende Hangul ahora →',
    'Hear It': 'Escuchar', 'More Words': 'Más palabras', 'Word of the Day': 'Palabra del día',
    'STRUCTURED PATHS · 학습 경로': 'Rutas estructuradas · 학습 경로',
    'Choose Your Learning Path': 'Elige tu ruta de aprendizaje',
    'Beginner': 'Principiante', 'Intermediate': 'Intermedio', 'Advanced': 'Avanzado',
    'Start Beginner Path →': 'Comenzar ruta principiante →', 'Start Intermediate Path →': 'Comenzar ruta intermedia →',
    'Start Advanced Path →': 'Comenzar ruta avanzada →', 'POPULAR': 'POPULAR',
    'Beginner–Intermediate': 'Principiante–Intermedio', 'Intermediate–Advanced': 'Intermedio–Avanzado',
    'Beg–Int': 'Prin–Int',
    // ── K-Culture & Home ──────────────────────────────
    'K-CULTURE': 'K-CULTURA', 'K-CULTURE · 한국 문화': 'K-CULTURA · 한국 문화',
    'Experience Korea Beyond Language': 'Experimenta Corea más allá del idioma',
    'Explore All K-Culture Content →': 'Explorar todo el contenido K-Cultura →',
    'TRAVEL · 여행': 'VIAJES · 여행', 'Explore Korea': 'Explorar Corea',
    'View Full Travel Guide →': 'Ver guía de viaje completa →',
    'PRACTICE · 연습': 'PRÁCTICA · 연습',
    '10 progressive levels · multiple choice · covers Hangul, Grammar & Vocabulary': '10 niveles progresivos · opción múltiple · cubre Hangul, Gramática y Vocabulario',
    'Choose a Level': 'Elige un nivel', 'questions': 'preguntas', '← All Levels': '← Todos los niveles',
    'Try Again': 'Intentar de nuevo', 'Next Level': 'Siguiente nivel', 'All Levels': 'Todos los niveles',
    'Next Level →': 'Siguiente nivel →',
    // ── Travel ────────────────────────────────────────
    '🇰🇷 · South Korea Travel Guide · 여행 안내': '🇰🇷 · Guía de viaje a Corea del Sur · 여행 안내',
    'South Korea Travel Guide': 'Guía de viaje a Corea del Sur',
    'Population': 'Población', 'UNESCO Sites': 'Sitios UNESCO',
    'Great to visit': 'Ideal para visitar', 'Visa-free nations': 'Países sin visa',
    'EXPLORE THE GUIDES · 가이드 탐색': 'EXPLORAR GUÍAS · 가이드 탐색',
    'Plan Your Perfect Korea Trip': 'Planifica tu viaje perfecto a Corea',
    'TOP DESTINATIONS · 인기 여행지': 'DESTINOS PRINCIPALES · 인기 여행지',
    'Where Will You Explore?': '¿Dónde explorarás?',
    'ESSENTIAL PHRASES · 필수 표현': 'FRASES ESENCIALES · 필수 표현',
    'Travel Korean Phrasebook': 'Guía de frases coreanas para viajeros',
    'TRANSPORTATION · 교통': 'TRANSPORTE · 교통', 'Getting Around Korea': 'Moverse por Corea',
    'FOOD TOUR · 음식 여행': 'TOUR GASTRONÓMICO · 음식 여행', 'Regional Korean Specialties': 'Especialidades regionales coreanas',
    'CULTURAL ETIQUETTE · 예절': 'ETIQUETA CULTURAL · 예절', 'Korean Cultural Tips': 'Consejos de cultura coreana',
    'TRAVEL APPS · 여행 앱': 'APPS DE VIAJE · 여행 앱', 'Essential Apps for Korea Travel': 'Apps esenciales para viajar a Corea',
    'READY TO LEARN?': '¿LISTO PARA APRENDER?', 'Start Speaking Korean Today': 'Empieza a hablar coreano hoy',
    'Start Learning Korean →': 'Empezar a aprender coreano →', 'Plan Your Trip': 'Planifica tu viaje',
    'K-Pop': 'K-Pop', 'K-Drama': 'K-Drama', 'K-Beauty': 'K-Beauty', 'All': 'Todo',
    // ── Footer & Company ──────────────────────────────
    'Learn · 학습': 'Aprender · 학습', 'K-Culture · 문화': 'K-Cultura · 문화',
    'Company · 회사': 'Empresa · 회사', 'Explore': 'Explorar', 'Company': 'Empresa',
    'Hangul Alphabet': 'Alfabeto Hangul', 'Grammar': 'Gramática', 'Vocabulary': 'Vocabulario',
    'Travel Guide': 'Guía de viaje', 'About Us': 'Sobre nosotros',
    'Contact': 'Contacto', 'Privacy Policy': 'Política de privacidad', 'Terms of Use': 'Términos de uso',
    'Made with ❤️ for Korean learners worldwide.': 'Hecho con ❤️ para estudiantes de coreano en todo el mundo.',
    '🇰🇷 학습을 즐기세요! (Enjoy your learning!)': '🇰🇷 학습을 즐기세요! (¡Disfruta tu aprendizaje!)',
    'Home': 'Inicio', 'Hangul': 'Hangul',
    'A free Korean language learning platform — combining language study with K-culture, travel guides, and real-world practice. For learners of every level, worldwide.': 'Plataforma gratuita de aprendizaje de coreano — combina el estudio del idioma con K-cultura, guías de viaje y práctica real. Para estudiantes de todos los niveles, en todo el mundo.',
    'A free Korean language learning platform for learners of every level, worldwide.': 'Plataforma gratuita de aprendizaje de coreano para todos los niveles, en todo el mundo.',
    '© 2026 한국어 학교. Made with ❤️ for Korean learners worldwide.': '© 2026 한국어 학교. Hecho con ❤️ para estudiantes de coreano en todo el mundo.',
    // ── Sidebar Dividers ──────────────────────────────
    'Getting Started': 'Para empezar', 'Tools': 'Herramientas',
    'CATEGORIES · 카테고리': 'CATEGORÍAS · 카테고리', 'DEEP DIVES · 심층 탐구': 'EN PROFUNDIDAD · 심층 탐구',
    // ── Learn Sidebar ─────────────────────────────────
    'Introduction': 'Introducción', 'Syllable Blocks': 'Bloques de sílabas', 'Pronunciation Guide': 'Guía de pronunciación',
    'Vocab': 'Vocabulario', 'Greetings': 'Saludos', 'Numbers': 'Números', 'Family': 'Familia',
    'Food & Drink': 'Comida y bebida', 'Colors': 'Colores', 'Days & Time': 'Días y tiempo', 'Places': 'Lugares',
    'Emotions': 'Emociones', 'Body Parts': 'Partes del cuerpo', 'Shopping': 'Compras', 'Weather': 'Clima',
    'Verbs & Actions': 'Verbos y acciones', 'Adjectives': 'Adjetivos', 'Workplace': 'Lugar de trabajo',
    'Health & Medicine': 'Salud y medicina', 'Media & K-Culture': 'Medios y K-Cultura',
    'Proverbs & Idioms': 'Proverbios y modismos', 'Academic Korean': 'Coreano académico',
    'News & Society': 'Noticias y sociedad', 'Konglish': 'Konglish', 'Pronouns': 'Pronombres',
    'Common Nouns': 'Sustantivos comunes', 'Sentence Structure': 'Estructura de oraciones', 'Korean Particles': 'Partículas coreanas',
    'Verb Conjugation': 'Conjugación verbal', 'Question Forms': 'Formas interrogativas', 'Connectors': 'Conectores',
    'And, With': 'Y, Con', 'To/From Someone': 'A/De alguien', 'Telling Time': 'Decir la hora',
    'Counters': 'Contadores', 'Present Progressive': 'Presente progresivo', 'Self Introduction': 'Autopresentación',
    'Dates and Months': 'Fechas y meses', 'Degree Adverbs': 'Adverbios de grado',
    'Nominalizer -는 것': 'Nominalizador -는 것', 'Comparatives': 'Comparativos',
    'Still, Already': 'Todavía, Ya', 'Someone, Something': 'Alguien, Algo',
    'Imperative -(으)세요': 'Imperativo -(으)세요', 'Don\'t: -지 마세요': 'No: -지 마세요',
    'Method: -(으)로': 'Método: -(으)로', 'Good/Poor At': 'Bueno/Malo en',
    '-도 Advanced Uses': 'Usos avanzados de 도', 'Formal vs Informal': 'Formal vs Informal',
    'Expressing Emotions': 'Expresar emociones', 'Shopping Phrases': 'Frases de compras', 'Writing Essays': 'Escribir ensayos',
    'Business Korean': 'Coreano de negocios', 'Classical Korean': 'Coreano clásico', 'Korean Dialogues': 'Diálogos en coreano',
    'Flashcards': 'Tarjetas de memoria',
    // ── Culture Sidebar ───────────────────────────────
    'K-Movie': 'K-Cine', 'K-Food': 'K-Gastronomía', 'K-Fashion': 'K-Moda',
    'Korean Thing': 'Cosas coreanas', 'K-Gaming': 'K-Gaming', 'K-Sports': 'K-Deportes',
    'K-Pop, K-Drama, food, beauty, fashion, gaming, sports & traditions.': 'K-Pop, K-Drama, gastronomía, belleza, moda, gaming, deportes y tradiciones.',
    'K-Pop History': 'Historia del K-Pop', 'Agencies': 'Agencias', 'Generations': 'Generaciones', 'Genres': 'Géneros',
    'Variety Shows': 'Programas de variedades', 'Film & Acting': 'Cine y actuación', 'Idol Phrases': 'Frases de ídolos',
    'Fan Slang': 'Argot de fans', 'Fan Chants': 'Cánticos de fans', 'Drama History': 'Historia del K-Drama',
    'Drama Genres': 'Géneros de K-Drama', 'Must-Watch Dramas': 'Dramas imprescindibles', 'K-Drama Tropes': 'Tópicos del K-Drama',
    'Speech Levels': 'Niveles de habla', 'Dialogue Practice': 'Práctica de diálogos',
    'Fan Culture & Slang': 'Cultura y argot de fans', 'Movie History': 'Historia del cine',
    'Movie Genres': 'Géneros de cine', 'Must-Watch Films': 'Películas imprescindibles', 'Directors': 'Directores',
    'Iconic Lines': 'Frases icónicas', 'Fan Culture': 'Cultura de fans',
    'K-Food Goes Global': 'K-Gastronomía conquista el mundo', 'Foods That Went Global': 'Comidas que se globalizaron',
    'K-Food Timeline': 'Cronología de K-Gastronomía', 'Essential Dishes': 'Platos esenciales',
    'World-Famous Chefs': 'Chefs de fama mundial', 'Ordering & Dining': 'Pedir y comer',
    'Street Food': 'Comida callejera', 'Food Culture & Drinking': 'Cultura culinaria y de bebidas',
    'Ramyeon Guide': 'Guía del ramyeon', 'Mandu Guide': 'Guía del mandu',
    'Chicken Guide': 'Guía del pollo frito', 'K-BBQ Guide': 'Guía del K-BBQ', 'Kimchi Guide': 'Guía del kimchi',
    'K-Beauty Goes Global': 'K-Beauty conquista el mundo', 'K-Beauty Timeline': 'Cronología de K-Beauty',
    'Iconic Brands': 'Marcas icónicas', 'Beauty Vocabulary': 'Vocabulario de belleza', '10-Step Skincare': 'Rutina de 10 pasos',
    'Key Ingredients': 'Ingredientes clave', 'Beauty Trends': 'Tendencias de belleza', 'Makeup Philosophy': 'Filosofía del maquillaje',
    'Skin Clinic Culture': 'Cultura de clínicas estéticas', 'K-Beauty Dialogue': 'Diálogo de K-Beauty',
    'K-Fashion Global': 'K-Moda global', 'Fashion Icons': 'Íconos de la moda',
    'Fashion Timeline': 'Cronología de la moda', 'Style Aesthetics': 'Estética del estilo', 'Idol Fashion': 'Moda de ídolos',
    'Seoul Fashion Week': 'Semana de la moda de Seúl', 'Fashion Vocabulary': 'Vocabulario de moda',
    'Fashion Districts': 'Distritos de moda', 'Shopping Dialogue': 'Diálogo de compras',
    'Hanbok & Traditional Fashion': 'Hanbok y moda tradicional', 'Rice Obsession': 'Obsesión con el arroz',
    'Youth Protection Laws': 'Leyes de protección juvenil', 'Fast Delivery Culture': 'Cultura de entrega rápida',
    'Invasive Species Crisis': 'Crisis de especies invasoras', 'Table Call Culture': 'Cultura del llamado a la mesa',
    'Public Transport': 'Transporte público', 'Jjimjilbang': 'Jjimjilbang', 'Plastic Surgery Culture': 'Cultura de cirugía estética',
    'Outdoor Drinking': 'Bebida al aire libre', 'Jeonse Housing': 'Sistema de vivienda jeonse',
    'Traditions & Holidays': 'Tradiciones y festividades', '100 Korean Proverbs': '100 proverbios coreanos',
    'K-Gaming Stats': 'Estadísticas de K-Gaming', 'Gaming Timeline': 'Cronología de gaming',
    'Gaming Legends': 'Leyendas del gaming', 'Iconic Games': 'Juegos icónicos', 'Streaming Culture': 'Cultura de streaming',
    'PC Bang Culture': 'Cultura PC bang', 'PC방 Culture': 'Cultura PC방', 'Esports Leagues': 'Ligas de esports',
    'Gamer Slang': 'Argot gamer', 'Gaming Vocabulary': 'Vocabulario de gaming', 'Sports Overview': 'Visión general de deportes',
    'Football Heroes': 'Héroes del fútbol', 'Baseball Heroes': 'Héroes del béisbol', 'Marathon Legends': 'Leyendas del maratón',
    'Individual Legends': 'Leyendas individuales', 'Traditional Sports': 'Deportes tradicionales', 'Cheer Chants': 'Cánticos de apoyo',
    // ── Travel Sidebar ────────────────────────────────
    'Travel Guide · 여행 안내': 'Guía de viaje · 여행 안내', 'South Korea': 'Corea del Sur',
    'By Days · 일수별': 'Por días · 일수별', '1 Day Trip · 당일치기': 'Excursión de 1 día · 당일치기',
    '2 Days · 1박 2일': '2 días · 1박 2일', '3 Days · 2박 3일': '3 días · 2박 3일',
    '5 Days · 4박 5일': '5 días · 4박 5일', '1 Week · 일주일': '1 semana · 일주일',
    '10 Days': '10 días', '2 Weeks · 2주': '2 semanas · 2주', '1 Month+ · 한달': '1 mes o más · 한달',
    'By City · 도시별': 'Por ciudad · 도시별', 'Seoul · 서울': 'Seúl · 서울',
    'Incheon · 인천': 'Incheon · 인천', 'Busan · 부산': 'Busan · 부산',
    'Suwon · 수원': 'Suwon · 수원', 'Jeju · 제주도': 'Jeju · 제주도',
    'Gyeongju · 경주': 'Gyeongju · 경주', 'Other Cities': 'Otras ciudades',
    'By Theme · 테마별': 'Por temática · 테마별', 'Food Tour · 음식 여행': 'Tour gastronómico · 음식 여행',
    'Events & Festivals · 이벤트': 'Eventos y festivales · 이벤트', 'Sightseeing · 관광': 'Turismo · 관광',
    'Cross-Country · 장거리': 'Larga distancia · 장거리',
    '📋 Trip Planner · 여행 계획표': '📋 Planificador de viaje · 여행 계획표',
    'Day-by-Day Itineraries': 'Itinerarios día a día', 'City Travel Guides': 'Guías de ciudades',
    'Themed Travel': 'Viajes temáticos', 'Bus': 'Autobús', 'Subway': 'Metro', 'Taxi': 'Taxi',
    'KTX High-speed Rail': 'KTX Tren de alta velocidad', 'Age': 'Edad', 'Bowing': 'Reverencia',
    'Drinking': 'Beber', 'Eating': 'Comer', 'Quiet': 'Silencio', 'Shoes': 'Zapatos',
    'Tipping': 'Propina', 'Two Hands': 'Dos manos',
    'International': 'Internacional', 'Politics': 'Política', 'Economy': 'Economía', 'Society': 'Sociedad',
    'Science': 'Ciencia', 'Culture': 'Cultura', 'Sports': 'Deportes', 'Education': 'Educación',
    'Environment': 'Medio ambiente',
    // ── Homepage Descriptions ─────────────────────────
    'Discover the beauty of Korea through language, culture, K-pop, travel, and cuisine — with free lessons designed for learners worldwide.': 'Descubre la belleza de Corea a través del idioma, la cultura, el K-Pop, los viajes y la gastronomía — con lecciones gratuitas para estudiantes de todo el mundo.',
    'Learn the Korean alphabet in just 2 hours. 한글 (Hangul) is remarkably logical — once you know the 24 basic letters, you can read anything.': 'Aprende el alfabeto coreano en solo 2 horas. 한글 (Hangul) es notablemente lógico — una vez que conoces las 24 letras básicas, puedes leer cualquier cosa.',
    'Learn Korean naturally through your favourite songs. Line-by-line breakdowns with vocabulary, grammar notes, and pronunciation guides.': 'Aprende coreano de forma natural a través de tus canciones favoritas. Análisis línea por línea con vocabulario, notas gramaticales y guías de pronunciación.',
    'Pick up everyday Korean from your favourite dramas. Contextual vocabulary lists organised by show, genre, and proficiency level.': 'Aprende coreano cotidiano de tus dramas favoritos. Listas de vocabulario contextual organizadas por serie, género y nivel.',
    'From 김치 (kimchi) to 삼겹살 (samgyeopsal) — explore the rich vocabulary of Korean cuisine with pronunciation and cultural context.': 'De 김치 (kimchi) a 삼겹살 (samgyeopsal) — explora el rico vocabulario de la cocina coreana con pronunciación y contexto cultural.',
    'Whether you are just starting or aiming for fluency, we have a clear roadmap to take you there step by step.': 'Tanto si estás empezando como si aspiras a la fluidez, tenemos una hoja de ruta clara para llevarte paso a paso.',
    'Language is the gateway — immerse yourself in Korean pop culture, food, and beauty to supercharge your learning.': 'El idioma es la puerta de entrada — sumérgete en la cultura pop coreana, la gastronomía y la belleza para potenciar tu aprendizaje.',
    'From BTS to BLACKPINK — the most common Korean words and phrases used by your favourite K-Pop artists, with pronunciation guides.': 'De BTS a BLACKPINK — las palabras y frases coreanas más comunes de tus artistas K-Pop favoritos, con guías de pronunciación.',
    'Korean dramas are packed with emotional vocabulary. Learn how characters express joy, sadness, anger, and love in authentic Korean.': 'Los K-Dramas están llenos de vocabulario emocional. Aprende cómo los personajes expresan alegría, tristeza, ira y amor en coreano auténtico.',
    'Essential phrases for ordering food, asking for the bill, and navigating a Korean restaurant menu with confidence.': 'Frases esenciales para pedir comida, solicitar la cuenta y manejar el menú de un restaurante coreano con confianza.',
    'Explore the world of K-Beauty with essential vocabulary for skincare routines, cosmetics, and Korean beauty trends.': 'Explora el mundo de K-Beauty con vocabulario esencial para rutinas de cuidado de la piel, cosméticos y tendencias de belleza coreana.',
    'Learn the language of every destination. From bustling Seoul to the serene shores of Jeju — your AI travel guide is ready.': 'Aprende el idioma de cada destino. Desde el bullicioso Seúl hasta las serenas costas de Jeju — tu guía de viaje AI está lista.',
    "South Korea's dazzling capital — from the ancient palaces of Gyeongbokgung to the neon streets of Gangnam and Hongdae.": 'La deslumbrante capital de Corea del Sur — desde los antiguos palacios de Gyeongbokgung hasta las calles de neón de Gangnam y Hongdae.',
    "Korea's vibrant port city with stunning beaches, fresh seafood markets, and a unique dialect worth discovering.": 'La vibrante ciudad portuaria de Corea con playas impresionantes, mercados de mariscos frescos y un dialecto único que vale la pena descubrir.',
    "Korea's paradise island — volcanic landscapes, pristine beaches, tangerine groves, and the famous haenyeo diving culture.": 'La isla del paraíso de Corea — paisajes volcánicos, playas prístinas, huertos de mandarinas y la famosa cultura de buceo haenyeo.',
    // ── Homepage Place Names & Quiz ───────────────────
    'Seoul': 'Seúl', 'Busan': 'Busan', 'Jeju Island': 'Isla Jeju',
    'Test Your Korean': 'Pon a prueba tu coreano', 'Explore →': 'Explorar →',
    // ── Homepage Cards & Labels ───────────────────────
    'K-Pop Lyrics Learning': 'Aprendizaje con letras K-Pop', 'K-Drama Vocabulary': 'Vocabulario de K-Drama',
    'Korean Food Dictionary': 'Diccionario de comida coreana',
    'Master Korean Emotions Through K-Drama': 'Domina las emociones en coreano a través del K-Drama',
    'Order Like a Local: Restaurant Korean': 'Pide como un local: coreano en restaurantes',
    'Beauty & Skincare Vocabulary in Korean': 'Vocabulario de belleza y cuidado en coreano',
    'K-Pop Stars\' Korean Phrases You Need to Know': 'Frases coreanas de estrellas K-Pop que debes conocer',
    'Read →': 'Leer →', 'Hello / Good day': 'Hola / Buenos días',
    'annyeonghaseyo': 'an-nyeong-ha-se-yo',
    // ── Learning Path Checklist ───────────────────────
    '✓ Hangul Alphabet': '✓ Alfabeto Hangul', '✓ Basic Vowels & Consonants': '✓ Vocales y consonantes básicas',
    '✓ Syllable Blocks': '✓ Bloques de sílabas', '✓ Essential Vocabulary': '✓ Vocabulario esencial',
    '✓ Basic Greetings': '✓ Saludos básicos', '✓ Korean Grammar (SOV)': '✓ Gramática coreana (SOV)',
    '✓ Particles & Conjugation': '✓ Partículas y conjugación', '✓ Speech Levels': '✓ Niveles de habla',
    '✓ 300+ Vocabulary Words': '✓ 300+ palabras de vocabulario', '✓ Real Dialogues': '✓ Diálogos reales',
    '✓ Business Korean': '✓ Coreano de negocios', '✓ Classical Korean': '✓ Coreano clásico',
    '✓ Essay Writing': '✓ Redacción de ensayos', '✓ TOPIK Preparation': '✓ Preparación TOPIK',
    '✓ Idiomatic Expressions': '✓ Expresiones idiomáticas',
    // ── Homepage Eyebrow Labels ───────────────────────
    'Hangul Basics · 한글 기초': 'Hangul básico · 한글 기초',
    'Korean Grammar · 문법': 'Gramática coreana · 문법', 'Vocabulary · 어휘': 'Vocabulario · 어휘',
    'Pronunciation · 발음': 'Pronunciación · 발음',
    'Korean Food · 음식': 'Comida coreana · 음식', 'K-Beauty · 뷰티': 'K-Beauty · 뷰티',
    'K-Drama · 드라마': 'K-Drama · 드라마', 'K-Pop Lyrics · 가사': 'Letras K-Pop · 가사',
    'TOPIK Prep · 토픽 준비': 'Preparación TOPIK · 토픽 준비',
    'Flashcards · 플래시카드': 'Tarjetas de memoria · 플래시카드',
    'Start Here · 여기서 시작': 'Empieza aquí · 여기서 시작',
    'Daily Vocabulary · 오늘의 단어': 'Vocabulario diario · 오늘의 단어',
    'Travel Guide · 여행': 'Guía de viaje · 여행', 'Blog · 블로그': 'Blog · 블로그',
    'About Us · 소개': 'Sobre nosotros · 소개', 'Contact · 연락처': 'Contacto · 연락처',
    'Seoul · 서울': 'Seúl · 서울', 'Busan · 부산': 'Busan · 부산', 'Jeju · 제주': 'Jeju · 제주',
    'Privacy': 'Privacidad', 'Terms': 'Términos', 'Terms of Service': 'Términos de servicio',
    'K-FOOD · 한국 음식': 'K-GASTRONOMÍA · 한국 음식',
    // ── Food Page Stats ───────────────────────────────
    'Charcoal grill (best)': 'Parrilla de carbón (la mejor)', 'Side dishes (free refill)': 'Guarniciones (refill gratis)',
    'Lettuce wrap style': 'Estilo envoltura de lechuga',
    // ── Lesson Header Meta ────────────────────────────
    'About this lesson': 'Sobre esta lección', 'Korean Grammar': 'Gramática coreana',
    '✏️ Beginner · Lesson 1': '✏️ Principiante · Lección 1',
    '📐 Intermediate · Lesson 7': '📐 Intermedio · Lección 7', '60 min read': '60 min de lectura',
    'Alphabet': 'Alfabeto', '📐 Intermediate · Lesson 5': '📐 Intermedio · Lección 5',
    '🎯 26 Stages · 70 Steps': '🎯 26 etapas · 70 pasos',
    '📊 Beginner–Advanced': '📊 Principiante–Avanzado', '⏱️ ~90 min': '⏱️ ~90 min',
    '⚡ XP + Streak system': '⚡ Sistema XP + racha',
    '📝 Advanced · Lesson 12': '📝 Avanzado · Lección 12', '✍️ Essay Structure Guide': '✍️ Guía de estructura de ensayo',
    '📊 Advanced': '📊 Avanzado', '🔖 Writing': '🔖 Escritura', '🔗 Connective Grammar': '🔗 Gramática conectiva',
    '💼 Advanced · Lesson 13': '💼 Avanzado · Lección 13', '🏢 Workplace Expressions': '🏢 Expresiones del lugar de trabajo',
    '🔖 Professional': '🔖 Profesional', '🤝 Business Etiquette': '🤝 Etiqueta empresarial',
    '📜 Advanced · Lesson 14': '📜 Avanzado · Lección 14', '📜 Hanja (한자) Roots': '📜 Raíces Hanja (한자)',
    '🔖 History & Literature': '🔖 Historia y literatura', '🏛️ Historical Korean Texts': '🏛️ Textos históricos coreanos',
    '💬 All Levels · 40 Dialogues': '💬 Todos los niveles · 40 diálogos',
    '💬 40 Full Dialogues': '💬 40 diálogos completos', '📊 All Levels': '📊 Todos los niveles',
    '🔖 Real-world Korean': '🔖 Coreano del mundo real', '🔊 Audio on Every Line': '🔊 Audio en cada línea',
    // ── Lesson Header — Shared Meta ───────────────────
    'Korean': 'Coreano', 'Expressing': 'Expresar', 'Nouns': 'Sustantivos',
    '📊 Intermediate': '📊 Intermedio', '📊 Beginner–Intermediate': '📊 Principiante–Intermedio',
    '🎯 6 Stages · 84 Steps': '🎯 6 etapas · 84 pasos',
    '🎯 5 Stages · 61 Steps': '🎯 5 etapas · 61 pasos',
    '🎯 6 Stages · 68 Steps': '🎯 6 etapas · 68 pasos',
    '⏱️ ~60–90 min': '⏱️ ~60–90 min', '⏱️ ~50 min': '⏱️ ~50 min', '⏱️ ~60 min': '⏱️ ~60 min',
    '⏱ 30 min': '⏱ 30 min', '⏱ 28 min': '⏱ 28 min', '⏱ 29 min': '⏱ 29 min',
    '🔊 Audio on every word': '🔊 Audio en cada palabra',
    '🔊 Audio on every phrase': '🔊 Audio en cada frase',
    '🔊 Audio on every form': '🔊 Audio en cada forma',
    '4 stages with listen-and-repeat audio and quizzes throughout': '4 etapas con audio de escucha-y-repite y cuestionarios',
    // ── Lesson Header — Hangul ────────────────────────
    'Learn Hangul in 1 Hour:': 'Aprende Hangul en 1 hora:',
    'Created in 1443 by King Sejong the Great': 'Creado en 1443 por el rey Sejong el Grande',
    'Phonetic alphabet — each symbol = one sound': 'Alfabeto fonético — cada símbolo = un sonido',
    '6 stages to cover every character': '6 etapas para cubrir cada carácter',
    'Most learners finish in under 90 minutes': 'La mayoría de los estudiantes termina en menos de 90 minutos',
    // ── Lesson Header — Syllable Blocks ──────────────
    '🔷 Beginner · Lesson 2': '🔷 Principiante · Lección 2',
    'Korean Syllable Blocks:': 'Bloques de sílabas coreanas:',
    'Every syllable is a compact square block — not a horizontal letter string': 'Cada sílaba es un bloque cuadrado compacto — no una cadena de letras horizontal',
    'Each block holds exactly 1 vowel plus up to 2 consonants': 'Cada bloque contiene exactamente 1 vocal y hasta 2 consonantes',
    '4 structural patterns: CV, V, CVC, VC — all follow the same rules': '4 patrones estructurales: CV, V, CVC, VC — todos siguen las mismas reglas',
    'Master the block structure and you can sound out any Korean word': 'Domina la estructura de bloques y podrás pronunciar cualquier palabra coreana',
    // ── Lesson Header — Pronunciation ────────────────
    '8 sound change rules — why Korean spelling and pronunciation differ': '8 reglas de cambio de sonido — por qué la ortografía y la pronunciación coreana difieren',
    'Batchim, liaison, assimilation, tensification, palatalization, and more': 'Batchim, enlace, asimilación, tensificación, palatalización y más',
    'Fix the 6 most common mistakes English speakers make': 'Corrige los 6 errores más comunes de los hablantes de inglés',
    'Audio examples on every step — tap any word to hear it': 'Ejemplos de audio en cada paso — toca cualquier palabra para escucharla',
    // ── Lesson Header — Grammar ───────────────────────
    'Korean Grammar:': 'Gramática coreana:',
    'SOV word order — the verb always comes last': 'Orden SOV — el verbo siempre va al final',
    'Particles replace rigid word-position rules': 'Las partículas reemplazan las reglas rígidas de posición de palabras',
    '26 stages: sentences to advanced patterns': '26 etapas: de oraciones a patrones avanzados',
    'Most learners complete in under 90 minutes': 'La mayoría de los estudiantes completa en menos de 90 minutos',
    // ── Lesson Header — Nouns ────────────────────────
    '🏠 Beginner · Lesson 5': '🏠 Principiante · Lección 5', 'Common Korean': 'Coreano común',
    'Master people, family, place, time, and object nouns in Korean': 'Domina sustantivos de personas, familia, lugar, tiempo y objetos en coreano',
    'Learn how Korean counters (개, 명, 잔) work with numbers': 'Aprende cómo los contadores coreanos (개, 명, 잔) funcionan con los números',
    'Understand the possessive marker 의 and polite vs casual forms': 'Entiende el marcador posesivo 의 y las formas formales vs informales',
    // ── Lesson Header — Pronouns ─────────────────────
    '👥 Beginner · Lesson 4': '👥 Principiante · Lección 4',
    'Learn polite 저 vs casual 나, and why Korean often drops pronouns entirely': 'Aprende el formal 저 vs el informal 나, y por qué el coreano a menudo omite los pronombres',
    'Understand why 당신 is rarely used and how to address people naturally': 'Entiende por qué 당신 rara vez se usa y cómo dirigirse a las personas de forma natural',
    'Master 우리 (our/my), demonstratives (이것·그것·저것), and question words': 'Domina 우리 (nuestro/mi), demostrativos (이것·그것·저것) y palabras interrogativas',
    // ── Lesson Header — Vocabulary ────────────────────
    '🗂 21 Categories': '🗂 21 categorías',
    '🔊 Audio on every card': '🔊 Audio en cada tarjeta',
    'Covers 500+ core Korean words across 21 categories': 'Cubre 500+ palabras coreanas esenciales en 21 categorías',
    'Bite-sized steps with instant audio — tap any card to hear it': 'Pasos pequeños con audio instantáneo — toca cualquier tarjeta para escucharla',
    'Quizzes after every category to lock in your memory': 'Cuestionarios después de cada categoría para fijar la memoria',
    'Most learners finish each category in under 15 minutes': 'La mayoría de los estudiantes termina cada categoría en menos de 15 minutos',
    // ── Hangul Page ───────────────────────────────────
    '✏️ Starter · Lesson 1': '✏️ Inicio · Lección 1', 'Hangul Alphabet:': 'Alfabeto Hangul:',
    '⏱ 45 min read': '⏱ 45 min de lectura', '📊 Beginner': '📊 Principiante',
    '🔖 Hangul Basics · 한글 기초': '🔖 Hangul básico · 한글 기초',
    '🔡 Syllable Block Patterns': '🔡 Patrones de bloques de sílabas',
    '📘 Common Compound Batchim Examples': '📘 Ejemplos de batchim compuesto común',
    '👁 18,204 views': '👁 18.204 vistas',
    'What is Hangul? (한글이란?)': '¿Qué es el Hangul? (한글이란?)',
    'Basic Vowels (기본 모음)': 'Vocales básicas (기본 모음)', 'Hangul at a Glance': 'Hangul de un vistazo',
    'Basic Consonants': 'Consonantes básicas', 'Basic Vowels': 'Vocales básicas',
    'Double Consonants': 'Consonantes dobles', 'Compound Vowels': 'Vocales compuestas', 'Fun Fact': 'Dato curioso',
    'Why does ㅇ appear at the start?': '¿Por qué aparece ㅇ al inicio?',
    'Vowel Shape Mnemonics': 'Reglas mnemónicas de forma de vocales', 'About Hangul (한글)': 'Sobre el Hangul (한글)',
    'Basic Vowels (모음)': 'Vocales básicas (모음)',
    'Compound Vowels (복합 모음)': 'Vocales compuestas (복합 모음)',
    'Basic Consonants (자음)': 'Consonantes básicas (자음)', 'Syllable Blocks (음절)': 'Bloques de sílabas (음절)',
    'Tense (Double) Consonants — 쌍자음': 'Consonantes tensas (dobles) — 쌍자음',
    'Compound Batchim (겹받침)': 'Batchim compuesto (겹받침)',
    'Aspirated Consonants — 거센소리': 'Consonantes aspiradas — 거센소리', 'Quick Practice Quiz': 'Cuestionario de práctica rápida',
    'Did you know?': '¿Sabías que?', 'Vowel Harmony': 'Armonía vocálica', 'Reading Practice': 'Práctica de lectura',
    'The Tissue Test': 'La prueba del pañuelo', '10 basic vowels': '10 vocales básicas',
    '11 compound vowels': '11 vocales compuestas', '14 basic consonants': '14 consonantes básicas',
    '5 tense consonants': '5 consonantes tensas', '5 aspirated consonants': '5 consonantes aspiradas',
    'October 9 is Hangul Day (한글날) in South Korea — a national holiday celebrating the invention of the alphabet in 1443.': 'El 9 de octubre es el Día del Hangul (한글날) en Corea del Sur — un día festivo nacional que celebra la invención del alfabeto en 1443.',
    'Structure': 'Estructura', 'Example': 'Ejemplo', 'Reading': 'Lectura', 'Meaning': 'Significado',
    'Consonant + Vowel': 'Consonante + vocal', 'go (verb stem)': 'ir (raíz verbal)',
    'Consonant + Vowel + Consonant': 'Consonante + vocal + consonante', 'Korean (prefix)': 'Coreano (prefijo)',
    'Silent ㅇ + Vowel': 'ㅇ muda + vocal', 'ah! (exclamation)': '¡ah! (exclamación)',
    'Batchim': 'Batchim', 'Example Word': 'Palabra de ejemplo', 'Note': 'Nota', 'to read': 'leer',
    'to sit': 'sentarse', 'life': 'vida',
    'k (aspirated)': 'k (aspirada)', 't (aspirated)': 't (aspirada)',
    'p (aspirated)': 'p (aspirada)', 'ch (aspirated)': 'ch (aspirada)',
    '← Home': '← Inicio', 'Mark as Complete ✓': 'Marcar como completado ✓', 'Syllable Blocks →': 'Bloques de sílabas →',
    // ── Grammar Page ──────────────────────────────────
    'Word Order — SOV Structure (어순)': 'Orden de palabras — Estructura SOV (어순)',
    'Korean Particles (조사)': 'Partículas coreanas (조사)', 'Particle Practice': 'Práctica de partículas',
    'Speech Levels (존댓말 vs 반말)': 'Niveles de habla (존댓말 vs 반말)',
    'Present Tense (-아요/-어요)': 'Presente (-아요/-어요)',
    'Past Tense (-았어요/-었어요)': 'Pasado (-았어요/-었어요)',
    'Future Tense (-을 거예요/-ㄹ 거예요)': 'Futuro (-을 거예요/-ㄹ 거예요)',
    'Making Sentences Negative (부정문)': 'Oraciones negativas (부정문)',
    'Forming Questions (의문문)': 'Formar preguntas (의문문)',
    'WH- Question Words': 'Palabras interrogativas WH',
    'Essential Sentence Patterns (문형)': 'Patrones de oraciones esenciales (문형)',
    'Connectors: 그리고, 그래서, 그렇지만, 그런데': 'Conectores: 그리고, 그래서, 그렇지만, 그런데',
    'And, With: -하고, -(이)랑': 'Y, Con: -하고, -(이)랑',
    'To/From Someone: -한테, -한테서': 'A/De alguien: -한테, -한테서',
    'Telling Time (시간 말하기)': 'Decir la hora (시간 말하기)',
    'Counters (단위 명사)': 'Contadores (단위 명사)',
    'Present Progressive: -고 있어요': 'Presente progresivo: -고 있어요',
    'Particle': 'Partícula', 'Function': 'Función', 'Rule': 'Regla', 'Level': 'Nivel',
    'When to Use': 'Cuándo usar', 'Dictionary Form': 'Forma de diccionario', 'Stem': 'Raíz',
    'Conjugated': 'Conjugado', 'Counter': 'Contador', 'Used for': 'Usado para',
    'Vowel': 'Vocal', 'Shape Mnemonic': 'Regla mnemónica de forma', 'Mouth Position': 'Posición de la boca',
    'Time': 'Tiempo', 'Register': 'Registro', 'Used with': 'Usado con',
    'Formal equivalent': 'Equivalente formal', 'Korean · 한국어': 'Coreano · 한국어',
    'Translation · 번역': 'Traducción · 번역', 'Topic marker': 'Marcador de tema',
    'Subject marker': 'Marcador de sujeto', 'Object marker': 'Marcador de objeto',
    // ── Pronunciation Page ────────────────────────────
    '🔊 Beginner · Lesson 3': '🔊 Principiante · Lección 3', 'Pronunciation Guide:': 'Guía de pronunciación:',
    '⏱ 50 min read': '⏱ 50 min de lectura', '🔖 Pronunciation': '🔖 Pronunciación',
    '👁 14,837 views': '👁 14.837 vistas', 'sound change rules': 'reglas de cambio de sonido',
    'Batchim — Syllable-Final Consonants (받침)': 'Batchim — Consonantes al final de sílaba (받침)',
    '7 possible sounds': '7 sonidos posibles', 'Sound Group': 'Grupo de sonidos', 'Written As': 'Escrito como',
    'Pronounced As': 'Pronunciado como', 'Unreleased stops': 'Oclusivas no liberadas',
    // ── Syllable Blocks Page ──────────────────────────
    'The ㅇ Placeholder Rule': 'Regla del marcador ㅇ',
    'Vertical vs Horizontal Vowels': 'Vocales verticales vs horizontales',
    'Quick Visual Trick': 'Truco visual rápido', 'Building Your First Syllables': 'Construyendo tus primeras sílabas',
    'Adding Batchim — The Final Consonant': 'Añadiendo batchim — La consonante final',
    'Reading Real Korean Words': 'Leyendo palabras coreanas reales',
    'Practice & Summary': 'Práctica y resumen',
    '5 Rules for Korean Syllable Blocks': '5 reglas para los bloques de sílabas coreanas',
    '📝 Self-Test: Identify the Components': '📝 Autotest: Identifica los componentes',
    // ── Pronouns Page ─────────────────────────────────
    'Saying \'You\' in Korean': 'Cómo decir "tú" en coreano',
    'Third Person & We (그·그녀·우리)': 'Tercera persona y nosotros (그·그녀·우리)',
    'Demonstrative Pronouns (이·그·저)': 'Pronombres demostrativos (이·그·저)',
    'Question Pronouns (의문대명사)': 'Pronombres interrogativos (의문대명사)',
    'Pronouns Complete!': '¡Pronombres completados!',
    // ── Emotions Page ─────────────────────────────────
    '😊 Intermediate · Lesson 7': '😊 Intermedio · Lección 7',
    'Core Emotions': 'Emociones básicas', 'Expressing Feelings': 'Expresar sentimientos',
    'Complex Emotions': 'Emociones complejas', 'Emotional Phrases': 'Frases emocionales',
    'Emotions in Korean (감정)': 'Emociones en coreano (감정)',
    'Emotions Complete!': '¡Emociones completadas!',
    // ── Shopping Page ─────────────────────────────────
    '🛒 Intermediate · Lesson 8': '🛒 Intermedio · Lección 8',
    'Shopping Vocabulary': 'Vocabulario de compras', 'In the Store': 'En la tienda', 'Prices & Numbers': 'Precios y números',
    'Transactions': 'Transacciones', 'Shopping in Korea (쇼핑)': 'Compras en Corea (쇼핑)',
    'Shopping Complete!': '¡Compras completadas!',
    // ── Speech Levels Page ────────────────────────────
    '🗣️ Intermediate · Lesson 6': '🗣️ Intermedio · Lección 6',
    '합쇼체 (Formal)': '합쇼체 (Formal)', '해요체 (Polite)': '해요체 (Cortés)',
    '반말 (Casual)': '반말 (Informal)', 'Choosing a Level': 'Elegir un nivel',
    'Korean Speech Levels Overview': 'Resumen de los niveles de habla coreanos',
    'Speech Levels Complete!': '¡Niveles de habla completados!',
    // ── Vocab Browser ───────────────────────────────────
    'Vocab Browser': 'Explorador de vocabulario',
    'saved to flashcards': 'guardadas en tarjetas',
    'Loading vocabulary…': 'Cargando vocabulario…',
    'No words match your search.': 'Ninguna palabra coincide con tu búsqueda.',
    'Failed to load vocabulary.': 'Error al cargar el vocabulario.',
    'Search Korean, English, or romanization…': 'Buscar en coreano, inglés o romanización…',
    '★ Add all in category': '★ Añadir todo en categoría',
    'Verbs': 'Verbos',
    'Health': 'Salud',
    'Media': 'Medios',
    'Proverbs': 'Proverbios',
    'Academic': 'Académico',
    // ── Progress system (streak / counters / resume) ────
    '✓ Correct!': '✓ ¡Correcto!',
    '✗ Not quite — try again!': '✗ Casi — ¡inténtalo de nuevo!',
    '{n}-day streak': 'Racha de {n} días',
    '{n} steps today': '{n} pasos hoy',
    'Continue': 'Continuar',
    'Step {n} of {m}': 'Paso {n} de {m}',
    'Steps completed': 'Pasos completados',
    'Words & phrases learned': 'Palabras y frases aprendidas',
    'Letters & syllables learned': 'Letras y sílabas aprendidas',
    'Best streak': 'Mejor racha',
    'Start Again': 'Empezar de nuevo',
    'Next Lesson →': 'Siguiente lección →',
    'Next →': 'Siguiente →',
    'Progress': 'Progreso',
    'Reset all progress': 'Restablecer todo el progreso',
    '🔥 Daily streak + real progress tracking': '🔥 Racha diaria + seguimiento real del progreso'
  };
  if (window.LangManager) window.LangManager.register('es', ES);
})();
