'use strict';
(function() {
  const FR = {
    // ── Navigation & Global UI ─────────────────────────
    'Learn': 'Apprendre', 'Quiz': 'Quiz', 'K-Culture': 'K-Culture', 'Travel': 'Voyage', 'News': 'Actualités',
    'Search...': 'Rechercher...', 'Search lessons, vocabulary…': 'Rechercher des leçons, du vocabulaire…', 'Search lessons...': 'Rechercher des leçons...',
    'Loading lesson…': 'Chargement de la leçon…', 'Previous': 'Précédent', 'Next': 'Suivant', '📚 Lesson 4 · vocabulary': '📚 Leçon 4 · Vocabulaire',
    'Search Results': 'Résultats de recherche', '← Back to Home': "← Retour à l'accueil",
    '🇰🇷 · Free · For Every Level': '🇰🇷 · Gratuit · Pour tous les niveaux',
    'Learn Korean': 'Apprendre le coréen', 'Start Learning': 'Commencer', 'Explore K-Culture': 'Explorer la K-Culture',
    'Vocabulary Words': 'Mots de vocabulaire', 'Lessons': 'Leçons', 'Active Learners': 'Apprenants actifs', '% Free': '% Gratuit',
    'FEATURES': 'FONCTIONNALITÉS', 'Everything You Need to Learn Korean': 'Tout ce qu\'il vous faut pour apprendre le coréen',
    'Start with 한글': 'Commencer avec 한글', 'Learn Hangul Now →': 'Apprendre le Hangul maintenant →',
    'Hear It': 'Écouter', 'More Words': 'Plus de mots', 'Word of the Day': 'Mot du jour',
    'STRUCTURED PATHS · 학습 경로': 'Parcours structurés · 학습 경로',
    'Choose Your Learning Path': 'Choisissez votre parcours',
    'Beginner': 'Débutant', 'Intermediate': 'Intermédiaire', 'Advanced': 'Avancé',
    'Start Beginner Path →': 'Commencer le parcours débutant →', 'Start Intermediate Path →': 'Commencer le parcours intermédiaire →',
    'Start Advanced Path →': 'Commencer le parcours avancé →', 'POPULAR': 'POPULAIRE',
    'Beginner–Intermediate': 'Débutant–Intermédiaire', 'Intermediate–Advanced': 'Intermédiaire–Avancé',
    'Beg–Int': 'Déb–Int',
    // ── K-Culture & Home ──────────────────────────────
    'K-CULTURE': 'K-CULTURE', 'K-CULTURE · 한국 문화': 'K-CULTURE · 한국 문화',
    'Experience Korea Beyond Language': 'Vivez la Corée au-delà de la langue',
    'Explore All K-Culture Content →': 'Explorer tout le contenu K-Culture →',
    'TRAVEL · 여행': 'VOYAGE · 여행', 'Explore Korea': 'Explorer la Corée',
    'View Full Travel Guide →': 'Voir le guide de voyage complet →',
    'PRACTICE · 연습': 'PRATIQUE · 연습',
    '10 progressive levels · multiple choice · covers Hangul, Grammar & Vocabulary': '10 niveaux progressifs · QCM · couvre le Hangul, la grammaire et le vocabulaire',
    'Choose a Level': 'Choisissez un niveau', 'questions': 'questions', '← All Levels': '← Tous les niveaux',
    'Try Again': 'Réessayer', 'Next Level': 'Niveau suivant', 'All Levels': 'Tous les niveaux',
    'Next Level →': 'Niveau suivant →',
    // ── Travel ────────────────────────────────────────
    '🇰🇷 · South Korea Travel Guide · 여행 안내': '🇰🇷 · Guide de voyage en Corée du Sud · 여행 안내',
    'South Korea Travel Guide': 'Guide de voyage en Corée du Sud',
    'Population': 'Population', 'UNESCO Sites': 'Sites UNESCO',
    'Great to visit': 'Idéal à visiter', 'Visa-free nations': 'Pays sans visa',
    'EXPLORE THE GUIDES · 가이드 탐색': 'EXPLORER LES GUIDES · 가이드 탐색',
    'Plan Your Perfect Korea Trip': 'Planifiez votre voyage parfait en Corée',
    'TOP DESTINATIONS · 인기 여행지': 'TOP DESTINATIONS · 인기 여행지',
    'Where Will You Explore?': 'Où allez-vous explorer ?',
    'ESSENTIAL PHRASES · 필수 표현': 'PHRASES ESSENTIELLES · 필수 표현',
    'Travel Korean Phrasebook': 'Guide de phrases coréennes pour voyageurs',
    'TRANSPORTATION · 교통': 'TRANSPORTS · 교통', 'Getting Around Korea': 'Se déplacer en Corée',
    'FOOD TOUR · 음식 여행': 'TOUR GASTRONOMIQUE · 음식 여행', 'Regional Korean Specialties': 'Spécialités régionales coréennes',
    'CULTURAL ETIQUETTE · 예절': 'ÉTIQUETTE CULTURELLE · 예절', 'Korean Cultural Tips': 'Conseils culturels coréens',
    'TRAVEL APPS · 여행 앱': 'APPLICATIONS DE VOYAGE · 여행 앱', 'Essential Apps for Korea Travel': 'Applications essentielles pour voyager en Corée',
    'READY TO LEARN?': 'PRÊT À APPRENDRE ?', 'Start Speaking Korean Today': 'Commencez à parler coréen aujourd\'hui',
    'Start Learning Korean →': 'Commencer à apprendre le coréen →', 'Plan Your Trip': 'Planifiez votre voyage',
    'K-Pop': 'K-Pop', 'K-Drama': 'K-Drama', 'K-Beauty': 'K-Beauty', 'All': 'Tout',
    // ── Footer & Company ──────────────────────────────
    'Learn · 학습': 'Apprendre · 학습', 'K-Culture · 문화': 'K-Culture · 문화',
    'Company · 회사': 'Entreprise · 회사', 'Explore': 'Explorer', 'Company': 'Entreprise',
    'Hangul Alphabet': 'Alphabet Hangul', 'Grammar': 'Grammaire', 'Vocabulary': 'Vocabulaire',
    'Travel Guide': 'Guide de voyage', 'Korean News': 'Actualités coréennes', 'About Us': 'À propos',
    'Contact': 'Contact', 'Privacy Policy': 'Politique de confidentialité', 'Terms of Use': 'Conditions d\'utilisation',
    'Made with ❤️ for Korean learners worldwide.': 'Fait avec ❤️ pour les apprenants de coréen du monde entier.',
    '🇰🇷 학습을 즐기세요! (Enjoy your learning!)': '🇰🇷 학습을 즐기세요! (Profitez de votre apprentissage !)',
    'Home': 'Accueil', 'Hangul': 'Hangul',
    'A free Korean language learning platform — combining language study with K-culture, travel guides, and real-world practice. For learners of every level, worldwide.': 'Plateforme gratuite d\'apprentissage du coréen — alliant étude de la langue, K-culture, guides de voyage et pratique réelle. Pour les apprenants de tous niveaux, dans le monde entier.',
    'A free Korean language learning platform for learners of every level, worldwide.': 'Plateforme gratuite d\'apprentissage du coréen pour tous les niveaux, partout dans le monde.',
    '© 2026 한국어 학교. Made with ❤️ for Korean learners worldwide.': '© 2026 한국어 학교. Fait avec ❤️ pour les apprenants de coréen du monde entier.',
    // ── Sidebar Dividers ──────────────────────────────
    'Getting Started': 'Pour commencer', 'Tools': 'Outils',
    'CATEGORIES · 카테고리': 'CATÉGORIES · 카테고리', 'DEEP DIVES · 심층 탐구': 'APPROFONDISSEMENTS · 심층 탐구',
    // ── Learn Sidebar ─────────────────────────────────
    'Introduction': 'Introduction', 'Syllable Blocks': 'Blocs syllabiques', 'Pronunciation Guide': 'Guide de prononciation',
    'Vocab': 'Vocabulaire', 'Greetings': 'Salutations', 'Numbers': 'Nombres', 'Family': 'Famille',
    'Food & Drink': 'Nourriture & Boissons', 'Colors': 'Couleurs', 'Days & Time': 'Jours & Temps', 'Places': 'Lieux',
    'Emotions': 'Émotions', 'Body Parts': 'Parties du corps', 'Shopping': 'Shopping', 'Weather': 'Météo',
    'Verbs & Actions': 'Verbes & Actions', 'Adjectives': 'Adjectifs', 'Workplace': 'Lieu de travail',
    'Health & Medicine': 'Santé & Médecine', 'Media & K-Culture': 'Médias & K-Culture',
    'Proverbs & Idioms': 'Proverbes & Expressions', 'Academic Korean': 'Coréen académique',
    'News & Society': 'Actualités & Société', 'Konglish': 'Konglish', 'Pronouns': 'Pronoms',
    'Common Nouns': 'Noms communs', 'Sentence Structure': 'Structure des phrases', 'Korean Particles': 'Particules coréennes',
    'Verb Conjugation': 'Conjugaison verbale', 'Question Forms': 'Formes interrogatives', 'Connectors': 'Connecteurs',
    'And, With': 'Et, Avec', 'To/From Someone': 'À/De quelqu\'un', 'Telling Time': 'Dire l\'heure',
    'Counters': 'Compteurs', 'Present Progressive': 'Présent progressif', 'Self Introduction': 'Présentation',
    'Dates and Months': 'Dates et mois', 'Degree Adverbs': 'Adverbes de degré',
    'Nominalizer -는 것': 'Nominalisateur -는 것', 'Comparatives': 'Comparatifs',
    'Still, Already': 'Encore, Déjà', 'Someone, Something': 'Quelqu\'un, Quelque chose',
    'Imperative -(으)세요': 'Impératif -(으)세요', 'Don\'t: -지 마세요': 'Ne pas : -지 마세요',
    'Method: -(으)로': 'Méthode : -(으)로', 'Good/Poor At': 'Bon/Mauvais en',
    '-도 Advanced Uses': 'Usages avancés de 도', 'Formal vs Informal': 'Formel vs Informel',
    'Expressing Emotions': 'Exprimer les émotions', 'Shopping Phrases': 'Phrases pour le shopping', 'Writing Essays': 'Rédiger des essais',
    'Business Korean': 'Coréen des affaires', 'Classical Korean': 'Coréen classique', 'Korean Dialogues': 'Dialogues en coréen',
    'Flashcards': 'Fiches de révision',
    // ── Culture Sidebar ───────────────────────────────
    'K-Movie': 'K-Cinéma', 'K-Food': 'K-Gastronomie', 'K-Fashion': 'K-Mode',
    'Korean Thing': 'Trucs coréens', 'K-Gaming': 'K-Gaming', 'K-Sports': 'K-Sports',
    'K-Pop, K-Drama, food, beauty, fashion, gaming, sports & traditions.': 'K-Pop, K-Drama, gastronomie, beauté, mode, gaming, sports et traditions.',
    'K-Pop History': 'Histoire du K-Pop', 'Agencies': 'Agences', 'Generations': 'Générations', 'Genres': 'Genres',
    'Variety Shows': 'Émissions de variétés', 'Film & Acting': 'Cinéma & Jeu d\'acteur', 'Idol Phrases': 'Phrases d\'idoles',
    'Fan Slang': 'Argot des fans', 'Fan Chants': 'Chants de fans', 'Drama History': 'Histoire du K-Drama',
    'Drama Genres': 'Genres de K-Drama', 'Must-Watch Dramas': 'Dramas incontournables', 'K-Drama Tropes': 'Clichés du K-Drama',
    'Speech Levels': 'Niveaux de langage', 'Dialogue Practice': 'Pratique des dialogues',
    'Fan Culture & Slang': 'Culture et argot des fans', 'Movie History': 'Histoire du cinéma',
    'Movie Genres': 'Genres de films', 'Must-Watch Films': 'Films incontournables', 'Directors': 'Réalisateurs',
    'Iconic Lines': 'Répliques cultes', 'Fan Culture': 'Culture des fans',
    'K-Food Goes Global': 'La K-Gastronomie conquiert le monde', 'Foods That Went Global': 'Aliments devenus mondiaux',
    'K-Food Timeline': 'Chronologie de la K-Gastronomie', 'Essential Dishes': 'Plats essentiels',
    'World-Famous Chefs': 'Chefs de renommée mondiale', 'Ordering & Dining': 'Commander & Manger',
    'Street Food': 'Street food', 'Food Culture & Drinking': 'Culture culinaire & boissons',
    'Ramyeon Guide': 'Guide du ramyeon', 'Mandu Guide': 'Guide du mandu',
    'Chicken Guide': 'Guide du poulet frit', 'K-BBQ Guide': 'Guide du K-BBQ', 'Kimchi Guide': 'Guide du kimchi',
    'K-Beauty Goes Global': 'La K-Beauty conquiert le monde', 'K-Beauty Timeline': 'Chronologie de la K-Beauty',
    'Iconic Brands': 'Marques emblématiques', 'Beauty Vocabulary': 'Vocabulaire de beauté', '10-Step Skincare': 'Routine beauté en 10 étapes',
    'Key Ingredients': 'Ingrédients clés', 'Beauty Trends': 'Tendances beauté', 'Makeup Philosophy': 'Philosophie du maquillage',
    'Skin Clinic Culture': 'Culture des cliniques esthétiques', 'K-Beauty Dialogue': 'Dialogue K-Beauty',
    'K-Fashion Global': 'K-Mode mondiale', 'Fashion Icons': 'Icônes de mode',
    'Fashion Timeline': 'Chronologie de la mode', 'Style Aesthetics': 'Esthétique de style', 'Idol Fashion': 'Mode des idoles',
    'Seoul Fashion Week': 'Semaine de la mode de Séoul', 'Fashion Vocabulary': 'Vocabulaire de mode',
    'Fashion Districts': 'Quartiers de mode', 'Shopping Dialogue': 'Dialogue shopping',
    'Hanbok & Traditional Fashion': 'Hanbok et mode traditionnelle', 'Rice Obsession': 'Obsession du riz',
    'Youth Protection Laws': 'Lois de protection de la jeunesse', 'Fast Delivery Culture': 'Culture de la livraison rapide',
    'Invasive Species Crisis': 'Crise des espèces invasives', 'Table Call Culture': 'Culture du bouton d\'appel',
    'Public Transport': 'Transports en commun', 'Jjimjilbang': 'Jjimjilbang', 'Plastic Surgery Culture': 'Culture de la chirurgie esthétique',
    'Outdoor Drinking': 'Boire en plein air', 'Jeonse Housing': 'Système de logement jeonse',
    'Traditions & Holidays': 'Traditions & Fêtes', '100 Korean Proverbs': '100 proverbes coréens',
    'K-Gaming Stats': 'Statistiques K-Gaming', 'Gaming Timeline': 'Chronologie du gaming',
    'Gaming Legends': 'Légendes du gaming', 'Iconic Games': 'Jeux emblématiques', 'Streaming Culture': 'Culture du streaming',
    'PC Bang Culture': 'Culture PC bang', 'PC방 Culture': 'Culture PC방', 'Esports Leagues': 'Ligues d\'esports',
    'Gamer Slang': 'Argot gamer', 'Gaming Vocabulary': 'Vocabulaire gaming', 'Sports Overview': 'Panorama sportif',
    'Football Heroes': 'Héros du football', 'Baseball Heroes': 'Héros du baseball', 'Marathon Legends': 'Légendes du marathon',
    'Individual Legends': 'Légendes individuelles', 'Traditional Sports': 'Sports traditionnels', 'Cheer Chants': 'Chants de soutien',
    // ── Travel Sidebar ────────────────────────────────
    'Travel Guide · 여행 안내': 'Guide de voyage · 여행 안내', 'South Korea': 'Corée du Sud',
    'By Days · 일수별': 'Par jours · 일수별', '1 Day Trip · 당일치기': 'Excursion d\'1 jour · 당일치기',
    '2 Days · 1박 2일': '2 jours · 1박 2일', '3 Days · 2박 3일': '3 jours · 2박 3일',
    '5 Days · 4박 5일': '5 jours · 4박 5일', '1 Week · 일주일': '1 semaine · 일주일',
    '10 Days': '10 jours', '2 Weeks · 2주': '2 semaines · 2주', '1 Month+ · 한달': '1 mois et plus · 한달',
    'By City · 도시별': 'Par ville · 도시별', 'Seoul · 서울': 'Séoul · 서울',
    'Incheon · 인천': 'Incheon · 인천', 'Busan · 부산': 'Busan · 부산',
    'Suwon · 수원': 'Suwon · 수원', 'Jeju · 제주도': 'Jeju · 제주도',
    'Gyeongju · 경주': 'Gyeongju · 경주', 'Other Cities': 'Autres villes',
    'By Theme · 테마별': 'Par thème · 테마별', 'Food Tour · 음식 여행': 'Tour gastronomique · 음식 여행',
    'Events & Festivals · 이벤트': 'Événements & Festivals · 이벤트', 'Sightseeing · 관광': 'Tourisme · 관광',
    'Cross-Country · 장거리': 'Longue distance · 장거리',
    '📋 Trip Planner · 여행 계획표': '📋 Planificateur de voyage · 여행 계획표',
    'Day-by-Day Itineraries': 'Itinéraires jour par jour', 'City Travel Guides': 'Guides de voyage par ville',
    'Themed Travel': 'Voyages thématiques', 'Bus': 'Bus', 'Subway': 'Métro', 'Taxi': 'Taxi',
    'KTX High-speed Rail': 'KTX Train à grande vitesse', 'Age': 'Âge', 'Bowing': 'Révérence',
    'Drinking': 'Alcool', 'Eating': 'Manger', 'Quiet': 'Silence', 'Shoes': 'Chaussures',
    'Tipping': 'Pourboire', 'Two Hands': 'Deux mains',
    'International': 'International', 'Politics': 'Politique', 'Economy': 'Économie', 'Society': 'Société',
    'Science': 'Science', 'Culture': 'Culture', 'Sports': 'Sports', 'Education': 'Éducation',
    'Environment': 'Environnement',
    // ── Homepage Descriptions ─────────────────────────
    'Discover the beauty of Korea through language, culture, K-pop, travel, and cuisine — with free lessons designed for learners worldwide.': 'Découvrez la beauté de la Corée à travers la langue, la culture, le K-Pop, les voyages et la cuisine — avec des leçons gratuites pour les apprenants du monde entier.',
    'Learn the Korean alphabet in just 2 hours. 한글 (Hangul) is remarkably logical — once you know the 24 basic letters, you can read anything.': 'Apprenez l\'alphabet coréen en seulement 2 heures. 한글 (Hangul) est remarquablement logique — une fois que vous connaissez les 24 lettres de base, vous pouvez tout lire.',
    'Learn Korean naturally through your favourite songs. Line-by-line breakdowns with vocabulary, grammar notes, and pronunciation guides.': 'Apprenez le coréen naturellement à travers vos chansons préférées. Décryptage ligne par ligne avec vocabulaire, notes de grammaire et guides de prononciation.',
    'Pick up everyday Korean from your favourite dramas. Contextual vocabulary lists organised by show, genre, and proficiency level.': 'Apprenez le coréen du quotidien à travers vos dramas préférés. Listes de vocabulaire contextuelles organisées par émission, genre et niveau.',
    'From 김치 (kimchi) to 삼겹살 (samgyeopsal) — explore the rich vocabulary of Korean cuisine with pronunciation and cultural context.': 'Du 김치 (kimchi) au 삼겹살 (samgyeopsal) — explorez le riche vocabulaire de la cuisine coréenne avec prononciation et contexte culturel.',
    'Whether you are just starting or aiming for fluency, we have a clear roadmap to take you there step by step.': 'Que vous débutiez ou visiez la fluidité, nous avons une feuille de route claire pour vous y emmener étape par étape.',
    'Language is the gateway — immerse yourself in Korean pop culture, food, and beauty to supercharge your learning.': 'La langue est la porte d\'entrée — plongez dans la pop culture coréenne, la gastronomie et la beauté pour booster votre apprentissage.',
    'From BTS to BLACKPINK — the most common Korean words and phrases used by your favourite K-Pop artists, with pronunciation guides.': 'De BTS à BLACKPINK — les mots et phrases coréens les plus courants utilisés par vos artistes K-Pop préférés, avec guides de prononciation.',
    'Korean dramas are packed with emotional vocabulary. Learn how characters express joy, sadness, anger, and love in authentic Korean.': 'Les K-Dramas regorgent de vocabulaire émotionnel. Apprenez comment les personnages expriment joie, tristesse, colère et amour en coréen authentique.',
    'Essential phrases for ordering food, asking for the bill, and navigating a Korean restaurant menu with confidence.': 'Phrases essentielles pour commander, demander l\'addition et naviguer un menu de restaurant coréen avec confiance.',
    'Explore the world of K-Beauty with essential vocabulary for skincare routines, cosmetics, and Korean beauty trends.': 'Explorez le monde de la K-Beauty avec le vocabulaire essentiel pour les routines de soin, les cosmétiques et les tendances beauté coréennes.',
    'Learn the language of every destination. From bustling Seoul to the serene shores of Jeju — your AI travel guide is ready.': 'Apprenez la langue de chaque destination. Du trépidant Séoul aux rivages sereins de Jeju — votre guide de voyage IA est prêt.',
    "South Korea's dazzling capital — from the ancient palaces of Gyeongbokgung to the neon streets of Gangnam and Hongdae.": 'La capitale éblouissante de la Corée du Sud — des anciens palais de Gyeongbokgung aux rues néon de Gangnam et Hongdae.',
    "Korea's vibrant port city with stunning beaches, fresh seafood markets, and a unique dialect worth discovering.": 'La vibrante ville portuaire de Corée avec des plages époustouflantes, des marchés de fruits de mer frais et un dialecte unique à découvrir.',
    "Korea's paradise island — volcanic landscapes, pristine beaches, tangerine groves, and the famous haenyeo diving culture.": 'L\'île paradisiaque de Corée — paysages volcaniques, plages vierges, vergers de mandarines et la célèbre culture de plongée haenyeo.',
    // ── Homepage Place Names & Quiz ───────────────────
    'Seoul': 'Séoul', 'Busan': 'Busan', 'Jeju Island': 'Île de Jeju',
    'Test Your Korean': 'Testez votre coréen', 'Explore →': 'Explorer →',
    // ── Homepage Cards & Labels ───────────────────────
    'K-Pop Lyrics Learning': 'Apprentissage par les paroles K-Pop', 'K-Drama Vocabulary': 'Vocabulaire K-Drama',
    'Korean Food Dictionary': 'Dictionnaire de la cuisine coréenne',
    'Master Korean Emotions Through K-Drama': 'Maîtrisez les émotions coréennes avec le K-Drama',
    'Order Like a Local: Restaurant Korean': 'Commandez comme un local : le coréen au restaurant',
    'Beauty & Skincare Vocabulary in Korean': 'Vocabulaire beauté & soin en coréen',
    'K-Pop Stars\' Korean Phrases You Need to Know': 'Phrases coréennes des stars K-Pop à connaître',
    'Read →': 'Lire →', 'Hello / Good day': 'Bonjour / Bonne journée',
    'annyeonghaseyo': 'an-nyeong-ha-se-yo',
    // ── Learning Path Checklist ───────────────────────
    '✓ Hangul Alphabet': '✓ Alphabet Hangul', '✓ Basic Vowels & Consonants': '✓ Voyelles & consonnes de base',
    '✓ Syllable Blocks': '✓ Blocs syllabiques', '✓ Essential Vocabulary': '✓ Vocabulaire essentiel',
    '✓ Basic Greetings': '✓ Salutations de base', '✓ Korean Grammar (SOV)': '✓ Grammaire coréenne (SOV)',
    '✓ Particles & Conjugation': '✓ Particules & conjugaison', '✓ Speech Levels': '✓ Niveaux de langage',
    '✓ 300+ Vocabulary Words': '✓ 300+ mots de vocabulaire', '✓ Real Dialogues': '✓ Dialogues réels',
    '✓ Business Korean': '✓ Coréen des affaires', '✓ Classical Korean': '✓ Coréen classique',
    '✓ Essay Writing': '✓ Rédaction', '✓ TOPIK Preparation': '✓ Préparation TOPIK',
    '✓ Idiomatic Expressions': '✓ Expressions idiomatiques',
    // ── Homepage Eyebrow Labels ───────────────────────
    'Hangul Basics · 한글 기초': 'Bases du Hangul · 한글 기초',
    'Korean Grammar · 문법': 'Grammaire coréenne · 문법', 'Vocabulary · 어휘': 'Vocabulaire · 어휘',
    'Pronunciation · 발음': 'Prononciation · 발음',
    'Korean Food · 음식': 'Cuisine coréenne · 음식', 'K-Beauty · 뷰티': 'K-Beauty · 뷰티',
    'K-Drama · 드라마': 'K-Drama · 드라마', 'K-Pop Lyrics · 가사': 'Paroles K-Pop · 가사',
    'TOPIK Prep · 토픽 준비': 'Préparation TOPIK · 토픽 준비',
    'Flashcards · 플래시카드': 'Fiches de révision · 플래시카드',
    'Start Here · 여기서 시작': 'Commencer ici · 여기서 시작',
    'Daily Vocabulary · 오늘의 단어': 'Vocabulaire quotidien · 오늘의 단어',
    'Travel Guide · 여행': 'Guide de voyage · 여행', 'Blog · 블로그': 'Blog · 블로그',
    'About Us · 소개': 'À propos · 소개', 'Contact · 연락처': 'Contact · 연락처',
    'Seoul · 서울': 'Séoul · 서울', 'Busan · 부산': 'Busan · 부산', 'Jeju · 제주': 'Jeju · 제주',
    'Privacy': 'Confidentialité', 'Terms': 'Conditions', 'Terms of Service': 'Conditions d\'utilisation',
    'K-FOOD · 한국 음식': 'K-GASTRONOMIE · 한국 음식',
    // ── Food Page Stats ───────────────────────────────
    'Charcoal grill (best)': 'Grill au charbon (le meilleur)', 'Side dishes (free refill)': 'Accompagnements (resservis gratuitement)',
    'Lettuce wrap style': 'Style wrap à la laitue',
    // ── Lesson Header Meta ────────────────────────────
    'About this lesson': 'À propos de cette leçon', 'Korean Grammar': 'Grammaire coréenne',
    '✏️ Beginner · Lesson 1': '✏️ Débutant · Leçon 1',
    '📐 Intermediate · Lesson 7': '📐 Intermédiaire · Leçon 7', '60 min read': '60 min de lecture',
    'Alphabet': 'Alphabet', '📐 Intermediate · Lesson 5': '📐 Intermédiaire · Leçon 5',
    '🎯 26 Stages · 70 Steps': '🎯 26 étapes · 70 pas',
    '📊 Beginner–Advanced': '📊 Débutant–Avancé', '⏱️ ~90 min': '⏱️ ~90 min',
    '⚡ XP + Streak system': '⚡ Système XP + série',
    '📝 Advanced · Lesson 12': '📝 Avancé · Leçon 12', '✍️ Essay Structure Guide': '✍️ Guide de structure d\'essai',
    '📊 Advanced': '📊 Avancé', '🔖 Writing': '🔖 Rédaction', '🔗 Connective Grammar': '🔗 Grammaire connective',
    '💼 Advanced · Lesson 13': '💼 Avancé · Leçon 13', '🏢 Workplace Expressions': '🏢 Expressions professionnelles',
    '🔖 Professional': '🔖 Professionnel', '🤝 Business Etiquette': '🤝 Étiquette professionnelle',
    '📜 Advanced · Lesson 14': '📜 Avancé · Leçon 14', '📜 Hanja (한자) Roots': '📜 Racines Hanja (한자)',
    '🔖 History & Literature': '🔖 Histoire & Littérature', '🏛️ Historical Korean Texts': '🏛️ Textes historiques coréens',
    '💬 All Levels · 40 Dialogues': '💬 Tous niveaux · 40 dialogues',
    '💬 40 Full Dialogues': '💬 40 dialogues complets', '📊 All Levels': '📊 Tous niveaux',
    '🔖 Real-world Korean': '🔖 Coréen du monde réel', '🔊 Audio on Every Line': '🔊 Audio sur chaque ligne',
    // ── Lesson Header — Shared Meta ───────────────────
    'Korean': 'Coréen', 'Expressing': 'Exprimer', 'Nouns': 'Noms',
    '📊 Intermediate': '📊 Intermédiaire', '📊 Beginner–Intermediate': '📊 Débutant–Intermédiaire',
    '🎯 6 Stages · 84 Steps': '🎯 6 étapes · 84 pas',
    '🎯 5 Stages · 61 Steps': '🎯 5 étapes · 61 pas',
    '🎯 6 Stages · 68 Steps': '🎯 6 étapes · 68 pas',
    '⏱️ ~60–90 min': '⏱️ ~60–90 min', '⏱️ ~50 min': '⏱️ ~50 min', '⏱️ ~60 min': '⏱️ ~60 min',
    '⏱ 30 min': '⏱ 30 min', '⏱ 28 min': '⏱ 28 min', '⏱ 29 min': '⏱ 29 min',
    '🔊 Audio on every word': '🔊 Audio sur chaque mot',
    '🔊 Audio on every phrase': '🔊 Audio sur chaque phrase',
    '🔊 Audio on every form': '🔊 Audio sur chaque forme',
    '4 stages with listen-and-repeat audio and quizzes throughout': '4 étapes avec audio écoute-et-répète et quiz tout au long',
    // ── Lesson Header — Hangul ────────────────────────
    'Learn Hangul in 1 Hour:': 'Apprendre le Hangul en 1 heure :',
    'Created in 1443 by King Sejong the Great': 'Créé en 1443 par le roi Sejong le Grand',
    'Phonetic alphabet — each symbol = one sound': 'Alphabet phonétique — chaque symbole = un son',
    '6 stages to cover every character': '6 étapes pour couvrir chaque caractère',
    'Most learners finish in under 90 minutes': 'La plupart des apprenants terminent en moins de 90 minutes',
    // ── Lesson Header — Syllable Blocks ──────────────
    '🔷 Beginner · Lesson 2': '🔷 Débutant · Leçon 2',
    'Korean Syllable Blocks:': 'Blocs syllabiques coréens :',
    'Every syllable is a compact square block — not a horizontal letter string': 'Chaque syllabe est un bloc carré compact — pas une suite de lettres horizontale',
    'Each block holds exactly 1 vowel plus up to 2 consonants': 'Chaque bloc contient exactement 1 voyelle et jusqu\'à 2 consonnes',
    '4 structural patterns: CV, V, CVC, VC — all follow the same rules': '4 modèles structurels : CV, V, CVC, VC — tous suivent les mêmes règles',
    'Master the block structure and you can sound out any Korean word': 'Maîtrisez la structure en blocs et vous pourrez prononcer n\'importe quel mot coréen',
    // ── Lesson Header — Pronunciation ────────────────
    '8 sound change rules — why Korean spelling and pronunciation differ': '8 règles de changement de son — pourquoi l\'orthographe et la prononciation coréennes diffèrent',
    'Batchim, liaison, assimilation, tensification, palatalization, and more': 'Batchim, liaison, assimilation, tensification, palatalisation et plus encore',
    'Fix the 6 most common mistakes English speakers make': 'Corrigez les 6 erreurs les plus courantes des anglophones',
    'Audio examples on every step — tap any word to hear it': 'Exemples audio à chaque étape — touchez n\'importe quel mot pour l\'entendre',
    // ── Lesson Header — Grammar ───────────────────────
    'Korean Grammar:': 'Grammaire coréenne :',
    'SOV word order — the verb always comes last': 'Ordre SOV — le verbe vient toujours en dernier',
    'Particles replace rigid word-position rules': 'Les particules remplacent les règles de position strictes',
    '26 stages: sentences to advanced patterns': '26 étapes : des phrases aux schémas avancés',
    'Most learners complete in under 90 minutes': 'La plupart des apprenants terminent en moins de 90 minutes',
    // ── Lesson Header — Nouns ────────────────────────
    '🏠 Beginner · Lesson 5': '🏠 Débutant · Leçon 5', 'Common Korean': 'Coréen courant',
    'Master people, family, place, time, and object nouns in Korean': 'Maîtrisez les noms de personnes, famille, lieu, temps et objets en coréen',
    'Learn how Korean counters (개, 명, 잔) work with numbers': 'Apprenez comment les compteurs coréens (개, 명, 잔) fonctionnent avec les nombres',
    'Understand the possessive marker 의 and polite vs casual forms': 'Comprenez le marqueur possessif 의 et les formes polies vs informelles',
    // ── Lesson Header — Pronouns ─────────────────────
    '👥 Beginner · Lesson 4': '👥 Débutant · Leçon 4',
    'Learn polite 저 vs casual 나, and why Korean often drops pronouns entirely': 'Apprenez le poli 저 vs l\'informel 나, et pourquoi le coréen omet souvent les pronoms',
    'Understand why 당신 is rarely used and how to address people naturally': 'Comprenez pourquoi 당신 est rarement utilisé et comment s\'adresser naturellement aux gens',
    'Master 우리 (our/my), demonstratives (이것·그것·저것), and question words': 'Maîtrisez 우리 (notre/mon), les démonstratifs (이것·그것·저것) et les mots interrogatifs',
    // ── Lesson Header — Vocabulary ────────────────────
    '🗂 21 Categories': '🗂 21 catégories',
    '🔊 Audio on every card': '🔊 Audio sur chaque fiche',
    'Covers 500+ core Korean words across 21 categories': 'Couvre 500+ mots coréens essentiels dans 21 catégories',
    'Bite-sized steps with instant audio — tap any card to hear it': 'Étapes courtes avec audio instantané — touchez n\'importe quelle fiche pour l\'entendre',
    'Quizzes after every category to lock in your memory': 'Quiz après chaque catégorie pour ancrer votre mémoire',
    'Most learners finish each category in under 15 minutes': 'La plupart des apprenants terminent chaque catégorie en moins de 15 minutes',
    // ── Hangul Page ───────────────────────────────────
    '✏️ Starter · Lesson 1': '✏️ Débutant · Leçon 1', 'Hangul Alphabet:': 'Alphabet Hangul :',
    '⏱ 45 min read': '⏱ 45 min de lecture', '📊 Beginner': '📊 Débutant',
    '🔖 Hangul Basics · 한글 기초': '🔖 Bases du Hangul · 한글 기초',
    '🔡 Syllable Block Patterns': '🔡 Modèles de blocs syllabiques',
    '📘 Common Compound Batchim Examples': '📘 Exemples courants de batchim composé',
    '👁 18,204 views': '👁 18 204 vues',
    'What is Hangul? (한글이란?)': 'Qu\'est-ce que le Hangul ? (한글이란?)',
    'Basic Vowels (기본 모음)': 'Voyelles de base (기본 모음)', 'Hangul at a Glance': 'Hangul en un coup d\'œil',
    'Basic Consonants': 'Consonnes de base', 'Basic Vowels': 'Voyelles de base',
    'Double Consonants': 'Consonnes doubles', 'Compound Vowels': 'Voyelles composées', 'Fun Fact': 'Le saviez-vous ?',
    'Why does ㅇ appear at the start?': 'Pourquoi ㅇ apparaît-il au début ?',
    'Vowel Shape Mnemonics': 'Mnémotechniques des formes de voyelles', 'About Hangul (한글)': 'À propos du Hangul (한글)',
    'Basic Vowels (모음)': 'Voyelles de base (모음)',
    'Compound Vowels (복합 모음)': 'Voyelles composées (복합 모음)',
    'Basic Consonants (자음)': 'Consonnes de base (자음)', 'Syllable Blocks (음절)': 'Blocs syllabiques (음절)',
    'Tense (Double) Consonants — 쌍자음': 'Consonnes tendues (doubles) — 쌍자음',
    'Compound Batchim (겹받침)': 'Batchim composé (겹받침)',
    'Aspirated Consonants — 거센소리': 'Consonnes aspirées — 거센소리', 'Quick Practice Quiz': 'Quiz de pratique rapide',
    'Did you know?': 'Le saviez-vous ?', 'Vowel Harmony': 'Harmonie vocalique', 'Reading Practice': 'Pratique de lecture',
    'The Tissue Test': 'Le test du mouchoir', '10 basic vowels': '10 voyelles de base',
    '11 compound vowels': '11 voyelles composées', '14 basic consonants': '14 consonnes de base',
    '5 tense consonants': '5 consonnes tendues', '5 aspirated consonants': '5 consonnes aspirées',
    'October 9 is Hangul Day (한글날) in South Korea — a national holiday celebrating the invention of the alphabet in 1443.': 'Le 9 octobre est la Journée du Hangul (한글날) en Corée du Sud — un jour férié national célébrant l\'invention de l\'alphabet en 1443.',
    'Structure': 'Structure', 'Example': 'Exemple', 'Reading': 'Lecture', 'Meaning': 'Signification',
    'Consonant + Vowel': 'Consonne + voyelle', 'go (verb stem)': 'aller (radical verbal)',
    'Consonant + Vowel + Consonant': 'Consonne + voyelle + consonne', 'Korean (prefix)': 'Coréen (préfixe)',
    'Silent ㅇ + Vowel': 'ㅇ muet + voyelle', 'ah! (exclamation)': 'ah ! (exclamation)',
    'Batchim': 'Batchim', 'Example Word': 'Exemple de mot', 'Note': 'Note', 'to read': 'lire',
    'to sit': 's\'asseoir', 'life': 'vie',
    'k (aspirated)': 'k (aspiré)', 't (aspirated)': 't (aspiré)',
    'p (aspirated)': 'p (aspiré)', 'ch (aspirated)': 'ch (aspiré)',
    '← Home': '← Accueil', 'Mark as Complete ✓': 'Marquer comme terminé ✓', 'Syllable Blocks →': 'Blocs syllabiques →',
    // ── Grammar Page ──────────────────────────────────
    'Word Order — SOV Structure (어순)': 'Ordre des mots — Structure SOV (어순)',
    'Korean Particles (조사)': 'Particules coréennes (조사)', 'Particle Practice': 'Pratique des particules',
    'Speech Levels (존댓말 vs 반말)': 'Niveaux de langage (존댓말 vs 반말)',
    'Present Tense (-아요/-어요)': 'Présent (-아요/-어요)',
    'Past Tense (-았어요/-었어요)': 'Passé (-았어요/-었어요)',
    'Future Tense (-을 거예요/-ㄹ 거예요)': 'Futur (-을 거예요/-ㄹ 거예요)',
    'Making Sentences Negative (부정문)': 'Phrases négatives (부정문)',
    'Forming Questions (의문문)': 'Poser des questions (의문문)',
    'WH- Question Words': 'Mots interrogatifs',
    'Essential Sentence Patterns (문형)': 'Modèles de phrases essentiels (문형)',
    'Connectors: 그리고, 그래서, 그렇지만, 그런데': 'Connecteurs : 그리고, 그래서, 그렇지만, 그런데',
    'And, With: -하고, -(이)랑': 'Et, Avec : -하고, -(이)랑',
    'To/From Someone: -한테, -한테서': 'À/De quelqu\'un : -한테, -한테서',
    'Telling Time (시간 말하기)': 'Dire l\'heure (시간 말하기)',
    'Counters (단위 명사)': 'Compteurs (단위 명사)',
    'Present Progressive: -고 있어요': 'Présent progressif : -고 있어요',
    'Particle': 'Particule', 'Function': 'Fonction', 'Rule': 'Règle', 'Level': 'Niveau',
    'When to Use': 'Quand utiliser', 'Dictionary Form': 'Forme du dictionnaire', 'Stem': 'Radical',
    'Conjugated': 'Conjugué', 'Counter': 'Compteur', 'Used for': 'Utilisé pour',
    'Vowel': 'Voyelle', 'Shape Mnemonic': 'Mnémotechnique de forme', 'Mouth Position': 'Position de la bouche',
    'Time': 'Temps', 'Register': 'Registre', 'Used with': 'Utilisé avec',
    'Formal equivalent': 'Équivalent formel', 'Korean · 한국어': 'Coréen · 한국어',
    'Translation · 번역': 'Traduction · 번역', 'Topic marker': 'Marqueur de thème',
    'Subject marker': 'Marqueur de sujet', 'Object marker': 'Marqueur d\'objet',
    // ── Pronunciation Page ────────────────────────────
    '🔊 Beginner · Lesson 3': '🔊 Débutant · Leçon 3', 'Pronunciation Guide:': 'Guide de prononciation :',
    '⏱ 50 min read': '⏱ 50 min de lecture', '🔖 Pronunciation': '🔖 Prononciation',
    '👁 14,837 views': '👁 14 837 vues', 'sound change rules': 'règles de changement de son',
    'Batchim — Syllable-Final Consonants (받침)': 'Batchim — Consonnes en fin de syllabe (받침)',
    '7 possible sounds': '7 sons possibles', 'Sound Group': 'Groupe sonore', 'Written As': 'Écrit comme',
    'Pronounced As': 'Prononcé comme', 'Unreleased stops': 'Occlusives non relâchées',
    // ── Syllable Blocks Page ──────────────────────────
    'The ㅇ Placeholder Rule': 'La règle du marqueur ㅇ',
    'Vertical vs Horizontal Vowels': 'Voyelles verticales vs horizontales',
    'Quick Visual Trick': 'Astuce visuelle rapide', 'Building Your First Syllables': 'Construire vos premières syllabes',
    'Adding Batchim — The Final Consonant': 'Ajouter le batchim — La consonne finale',
    'Reading Real Korean Words': 'Lire de vrais mots coréens',
    'Practice & Summary': 'Pratique & Résumé',
    '5 Rules for Korean Syllable Blocks': '5 règles pour les blocs syllabiques coréens',
    '📝 Self-Test: Identify the Components': '📝 Auto-test : Identifiez les composants',
    // ── Pronouns Page ─────────────────────────────────
    'Saying \'You\' in Korean': 'Dire « vous/tu » en coréen',
    'Third Person & We (그·그녀·우리)': 'Troisième personne & Nous (그·그녀·우리)',
    'Demonstrative Pronouns (이·그·저)': 'Pronoms démonstratifs (이·그·저)',
    'Question Pronouns (의문대명사)': 'Pronoms interrogatifs (의문대명사)',
    'Pronouns Complete!': 'Pronoms terminés !',
    // ── Emotions Page ─────────────────────────────────
    '😊 Intermediate · Lesson 7': '😊 Intermédiaire · Leçon 7',
    'Core Emotions': 'Émotions fondamentales', 'Expressing Feelings': 'Exprimer ses sentiments',
    'Complex Emotions': 'Émotions complexes', 'Emotional Phrases': 'Phrases émotionnelles',
    'Emotions in Korean (감정)': 'Émotions en coréen (감정)',
    'Emotions Complete!': 'Émotions terminées !',
    // ── Shopping Page ─────────────────────────────────
    '🛒 Intermediate · Lesson 8': '🛒 Intermédiaire · Leçon 8',
    'Shopping Vocabulary': 'Vocabulaire du shopping', 'In the Store': 'En magasin', 'Prices & Numbers': 'Prix & Nombres',
    'Transactions': 'Transactions', 'Shopping in Korea (쇼핑)': 'Faire du shopping en Corée (쇼핑)',
    'Shopping Complete!': 'Shopping terminé !',
    // ── Speech Levels Page ────────────────────────────
    '🗣️ Intermediate · Lesson 6': '🗣️ Intermédiaire · Leçon 6',
    '합쇼체 (Formal)': '합쇼체 (Formel)', '해요체 (Polite)': '해요체 (Poli)',
    '반말 (Casual)': '반말 (Informel)', 'Choosing a Level': 'Choisir un niveau',
    'Korean Speech Levels Overview': 'Aperçu des niveaux de langage coréens',
    'Speech Levels Complete!': 'Niveaux de langage terminés !',
    // ── Vocab Browser ───────────────────────────────────
    'Vocab Browser': 'Navigateur de vocabulaire',
    'saved to flashcards': 'enregistrés dans les fiches',
    'Loading vocabulary…': 'Chargement du vocabulaire…',
    'No words match your search.': 'Aucun mot ne correspond à votre recherche.',
    'Failed to load vocabulary.': 'Échec du chargement du vocabulaire.',
    'Search Korean, English, or romanization…': 'Rechercher en coréen, anglais ou romanisation…',
    '★ Add all in category': '★ Ajouter tout dans la catégorie',
    'Verbs': 'Verbes',
    'Health': 'Santé',
    'Media': 'Médias',
    'Proverbs': 'Proverbes',
    'Academic': 'Académique',
    // ── Progress system (streak / counters / resume) ────
    '✓ Correct!': '✓ Correct !',
    '✗ Not quite — try again!': '✗ Presque — réessaie !',
    '{n}-day streak': 'Série de {n} jours',
    '{n} steps today': '{n} étapes aujourd\'hui',
    'Continue': 'Continuer',
    'Step {n} of {m}': 'Étape {n} sur {m}',
    'Steps completed': 'Étapes terminées',
    'Words & phrases learned': 'Mots et phrases appris',
    'Letters & syllables learned': 'Lettres et syllabes apprises',
    'Best streak': 'Meilleure série',
    'Start Again': 'Recommencer',
    'Next Lesson →': 'Leçon suivante →',
    'Next →': 'Suivant →',
    'Progress': 'Progression',
    'Reset all progress': 'Réinitialiser toute la progression',
    '🔥 Daily streak + real progress tracking': '🔥 Série quotidienne + suivi réel des progrès'
  };
  if (window.LangManager) window.LangManager.register('fr', FR);
})();
