'use strict';
(function() {
  const TH = {
    // ── Navigation & Global UI ─────────────────────────
    'Learn': 'เรียนรู้', 'Quiz': 'แบบทดสอบ', 'K-Culture': 'K-วัฒนธรรม', 'Travel': 'ท่องเที่ยว',
    'Search...': 'ค้นหา...', 'Search lessons, vocabulary…': 'ค้นหาบทเรียน คำศัพท์…',
    '🇰🇷 · Free · For Every Level': '🇰🇷 · ฟรี · สำหรับทุกระดับ',
    'Learn Korean': 'เรียนภาษาเกาหลี', 'Start Learning': 'เริ่มเรียน', 'Explore K-Culture': 'สำรวจ K-วัฒนธรรม',
    'Vocabulary Words': 'คำศัพท์', 'Lessons': 'บทเรียน', 'Active Learners': 'ผู้เรียนที่กำลังเรียน', '% Free': '% ฟรี',
    'FEATURES': 'ฟีเจอร์', 'Everything You Need to Learn Korean': 'ทุกสิ่งที่คุณต้องการเพื่อเรียนภาษาเกาหลี',
    'Start with 한글': 'เริ่มต้นกับ 한글', 'Learn Hangul Now →': 'เรียนฮันกึลเลย →',
    'Hear It': 'ฟัง', 'More Words': 'คำเพิ่มเติม', 'Word of the Day': 'คำศัพท์ประจำวัน',
    'STRUCTURED PATHS · 학습 경로': 'เส้นทางการเรียน · 학습 경로',
    'Choose Your Learning Path': 'เลือกเส้นทางการเรียนของคุณ',
    'Beginner': 'ผู้เริ่มต้น', 'Intermediate': 'ระดับกลาง', 'Advanced': 'ระดับสูง',
    'Start Beginner Path →': 'เริ่มเส้นทางผู้เริ่มต้น →', 'Start Intermediate Path →': 'เริ่มเส้นทางระดับกลาง →',
    'Start Advanced Path →': 'เริ่มเส้นทางระดับสูง →', 'POPULAR': 'ยอดนิยม',
    'Beginner–Intermediate': 'ผู้เริ่มต้น–ระดับกลาง', 'Intermediate–Advanced': 'ระดับกลาง–ระดับสูง',
    'Beg–Int': 'เริ่ม–กลาง',
    // ── K-Culture & Home ──────────────────────────────
    'K-CULTURE': 'K-วัฒนธรรม', 'K-CULTURE · 한국 문화': 'K-วัฒนธรรม · 한국 문화',
    'Experience Korea Beyond Language': 'สัมผัสเกาหลีเกินกว่าภาษา',
    'Explore All K-Culture Content →': 'สำรวจเนื้อหา K-วัฒนธรรมทั้งหมด →',
    'TRAVEL · 여행': 'ท่องเที่ยว · 여행', 'Explore Korea': 'สำรวจเกาหลี',
    'View Full Travel Guide →': 'ดูคู่มือการท่องเที่ยวฉบับเต็ม →',
    'PRACTICE · 연습': 'ฝึกฝน · 연습',
    '10 progressive levels · multiple choice · covers Hangul, Grammar & Vocabulary': '10 ระดับ · ตัวเลือก · ครอบคลุมฮันกึล ไวยากรณ์ และคำศัพท์',
    'Choose a Level': 'เลือกระดับ', 'questions': 'คำถาม', '← All Levels': '← ทุกระดับ',
    'Try Again': 'ลองใหม่', 'Next Level': 'ระดับถัดไป', 'All Levels': 'ทุกระดับ',
    'Next Level →': 'ระดับถัดไป →',
    // ── Travel ────────────────────────────────────────
    '🇰🇷 · South Korea Travel Guide · 여행 안내': '🇰🇷 · คู่มือท่องเที่ยวเกาหลีใต้ · 여행 안내',
    'South Korea Travel Guide': 'คู่มือท่องเที่ยวเกาหลีใต้',
    'Population': 'ประชากร', 'UNESCO Sites': 'แหล่งมรดกโลก UNESCO',
    'Great to visit': 'น่าเที่ยวมาก', 'Visa-free nations': 'ประเทศที่ไม่ต้องขอวีซ่า',
    'EXPLORE THE GUIDES · 가이드 탐색': 'สำรวจคู่มือ · 가이드 탐색',
    'Plan Your Perfect Korea Trip': 'วางแผนทริปเกาหลีในฝัน',
    'TOP DESTINATIONS · 인기 여행지': 'จุดหมายยอดนิยม · 인기 여행지',
    'Where Will You Explore?': 'คุณจะสำรวจที่ไหน?',
    'ESSENTIAL PHRASES · 필수 표현': 'ประโยคสำคัญ · 필수 표현',
    'Travel Korean Phrasebook': 'คู่มือสำนวนภาษาเกาหลีสำหรับนักท่องเที่ยว',
    'TRANSPORTATION · 교통': 'การเดินทาง · 교통', 'Getting Around Korea': 'การเดินทางในเกาหลี',
    'FOOD TOUR · 음식 여행': 'ทัวร์อาหาร · 음식 여행', 'Regional Korean Specialties': 'อาหารพิเศษประจำภูมิภาคเกาหลี',
    'CULTURAL ETIQUETTE · 예절': 'มารยาทวัฒนธรรม · 예절', 'Korean Cultural Tips': 'เคล็ดลับวัฒนธรรมเกาหลี',
    'TRAVEL APPS · 여행 앱': 'แอปท่องเที่ยว · 여행 앱', 'Essential Apps for Korea Travel': 'แอปจำเป็นสำหรับการท่องเที่ยวเกาหลี',
    'READY TO LEARN?': 'พร้อมเรียนแล้วหรือยัง?', 'Start Speaking Korean Today': 'เริ่มพูดภาษาเกาหลีวันนี้เลย',
    'Start Learning Korean →': 'เริ่มเรียนภาษาเกาหลี →', 'Plan Your Trip': 'วางแผนการเดินทาง',
    'K-Pop': 'K-Pop', 'K-Drama': 'K-Drama', 'K-Beauty': 'K-Beauty', 'All': 'ทั้งหมด',
    // ── Footer & Company ──────────────────────────────
    'Learn · 학습': 'เรียนรู้ · 학습', 'K-Culture · 문화': 'K-วัฒนธรรม · 문화',
    'Company · 회사': 'บริษัท · 회사', 'Explore': 'สำรวจ', 'Company': 'บริษัท',
    'Hangul Alphabet': 'ตัวอักษรฮันกึล', 'Grammar': 'ไวยากรณ์', 'Vocabulary': 'คำศัพท์',
    'Travel Guide': 'คู่มือการท่องเที่ยว', 'About Us': 'เกี่ยวกับเรา',
    'Contact': 'ติดต่อ', 'Privacy Policy': 'นโยบายความเป็นส่วนตัว', 'Terms of Use': 'ข้อกำหนดการใช้งาน',
    'Made with ❤️ for Korean learners worldwide.': 'สร้างด้วย ❤️ สำหรับผู้เรียนภาษาเกาหลีทั่วโลก',
    '🇰🇷 학습을 즐기세요! (Enjoy your learning!)': '🇰🇷 학습을 즐기세요! (สนุกกับการเรียน!)',
    'Home': 'หน้าแรก', 'Hangul': 'ฮันกึล',
    'A free Korean language learning platform — combining language study with K-culture, travel guides, and real-world practice. For learners of every level, worldwide.': 'แพลตฟอร์มเรียนภาษาเกาหลีฟรี — ผสมผสานการเรียนภาษากับ K-วัฒนธรรม คู่มือท่องเที่ยว และการฝึกจริง สำหรับผู้เรียนทุกระดับทั่วโลก',
    'A free Korean language learning platform for learners of every level, worldwide.': 'แพลตฟอร์มเรียนภาษาเกาหลีฟรีสำหรับผู้เรียนทุกระดับทั่วโลก',
    '© 2026 한국어 학교. Made with ❤️ for Korean learners worldwide.': '© 2026 한국어 학교. สร้างด้วย ❤️ สำหรับผู้เรียนภาษาเกาหลีทั่วโลก',
    // ── Sidebar Dividers ──────────────────────────────
    'Getting Started': 'เริ่มต้น', 'Tools': 'เครื่องมือ',
    'CATEGORIES · 카테고리': 'หมวดหมู่ · 카테고리', 'DEEP DIVES · 심층 탐구': 'เจาะลึก · 심층 탐구',
    // ── Learn Sidebar ─────────────────────────────────
    'Introduction': 'บทนำ', 'Syllable Blocks': 'บล็อกพยางค์', 'Pronunciation Guide': 'คู่มือการออกเสียง',
    'Vocab': 'คำศัพท์', 'Greetings': 'คำทักทาย', 'Numbers': 'ตัวเลข', 'Family': 'ครอบครัว',
    'Food & Drink': 'อาหารและเครื่องดื่ม', 'Colors': 'สี', 'Days & Time': 'วันและเวลา', 'Places': 'สถานที่',
    'Emotions': 'อารมณ์', 'Body Parts': 'ส่วนของร่างกาย', 'Shopping': 'การช้อปปิ้ง', 'Weather': 'สภาพอากาศ',
    'Verbs & Actions': 'กริยาและการกระทำ', 'Adjectives': 'คำคุณศัพท์', 'Workplace': 'สถานที่ทำงาน',
    'Travel': 'การท่องเที่ยว', 'Health': 'สุขภาพ', 'Media & Entertainment': 'สื่อและความบันเทิง',
    'Konglish': 'คองลิช', 'Academic': 'วิชาการ', 'Proverbs': 'สุภาษิต',
    'Speech Levels': 'ระดับความสุภาพ', 'Nouns': 'คำนาม', 'Pronouns': 'สรรพนาม',
    'Flashcards': 'บัตรคำ', 'Vocabulary Browser': 'เบราเซอร์คำศัพท์',
    'Dialogues': 'บทสนทนา', 'Business Korean': 'ภาษาเกาหลีธุรกิจ',
    'Classical Korean': 'ภาษาเกาหลีโบราณ', 'Writing Essays': 'การเขียนเรียงความ',
    // ── Culture Sidebar ───────────────────────────────
    'K-Pop Guide': 'คู่มือ K-Pop', 'K-Drama Guide': 'คู่มือ K-Drama',
    'K-Food Guide': 'คู่มือ K-Food', 'K-Beauty Guide': 'คู่มือ K-Beauty',
    'K-Fashion': 'K-แฟชั่น', 'K-Gaming': 'K-เกมส์', 'K-Movies': 'K-ภาพยนตร์',
    'K-Sports': 'K-กีฬา', 'Korean Traditions': 'ประเพณีเกาหลี',
    'Korean BBQ': 'Korean BBQ', 'Kimchi Guide': 'คู่มือกิมจิ', 'Ramyeon Guide': 'คู่มือราเม็ง',
    'Mandu Guide': 'คู่มือมันดู', 'Korean Chicken': 'ไก่เกาหลี', 'Korean Things': 'สิ่งของเกาหลี',
    // ── Vocab categories ─────────────────────────────
    'Beginner–Intermediate': 'ผู้เริ่มต้น–ระดับกลาง', 'Intermediate–Advanced': 'ระดับกลาง–ระดับสูง',
    // ── About / Contact ───────────────────────────────
    'About Korean School': 'เกี่ยวกับ Korean School',
    'Contact Korean School': 'ติดต่อ Korean School',
    // ── Misc ──────────────────────────────────────────
    'Loading lesson…': 'กำลังโหลดบทเรียน…',
    'Loading vocabulary…': 'กำลังโหลดคำศัพท์…',
    'Search lessons, vocabulary…': 'ค้นหาบทเรียน คำศัพท์…',
    'Search lessons...': 'ค้นหาบทเรียน...',
    'Search Korean, English, or romanization…': 'ค้นหาภาษาเกาหลี อังกฤษ หรือคำอ่าน…',
    'Search Results': 'ผลการค้นหา', '← Back to Home': '← กลับหน้าแรก',
    // ── vocabulary.html intro + generic nav ───────────
    'Previous': 'ก่อนหน้า', 'Next': 'ถัดไป', 'Korean': 'เกาหลี',
    '📚 Lesson 4 · vocabulary': '📚 บทที่ 4 · คำศัพท์',
    '🗂 21 Categories': '🗂 21 หมวดหมู่',
    '📊 All Levels': '📊 ทุกระดับ',
    '🔊 Audio on every card': '🔊 เสียงในทุกบัตรคำ',
    '⚡ XP + Streak system': '⚡ ระบบ XP + สตรีค',
    'Covers 500+ core Korean words across 21 categories': 'ครอบคลุมคำศัพท์เกาหลีหลัก 500+ คำใน 21 หมวดหมู่',
    'Bite-sized steps with instant audio — tap any card to hear it': 'เรียนทีละขั้นตอนพร้อมเสียงทันที — แตะบัตรคำใดก็ได้เพื่อฟัง',
    'Quizzes after every category to lock in your memory': 'แบบทดสอบหลังทุกหมวดหมู่เพื่อจดจำได้แม่นยำ',
    'Most learners finish each category in under 15 minutes': 'ผู้เรียนส่วนใหญ่เรียนจบแต่ละหมวดหมู่ในเวลาไม่ถึง 15 นาที',
    // ── Sidebar: vocabulary categories ────────────────
    'Health & Medicine': 'สุขภาพและการแพทย์',
    'Media & K-Culture': 'สื่อและเค-คัลเจอร์',
    'Proverbs & Idioms': 'สุภาษิตและสำนวน',
    'Academic Korean': 'ภาษาเกาหลีเชิงวิชาการ',
    'News & Society': 'ข่าวและสังคม',
    'Common Nouns': 'คำนามที่ใช้บ่อย',
    // ── Sidebar: grammar topics ───────────────────────
    'Sentence Structure': 'โครงสร้างประโยค',
    'Korean Particles': 'คำช่วย',
    'Verb Conjugation': 'การผันคำกริยา',
    'Question Forms': 'คำถาม',
    'Connectors': 'คำเชื่อม',
    'And, With': 'และ/กับ',
    'To/From Someone': 'ให้/จาก',
    'Telling Time': 'การบอกเวลา',
    'Counters': 'ตัวนับ',
    'Present Progressive': 'กำลังทำ',
    'Self Introduction': 'การแนะนำตัว',
    'Dates and Months': 'วันที่และเดือน',
    'Degree Adverbs': 'คำวิเศษณ์บอกระดับ',
    'Nominalizer -는 것': 'การทำเป็นคำนาม -는 것',
    'Comparatives': 'การเปรียบเทียบ',
    'Imperative -(으)세요': 'รูปคำสั่ง -(으)세요',
    'Don\'t: -지 마세요': 'ห้าม: -지 마세요',
    'Method: -(으)로': 'วิธีการ: -(으)로',
    // ── Sidebar: lesson names ─────────────────────────
    'Formal vs Informal': 'ทางการ vs ไม่ทางการ',
    'Expressing Emotions': 'การแสดงอารมณ์',
    'Shopping Phrases': 'วลีสำหรับช้อปปิ้ง',
    'Korean Dialogues': 'บทสนทนาภาษาเกาหลี',
    'Vocab Browser': 'เบราเซอร์คำศัพท์',
    // ── Progress system (streak / counters / resume) ────
    '✓ Correct!': '✓ ถูกต้อง!',
    '✗ Not quite — try again!': '✗ ยังไม่ถูก — ลองใหม่!',
    '{n}-day streak': 'สตรีค {n} วัน',
    '{n} steps today': 'วันนี้ {n} ขั้นตอน',
    'Continue': 'เรียนต่อ',
    'Step {n} of {m}': 'ขั้นตอนที่ {n} จาก {m}',
    'Steps completed': 'ขั้นตอนที่ทำเสร็จ',
    'Words & phrases learned': 'คำศัพท์และวลีที่เรียนแล้ว',
    'Letters & syllables learned': 'ตัวอักษรและพยางค์ที่เรียนแล้ว',
    'Best streak': 'สตรีคที่ดีที่สุด',
    'Start Again': 'เริ่มใหม่',
    'Next Lesson →': 'บทเรียนถัดไป →',
    'Next →': 'ถัดไป →',
    'Progress': 'ความคืบหน้า',
    'Reset all progress': 'รีเซ็ตความคืบหน้าทั้งหมด',
    '🔥 Daily streak + real progress tracking': '🔥 สตรีครายวัน + ติดตามความคืบหน้าจริง',
  };

  if (window.LangManager) {
    LangManager.register('th', TH);
  }
})();
