'use strict';
(function() {
  const TH = {
    // ── Navigation & Global UI ─────────────────────────
    'Learn': 'เรียนรู้', 'Quiz': 'แบบทดสอบ', 'K-Culture': 'K-วัฒนธรรม', 'Travel': 'ท่องเที่ยว',
    'Search...': 'ค้นหา...', 'Search lessons, vocabulary…': 'ค้นหาบทเรียน คำศัพท์…',
    '🇰🇷 · Free · For Every Level': '🇰🇷 · ฟรี · สำหรับทุกระดับ',
    'Learn Korean': 'เรียนภาษาเกาหลี', 'Start Learning': 'เริ่มเรียน', 'Explore K-Culture': 'สำรวจ K-วัฒนธรรม',
    'Vocabulary Words': 'คำศัพท์', 'Lessons': 'บทเรียน', 'Active Learners': 'ผู้เรียนที่กำลังเรียน', '% Free': '% ฟรี',
    'FEATURES': 'ฟีเจอร์', 'Everything You Need to Learn Korean': 'ทุกสิ่งที่คุณต้องการเพื่อเรียนภาษาเกาหลี',
    'Start with 한글': 'เริ่มต้นกับ 한글', 'Learn Hangul Now →': 'เรียนฮันกึลเลย →',
    'Hear It': 'ฟัง', 'More Words': 'คำเพิ่มเติม', 'Word of the Day': 'คำศัพท์ประจำวัน',
    'STRUCTURED PATHS · 학습 경로': 'เส้นทางการเรียน · 학습 경로',
    'Choose Your Learning Path': 'เลือกเส้นทางการเรียนของคุณ',
    'Beginner': 'ผู้เริ่มต้น', 'Intermediate': 'ระดับกลาง', 'Advanced': 'ระดับสูง',
    'Start Beginner Path →': 'เริ่มเส้นทางผู้เริ่มต้น →', 'Start Intermediate Path →': 'เริ่มเส้นทางระดับกลาง →',
    'Start Advanced Path →': 'เริ่มเส้นทางระดับสูง →', 'POPULAR': 'ยอดนิยม',
    'Beginner–Intermediate': 'ผู้เริ่มต้น–ระดับกลาง', 'Intermediate–Advanced': 'ระดับกลาง–ระดับสูง',
    'Beg–Int': 'เริ่ม–กลาง',
    // ── K-Culture & Home ──────────────────────────────
    'K-CULTURE': 'K-วัฒนธรรม', 'K-CULTURE · 한국 문화': 'K-วัฒนธรรม · 한국 문화',
    'Experience Korea Beyond Language': 'สัมผัสเกาหลีเกินกว่าภาษา',
    'Explore All K-Culture Content →': 'สำรวจเนื้อหา K-วัฒนธรรมทั้งหมด →',
    'TRAVEL · 여행': 'ท่องเที่ยว · 여행', 'Explore Korea': 'สำรวจเกาหลี',
    'View Full Travel Guide →': 'ดูคู่มือการท่องเที่ยวฉบับเต็ม →',
    'PRACTICE · 연습': 'ฝึกฝน · 연습',
    '10 progressive levels · multiple choice · covers Hangul, Grammar & Vocabulary': '10 ระดับ · ตัวเลือก · ครอบคลุมฮันกึล ไวยากรณ์ และคำศัพท์',
    'Choose a Level': 'เลือกระดับ', 'questions': 'คำถาม', '← All Levels': '← ทุกระดับ',
    'Try Again': 'ลองใหม่', 'Next Level': 'ระดับถัดไป', 'All Levels': 'ทุกระดับ',
    'Next Level →': 'ระดับถัดไป →',
    // ── Travel ────────────────────────────────────────
    '🇰🇷 · South Korea Travel Guide · 여행 안내': '🇰🇷 · คู่มือท่องเที่ยวเกาหลีใต้ · 여행 안내',
    'South Korea Travel Guide': 'คู่มือท่องเที่ยวเกาหลีใต้',
    'Population': 'ประชากร', 'UNESCO Sites': 'แหล่งมรดกโลก UNESCO',
    'Great to visit': 'น่าเที่ยวมาก', 'Visa-free nations': 'ประเทศที่ไม่ต้องขอวีซ่า',
    'EXPLORE THE GUIDES · 가이드 탐색': 'สำรวจคู่มือ · 가이드 탐색',
    'Plan Your Perfect Korea Trip': 'วางแผนทริปเกาหลีในฝัน',
    'TOP DESTINATIONS · 인기 여행지': 'จุดหมายยอดนิยม · 인기 여행지',
    'Where Will You Explore?': 'คุณจะสำรวจที่ไหน?',
    'ESSENTIAL PHRASES · 필수 표현': 'ประโยคสำคัญ · 필수 표현',
    'Travel Korean Phrasebook': 'คู่มือสำนวนภาษาเกาหลีสำหรับนักท่องเที่ยว',
    'TRANSPORTATION · 교통': 'การเดินทาง · 교통', 'Getting Around Korea': 'การเดินทางในเกาหลี',
    'FOOD TOUR · 음식 여행': 'ทัวร์อาหาร · 음식 여행', 'Regional Korean Specialties': 'อาหารพิเศษประจำภูมิภาคเกาหลี',
    'CULTURAL ETIQUETTE · 예절': 'มารยาทวัฒนธรรม · 예절', 'Korean Cultural Tips': 'เคล็ดลับวัฒนธรรมเกาหลี',
    'TRAVEL APPS · 여행 앱': 'แอปท่องเที่ยว · 여행 앱', 'Essential Apps for Korea Travel': 'แอปจำเป็นสำหรับการท่องเที่ยวเกาหลี',
    'READY TO LEARN?': 'พร้อมเรียนแล้วหรือยัง?', 'Start Speaking Korean Today': 'เริ่มพูดภาษาเกาหลีวันนี้เลย',
    'Start Learning Korean →': 'เริ่มเรียนภาษาเกาหลี →', 'Plan Your Trip': 'วางแผนการเดินทาง',
    'K-Pop': 'K-Pop', 'K-Drama': 'K-Drama', 'K-Beauty': 'K-Beauty', 'All': 'ทั้งหมด',
    // ── Footer & Company ──────────────────────────────
    'Learn · 학습': 'เรียนรู้ · 학습', 'K-Culture · 문화': 'K-วัฒนธรรม · 문화',
    'Company · 회사': 'บริษัท · 회사', 'Explore': 'สำรวจ', 'Company': 'บริษัท',
    'Hangul Alphabet': 'ตัวอักษรฮันกึล', 'Grammar': 'ไวยากรณ์', 'Vocabulary': 'คำศัพท์',
    'Travel Guide': 'คู่มือการท่องเที่ยว', 'About Us': 'เกี่ยวกับเรา',
    'Contact': 'ติดต่อ', 'Privacy Policy': 'นโยบายความเป็นส่วนตัว', 'Terms of Use': 'ข้อกำหนดการใช้งาน',
    'Made with ❤️ for Korean learners worldwide.': 'สร้างด้วย ❤️ สำหรับผู้เรียนภาษาเกาหลีทั่วโลก',
    '🇰🇷 학습을 즐기세요! (Enjoy your learning!)': '🇰🇷 학습을 즐기세요! (สนุกกับการเรียน!)',
    'Home': 'หน้าแรก', 'Hangul': 'ฮันกึล',
    'A free Korean language learning platform — combining language study with K-culture, travel guides, and real-world practice. For learners of every level, worldwide.': 'แพลตฟอร์มเรียนภาษาเกาหลีฟรี — ผสมผสานการเรียนภาษากับ K-วัฒนธรรม คู่มือท่องเที่ยว และการฝึกจริง สำหรับผู้เรียนทุกระดับทั่วโลก',
    'A free Korean language learning platform for learners of every level, worldwide.': 'แพลตฟอร์มเรียนภาษาเกาหลีฟรีสำหรับผู้เรียนทุกระดับทั่วโลก',
    '© 2026 한국어 학교. Made with ❤️ for Korean learners worldwide.': '© 2026 한국어 학교. สร้างด้วย ❤️ สำหรับผู้เรียนภาษาเกาหลีทั่วโลก',
    // ── Sidebar Dividers ──────────────────────────────
    'Getting Started': 'เริ่มต้น', 'Tools': 'เครื่องมือ',
    'CATEGORIES · 카테고리': 'หมวดหมู่ · 카테고리', 'DEEP DIVES · 심층 탐구': 'เจาะลึก · 심층 탐구',
    // ── Learn Sidebar ─────────────────────────────────
    'Introduction': 'บทนำ', 'Syllable Blocks': 'บล็อกพยางค์', 'Pronunciation Guide': 'คู่มือการออกเสียง',
    'Letter Writing': 'การเขียนตัวอักษร', 'Korean Typing': 'การพิมพ์ภาษาเกาหลี',
    'Vocab': 'คำศัพท์', 'Greetings': 'คำทักทาย', 'Numbers': 'ตัวเลข', 'Family': 'ครอบครัว',
    'Food & Drink': 'อาหารและเครื่องดื่ม', 'Colors': 'สี', 'Days & Time': 'วันและเวลา', 'Places': 'สถานที่',
    'Emotions': 'อารมณ์', 'Body Parts': 'ส่วนของร่างกาย', 'Shopping': 'การช้อปปิ้ง', 'Weather': 'สภาพอากาศ',
    'Verbs & Actions': 'กริยาและการกระทำ', 'Adjectives': 'คำคุณศัพท์', 'Workplace': 'สถานที่ทำงาน',
    'Travel': 'การท่องเที่ยว', 'Health': 'สุขภาพ', 'Media & Entertainment': 'สื่อและความบันเทิง',
    'Konglish': 'คองลิช', 'Academic': 'วิชาการ', 'Proverbs': 'สุภาษิต',
    'Speech Levels': 'ระดับความสุภาพ', 'Nouns': 'คำนาม', 'Pronouns': 'สรรพนาม',
    'Flashcards': 'บัตรคำ', 'Vocabulary Browser': 'เบราเซอร์คำศัพท์',
    'Dialogues': 'บทสนทนา', 'Business Korean': 'ภาษาเกาหลีธุรกิจ',
    'Classical Korean': 'ภาษาเกาหลีโบราณ', 'Writing Essays': 'การเขียนเรียงความ',
    // ── Culture Sidebar ───────────────────────────────
    'K-Pop Guide': 'คู่มือ K-Pop', 'K-Drama Guide': 'คู่มือ K-Drama',
    'K-Food Guide': 'คู่มือ K-Food', 'K-Beauty Guide': 'คู่มือ K-Beauty',
    'K-Fashion': 'K-แฟชั่น', 'K-Gaming': 'K-เกมส์', 'K-Movies': 'K-ภาพยนตร์',
    'K-Sports': 'K-กีฬา', 'Korean Traditions': 'ประเพณีเกาหลี',
    'Korean BBQ': 'Korean BBQ', 'Kimchi Guide': 'คู่มือกิมจิ', 'Ramyeon Guide': 'คู่มือราเม็ง',
    'Mandu Guide': 'คู่มือมันดู', 'Korean Chicken': 'ไก่เกาหลี', 'Korean Things': 'สิ่งของเกาหลี',
    // ── Vocab categories ─────────────────────────────
    'Beginner–Intermediate': 'ผู้เริ่มต้น–ระดับกลาง', 'Intermediate–Advanced': 'ระดับกลาง–ระดับสูง',
    // ── About / Contact ───────────────────────────────
    'About Korean School': 'เกี่ยวกับ Korean School',
    'Contact Korean School': 'ติดต่อ Korean School',
    // ── Misc ──────────────────────────────────────────
    'Loading lesson…': 'กำลังโหลดบทเรียน…',
    'Loading vocabulary…': 'กำลังโหลดคำศัพท์…',
    'Search lessons, vocabulary…': 'ค้นหาบทเรียน คำศัพท์…',
    'Search lessons...': 'ค้นหาบทเรียน...',
    'Search Korean, English, or romanization…': 'ค้นหาภาษาเกาหลี อังกฤษ หรือคำอ่าน…',
    'Search Results': 'ผลการค้นหา', '← Back to Home': '← กลับหน้าแรก',
    // ── vocabulary.html intro + generic nav ───────────
    'Previous': 'ก่อนหน้า', 'Next': 'ถัดไป', 'Korean': 'เกาหลี',
    '📚 Lesson 4 · vocabulary': '📚 บทที่ 4 · คำศัพท์',
    '🗂 21 Categories': '🗂 21 หมวดหมู่',
    '📊 All Levels': '📊 ทุกระดับ',
    '🔊 Audio on every card': '🔊 เสียงในทุกบัตรคำ',
    '⚡ XP + Streak system': '⚡ ระบบ XP + สตรีค',
    'Covers 500+ core Korean words across 21 categories': 'ครอบคลุมคำศัพท์เกาหลีหลัก 500+ คำใน 21 หมวดหมู่',
    'Bite-sized steps with instant audio — tap any card to hear it': 'เรียนทีละขั้นตอนพร้อมเสียงทันที — แตะบัตรคำใดก็ได้เพื่อฟัง',
    'Quizzes after every category to lock in your memory': 'แบบทดสอบหลังทุกหมวดหมู่เพื่อจดจำได้แม่นยำ',
    'Most learners finish each category in under 15 minutes': 'ผู้เรียนส่วนใหญ่เรียนจบแต่ละหมวดหมู่ในเวลาไม่ถึง 15 นาที',
    // ── Sidebar: vocabulary categories ────────────────
    'Health & Medicine': 'สุขภาพและการแพทย์',
    'Media & K-Culture': 'สื่อและเค-คัลเจอร์',
    'Proverbs & Idioms': 'สุภาษิตและสำนวน',
    'Academic Korean': 'ภาษาเกาหลีเชิงวิชาการ',
    'News & Society': 'ข่าวและสังคม',
    'Common Nouns': 'คำนามที่ใช้บ่อย',
    // ── Sidebar: grammar topics ───────────────────────
    'Sentence Structure': 'โครงสร้างประโยค',
    'Korean Particles': 'คำช่วย',
    'Verb Conjugation': 'การผันคำกริยา',
    'Question Forms': 'คำถาม',
    'Connectors': 'คำเชื่อม',
    'And, With': 'และ/กับ',
    'To/From Someone': 'ให้/จาก',
    'Telling Time': 'การบอกเวลา',
    'Counters': 'ตัวนับ',
    'Present Progressive': 'กำลังทำ',
    'Self Introduction': 'การแนะนำตัว',
    'Dates and Months': 'วันที่และเดือน',
    'Degree Adverbs': 'คำวิเศษณ์บอกระดับ',
    'Nominalizer -는 것': 'การทำเป็นคำนาม -는 것',
    'Comparatives': 'การเปรียบเทียบ',
    'Imperative -(으)세요': 'รูปคำสั่ง -(으)세요',
    'Don\'t: -지 마세요': 'ห้าม: -지 마세요',
    'Method: -(으)로': 'วิธีการ: -(으)로',
    // ── Sidebar: lesson names ─────────────────────────
    'Formal vs Informal': 'ทางการ vs ไม่ทางการ',
    'Expressing Emotions': 'การแสดงอารมณ์',
    'Shopping Phrases': 'วลีสำหรับช้อปปิ้ง',
    'Korean Dialogues': 'บทสนทนาภาษาเกาหลี',
    'Vocab Browser': 'เบราเซอร์คำศัพท์',
    // ── Progress system (streak / counters / resume) ────
    '✓ Correct!': '✓ ถูกต้อง!',
    '✗ Not quite — try again!': '✗ ยังไม่ถูก — ลองใหม่!',
    '{n}-day streak': 'สตรีค {n} วัน',
    '{n} steps today': 'วันนี้ {n} ขั้นตอน',
    'Continue': 'เรียนต่อ',
    'Step {n} of {m}': 'ขั้นตอนที่ {n} จาก {m}',
    'Steps completed': 'ขั้นตอนที่ทำเสร็จ',
    'Words & phrases learned': 'คำศัพท์และวลีที่เรียนแล้ว',
    'Letters & syllables learned': 'ตัวอักษรและพยางค์ที่เรียนแล้ว',
    'Best streak': 'สตรีคที่ดีที่สุด',
    'Start Again': 'เริ่มใหม่',
    'Next Lesson →': 'บทเรียนถัดไป →',
    'Next →': 'ถัดไป →',
    'Progress': 'ความคืบหน้า',
    'Reset all progress': 'รีเซ็ตความคืบหน้าทั้งหมด',
    '🔥 Daily streak + real progress tracking': '🔥 สตรีครายวัน + ติดตามความคืบหน้าจริง',
    // ── added by scripts/ui-lang.cjs ───────────────────────
    'Still, Already': 'ยังคง, แล้ว',
    'Someone, Something': 'ใครสักคน, บางสิ่ง',
    'Good/Poor At': 'เก่ง/ไม่เก่ง',
    '-도 Advanced Uses': 'การใช้ -도 ขั้นสูง',
    'K-Movie': 'K-Movie',
    'K-Food': 'K-Food',
    'Korean Thing': 'เรื่องเกาหลี',
    'K-Pop, K-Drama, food, beauty, fashion, gaming, sports & traditions.': 'K-Pop, K-Drama, อาหาร, ความงาม, แฟชั่น, เกม, กีฬา และประเพณี',
    'K-Pop History': 'ประวัติ K-Pop',
    'Agencies': 'ค่ายเพลง',
    'Generations': 'รุ่น',
    'Genres': 'แนวเพลง',
    'Variety Shows': 'วาไรตี้โชว์',
    'Film & Acting': 'ภาพยนตร์และการแสดง',
    'Idol Phrases': 'วลีไอดอล',
    'Fan Slang': 'สแลงแฟนคลับ',
    'Fan Chants': 'เสียงเชียร์แฟนคลับ',
    'Drama History': 'ประวัติซีรีส์',
    'Drama Genres': 'แนวซีรีส์',
    'Must-Watch Dramas': 'ซีรีส์ที่ต้องดู',
    'K-Drama Tropes': 'สูตร K-Drama',
    'Dialogue Practice': 'ฝึกบทสนทนา',
    'Fan Culture & Slang': 'วัฒนธรรมแฟนคลับและสแลง',
    'Movie History': 'ประวัติภาพยนตร์',
    'Movie Genres': 'แนวภาพยนตร์',
    'Must-Watch Films': 'หนังที่ต้องดู',
    'Directors': 'ผู้กำกับ',
    'Iconic Lines': 'บทพูดในตำนาน',
    'Fan Culture': 'วัฒนธรรมแฟนคลับ',
    'K-Food Goes Global': 'K-Food สู่ระดับโลก',
    'Foods That Went Global': 'อาหารที่โด่งดังทั่วโลก',
    'K-Food Timeline': 'ไทม์ไลน์ K-Food',
    'Essential Dishes': 'เมนูสำคัญ',
    'World-Famous Chefs': 'เชฟระดับโลก',
    'Ordering & Dining': 'สั่งอาหารและรับประทาน',
    'Street Food': 'อาหารข้างทาง',
    'Food Culture & Drinking': 'วัฒนธรรมอาหารและการดื่ม',
    'Chicken Guide': 'คู่มือไก่',
    'K-BBQ Guide': 'คู่มือ K-BBQ',
    'K-Beauty Goes Global': 'K-Beauty สู่ระดับโลก',
    'K-Beauty Timeline': 'ไทม์ไลน์ K-Beauty',
    'Iconic Brands': 'แบรนด์ในตำนาน',
    'Beauty Vocabulary': 'คำศัพท์ความงาม',
    '10-Step Skincare': 'สกินแคร์ 10 ขั้นตอน',
    'Key Ingredients': 'ส่วนผสมสำคัญ',
    'Beauty Trends': 'เทรนด์ความงาม',
    'Makeup Philosophy': 'ปรัชญาการแต่งหน้า',
    'Skin Clinic Culture': 'วัฒนธรรมคลินิกผิว',
    'K-Beauty Dialogue': 'บทสนทนา K-Beauty',
    'K-Fashion Global': 'K-Fashion ระดับโลก',
    'Fashion Icons': 'ไอคอนแฟชั่น',
    'Fashion Timeline': 'ไทม์ไลน์แฟชั่น',
    'Style Aesthetics': 'สุนทรียะแฟชั่น',
    'Idol Fashion': 'แฟชั่นไอดอล',
    'Seoul Fashion Week': 'Seoul Fashion Week',
    'Fashion Vocabulary': 'คำศัพท์แฟชั่น',
    'Fashion Districts': 'ย่านแฟชั่น',
    'Shopping Dialogue': 'บทสนทนาช้อปปิ้ง',
    'Hanbok & Traditional Fashion': 'ฮันบกและแฟชั่นดั้งเดิม',
    'Rice Obsession': 'ความหลงใหลในข้าว',
    'Youth Protection Laws': 'กฎหมายคุ้มครองเยาวชน',
    'Fast Delivery Culture': 'วัฒนธรรมส่งด่วน',
    'Invasive Species Crisis': 'วิกฤตสิ่งมีชีวิตต่างถิ่น',
    'Table Call Culture': 'วัฒนธรรมกดออดที่โต๊ะ',
    'Public Transport': 'ขนส่งสาธารณะ',
    'Jjimjilbang': 'จิมจิลบัง',
    'Plastic Surgery Culture': 'วัฒนธรรมศัลยกรรม',
    'Outdoor Drinking': 'ดื่มกลางแจ้ง',
    'Jeonse Housing': 'ที่อยู่อาศัยระบบจอนเซ',
    'Traditions & Holidays': 'ประเพณีและวันหยุด',
    '100 Korean Proverbs': 'สุภาษิตเกาหลี 100 คำ',
    'K-Gaming Stats': 'สถิติ K-Gaming',
    'Gaming Timeline': 'ไทม์ไลน์เกม',
    'Gaming Legends': 'ตำนานวงการเกม',
    'Iconic Games': 'เกมในตำนาน',
    'Streaming Culture': 'วัฒนธรรมสตรีมมิ่ง',
    'PC Bang Culture': 'วัฒนธรรมพีซีบัง',
    'PC방 Culture': 'วัฒนธรรม PC방',
    'Esports Leagues': 'ลีกอีสปอร์ต',
    'Gamer Slang': 'สแลงเกมเมอร์',
    'Gaming Vocabulary': 'คำศัพท์เกม',
    'Sports Overview': 'ภาพรวมกีฬา',
    'Football Heroes': 'ฮีโร่ฟุตบอล',
    'Baseball Heroes': 'ฮีโร่เบสบอล',
    'Marathon Legends': 'ตำนานมาราธอน',
    'Individual Legends': 'ตำนานประเภทบุคคล',
    'Traditional Sports': 'กีฬาดั้งเดิม',
    'Cheer Chants': 'เพลงเชียร์',
    'Travel Guide · 여행 안내': 'คู่มือท่องเที่ยว · 여행 안내',
    'South Korea': 'เกาหลีใต้',
    'By Days · 일수별': 'ตามจำนวนวัน · 일수별',
    '1 Day Trip · 당일치기': 'ทริป 1 วัน · 당일치기',
    '2 Days · 1박 2일': '2 วัน · 1박 2일',
    '3 Days · 2박 3일': '3 วัน · 2박 3일',
    '5 Days · 4박 5일': '5 วัน · 4박 5일',
    '1 Week · 일주일': '1 สัปดาห์ · 일주일',
    '10 Days': '10 วัน',
    '2 Weeks · 2주': '2 สัปดาห์ · 2주',
    '1 Month+ · 한달': '1 เดือน+ · 한달',
    'By City · 도시별': 'ตามเมือง · 도시별',
    'Seoul · 서울': 'โซล · 서울',
    'Incheon · 인천': 'อินชอน · 인천',
    'Busan · 부산': 'ปูซาน · 부산',
    'Suwon · 수원': 'ซูวอน · 수원',
    'Jeju · 제주도': 'เชจู · 제주도',
    'Gyeongju · 경주': 'คย็องจู · 경주',
    'Other Cities': 'เมืองอื่นๆ',
    'By Theme · 테마별': 'ตามธีม · 테마별',
    'Food Tour · 음식 여행': 'ทัวร์อาหาร · 음식 여행',
    'Events & Festivals · 이벤트': 'งานอีเวนต์และเทศกาล · 이벤트',
    'Sightseeing · 관광': 'เที่ยวชม · 관광',
    'Cross-Country · 장거리': 'ทางไกล · 장거리',
    '📋 Trip Planner · 여행 계획표': '📋 วางแผนทริป · 여행 계획표',
    'Day-by-Day Itineraries': 'แผนเที่ยวรายวัน',
    'City Travel Guides': 'คู่มือเที่ยวเมือง',
    'Themed Travel': 'ท่องเที่ยวตามธีม',
    'Bus': 'รถบัส',
    'Subway': 'รถไฟใต้ดิน',
    'Taxi': 'แท็กซี่',
    'KTX High-speed Rail': 'รถไฟความเร็วสูง KTX',
    'Age': 'อายุ',
    'Bowing': 'การโค้งคำนับ',
    'Drinking': 'การดื่ม',
    'Eating': 'การกิน',
    'Quiet': 'ความเงียบ',
    'Shoes': 'รองเท้า',
    'Tipping': 'ทิป',
    'Two Hands': 'สองมือ',
    'International': 'ต่างประเทศ',
    'Politics': 'การเมือง',
    'Economy': 'เศรษฐกิจ',
    'Society': 'สังคม',
    'Science': 'วิทยาศาสตร์',
    'Culture': 'วัฒนธรรม',
    'Sports': 'กีฬา',
    'Education': 'การศึกษา',
    'Environment': 'สิ่งแวดล้อม',
    'Discover the beauty of Korea through language, culture, K-pop, travel, and cuisine — with free lessons designed for learners worldwide.': 'ค้นพบความงดงามของเกาหลีผ่านภาษา วัฒนธรรม K-pop การท่องเที่ยว และอาหาร — พร้อมบทเรียนฟรีที่ออกแบบมาสำหรับผู้เรียนทั่วโลก',
    'Learn the Korean alphabet in just 2 hours. 한글 (Hangul) is remarkably logical — once you know the 24 basic letters, you can read anything.': 'เรียนอักษรเกาหลีในเวลาเพียง 2 ชั่วโมง 한글 (Hangul) มีเหตุผลอย่างน่าทึ่ง — เมื่อรู้ตัวอักษรพื้นฐาน 24 ตัว คุณจะอ่านได้ทุกอย่าง',
    'Learn Korean naturally through your favourite songs. Line-by-line breakdowns with vocabulary, grammar notes, and pronunciation guides.': 'เรียนภาษาเกาหลีอย่างเป็นธรรมชาติผ่านเพลงโปรดของคุณ วิเคราะห์ทีละบรรทัดพร้อมคำศัพท์ หมายเหตุไวยากรณ์ และคำแนะนำการออกเสียง',
    'Pick up everyday Korean from your favourite dramas. Contextual vocabulary lists organised by show, genre, and proficiency level.': 'เรียนภาษาเกาหลีในชีวิตประจำวันจากซีรีส์โปรดของคุณ รายการคำศัพท์ตามบริบท จัดตามเรื่อง แนว และระดับความสามารถ',
    'From 김치 (kimchi) to 삼겹살 (samgyeopsal) — explore the rich vocabulary of Korean cuisine with pronunciation and cultural context.': 'จาก 김치 (กิมจิ) ถึง 삼겹살 (ซัมกยอบซัล) — สำรวจคำศัพท์อาหารเกาหลีอันหลากหลาย พร้อมคำอ่านและบริบททางวัฒนธรรม',
    'Whether you are just starting or aiming for fluency, we have a clear roadmap to take you there step by step.': 'ไม่ว่าคุณจะเพิ่งเริ่มต้นหรือมุ่งสู่ความคล่องแคล่ว เรามีแผนการเรียนที่ชัดเจนพาคุณไปทีละขั้น',
    'Language is the gateway — immerse yourself in Korean pop culture, food, and beauty to supercharge your learning.': 'ภาษาคือประตูสู่ทุกสิ่ง — ดื่มด่ำกับวัฒนธรรมป๊อป อาหาร และความงามเกาหลี เพื่อเร่งการเรียนรู้ของคุณ',
    'From BTS to BLACKPINK — the most common Korean words and phrases used by your favourite K-Pop artists, with pronunciation guides.': 'จาก BTS ถึง BLACKPINK — คำและวลีเกาหลีที่ใช้บ่อยที่สุดโดยศิลปิน K-Pop คนโปรดของคุณ พร้อมคำแนะนำการออกเสียง',
    'Korean dramas are packed with emotional vocabulary. Learn how characters express joy, sadness, anger, and love in authentic Korean.': 'ซีรีส์เกาหลีเต็มไปด้วยคำศัพท์แสดงอารมณ์ เรียนรู้วิธีที่ตัวละครแสดงความสุข เศร้า โกรธ และรักในภาษาเกาหลีแท้ๆ',
    'Essential phrases for ordering food, asking for the bill, and navigating a Korean restaurant menu with confidence.': 'วลีสำคัญสำหรับสั่งอาหาร ขอเช็กบิล และอ่านเมนูร้านอาหารเกาหลีอย่างมั่นใจ',
    'Explore the world of K-Beauty with essential vocabulary for skincare routines, cosmetics, and Korean beauty trends.': 'สำรวจโลกของ K-Beauty ด้วยคำศัพท์สำคัญเกี่ยวกับสกินแคร์ เครื่องสำอาง และเทรนด์ความงามเกาหลี',
    'Learn the language of every destination. From bustling Seoul to the serene shores of Jeju — your AI travel guide is ready.': 'เรียนภาษาของทุกจุดหมายปลายทาง จากโซลอันคึกคักถึงชายฝั่งอันสงบของเชจู — ไกด์ทัวร์ AI ของคุณพร้อมแล้ว',
    'South Korea\'s dazzling capital — from the ancient palaces of Gyeongbokgung to the neon streets of Gangnam and Hongdae.': 'เมืองหลวงอันตระการตาของเกาหลีใต้ — จากพระราชวังเคียงบกกุงโบราณถึงถนนไฟนีออนของกังนัมและฮงแด',
    'Korea\'s vibrant port city with stunning beaches, fresh seafood markets, and a unique dialect worth discovering.': 'เมืองท่าอันมีชีวิตชีวาของเกาหลี พร้อมชายหาดสวยงาม ตลาดอาหารทะเลสด และสำเนียงเฉพาะตัวที่น่าค้นหา',
    'Korea\'s paradise island — volcanic landscapes, pristine beaches, tangerine groves, and the famous haenyeo diving culture.': 'เกาะสวรรค์ของเกาหลี — ภูมิประเทศภูเขาไฟ ชายหาดบริสุทธิ์ สวนส้มเขียวหวาน และวัฒนธรรมนักดำน้ำแฮนยอชื่อดัง',
    'Seoul': 'โซล',
    'Busan': 'ปูซาน',
    'Jeju Island': 'เกาะเชจู',
    'Test Your Korean': 'ทดสอบภาษาเกาหลีของคุณ',
    'Explore →': 'สำรวจ →',
    'K-Pop Lyrics Learning': 'เรียนเนื้อเพลง K-Pop',
    'K-Drama Vocabulary': 'คำศัพท์ K-Drama',
    'Korean Food Dictionary': 'พจนานุกรมอาหารเกาหลี',
    'Master Korean Emotions Through K-Drama': 'เชี่ยวชาญอารมณ์เกาหลีผ่าน K-Drama',
    'Order Like a Local: Restaurant Korean': 'สั่งอาหารแบบคนท้องถิ่น: ภาษาเกาหลีในร้านอาหาร',
    'Beauty & Skincare Vocabulary in Korean': 'คำศัพท์ความงามและสกินแคร์ภาษาเกาหลี',
    'K-Pop Stars\' Korean Phrases You Need to Know': 'วลีเกาหลีจากสตาร์ K-Pop ที่ควรรู้',
    'Read →': 'อ่าน →',
    'Hello / Good day': 'สวัสดี',
    'annyeonghaseyo': 'อันนยองฮาเซโย',
    '✓ Hangul Alphabet': '✓ อักษร Hangul',
    '✓ Basic Vowels & Consonants': '✓ สระและพยัญชนะพื้นฐาน',
    '✓ Syllable Blocks': '✓ บล็อกพยางค์',
    '✓ Essential Vocabulary': '✓ คำศัพท์จำเป็น',
    '✓ Basic Greetings': '✓ คำทักทายพื้นฐาน',
    '✓ Korean Grammar (SOV)': '✓ ไวยากรณ์เกาหลี (SOV)',
    '✓ Particles & Conjugation': '✓ คำช่วยและการผันคำ',
    '✓ Speech Levels': '✓ ระดับภาษา',
    '✓ 300+ Vocabulary Words': '✓ คำศัพท์ 300+ คำ',
    '✓ Real Dialogues': '✓ บทสนทนาจริง',
    '✓ Business Korean': '✓ ภาษาเกาหลีธุรกิจ',
    '✓ Classical Korean': '✓ ภาษาเกาหลีคลาสสิก',
    '✓ Essay Writing': '✓ การเขียนเรียงความ',
    '✓ TOPIK Preparation': '✓ เตรียมสอบ TOPIK',
    '✓ Idiomatic Expressions': '✓ สำนวนภาษา',
    'Hangul Basics · 한글 기초': 'พื้นฐาน Hangul · 한글 기초',
    'Korean Grammar · 문법': 'ไวยากรณ์เกาหลี · 문법',
    'Vocabulary · 어휘': 'คำศัพท์ · 어휘',
    'Pronunciation · 발음': 'การออกเสียง · 발음',
    'Korean Food · 음식': 'อาหารเกาหลี · 음식',
    'K-Beauty · 뷰티': 'K-Beauty · 뷰티',
    'K-Drama · 드라마': 'K-Drama · 드라마',
    'K-Pop Lyrics · 가사': 'เนื้อเพลง K-Pop · 가사',
    'TOPIK Prep · 토픽 준비': 'เตรียมสอบ TOPIK · 토픽 준비',
    'Flashcards · 플래시카드': 'แฟลชการ์ด · 플래시카드',
    'Start Here · 여기서 시작': 'เริ่มที่นี่ · 여기서 시작',
    'Daily Vocabulary · 오늘의 단어': 'คำศัพท์รายวัน · 오늘의 단어',
    'Travel Guide · 여행': 'คู่มือท่องเที่ยว · 여행',
    'Blog · 블로그': 'บล็อก · 블로그',
    'About Us · 소개': 'เกี่ยวกับเรา · 소개',
    'Contact · 연락처': 'ติดต่อ · 연락처',
    'Jeju · 제주': 'เชจู · 제주',
    'Privacy': 'ความเป็นส่วนตัว',
    'Terms': 'ข้อกำหนด',
    'Terms of Service': 'ข้อกำหนดการใช้งาน',
    'K-FOOD · 한국 음식': 'K-FOOD · 한국 음식',
    'Charcoal grill (best)': 'ย่างถ่าน (ดีที่สุด)',
    'Side dishes (free refill)': 'เครื่องเคียง (เติมฟรี)',
    'Lettuce wrap style': 'ห่อผักกาดหอม',
    'About this lesson': 'เกี่ยวกับบทเรียนนี้',
    'Korean Grammar': 'ไวยากรณ์เกาหลี',
    '✏️ Beginner · Lesson 1': '✏️ เริ่มต้น · บทที่ 1',
    '📐 Intermediate · Lesson 7': '📐 ปานกลาง · บทที่ 7',
    '60 min read': 'อ่าน 60 นาที',
    'Alphabet': 'อักษร',
    '📐 Intermediate · Lesson 5': '📐 ปานกลาง · บทที่ 5',
    '🎯 26 Stages · 70 Steps': '🎯 26 ระดับ · 70 ขั้น',
    '📊 Beginner–Advanced': '📊 เริ่มต้น–ขั้นสูง',
    '⏱️ ~90 min': '⏱️ ~90 นาที',
    '📝 Advanced · Lesson 12': '📝 ขั้นสูง · บทที่ 12',
    '✍️ Essay Structure Guide': '✍️ คู่มือโครงสร้างเรียงความ',
    '📊 Advanced': '📊 ขั้นสูง',
    '🔖 Writing': '🔖 การเขียน',
    '🔗 Connective Grammar': '🔗 ไวยากรณ์เชื่อมประโยค',
    '💼 Advanced · Lesson 13': '💼 ขั้นสูง · บทที่ 13',
    '🏢 Workplace Expressions': '🏢 สำนวนที่ทำงาน',
    '🔖 Professional': '🔖 มืออาชีพ',
    '🤝 Business Etiquette': '🤝 มารยาททางธุรกิจ',
    '📜 Advanced · Lesson 14': '📜 ขั้นสูง · บทที่ 14',
    '📜 Hanja (한자) Roots': '📜 รากศัพท์ฮันจา (한자)',
    '🔖 History & Literature': '🔖 ประวัติศาสตร์และวรรณกรรม',
    '🏛️ Historical Korean Texts': '🏛️ ตำราเกาหลีโบราณ',
    '💬 All Levels · 40 Dialogues': '💬 ทุกระดับ · 40 บทสนทนา',
    '💬 40 Full Dialogues': '💬 บทสนทนาเต็ม 40 บท',
    '🔖 Real-world Korean': '🔖 ภาษาเกาหลีในชีวิตจริง',
    '🔊 Audio on Every Line': '🔊 เสียงทุกบรรทัด',
    'Expressing': 'การแสดงออก',
    '📊 Intermediate': '📊 ปานกลาง',
    '📊 Beginner–Intermediate': '📊 เริ่มต้น–ปานกลาง',
    '🎯 6 Stages · 84 Steps': '🎯 6 ระดับ · 84 ขั้น',
    '🎯 5 Stages · 61 Steps': '🎯 5 ระดับ · 61 ขั้น',
    '🎯 6 Stages · 68 Steps': '🎯 6 ระดับ · 68 ขั้น',
    '⏱️ ~60–90 min': '⏱️ ~60–90 นาที',
    '⏱️ ~50 min': '⏱️ ~50 นาที',
    '⏱️ ~60 min': '⏱️ ~60 นาที',
    '⏱ 30 min': '⏱ 30 นาที',
    '⏱ 28 min': '⏱ 28 นาที',
    '⏱ 29 min': '⏱ 29 นาที',
    '🔊 Audio on every word': '🔊 เสียงทุกคำ',
    '🔊 Audio on every phrase': '🔊 เสียงทุกวลี',
    '🔊 Audio on every form': '🔊 เสียงทุกรูปแบบ',
    '4 stages with listen-and-repeat audio and quizzes throughout': '4 ระดับ พร้อมเสียงฟังตามและแบบทดสอบตลอดบทเรียน',
    'Learn Hangul in 1 Hour:': 'เรียน Hangul ใน 1 ชั่วโมง:',
    'Created in 1443 by King Sejong the Great': 'สร้างขึ้นในปี 1443 โดยพระเจ้าเซจงมหาราช',
    'Phonetic alphabet — each symbol = one sound': 'อักษรแทนเสียง — 1 สัญลักษณ์ = 1 เสียง',
    '6 stages to cover every character': '6 ระดับครอบคลุมทุกตัวอักษร',
    'Most learners finish in under 90 minutes': 'ผู้เรียนส่วนใหญ่จบภายใน 90 นาที',
    '🔷 Beginner · Lesson 2': '🔷 เริ่มต้น · บทที่ 2',
    'Korean Syllable Blocks:': 'บล็อกพยางค์เกาหลี:',
    'Every syllable is a compact square block — not a horizontal letter string': 'ทุกพยางค์คือบล็อกสี่เหลี่ยม ไม่ใช่ตัวอักษรเรียงแนวนอน',
    'Each block holds exactly 1 vowel plus up to 2 consonants': 'แต่ละบล็อกมี 1 สระ และพยัญชนะได้สูงสุด 2 ตัว',
    '4 structural patterns: CV, V, CVC, VC — all follow the same rules': '4 รูปแบบโครงสร้าง: CV, V, CVC, VC — ใช้กฎเดียวกันทั้งหมด',
    'Master the block structure and you can sound out any Korean word': 'เข้าใจโครงสร้างบล็อกแล้วอ่านออกเสียงคำเกาหลีได้ทุกคำ',
    '8 sound change rules — why Korean spelling and pronunciation differ': '8 กฎการเปลี่ยนเสียง — ทำไมตัวสะกดกับการออกเสียงเกาหลีต่างกัน',
    'Batchim, liaison, assimilation, tensification, palatalization, and more': 'ตัวสะกด การเชื่อมเสียง การกลมกลืนเสียง การกลายเป็นเสียงเข้ม การเปลี่ยนเสียงเพดาน และอื่นๆ',
    'Fix the 6 most common mistakes English speakers make': 'แก้ 6 ข้อผิดพลาดที่พบบ่อยของผู้พูดภาษาอังกฤษ',
    'Audio examples on every step — tap any word to hear it': 'ตัวอย่างเสียงทุกขั้นตอน — แตะคำเพื่อฟังเสียง',
    'Korean Grammar:': 'ไวยากรณ์เกาหลี:',
    'SOV word order — the verb always comes last': 'โครงสร้างประโยค SOV — คำกริยาอยู่ท้ายเสมอ',
    'Particles replace rigid word-position rules': 'คำช่วยแทนที่กฎตำแหน่งคำตายตัว',
    '26 stages: sentences to advanced patterns': '26 ระดับ: จากประโยคพื้นฐานถึงรูปแบบขั้นสูง',
    'Most learners complete in under 90 minutes': 'ผู้เรียนส่วนใหญ่จบภายใน 90 นาที',
    '🏠 Beginner · Lesson 5': '🏠 เริ่มต้น · บทที่ 5',
    'Common Korean': 'ภาษาเกาหลีที่ใช้บ่อย',
    'Master people, family, place, time, and object nouns in Korean': 'เชี่ยวชาญคำนามบุคคล ครอบครัว สถานที่ เวลา และสิ่งของในภาษาเกาหลี',
    'Learn how Korean counters (개, 명, 잔) work with numbers': 'เรียนรู้การใช้ลักษณนาม (개, 명, 잔) กับตัวเลข',
    'Understand the possessive marker 의 and polite vs casual forms': 'เข้าใจคำช่วยแสดงความเป็นเจ้าของ 의 และรูปแบบสุภาพกับไม่เป็นทางการ',
    '👥 Beginner · Lesson 4': '👥 เริ่มต้น · บทที่ 4',
    'Learn polite 저 vs casual 나, and why Korean often drops pronouns entirely': 'เรียนรู้ 저 แบบสุภาพกับ 나 แบบไม่เป็นทางการ และทำไมเกาหลีมักละคำสรรพนาม',
    'Understand why 당신 is rarely used and how to address people naturally': 'เข้าใจว่าทำไม 당신 แทบไม่ถูกใช้ และวิธีเรียกคนอย่างเป็นธรรมชาติ',
    'Master 우리 (our/my), demonstratives (이것·그것·저것), and question words': 'เชี่ยวชาญ 우리 (ของเรา/ของฉัน) คำชี้ (이것·그것·저것) และคำถาม',
    '✏️ Starter · Lesson 1': '✏️ เริ่มต้น · บทที่ 1',
    'Hangul Alphabet:': 'อักษร Hangul:',
    '⏱ 45 min read': '⏱ อ่าน 45 นาที',
    '📊 Beginner': '📊 เริ่มต้น',
    '🔖 Hangul Basics · 한글 기초': '🔖 พื้นฐาน Hangul · 한글 기초',
    '🔡 Syllable Block Patterns': '🔡 รูปแบบบล็อกพยางค์',
    '📘 Common Compound Batchim Examples': '📘 ตัวอย่างตัวสะกดควบที่พบบ่อย',
    '👁 18,204 views': '👁 18,204 ครั้ง',
    'What is Hangul? (한글이란?)': 'Hangul คืออะไร? (한글이란?)',
    'Basic Vowels (기본 모음)': 'สระพื้นฐาน (기본 모음)',
    'Hangul at a Glance': 'Hangul โดยสรุป',
    'Basic Consonants': 'พยัญชนะพื้นฐาน',
    'Basic Vowels': 'สระพื้นฐาน',
    'Double Consonants': 'พยัญชนะคู่',
    'Compound Vowels': 'สระประสม',
    'Fun Fact': 'เกร็ดน่ารู้',
    'Why does ㅇ appear at the start?': 'ทำไม ㅇ ถึงอยู่ต้นพยางค์?',
    'Vowel Shape Mnemonics': 'เทคนิคจำรูปสระ',
    'About Hangul (한글)': 'เกี่ยวกับ Hangul (한글)',
    'Basic Vowels (모음)': 'สระพื้นฐาน (모음)',
    'Compound Vowels (복합 모음)': 'สระประสม (복합 모음)',
    'Basic Consonants (자음)': 'พยัญชนะพื้นฐาน (자음)',
    'Syllable Blocks (음절)': 'บล็อกพยางค์ (음절)',
    'Tense (Double) Consonants — 쌍자음': 'พยัญชนะเสียงเข้ม (คู่) — 쌍자음',
    'Compound Batchim (겹받침)': 'ตัวสะกดควบ (겹받침)',
    'Aspirated Consonants — 거센소리': 'พยัญชนะเสียงพ่นลม — 거센소리',
    'Quick Practice Quiz': 'แบบทดสอบสั้นๆ',
    'Did you know?': 'รู้หรือไม่?',
    'Vowel Harmony': 'ความกลมกลืนของสระ',
    'Reading Practice': 'ฝึกอ่าน',
    'The Tissue Test': 'การทดสอบด้วยกระดาษทิชชู',
    '10 basic vowels': 'สระพื้นฐาน 10 ตัว',
    '11 compound vowels': 'สระประสม 11 ตัว',
    '14 basic consonants': 'พยัญชนะพื้นฐาน 14 ตัว',
    '5 tense consonants': 'พยัญชนะเสียงเข้ม 5 ตัว',
    '5 aspirated consonants': 'พยัญชนะเสียงพ่นลม 5 ตัว',
    'October 9 is Hangul Day (한글날) in South Korea — a national holiday celebrating the invention of the alphabet in 1443.': '9 ตุลาคม คือวัน Hangul (한글날) ในเกาหลีใต้ — วันหยุดประจำชาติเฉลิมฉลองการประดิษฐ์อักษรในปี 1443',
    'Structure': 'โครงสร้าง',
    'Example': 'ตัวอย่าง',
    'Reading': 'การอ่าน',
    'Meaning': 'ความหมาย',
    'Consonant + Vowel': 'พยัญชนะ + สระ',
    'go (verb stem)': 'ไป (รากคำกริยา)',
    'Consonant + Vowel + Consonant': 'พยัญชนะ + สระ + พยัญชนะ',
    'Korean (prefix)': 'เกาหลี (คำนำหน้า)',
    'Silent ㅇ + Vowel': 'ㅇ ไม่ออกเสียง + สระ',
    'ah! (exclamation)': 'อ๊ะ! (คำอุทาน)',
    'Batchim': 'ตัวสะกด',
    'Example Word': 'คำตัวอย่าง',
    'Note': 'หมายเหตุ',
    'to read': 'อ่าน',
    'to sit': 'นั่ง',
    'life': 'ชีวิต',
    'k (aspirated)': 'k (เสียงพ่นลม)',
    't (aspirated)': 't (เสียงพ่นลม)',
    'p (aspirated)': 'p (เสียงพ่นลม)',
    'ch (aspirated)': 'ch (เสียงพ่นลม)',
    '← Home': '← หน้าแรก',
    'Mark as Complete ✓': 'ทำเครื่องหมายว่าเสร็จ ✓',
    'Syllable Blocks →': 'บล็อกพยางค์ →',
    'Word Order — SOV Structure (어순)': 'ลำดับคำ — โครงสร้าง SOV (어순)',
    'Korean Particles (조사)': 'คำช่วยเกาหลี (조사)',
    'Particle Practice': 'ฝึกคำช่วย',
    'Speech Levels (존댓말 vs 반말)': 'ระดับภาษา (존댓말 vs 반말)',
    'Present Tense (-아요/-어요)': 'ปัจจุบันกาล (-아요/-어요)',
    'Past Tense (-았어요/-었어요)': 'อดีตกาล (-았어요/-었어요)',
    'Future Tense (-을 거예요/-ㄹ 거예요)': 'อนาคตกาล (-을 거예요/-ㄹ 거예요)',
    'Making Sentences Negative (부정문)': 'ประโยคปฏิเสธ (부정문)',
    'Forming Questions (의문문)': 'การตั้งคำถาม (의문문)',
    'WH- Question Words': 'คำถาม WH',
    'Essential Sentence Patterns (문형)': 'รูปประโยคสำคัญ (문형)',
    'Connectors: 그리고, 그래서, 그렇지만, 그런데': 'คำเชื่อม: 그리고, 그래서, 그렇지만, 그런데',
    'And, With: -하고, -(이)랑': 'และ, กับ: -하고, -(이)랑',
    'To/From Someone: -한테, -한테서': 'ให้/จาก: -한테, -한테서',
    'Telling Time (시간 말하기)': 'บอกเวลา (시간 말하기)',
    'Counters (단위 명사)': 'ลักษณนาม (단위 명사)',
    'Present Progressive: -고 있어요': 'กำลังทำ: -고 있어요',
    'Particle': 'คำช่วย',
    'Function': 'หน้าที่',
    'Rule': 'กฎ',
    'Level': 'ระดับ',
    'When to Use': 'ใช้เมื่อไร',
    'Dictionary Form': 'รูปพจนานุกรม',
    'Stem': 'ราก',
    'Conjugated': 'รูปผัน',
    'Counter': 'ลักษณนาม',
    'Used for': 'ใช้กับ',
    'Vowel': 'สระ',
    'Shape Mnemonic': 'เทคนิคจำรูปร่าง',
    'Mouth Position': 'ตำแหน่งปาก',
    'Time': 'เวลา',
    'Register': 'ระดับภาษา',
    'Used with': 'ใช้กับ',
    'Formal equivalent': 'คำที่เป็นทางการ',
    'Korean · 한국어': 'ภาษาเกาหลี · 한국어',
    'Translation · 번역': 'คำแปล · 번역',
    'Topic marker': 'คำช่วยหัวข้อ',
    'Subject marker': 'คำช่วยประธาน',
    'Object marker': 'คำช่วยกรรม',
    '🔊 Beginner · Lesson 3': '🔊 เริ่มต้น · บทที่ 3',
    'Pronunciation Guide:': 'คู่มือการออกเสียง:',
    '⏱ 50 min read': '⏱ อ่าน 50 นาที',
    '🔖 Pronunciation': '🔖 การออกเสียง',
    '👁 14,837 views': '👁 14,837 ครั้ง',
    'sound change rules': 'กฎการเปลี่ยนเสียง',
    'Batchim — Syllable-Final Consonants (받침)': 'ตัวสะกด — พยัญชนะท้ายพยางค์ (받침)',
    '7 possible sounds': '7 เสียงที่เป็นไปได้',
    'Sound Group': 'กลุ่มเสียง',
    'Written As': 'เขียนเป็น',
    'Pronounced As': 'ออกเสียงเป็น',
    'Unreleased stops': 'เสียงกักไม่ปล่อยลม',
    'The ㅇ Placeholder Rule': 'กฎ ㅇ ตัวเติมช่องว่าง',
    'Vertical vs Horizontal Vowels': 'สระแนวตั้งกับแนวนอน',
    'Quick Visual Trick': 'เทคนิคจำด้วยภาพ',
    'Building Your First Syllables': 'สร้างพยางค์แรกของคุณ',
    'Adding Batchim — The Final Consonant': 'เพิ่มตัวสะกด — พยัญชนะท้าย',
    'Reading Real Korean Words': 'อ่านคำเกาหลีจริง',
    'Practice & Summary': 'ฝึกฝนและสรุป',
    '5 Rules for Korean Syllable Blocks': '5 กฎบล็อกพยางค์เกาหลี',
    '📝 Self-Test: Identify the Components': '📝 ทดสอบตัวเอง: ระบุส่วนประกอบ',
    'Saying \'You\' in Korean': 'พูดคำว่า "คุณ" ในภาษาเกาหลี',
    'Third Person & We (그·그녀·우리)': 'บุรุษที่สามและเรา (그·그녀·우리)',
    'Demonstrative Pronouns (이·그·저)': 'คำสรรพนามชี้ (이·그·저)',
    'Question Pronouns (의문대명사)': 'คำสรรพนามคำถาม (의문대명사)',
    'Pronouns Complete!': 'จบเรื่องสรรพนาม!',
    '😊 Intermediate · Lesson 7': '😊 ปานกลาง · บทที่ 7',
    'Core Emotions': 'อารมณ์พื้นฐาน',
    'Expressing Feelings': 'แสดงความรู้สึก',
    'Complex Emotions': 'อารมณ์ซับซ้อน',
    'Emotional Phrases': 'วลีแสดงอารมณ์',
    'Emotions in Korean (감정)': 'อารมณ์ในภาษาเกาหลี (감정)',
    'Emotions Complete!': 'จบเรื่องอารมณ์!',
    '🛒 Intermediate · Lesson 8': '🛒 ปานกลาง · บทที่ 8',
    'Shopping Vocabulary': 'คำศัพท์ช้อปปิ้ง',
    'In the Store': 'ในร้าน',
    'Prices & Numbers': 'ราคาและตัวเลข',
    'Transactions': 'การซื้อขาย',
    'Shopping in Korea (쇼핑)': 'ช้อปปิ้งในเกาหลี (쇼핑)',
    'Shopping Complete!': 'จบเรื่องช้อปปิ้ง!',
    '🗣️ Intermediate · Lesson 6': '🗣️ ปานกลาง · บทที่ 6',
    '합쇼체 (Formal)': '합쇼체 (ทางการ)',
    '해요체 (Polite)': '해요체 (สุภาพ)',
    '반말 (Casual)': '반말 (ไม่เป็นทางการ)',
    'Choosing a Level': 'เลือกระดับภาษา',
    'Korean Speech Levels Overview': 'ภาพรวมระดับภาษาเกาหลี',
    'Speech Levels Complete!': 'จบเรื่องระดับภาษา!',
    'saved to flashcards': 'บันทึกลงแฟลชการ์ดแล้ว',
    'No words match your search.': 'ไม่พบคำที่ตรงกับการค้นหา',
    'Failed to load vocabulary.': 'โหลดคำศัพท์ไม่สำเร็จ',
    '★ Add all in category': '★ เพิ่มทั้งหมดในหมวดนี้',
    'Verbs': 'คำกริยา',
    'Media': 'สื่อ',
  };

  if (window.LangManager) {
    LangManager.register('th', TH);
  }
})();
