'use strict';
/* ═══════════════════════════════════════════════════════════════════════
   Brazilian Portuguese UI language pack.

   These are the strings LangManager.t() substitutes into page chrome — nav,
   sidebar, buttons, card titles, section headings. NOTHING else in this repo
   can see them: the lesson-content audits (qa-lang.cjs) and the prose audits
   (audit-*-locale-dup.cjs) are both blind here. Coverage is measured ONLY by
   `node scripts/ui-lang.cjs --status`, against the 631-key `de` baseline.

   Thai shipped with 430 of 631 keys missing — two thirds of the interface in
   English — while its lesson content scored 4/5, because nothing measured
   this file. Do not let pt-BR repeat that: this pack must read 631/631
   before any page of pt-BR content is generated.

   ⚠️ DO NOT HAND-EDIT THE TAIL. `ui-lang.cjs --apply` appends entries just
   before the closing `};`. Trailing-comma conventions differ between packs,
   and a bad append produces two adjacent string literals — a SyntaxError that
   silently kills every translation for the locale. --apply detects this,
   re-parses after writing, and rolls back if the file does not survive.

   Register: você, informal. Brazilian Portuguese, not European — see
   scripts/_trans/glossary/pt-br.json for the binding terminology decisions.
   ═══════════════════════════════════════════════════════════════════════ */
(function() {
  const PT_BR = {
    // ── added by scripts/ui-lang.cjs ───────────────────────
    'Learn': 'Aprender',
    'Quiz': 'Quiz',
    'K-Culture': 'K-Culture',
    'Travel': 'Viagem',
    'Search...': 'Buscar...',
    'Search lessons, vocabulary…': 'Buscar lições, vocabulário…',
    'Search lessons...': 'Buscar lições...',
    'Loading lesson…': 'Carregando lição…',
    'Previous': 'Anterior',
    'Next': 'Próximo',
    '📚 Lesson 4 · vocabulary': '📚 Lição 4 · vocabulário',
    'Search Results': 'Resultados da Busca',
    '← Back to Home': '← Voltar ao Início',
    '🇰🇷 · Free · For Every Level': '🇰🇷 · Grátis · Para Todos os Níveis',
    'Learn Korean': 'Aprender Coreano',
    'Start Learning': 'Começar a Aprender',
    'Explore K-Culture': 'Explorar K-Culture',
    'Vocabulary Words': 'Palavras do Vocabulário',
    'Lessons': 'Lições',
    'Active Learners': 'Estudantes Ativos',
    '% Free': '% Grátis',
    'FEATURES': 'RECURSOS',
    'Everything You Need to Learn Korean': 'Tudo que Você Precisa para Aprender Coreano',
    'Start with 한글': 'Comece com 한글',
    'Learn Hangul Now →': 'Aprenda Hangul Agora →',
    'Hear It': 'Ouvir',
    'More Words': 'Mais Palavras',
    'Word of the Day': 'Palavra do Dia',
    'STRUCTURED PATHS · 학습 경로': 'TRILHAS ESTRUTURADAS · 학습 경로',
    'Choose Your Learning Path': 'Escolha sua Trilha de Aprendizado',
    'Beginner': 'Iniciante',
    'Intermediate': 'Intermediário',
    'Advanced': 'Avançado',
    'Start Beginner Path →': 'Iniciar Trilha Iniciante →',
    'Start Intermediate Path →': 'Iniciar Trilha Intermediária →',
    'Start Advanced Path →': 'Iniciar Trilha Avançada →',
    'POPULAR': 'POPULAR',
    'Beginner–Intermediate': 'Iniciante–Intermediário',
    'Intermediate–Advanced': 'Intermediário–Avançado',
    'Beg–Int': 'Ini–Int',
    'K-CULTURE': 'K-CULTURE',
    'K-CULTURE · 한국 문화': 'K-CULTURE · 한국 문화',
    'Experience Korea Beyond Language': 'Viva a Coreia Além do Idioma',
    'Explore All K-Culture Content →': 'Explorar Todo Conteúdo K-Culture →',
    'TRAVEL · 여행': 'VIAGEM · 여행',
    'Explore Korea': 'Explorar a Coreia',
    'View Full Travel Guide →': 'Ver Guia de Viagem Completo →',
    'PRACTICE · 연습': 'PRÁTICA · 연습',
    '10 progressive levels · multiple choice · covers Hangul, Grammar & Vocabulary': '10 níveis progressivos · múltipla escolha · abrange Hangul, Gramática e Vocabulário',
    'Choose a Level': 'Escolha um Nível',
    'questions': 'perguntas',
    '← All Levels': '← Todos os Níveis',
    'Try Again': 'Tentar de Novo',
    'Next Level': 'Próximo Nível',
    'All Levels': 'Todos os Níveis',
    'Next Level →': 'Próximo Nível →',
    '🇰🇷 · South Korea Travel Guide · 여행 안내': '🇰🇷 · Guia de Viagem da Coreia do Sul · 여행 안내',
    'South Korea Travel Guide': 'Guia de Viagem da Coreia do Sul',
    'Population': 'População',
    'UNESCO Sites': 'Sítios da UNESCO',
    'Great to visit': 'Ótimo para visitar',
    'Visa-free nations': 'Países sem necessidade de visto',
    'EXPLORE THE GUIDES · 가이드 탐색': 'EXPLORE OS GUIAS · 가이드 탐색',
    'Plan Your Perfect Korea Trip': 'Planeje sua Viagem Perfeita à Coreia',
    'TOP DESTINATIONS · 인기 여행지': 'PRINCIPAIS DESTINOS · 인기 여행지',
    'Where Will You Explore?': 'Onde Você Vai Explorar?',
    'ESSENTIAL PHRASES · 필수 표현': 'FRASES ESSENCIAIS · 필수 표현',
    'Travel Korean Phrasebook': 'Guia de Frases de Coreano para Viagem',
    'TRANSPORTATION · 교통': 'TRANSPORTE · 교통',
    'Getting Around Korea': 'Se Locomovendo na Coreia',
    'FOOD TOUR · 음식 여행': 'TOUR GASTRONÔMICO · 음식 여행',
    'Regional Korean Specialties': 'Especialidades Regionais Coreanas',
    'CULTURAL ETIQUETTE · 예절': 'ETIQUETA CULTURAL · 예절',
    'Korean Cultural Tips': 'Dicas Culturais Coreanas',
    'TRAVEL APPS · 여행 앱': 'APLICATIVOS DE VIAGEM · 여행 앱',
    'Essential Apps for Korea Travel': 'Aplicativos Essenciais para Viajar à Coreia',
    'READY TO LEARN?': 'PRONTO PARA APRENDER?',
    'Start Speaking Korean Today': 'Comece a Falar Coreano Hoje',
    'Start Learning Korean →': 'Comece a Aprender Coreano →',
    'Plan Your Trip': 'Planeje sua Viagem',
    'K-Pop': 'K-Pop',
    'K-Drama': 'K-Drama',
    'K-Beauty': 'K-Beauty',
    'All': 'Todos',
    'Learn · 학습': 'Aprender · 학습',
    'K-Culture · 문화': 'K-Culture · 문화',
    'Company · 회사': 'Empresa · 회사',
    'Explore': 'Explorar',
    'Company': 'Empresa',
    'Hangul Alphabet': 'Alfabeto Hangul',
    'Grammar': 'Gramática',
    'Vocabulary': 'Vocabulário',
    'Travel Guide': 'Guia de Viagem',
    'About Us': 'Sobre Nós',
    'Contact': 'Contato',
    'Privacy Policy': 'Política de Privacidade',
    'Terms of Use': 'Termos de Uso',
    'Made with ❤️ for Korean learners worldwide.': 'Feito com ❤️ para quem aprende coreano no mundo todo.',
    '🇰🇷 학습을 즐기세요! (Enjoy your learning!)': '🇰🇷 학습을 즐기세요! (Aproveite seu aprendizado!)',
    'Home': 'Início',
    'Hangul': 'Hangul',
    'A free Korean language learning platform — combining language study with K-culture, travel guides, and real-world practice. For learners of every level, worldwide.': 'Uma plataforma gratuita de aprendizado de coreano — combinando o estudo do idioma com K-Culture, guias de viagem e prática no mundo real. Para quem aprende de todos os níveis, no mundo todo.',
    'A free Korean language learning platform for learners of every level, worldwide.': 'Uma plataforma gratuita de aprendizado de coreano para quem aprende de todos os níveis, no mundo todo.',
    '© 2026 한국어 학교. Made with ❤️ for Korean learners worldwide.': '© 2026 한국어 학교. Feito com ❤️ para quem aprende coreano no mundo todo.',
    'Getting Started': 'Primeiros Passos',
    'Tools': 'Ferramentas',
    'CATEGORIES · 카테고리': 'CATEGORIAS · 카테고리',
    'DEEP DIVES · 심층 탐구': 'APROFUNDAMENTOS · 심층 탐구',
    'Introduction': 'Introdução',
    'Syllable Blocks': 'Blocos Silábicos',
    'Pronunciation Guide': 'Guia de Pronúncia',
    'Letter Writing': 'Escrita de Letras',
    'Korean Typing': 'Digitação em Coreano',
    'Vocab': 'Vocabulário',
    'Greetings': 'Cumprimentos',
    'Numbers': 'Números',
    'Family': 'Família',
    'Food & Drink': 'Comida e Bebida',
    'Colors': 'Cores',
    'Days & Time': 'Dias e Horários',
    'Places': 'Lugares',
    'Emotions': 'Emoções',
    'Body Parts': 'Partes do Corpo',
    'Shopping': 'Compras',
    'Weather': 'Clima',
    'Verbs & Actions': 'Verbos e Ações',
    'Adjectives': 'Adjetivos',
    'Workplace': 'Local de Trabalho',
    'Health & Medicine': 'Saúde e Medicina',
    'Media & K-Culture': 'Mídia e K-Culture',
    'Proverbs & Idioms': 'Provérbios e Expressões Idiomáticas',
    'Academic Korean': 'Coreano Acadêmico',
    'News & Society': 'Notícias e Sociedade',
    'Konglish': 'Konglish',
    'Pronouns': 'Pronomes',
    'Common Nouns': 'Substantivos Comuns',
    'Sentence Structure': 'Estrutura da Frase',
    'Korean Particles': 'Partículas Coreanas',
    'Verb Conjugation': 'Conjugação Verbal',
    'Question Forms': 'Formas Interrogativas',
    'Connectors': 'Conectores',
    'And, With': 'E, Com',
    'To/From Someone': 'Para/De Alguém',
    'Telling Time': 'Dizer as Horas',
    'Counters': 'Contadores',
    'Present Progressive': 'Presente Contínuo',
    'Self Introduction': 'Autoapresentação',
    'Dates and Months': 'Datas e Meses',
    'Degree Adverbs': 'Advérbios de Grau',
    'Nominalizer -는 것': 'Nominalizador -는 것',
    'Comparatives': 'Comparativos',
    'Still, Already': 'Ainda, Já',
    'Someone, Something': 'Alguém, Algo',
    'Imperative -(으)세요': 'Imperativo -(으)세요',
    'Don\'t: -지 마세요': 'Não: -지 마세요',
    'Method: -(으)로': 'Método: -(으)로',
    'Good/Poor At': 'Bom/Ruim em',
    '-도 Advanced Uses': 'Usos Avançados de -도',
    'Formal vs Informal': 'Formal vs. Informal',
    'Expressing Emotions': 'Expressando Emoções',
    'Shopping Phrases': 'Frases de Compras',
    'Writing Essays': 'Escrevendo Redações',
    'Business Korean': 'Coreano para Negócios',
    'Classical Korean': 'Coreano Clássico',
    'Korean Dialogues': 'Diálogos em Coreano',
    'Flashcards': 'Cartões de Memorização',
    'K-Movie': 'K-Movie',
    'K-Food': 'K-Food',
    'K-Fashion': 'K-Fashion',
    'Korean Thing': 'Coisa Coreana',
    'K-Gaming': 'K-Gaming',
    'K-Sports': 'K-Sports',
    'K-Pop, K-Drama, food, beauty, fashion, gaming, sports & traditions.': 'K-Pop, K-Drama, comida, beleza, moda, games, esportes e tradições.',
    'K-Pop History': 'História do K-Pop',
    'Agencies': 'Agências',
    'Generations': 'Gerações',
    'Genres': 'Gêneros',
    'Variety Shows': 'Programas de Variedades',
    'Film & Acting': 'Cinema e Atuação',
    'Idol Phrases': 'Frases de Idols',
    'Fan Slang': 'Gírias de Fã',
    'Fan Chants': 'Cânticos de Fã',
    'Drama History': 'História dos K-Dramas',
    'Drama Genres': 'Gêneros de K-Drama',
    'Must-Watch Dramas': 'Dramas Imperdíveis',
    'K-Drama Tropes': 'Clichês de K-Drama',
    'Speech Levels': 'Níveis de Formalidade',
    'Dialogue Practice': 'Prática de Diálogo',
    'Fan Culture & Slang': 'Cultura de Fã e Gírias',
    'Movie History': 'História do Cinema',
    'Movie Genres': 'Gêneros de Filme',
    'Must-Watch Films': 'Filmes Imperdíveis',
    'Directors': 'Diretores',
    'Iconic Lines': 'Falas Icônicas',
    'Fan Culture': 'Cultura de Fã',
    'K-Food Goes Global': 'K-Food Conquista o Mundo',
    'Foods That Went Global': 'Comidas que Conquistaram o Mundo',
    'K-Food Timeline': 'Linha do Tempo do K-Food',
    'Essential Dishes': 'Pratos Essenciais',
    'World-Famous Chefs': 'Chefs Mundialmente Famosos',
    'Ordering & Dining': 'Pedindo e Jantando',
    'Street Food': 'Comida de Rua',
    'Food Culture & Drinking': 'Cultura Gastronômica e Bebidas',
    'Ramyeon Guide': 'Guia de Ramyeon',
    'Mandu Guide': 'Guia de Mandu',
    'Chicken Guide': 'Guia de Frango',
    'K-BBQ Guide': 'Guia de K-BBQ',
    'Kimchi Guide': 'Guia de Kimchi',
    'K-Beauty Goes Global': 'K-Beauty Conquista o Mundo',
    'K-Beauty Timeline': 'Linha do Tempo do K-Beauty',
    'Iconic Brands': 'Marcas Icônicas',
    'Beauty Vocabulary': 'Vocabulário de Beleza',
    '10-Step Skincare': 'Skincare de 10 Passos',
    'Key Ingredients': 'Ingredientes Principais',
    'Beauty Trends': 'Tendências de Beleza',
    'Makeup Philosophy': 'Filosofia da Maquiagem',
    'Skin Clinic Culture': 'Cultura das Clínicas de Estética',
    'K-Beauty Dialogue': 'Diálogo K-Beauty',
    'K-Fashion Global': 'K-Fashion Global',
    'Fashion Icons': 'Ícones da Moda',
    'Fashion Timeline': 'Linha do Tempo da Moda',
    'Style Aesthetics': 'Estética de Estilo',
    'Idol Fashion': 'Moda dos Idols',
    'Seoul Fashion Week': 'Seoul Fashion Week',
    'Fashion Vocabulary': 'Vocabulário de Moda',
    'Fashion Districts': 'Bairros de Moda',
    'Shopping Dialogue': 'Diálogo de Compras',
    'Hanbok & Traditional Fashion': 'Hanbok & Moda Tradicional',
    'Rice Obsession': 'Obsessão pelo Arroz',
    'Youth Protection Laws': 'Leis de Proteção à Juventude',
    'Fast Delivery Culture': 'Cultura de Entrega Rápida',
    'Invasive Species Crisis': 'Crise das Espécies Invasoras',
    'Table Call Culture': 'Cultura da Campainha de Mesa',
    'Public Transport': 'Transporte Público',
    'Jjimjilbang': 'Jjimjilbang',
    'Plastic Surgery Culture': 'Cultura da Cirurgia Plástica',
    'Outdoor Drinking': 'Bebida ao Ar Livre',
    'Jeonse Housing': 'Moradia Jeonse',
    'Traditions & Holidays': 'Tradições & Feriados',
    '100 Korean Proverbs': '100 Provérbios Coreanos',
    'K-Gaming Stats': 'Estatísticas de K-Gaming',
    'Gaming Timeline': 'Linha do Tempo dos Games',
    'Gaming Legends': 'Lendas dos Games',
    'Iconic Games': 'Jogos Icônicos',
    'Streaming Culture': 'Cultura de Streaming',
    'PC Bang Culture': 'Cultura do PC Bang',
    'PC방 Culture': 'Cultura PC방',
    'Esports Leagues': 'Ligas de Esports',
    'Gamer Slang': 'Gíria de Gamers',
    'Gaming Vocabulary': 'Vocabulário de Games',
    'Sports Overview': 'Visão Geral dos Esportes',
    'Football Heroes': 'Heróis do Futebol',
    'Baseball Heroes': 'Heróis do Beisebol',
    'Marathon Legends': 'Lendas da Maratona',
    'Individual Legends': 'Lendas Individuais',
    'Traditional Sports': 'Esportes Tradicionais',
    'Cheer Chants': 'Cantos de Torcida',
    'Travel Guide · 여행 안내': 'Guia de Viagem · 여행 안내',
    'South Korea': 'Coreia do Sul',
    'By Days · 일수별': 'Por Dias · 일수별',
    '1 Day Trip · 당일치기': 'Viagem de 1 Dia · 당일치기',
    '2 Days · 1박 2일': '2 Dias · 1박 2일',
    '3 Days · 2박 3일': '3 Dias · 2박 3일',
    '5 Days · 4박 5일': '5 Dias · 4박 5일',
    '1 Week · 일주일': '1 Semana · 일주일',
    '10 Days': '10 Dias',
    '2 Weeks · 2주': '2 Semanas · 2주',
    '1 Month+ · 한달': '1 Mês+ · 한달',
    'By City · 도시별': 'Por Cidade · 도시별',
    'Seoul · 서울': 'Seul · 서울',
    'Incheon · 인천': 'Incheon · 인천',
    'Busan · 부산': 'Busan · 부산',
    'Suwon · 수원': 'Suwon · 수원',
    'Jeju · 제주도': 'Jeju · 제주도',
    'Gyeongju · 경주': 'Gyeongju · 경주',
    'Other Cities': 'Outras Cidades',
    'By Theme · 테마별': 'Por Tema · 테마별',
    'Food Tour · 음식 여행': 'Tour Gastronômico · 음식 여행',
    'Events & Festivals · 이벤트': 'Eventos & Festivais · 이벤트',
    'Sightseeing · 관광': 'Turismo · 관광',
    'Cross-Country · 장거리': 'Longa Distância · 장거리',
    '📋 Trip Planner · 여행 계획표': '📋 Planejador de Viagem · 여행 계획표',
    'Day-by-Day Itineraries': 'Roteiros Dia a Dia',
    'City Travel Guides': 'Guias de Viagem por Cidade',
    'Themed Travel': 'Viagens Temáticas',
    'Bus': 'Ônibus',
    'Subway': 'Metrô',
    'Taxi': 'Táxi',
    'KTX High-speed Rail': 'Trem de Alta Velocidade KTX',
    'Age': 'Idade',
    'Bowing': 'Reverência',
    'Drinking': 'Bebida',
    'Eating': 'Alimentação',
    'Quiet': 'Silêncio',
    'Shoes': 'Sapatos',
    'Tipping': 'Gorjeta',
    'Two Hands': 'Duas Mãos',
    'International': 'Internacional',
    'Politics': 'Política',
    'Economy': 'Economia',
    'Society': 'Sociedade',
    'Science': 'Ciência',
    'Culture': 'Cultura',
    'Sports': 'Esportes',
    'Education': 'Educação',
    'Environment': 'Meio Ambiente',
    'Discover the beauty of Korea through language, culture, K-pop, travel, and cuisine — with free lessons designed for learners worldwide.': 'Descubra a beleza da Coreia através do idioma, da cultura, do K-pop, das viagens e da culinária — com aulas gratuitas criadas para quem aprende no mundo todo.',
    'Learn the Korean alphabet in just 2 hours. 한글 (Hangul) is remarkably logical — once you know the 24 basic letters, you can read anything.': 'Aprenda o alfabeto coreano em apenas 2 horas. 한글 (Hangul) é surpreendentemente lógico — assim que você conhecer as 24 letras básicas, poderá ler qualquer coisa.',
    'Learn Korean naturally through your favourite songs. Line-by-line breakdowns with vocabulary, grammar notes, and pronunciation guides.': 'Aprenda coreano naturalmente através das suas músicas favoritas. Explicações linha por linha com vocabulário, notas de gramática e guias de pronúncia.',
    'Pick up everyday Korean from your favourite dramas. Contextual vocabulary lists organised by show, genre, and proficiency level.': 'Aprenda coreano do dia a dia com seus doramas favoritos. Listas de vocabulário contextual organizadas por série, gênero e nível de proficiência.',
    'From 김치 (kimchi) to 삼겹살 (samgyeopsal) — explore the rich vocabulary of Korean cuisine with pronunciation and cultural context.': 'De 김치 (kimchi) a 삼겹살 (samgyeopsal) — explore o rico vocabulário da culinária coreana com pronúncia e contexto cultural.',
    'Whether you are just starting or aiming for fluency, we have a clear roadmap to take you there step by step.': 'Seja você iniciante ou esteja buscando fluência, temos um roteiro claro para te levar até lá passo a passo.',
    'Language is the gateway — immerse yourself in Korean pop culture, food, and beauty to supercharge your learning.': 'O idioma é a porta de entrada — mergulhe na cultura pop coreana, na comida e na beleza para turbinar seu aprendizado.',
    'From BTS to BLACKPINK — the most common Korean words and phrases used by your favourite K-Pop artists, with pronunciation guides.': 'De BTS a BLACKPINK — as palavras e frases coreanas mais comuns usadas pelos seus artistas de K-Pop favoritos, com guias de pronúncia.',
    'Korean dramas are packed with emotional vocabulary. Learn how characters express joy, sadness, anger, and love in authentic Korean.': 'Os doramas coreanos são repletos de vocabulário emocional. Aprenda como os personagens expressam alegria, tristeza, raiva e amor em coreano autêntico.',
    'Essential phrases for ordering food, asking for the bill, and navigating a Korean restaurant menu with confidence.': 'Frases essenciais para pedir comida, solicitar a conta e navegar com confiança pelo cardápio de um restaurante coreano.',
    'Explore the world of K-Beauty with essential vocabulary for skincare routines, cosmetics, and Korean beauty trends.': 'Explore o mundo do K-Beauty com vocabulário essencial para rotinas de skincare, cosméticos e tendências de beleza coreana.',
    'Learn the language of every destination. From bustling Seoul to the serene shores of Jeju — your AI travel guide is ready.': 'Aprenda o idioma de cada destino. Da agitada Seul às serenas praias de Jeju — seu guia de viagem com IA está pronto.',
    'South Korea\'s dazzling capital — from the ancient palaces of Gyeongbokgung to the neon streets of Gangnam and Hongdae.': 'A deslumbrante capital da Coreia do Sul — dos antigos palácios de Gyeongbokgung às ruas neon de Gangnam e Hongdae.',
    'Korea\'s vibrant port city with stunning beaches, fresh seafood markets, and a unique dialect worth discovering.': 'A vibrante cidade portuária da Coreia, com praias deslumbrantes, mercados de frutos do mar frescos e um dialeto único que vale a pena descobrir.',
    'Korea\'s paradise island — volcanic landscapes, pristine beaches, tangerine groves, and the famous haenyeo diving culture.': 'A ilha paraíso da Coreia — paisagens vulcânicas, praias intocadas, pomares de tangerina e a famosa cultura de mergulho haenyeo.',
    'Seoul': 'Seul',
    'Busan': 'Busan',
    'Jeju Island': 'Ilha de Jeju',
    'Test Your Korean': 'Teste Seu Coreano',
    'Explore →': 'Explorar →',
    'K-Pop Lyrics Learning': 'Aprendizado de Letras de K-Pop',
    'K-Drama Vocabulary': 'Vocabulário de K-Drama',
    'Korean Food Dictionary': 'Dicionário de Comida Coreana',
    'Master Korean Emotions Through K-Drama': 'Domine as Emoções Coreanas Através do K-Drama',
    'Order Like a Local: Restaurant Korean': 'Peça Como um Local: Coreano de Restaurante',
    'Beauty & Skincare Vocabulary in Korean': 'Vocabulário de Beleza & Skincare em Coreano',
    'K-Pop Stars\' Korean Phrases You Need to Know': 'Frases Coreanas de Estrelas do K-Pop Que Você Precisa Saber',
    'Read →': 'Ler →',
    'Hello / Good day': 'Olá / Bom dia',
    'annyeonghaseyo': 'annyeonghaseyo',
    '✓ Hangul Alphabet': '✓ Alfabeto Hangul',
    '✓ Basic Vowels & Consonants': '✓ Vogais & Consoantes Básicas',
    '✓ Syllable Blocks': '✓ Blocos Silábicos',
    '✓ Essential Vocabulary': '✓ Vocabulário Essencial',
    '✓ Basic Greetings': '✓ Saudações Básicas',
    '✓ Korean Grammar (SOV)': '✓ Gramática Coreana (SOV)',
    '✓ Particles & Conjugation': '✓ Partículas & Conjugação',
    '✓ Speech Levels': '✓ Níveis de Formalidade',
    '✓ 300+ Vocabulary Words': '✓ 300+ Palavras de Vocabulário',
    '✓ Real Dialogues': '✓ Diálogos Reais',
    '✓ Business Korean': '✓ Coreano de Negócios',
    '✓ Classical Korean': '✓ Coreano Clássico',
    '✓ Essay Writing': '✓ Redação',
    '✓ TOPIK Preparation': '✓ Preparação para o TOPIK',
    '✓ Idiomatic Expressions': '✓ Expressões Idiomáticas',
    'Hangul Basics · 한글 기초': 'Fundamentos do Hangul · 한글 기초',
    'Korean Grammar · 문법': 'Gramática Coreana · 문법',
    'Vocabulary · 어휘': 'Vocabulário · 어휘',
    'Pronunciation · 발음': 'Pronúncia · 발음',
    'Korean Food · 음식': 'Comida Coreana · 음식',
    'K-Beauty · 뷰티': 'K-Beauty · 뷰티',
    'K-Drama · 드라마': 'K-Drama · 드라마',
    'K-Pop Lyrics · 가사': 'Letras de K-Pop · 가사',
    'TOPIK Prep · 토픽 준비': 'Preparação para o TOPIK · 토픽 준비',
    'Flashcards · 플래시카드': 'Cartões de Memorização · 플래시카드',
    'Start Here · 여기서 시작': 'Comece Aqui · 여기서 시작',
    'Daily Vocabulary · 오늘의 단어': 'Vocabulário Diário · 오늘의 단어',
    'Travel Guide · 여행': 'Guia de Viagem · 여행',
    'Blog · 블로그': 'Blog · 블로그',
    'About Us · 소개': 'Sobre Nós · 소개',
    'Contact · 연락처': 'Contato · 연락처',
    'Jeju · 제주': 'Jeju · 제주',
    'Privacy': 'Privacidade',
    'Terms': 'Termos',
    'Terms of Service': 'Termos de Serviço',
    'K-FOOD · 한국 음식': 'K-FOOD · 한국 음식',
    'Charcoal grill (best)': 'Grelha de carvão (melhor)',
    'Side dishes (free refill)': 'Acompanhamentos (reposição grátis)',
    'Lettuce wrap style': 'Enrolado em alface',
    'About this lesson': 'Sobre esta lição',
    'Korean Grammar': 'Gramática Coreana',
    '✏️ Beginner · Lesson 1': '✏️ Iniciante · Lição 1',
    '📐 Intermediate · Lesson 7': '📐 Intermediário · Lição 7',
    '60 min read': '60 min de leitura',
    'Alphabet': 'Alfabeto',
    '📐 Intermediate · Lesson 5': '📐 Intermediário · Lição 5',
    '🎯 26 Stages · 70 Steps': '🎯 26 Estágios · 70 Etapas',
    '📊 Beginner–Advanced': '📊 Iniciante–Avançado',
    '⏱️ ~90 min': '⏱️ ~90 min',
    '⚡ XP + Streak system': '⚡ Sistema de XP + Sequência',
    '📝 Advanced · Lesson 12': '📝 Avançado · Lição 12',
    '✍️ Essay Structure Guide': '✍️ Guia de Estrutura de Redação',
    '📊 Advanced': '📊 Avançado',
    '🔖 Writing': '🔖 Escrita',
    '🔗 Connective Grammar': '🔗 Gramática Conectiva',
    '💼 Advanced · Lesson 13': '💼 Avançado · Lição 13',
    '🏢 Workplace Expressions': '🏢 Expressões do Ambiente de Trabalho',
    '🔖 Professional': '🔖 Profissional',
    '🤝 Business Etiquette': '🤝 Etiqueta Empresarial',
    '📜 Advanced · Lesson 14': '📜 Avançado · Lição 14',
    '📜 Hanja (한자) Roots': '📜 Raízes Hanja (한자)',
    '🔖 History & Literature': '🔖 História & Literatura',
    '🏛️ Historical Korean Texts': '🏛️ Textos Históricos Coreanos',
    '💬 All Levels · 40 Dialogues': '💬 Todos os Níveis · 40 Diálogos',
    '💬 40 Full Dialogues': '💬 40 Diálogos Completos',
    '📊 All Levels': '📊 Todos os Níveis',
    '🔖 Real-world Korean': '🔖 Coreano do Dia a Dia',
    '🔊 Audio on Every Line': '🔊 Áudio em Cada Linha',
    'Korean': 'Coreano',
    'Expressing': 'Expressando',
    'Nouns': 'Substantivos',
    '📊 Intermediate': '📊 Intermediário',
    '📊 Beginner–Intermediate': '📊 Iniciante–Intermediário',
    '🎯 6 Stages · 84 Steps': '🎯 6 Estágios · 84 Etapas',
    '🎯 5 Stages · 61 Steps': '🎯 5 Estágios · 61 Etapas',
    '🎯 6 Stages · 68 Steps': '🎯 6 Estágios · 68 Etapas',
    '⏱️ ~60–90 min': '⏱️ ~60–90 min',
    '⏱️ ~50 min': '⏱️ ~50 min',
    '⏱️ ~60 min': '⏱️ ~60 min',
    '⏱ 30 min': '⏱ 30 min',
    '⏱ 28 min': '⏱ 28 min',
    '⏱ 29 min': '⏱ 29 min',
    '🔊 Audio on every word': '🔊 Áudio em cada palavra',
    '🔊 Audio on every phrase': '🔊 Áudio em cada frase',
    '🔊 Audio on every form': '🔊 Áudio em cada forma',
    '4 stages with listen-and-repeat audio and quizzes throughout': '4 estágios com áudio de ouvir e repetir e quizzes ao longo do caminho',
    'Learn Hangul in 1 Hour:': 'Aprenda Hangul em 1 Hora:',
    'Created in 1443 by King Sejong the Great': 'Criado em 1443 pelo Rei Sejong, o Grande',
    'Phonetic alphabet — each symbol = one sound': 'Alfabeto fonético — cada símbolo = um som',
    '6 stages to cover every character': '6 estágios para cobrir cada caractere',
    'Most learners finish in under 90 minutes': 'A maioria dos estudantes termina em menos de 90 minutos',
    '🔷 Beginner · Lesson 2': '🔷 Iniciante · Lição 2',
    'Korean Syllable Blocks:': 'Blocos Silábicos Coreanos:',
    'Every syllable is a compact square block — not a horizontal letter string': 'Cada sílaba é um bloco quadrado compacto — não uma sequência horizontal de letras',
    'Each block holds exactly 1 vowel plus up to 2 consonants': 'Cada bloco contém exatamente 1 vogal e até 2 consoantes',
    '4 structural patterns: CV, V, CVC, VC — all follow the same rules': '4 padrões estruturais: CV, V, CVC, VC — todos seguem as mesmas regras',
    'Master the block structure and you can sound out any Korean word': 'Domine a estrutura dos blocos e você conseguirá pronunciar qualquer palavra coreana',
    '8 sound change rules — why Korean spelling and pronunciation differ': '8 regras de mudança sonora — por que a escrita e a pronúncia coreanas diferem',
    'Batchim, liaison, assimilation, tensification, palatalization, and more': 'Batchim, ligação, assimilação, tensificação, palatalização e mais',
    'Fix the 6 most common mistakes English speakers make': 'Corrija os 6 erros mais comuns cometidos por falantes de inglês',
    'Audio examples on every step — tap any word to hear it': 'Exemplos de áudio em cada etapa — toque em qualquer palavra para ouvi-la',
    'Korean Grammar:': 'Gramática Coreana:',
    'SOV word order — the verb always comes last': 'Ordem das palavras SOV — o verbo sempre vem por último',
    'Particles replace rigid word-position rules': 'Partículas substituem regras rígidas de posição das palavras',
    '26 stages: sentences to advanced patterns': '26 estágios: de frases a padrões avançados',
    'Most learners complete in under 90 minutes': 'A maioria dos estudantes conclui em menos de 90 minutos',
    '🏠 Beginner · Lesson 5': '🏠 Iniciante · Lição 5',
    'Common Korean': 'Coreano Comum',
    'Master people, family, place, time, and object nouns in Korean': 'Domine substantivos de pessoas, família, lugar, tempo e objetos em coreano',
    'Learn how Korean counters (개, 명, 잔) work with numbers': 'Aprenda como os classificadores coreanos (개, 명, 잔) funcionam com números',
    'Understand the possessive marker 의 and polite vs casual forms': 'Entenda o marcador possessivo 의 e as formas polidas e casuais',
    '👥 Beginner · Lesson 4': '👥 Iniciante · Lição 4',
    'Learn polite 저 vs casual 나, and why Korean often drops pronouns entirely': 'Aprenda o 저 polido vs. o 나 casual, e por que o coreano costuma omitir pronomes completamente',
    'Understand why 당신 is rarely used and how to address people naturally': 'Entenda por que 당신 raramente é usado e como se dirigir às pessoas naturalmente',
    'Master 우리 (our/my), demonstratives (이것·그것·저것), and question words': 'Domine 우리 (nosso/meu), demonstrativos (이것·그것·저것) e palavras interrogativas',
    '🗂 21 Categories': '🗂 21 Categorias',
    '🔊 Audio on every card': '🔊 Áudio em cada cartão',
    'Covers 500+ core Korean words across 21 categories': 'Abrange mais de 500 palavras essenciais do coreano em 21 categorias',
    'Bite-sized steps with instant audio — tap any card to hear it': 'Etapas curtas com áudio instantâneo — toque em qualquer cartão para ouvir',
    'Quizzes after every category to lock in your memory': 'Quizzes após cada categoria para fixar na memória',
    'Most learners finish each category in under 15 minutes': 'A maioria dos estudantes termina cada categoria em menos de 15 minutos',
    '✏️ Starter · Lesson 1': '✏️ Inicial · Lição 1',
    'Hangul Alphabet:': 'Alfabeto Hangul:',
    '⏱ 45 min read': '⏱ 45 min de leitura',
    '📊 Beginner': '📊 Iniciante',
    '🔖 Hangul Basics · 한글 기초': '🔖 Fundamentos do Hangul · 한글 기초',
    '🔡 Syllable Block Patterns': '🔡 Padrões de Blocos Silábicos',
    '📘 Common Compound Batchim Examples': '📘 Exemplos Comuns de Batchim Composto',
    '👁 18,204 views': '👁 18.204 visualizações',
    'What is Hangul? (한글이란?)': 'O que é Hangul? (한글이란?)',
    'Basic Vowels (기본 모음)': 'Vogais Básicas (기본 모음)',
    'Hangul at a Glance': 'Hangul em Resumo',
    'Basic Consonants': 'Consoantes Básicas',
    'Basic Vowels': 'Vogais Básicas',
    'Double Consonants': 'Consoantes Duplas',
    'Compound Vowels': 'Vogais Compostas',
    'Fun Fact': 'Curiosidade',
    'Why does ㅇ appear at the start?': 'Por que ㅇ aparece no início?',
    'Vowel Shape Mnemonics': 'Mnemônicos de Formato das Vogais',
    'About Hangul (한글)': 'Sobre o Hangul (한글)',
    'Basic Vowels (모음)': 'Vogais Básicas (모음)',
    'Compound Vowels (복합 모음)': 'Vogais Compostas (복합 모음)',
    'Basic Consonants (자음)': 'Consoantes Básicas (자음)',
    'Syllable Blocks (음절)': 'Blocos Silábicos (음절)',
    'Tense (Double) Consonants — 쌍자음': 'Consoantes Tensas (Duplas) — 쌍자음',
    'Compound Batchim (겹받침)': 'Batchim Composto (겹받침)',
    'Aspirated Consonants — 거센소리': 'Consoantes Aspiradas — 거센소리',
    'Quick Practice Quiz': 'Quiz Rápido de Prática',
    'Did you know?': 'Você sabia?',
    'Vowel Harmony': 'Harmonia Vocálica',
    'Reading Practice': 'Prática de Leitura',
    'The Tissue Test': 'O Teste do Lenço de Papel',
    '10 basic vowels': '10 vogais básicas',
    '11 compound vowels': '11 vogais compostas',
    '14 basic consonants': '14 consoantes básicas',
    '5 tense consonants': '5 consoantes tensas',
    '5 aspirated consonants': '5 consoantes aspiradas',
    'October 9 is Hangul Day (한글날) in South Korea — a national holiday celebrating the invention of the alphabet in 1443.': '9 de outubro é o Dia do Hangul (한글날) na Coreia do Sul — um feriado nacional que celebra a invenção do alfabeto em 1443.',
    'Structure': 'Estrutura',
    'Example': 'Exemplo',
    'Reading': 'Leitura',
    'Meaning': 'Significado',
    'Consonant + Vowel': 'Consoante + Vogal',
    'go (verb stem)': 'ir (raiz verbal)',
    'Consonant + Vowel + Consonant': 'Consoante + Vogal + Consoante',
    'Korean (prefix)': 'Coreano (prefixo)',
    'Silent ㅇ + Vowel': 'ㅇ Mudo + Vogal',
    'ah! (exclamation)': 'ah! (exclamação)',
    'Batchim': 'Batchim',
    'Example Word': 'Palavra de Exemplo',
    'Note': 'Observação',
    'to read': 'ler',
    'to sit': 'sentar',
    'life': 'vida',
    'k (aspirated)': 'k (aspirado)',
    't (aspirated)': 't (aspirado)',
    'p (aspirated)': 'p (aspirado)',
    'ch (aspirated)': 'ch (aspirado)',
    '← Home': '← Início',
    'Mark as Complete ✓': 'Marcar como concluída ✓',
    'Syllable Blocks →': 'Blocos Silábicos →',
    'Word Order — SOV Structure (어순)': 'Ordem das Palavras — Estrutura SOV (어순)',
    'Korean Particles (조사)': 'Partículas Coreanas (조사)',
    'Particle Practice': 'Prática de Partículas',
    'Speech Levels (존댓말 vs 반말)': 'Níveis de Formalidade (존댓말 vs 반말)',
    'Present Tense (-아요/-어요)': 'Presente (-아요/-어요)',
    'Past Tense (-았어요/-었어요)': 'Passado (-았어요/-었어요)',
    'Future Tense (-을 거예요/-ㄹ 거예요)': 'Futuro (-을 거예요/-ㄹ 거예요)',
    'Making Sentences Negative (부정문)': 'Formando Frases Negativas (부정문)',
    'Forming Questions (의문문)': 'Formando Perguntas (의문문)',
    'WH- Question Words': 'Palavras Interrogativas (WH-)',
    'Essential Sentence Patterns (문형)': 'Padrões Essenciais de Frases (문형)',
    'Connectors: 그리고, 그래서, 그렇지만, 그런데': 'Conectivos: 그리고, 그래서, 그렇지만, 그런데',
    'And, With: -하고, -(이)랑': 'E, Com: -하고, -(이)랑',
    'To/From Someone: -한테, -한테서': 'Para/De Alguém: -한테, -한테서',
    'Telling Time (시간 말하기)': 'Dizendo as Horas (시간 말하기)',
    'Counters (단위 명사)': 'Classificadores (단위 명사)',
    'Present Progressive: -고 있어요': 'Presente Contínuo: -고 있어요',
    'Particle': 'Partícula',
    'Function': 'Função',
    'Rule': 'Regra',
    'Level': 'Nível',
    'When to Use': 'Quando Usar',
    'Dictionary Form': 'Forma de Dicionário',
    'Stem': 'Raiz',
    'Conjugated': 'Conjugado',
    'Counter': 'Classificador',
    'Used for': 'Usado para',
    'Vowel': 'Vogal',
    'Shape Mnemonic': 'Mnemônico de Formato',
    'Mouth Position': 'Posição da Boca',
    'Time': 'Hora',
    'Register': 'Registro',
    'Used with': 'Usado com',
    'Formal equivalent': 'Equivalente Formal',
    'Korean · 한국어': 'Coreano · 한국어',
    'Translation · 번역': 'Tradução · 번역',
    'Topic marker': 'Marcador de tópico',
    'Subject marker': 'Marcador de sujeito',
    'Object marker': 'Marcador de objeto',
    '🔊 Beginner · Lesson 3': '🔊 Iniciante · Lição 3',
    'Pronunciation Guide:': 'Guia de Pronúncia:',
    '⏱ 50 min read': '⏱ 50 min de leitura',
    '🔖 Pronunciation': '🔖 Pronúncia',
    '👁 14,837 views': '👁 14.837 visualizações',
    'sound change rules': 'regras de mudança sonora',
    'Batchim — Syllable-Final Consonants (받침)': 'Batchim — Consoantes Finais de Sílaba (받침)',
    '7 possible sounds': '7 sons possíveis',
    'Sound Group': 'Grupo Sonoro',
    'Written As': 'Escrito Como',
    'Pronounced As': 'Pronunciado Como',
    'Unreleased stops': 'Oclusivas Não Liberadas',
    'The ㅇ Placeholder Rule': 'A Regra do ㅇ como Marcador de Posição',
    'Vertical vs Horizontal Vowels': 'Vogais Verticais vs. Horizontais',
    'Quick Visual Trick': 'Truque Visual Rápido',
    'Building Your First Syllables': 'Construindo Suas Primeiras Sílabas',
    'Adding Batchim — The Final Consonant': 'Adicionando Batchim — A Consoante Final',
    'Reading Real Korean Words': 'Lendo Palavras Reais em Coreano',
    'Practice & Summary': 'Prática & Resumo',
    '5 Rules for Korean Syllable Blocks': '5 Regras para Blocos Silábicos Coreanos',
    '📝 Self-Test: Identify the Components': '📝 Autoteste: Identifique os Componentes',
    'Saying \'You\' in Korean': 'Dizendo “Você” em Coreano',
    'Third Person & We (그·그녀·우리)': 'Terceira Pessoa & Nós (그·그녀·우리)',
    'Demonstrative Pronouns (이·그·저)': 'Pronomes Demonstrativos (이·그·저)',
    'Question Pronouns (의문대명사)': 'Pronomes Interrogativos (의문대명사)',
    'Pronouns Complete!': 'Pronomes Concluídos!',
    '😊 Intermediate · Lesson 7': '😊 Intermediário · Lição 7',
    'Core Emotions': 'Emoções Básicas',
    'Expressing Feelings': 'Expressando Sentimentos',
    'Complex Emotions': 'Emoções Complexas',
    'Emotional Phrases': 'Frases Emocionais',
    'Emotions in Korean (감정)': 'Emoções em Coreano (감정)',
    'Emotions Complete!': 'Emoções Concluídas!',
    '🛒 Intermediate · Lesson 8': '🛒 Intermediário · Lição 8',
    'Shopping Vocabulary': 'Vocabulário de Compras',
    'In the Store': 'Na Loja',
    'Prices & Numbers': 'Preços & Números',
    'Transactions': 'Transações',
    'Shopping in Korea (쇼핑)': 'Compras na Coreia (쇼핑)',
    'Shopping Complete!': 'Compras Concluídas!',
    '🗣️ Intermediate · Lesson 6': '🗣️ Intermediário · Lição 6',
    '합쇼체 (Formal)': '합쇼체 (Formal)',
    '해요체 (Polite)': '해요체 (Polido)',
    '반말 (Casual)': '반말 (Casual)',
    'Choosing a Level': 'Escolhendo um Nível',
    'Korean Speech Levels Overview': 'Visão Geral dos Níveis de Formalidade do Coreano',
    'Speech Levels Complete!': 'Níveis de Formalidade Concluídos!',
    'Vocab Browser': 'Navegador de Vocabulário',
    'saved to flashcards': 'salvo nos cartões de memorização',
    'Loading vocabulary…': 'Carregando vocabulário…',
    'No words match your search.': 'Nenhuma palavra corresponde à sua busca.',
    'Failed to load vocabulary.': 'Falha ao carregar o vocabulário.',
    'Search Korean, English, or romanization…': 'Buscar em coreano, inglês ou romanização…',
    '★ Add all in category': '★ Adicionar todos da categoria',
    'Verbs': 'Verbos',
    'Health': 'Saúde',
    'Media': 'Mídia',
    'Proverbs': 'Provérbios',
    'Academic': 'Acadêmico',
    '✓ Correct!': '✓ Correto!',
    '✗ Not quite — try again!': '✗ Quase — tente de novo!',
    '{n}-day streak': 'sequência de {n} dias',
    '{n} steps today': '{n} etapas hoje',
    'Continue': 'Continuar',
    'Step {n} of {m}': 'Etapa {n} de {m}',
    'Steps completed': 'Etapas concluídas',
    'Words & phrases learned': 'Palavras e frases aprendidas',
    'Letters & syllables learned': 'Letras e sílabas aprendidas',
    'Best streak': 'Melhor sequência',
    'Start Again': 'Começar de novo',
    'Next Lesson →': 'Próxima Lição →',
    'Next →': 'Próximo →',
    'Progress': 'Progresso',
    'Reset all progress': 'Redefinir todo o progresso',
    '🔥 Daily streak + real progress tracking': '🔥 Sequência diária + rastreamento real de progresso',
  };
  if (window.LangManager) window.LangManager.register('pt-br', PT_BR);
})();
