'use strict';
(function() {
  const DE = {
    // ── Navigation & Global UI ─────────────────────────
    'Learn': 'Lernen', 'Quiz': 'Quiz', 'K-Culture': 'K-Culture', 'Travel': 'Reisen',
    'Search...': 'Suchen...', 'Search lessons, vocabulary…': 'Lektionen, Vokabular suchen…', 'Search lessons...': 'Lektionen suchen...',
    'Loading lesson…': 'Lektion wird geladen…', 'Previous': 'Zurück', 'Next': 'Weiter', '📚 Lesson 4 · vocabulary': '📚 Lektion 4 · Vokabeln',
    'Search Results': 'Suchergebnisse', '← Back to Home': '← Zurück zur Startseite',
    '🇰🇷 · Free · For Every Level': '🇰🇷 · Kostenlos · Für jedes Niveau',
    'Learn Korean': 'Koreanisch lernen', 'Start Learning': 'Jetzt starten', 'Explore K-Culture': 'K-Culture entdecken',
    'Vocabulary Words': 'Vokabeln', 'Lessons': 'Lektionen', 'Active Learners': 'Aktive Lernende', '% Free': '% Kostenlos',
    'FEATURES': 'FUNKTIONEN', 'Everything You Need to Learn Korean': 'Alles, was du brauchst, um Koreanisch zu lernen',
    'Start with 한글': 'Beginne mit 한글', 'Learn Hangul Now →': 'Hangul jetzt lernen →',
    'Hear It': 'Anhören', 'More Words': 'Mehr Wörter', 'Word of the Day': 'Wort des Tages',
    'STRUCTURED PATHS · 학습 경로': 'Strukturierte Lernpfade · 학습 경로',
    'Choose Your Learning Path': 'Wähle deinen Lernpfad',
    'Beginner': 'Anfänger', 'Intermediate': 'Mittelstufe', 'Advanced': 'Fortgeschritten',
    'Start Beginner Path →': 'Anfängerpfad starten →', 'Start Intermediate Path →': 'Mittelstufenpfad starten →',
    'Start Advanced Path →': 'Fortgeschrittenpfad starten →', 'POPULAR': 'BELIEBT',
    'Beginner–Intermediate': 'Anfänger–Mittelstufe', 'Intermediate–Advanced': 'Mittelstufe–Fortgeschritten',
    'Beg–Int': 'Anf–Mit',
    // ── K-Culture & Home ──────────────────────────────
    'K-CULTURE': 'K-CULTURE', 'K-CULTURE · 한국 문화': 'K-CULTURE · 한국 문화',
    'Experience Korea Beyond Language': 'Korea jenseits der Sprache erleben',
    'Explore All K-Culture Content →': 'Alle K-Culture-Inhalte entdecken →',
    'TRAVEL · 여행': 'REISEN · 여행', 'Explore Korea': 'Korea erkunden',
    'View Full Travel Guide →': 'Vollständigen Reiseführer ansehen →',
    'PRACTICE · 연습': 'ÜBEN · 연습',
    '10 progressive levels · multiple choice · covers Hangul, Grammar & Vocabulary': '10 progressive Stufen · Multiple Choice · Hangul, Grammatik & Vokabular',
    'Choose a Level': 'Stufe wählen', 'questions': 'Fragen', '← All Levels': '← Alle Stufen',
    'Try Again': 'Nochmal versuchen', 'Next Level': 'Nächste Stufe', 'All Levels': 'Alle Stufen',
    'Next Level →': 'Nächste Stufe →',
    // ── Travel ────────────────────────────────────────
    '🇰🇷 · South Korea Travel Guide · 여행 안내': '🇰🇷 · Südkorea-Reiseführer · 여행 안내',
    'South Korea Travel Guide': 'Südkorea-Reiseführer',
    'Population': 'Bevölkerung', 'UNESCO Sites': 'UNESCO-Stätten',
    'Great to visit': 'Besuchsempfehlung', 'Visa-free nations': 'Visafreie Länder',
    'EXPLORE THE GUIDES · 가이드 탐색': 'GUIDES ERKUNDEN · 가이드 탐색',
    'Plan Your Perfect Korea Trip': 'Plane deine perfekte Korea-Reise',
    'TOP DESTINATIONS · 인기 여행지': 'TOP REISEZIELE · 인기 여행지',
    'Where Will You Explore?': 'Wohin reist du?',
    'ESSENTIAL PHRASES · 필수 표현': 'WICHTIGE PHRASEN · 필수 표현',
    'Travel Korean Phrasebook': 'Koreanisches Reise-Phrasenbuch',
    'TRANSPORTATION · 교통': 'VERKEHRSMITTEL · 교통', 'Getting Around Korea': 'Fortbewegung in Korea',
    'FOOD TOUR · 음식 여행': 'FOOD-TOUR · 음식 여행', 'Regional Korean Specialties': 'Regionale koreanische Spezialitäten',
    'CULTURAL ETIQUETTE · 예절': 'KULTURELLE ETIKETTE · 예절', 'Korean Cultural Tips': 'Koreanische Kulturtipps',
    'TRAVEL APPS · 여행 앱': 'REISE-APPS · 여행 앱', 'Essential Apps for Korea Travel': 'Unverzichtbare Apps für Korea-Reisen',
    'READY TO LEARN?': 'BEREIT ZUM LERNEN?', 'Start Speaking Korean Today': 'Fang heute an, Koreanisch zu sprechen',
    'Start Learning Korean →': 'Koreanisch lernen starten →', 'Plan Your Trip': 'Reise planen',
    'K-Pop': 'K-Pop', 'K-Drama': 'K-Drama', 'K-Beauty': 'K-Beauty', 'All': 'Alle',
    // ── Footer & Company ──────────────────────────────
    'Learn · 학습': 'Lernen · 학습', 'K-Culture · 문화': 'K-Culture · 문화',
    'Company · 회사': 'Unternehmen · 회사', 'Explore': 'Entdecken', 'Company': 'Unternehmen',
    'Hangul Alphabet': 'Hangul-Alphabet', 'Grammar': 'Grammatik', 'Vocabulary': 'Vokabular',
    'Travel Guide': 'Reiseführer', 'About Us': 'Über uns',
    'Contact': 'Kontakt', 'Privacy Policy': 'Datenschutzrichtlinie', 'Terms of Use': 'Nutzungsbedingungen',
    'Made with ❤️ for Korean learners worldwide.': 'Mit ❤️ für Koreanischlernende weltweit gemacht.',
    '🇰🇷 학습을 즐기세요! (Enjoy your learning!)': '🇰🇷 학습을 즐기세요! (Viel Spaß beim Lernen!)',
    'Home': 'Startseite', 'Hangul': 'Hangul',
    'A free Korean language learning platform — combining language study with K-culture, travel guides, and real-world practice. For learners of every level, worldwide.': 'Eine kostenlose Plattform zum Koreanischlernen — Sprachunterricht verbunden mit K-Culture, Reiseführern und realer Praxis. Für Lernende jedes Niveaus weltweit.',
    'A free Korean language learning platform for learners of every level, worldwide.': 'Eine kostenlose Koreanisch-Lernplattform für Lernende jedes Niveaus weltweit.',
    '© 2026 한국어 학교. Made with ❤️ for Korean learners worldwide.': '© 2026 한국어 학교. Mit ❤️ für Koreanischlernende weltweit gemacht.',
    // ── Sidebar Dividers ──────────────────────────────
    'Getting Started': 'Erste Schritte', 'Tools': 'Werkzeuge',
    'CATEGORIES · 카테고리': 'KATEGORIEN · 카테고리', 'DEEP DIVES · 심층 탐구': 'VERTIEFUNG · 심층 탐구',
    // ── Learn Sidebar ─────────────────────────────────
    'Introduction': 'Einführung', 'Syllable Blocks': 'Silbenblöcke', 'Pronunciation Guide': 'Ausspracheführer',
    'Vocab': 'Vokabular', 'Greetings': 'Begrüßungen', 'Numbers': 'Zahlen', 'Family': 'Familie',
    'Food & Drink': 'Essen & Trinken', 'Colors': 'Farben', 'Days & Time': 'Tage & Zeit', 'Places': 'Orte',
    'Emotions': 'Gefühle', 'Body Parts': 'Körperteile', 'Shopping': 'Einkaufen', 'Weather': 'Wetter',
    'Verbs & Actions': 'Verben & Handlungen', 'Adjectives': 'Adjektive', 'Workplace': 'Arbeitsplatz',
    'Health & Medicine': 'Gesundheit & Medizin', 'Media & K-Culture': 'Medien & K-Culture',
    'Proverbs & Idioms': 'Sprichwörter & Redewendungen', 'Academic Korean': 'Akademisches Koreanisch',
    'News & Society': 'Nachrichten & Gesellschaft', 'Konglish': 'Konglish', 'Pronouns': 'Pronomen',
    'Common Nouns': 'Häufige Nomen', 'Sentence Structure': 'Satzstruktur', 'Korean Particles': 'Koreanische Partikel',
    'Verb Conjugation': 'Verbkonjugation', 'Question Forms': 'Frageformen', 'Connectors': 'Konnektoren',
    'And, With': 'Und, Mit', 'To/From Someone': 'An/Von jemandem', 'Telling Time': 'Uhrzeit sagen',
    'Counters': 'Zählwörter', 'Present Progressive': 'Verlaufsform', 'Self Introduction': 'Vorstellung',
    'Dates and Months': 'Datum und Monate', 'Degree Adverbs': 'Gradpartikeln',
    'Nominalizer -는 것': 'Nominalisierung -는 것', 'Comparatives': 'Komparative',
    'Still, Already': 'Noch, Schon', 'Someone, Something': 'Jemand, Etwas',
    'Imperative -(으)세요': 'Imperativ -(으)세요', 'Don\'t: -지 마세요': 'Nicht: -지 마세요',
    'Method: -(으)로': 'Methode: -(으)로', 'Good/Poor At': 'Gut/Schlecht in',
    '-도 Advanced Uses': 'Erweiterte Verwendung von 도', 'Formal vs Informal': 'Formell vs. Informell',
    'Expressing Emotions': 'Gefühle ausdrücken', 'Shopping Phrases': 'Einkaufsphrasen', 'Writing Essays': 'Aufsätze schreiben',
    'Business Korean': 'Koreanisch im Geschäftsleben', 'Classical Korean': 'Klassisches Koreanisch', 'Korean Dialogues': 'Koreanische Dialoge',
    'Flashcards': 'Lernkarten',
    // ── Culture Sidebar ───────────────────────────────
    'K-Movie': 'K-Kino', 'K-Food': 'K-Food', 'K-Fashion': 'K-Mode',
    'Korean Thing': 'Koreanisches', 'K-Gaming': 'K-Gaming', 'K-Sports': 'K-Sport',
    'K-Pop, K-Drama, food, beauty, fashion, gaming, sports & traditions.': 'K-Pop, K-Drama, Essen, Beauty, Mode, Gaming, Sport & Traditionen.',
    'K-Pop History': 'K-Pop-Geschichte', 'Agencies': 'Agenturen', 'Generations': 'Generationen', 'Genres': 'Genres',
    'Variety Shows': 'Varieté-Shows', 'Film & Acting': 'Film & Schauspiel', 'Idol Phrases': 'Idol-Phrasen',
    'Fan Slang': 'Fan-Slang', 'Fan Chants': 'Fan-Gesänge', 'Drama History': 'K-Drama-Geschichte',
    'Drama Genres': 'K-Drama-Genres', 'Must-Watch Dramas': 'Sehenswerte Dramas', 'K-Drama Tropes': 'K-Drama-Klischees',
    'Speech Levels': 'Sprachebenen', 'Dialogue Practice': 'Dialogübung',
    'Fan Culture & Slang': 'Fankultur & Slang', 'Movie History': 'Filmgeschichte',
    'Movie Genres': 'Filmgenres', 'Must-Watch Films': 'Sehenswerte Filme', 'Directors': 'Regisseure',
    'Iconic Lines': 'Unvergessliche Zitate', 'Fan Culture': 'Fankultur',
    'K-Food Goes Global': 'K-Food erobert die Welt', 'Foods That Went Global': 'Weltbekannte Lebensmittel',
    'K-Food Timeline': 'K-Food-Zeitlinie', 'Essential Dishes': 'Wichtige Gerichte',
    'World-Famous Chefs': 'Weltbekannte Köche', 'Ordering & Dining': 'Bestellen & Essen',
    'Street Food': 'Streetfood', 'Food Culture & Drinking': 'Esskultur & Trinken',
    'Ramyeon Guide': 'Ramyeon-Leitfaden', 'Mandu Guide': 'Mandu-Leitfaden',
    'Chicken Guide': 'Hühnchen-Leitfaden', 'K-BBQ Guide': 'K-BBQ-Leitfaden', 'Kimchi Guide': 'Kimchi-Leitfaden',
    'K-Beauty Goes Global': 'K-Beauty erobert die Welt', 'K-Beauty Timeline': 'K-Beauty-Zeitlinie',
    'Iconic Brands': 'Ikonische Marken', 'Beauty Vocabulary': 'Beauty-Vokabular', '10-Step Skincare': '10-Schritte-Pflegeroutine',
    'Key Ingredients': 'Wichtige Inhaltsstoffe', 'Beauty Trends': 'Beauty-Trends', 'Makeup Philosophy': 'Make-up-Philosophie',
    'Skin Clinic Culture': 'Schönheitsklinik-Kultur', 'K-Beauty Dialogue': 'K-Beauty-Dialog',
    'K-Fashion Global': 'K-Mode weltweit', 'Fashion Icons': 'Mode-Ikonen',
    'Fashion Timeline': 'Mode-Zeitlinie', 'Style Aesthetics': 'Stil-Ästhetik', 'Idol Fashion': 'Idol-Mode',
    'Seoul Fashion Week': 'Seoul Fashion Week', 'Fashion Vocabulary': 'Mode-Vokabular',
    'Fashion Districts': 'Mode-Viertel', 'Shopping Dialogue': 'Einkaufs-Dialog',
    'Hanbok & Traditional Fashion': 'Hanbok & traditionelle Mode', 'Rice Obsession': 'Reis-Besessenheit',
    'Youth Protection Laws': 'Jugendschutzgesetze', 'Fast Delivery Culture': 'Schnelllieferkultur',
    'Invasive Species Crisis': 'Krise invasiver Arten', 'Table Call Culture': 'Tischklingelkultur',
    'Public Transport': 'Öffentliche Verkehrsmittel', 'Jjimjilbang': 'Jjimjilbang', 'Plastic Surgery Culture': 'Schönheitsoperationskultur',
    'Outdoor Drinking': 'Trinken im Freien', 'Jeonse Housing': 'Jeonse-Wohnungssystem',
    'Traditions & Holidays': 'Traditionen & Feiertage', '100 Korean Proverbs': '100 koreanische Sprichwörter',
    'K-Gaming Stats': 'K-Gaming-Statistiken', 'Gaming Timeline': 'Gaming-Zeitlinie',
    'Gaming Legends': 'Gaming-Legenden', 'Iconic Games': 'Ikonische Spiele', 'Streaming Culture': 'Streaming-Kultur',
    'PC Bang Culture': 'PC-Bang-Kultur', 'PC방 Culture': 'PC방-Kultur', 'Esports Leagues': 'Esports-Ligen',
    'Gamer Slang': 'Gamer-Slang', 'Gaming Vocabulary': 'Gaming-Vokabular', 'Sports Overview': 'Sportüberblick',
    'Football Heroes': 'Fußball-Helden', 'Baseball Heroes': 'Baseball-Helden', 'Marathon Legends': 'Marathon-Legenden',
    'Individual Legends': 'Einzellegenden', 'Traditional Sports': 'Traditionelle Sportarten', 'Cheer Chants': 'Jubel-Gesänge',
    // ── Travel Sidebar ────────────────────────────────
    'Travel Guide · 여행 안내': 'Reiseführer · 여행 안내', 'South Korea': 'Südkorea',
    'By Days · 일수별': 'Nach Tagen · 일수별', '1 Day Trip · 당일치기': 'Tagesausflug · 당일치기',
    '2 Days · 1박 2일': '2 Tage · 1박 2일', '3 Days · 2박 3일': '3 Tage · 2박 3일',
    '5 Days · 4박 5일': '5 Tage · 4박 5일', '1 Week · 일주일': '1 Woche · 일주일',
    '10 Days': '10 Tage', '2 Weeks · 2주': '2 Wochen · 2주', '1 Month+ · 한달': '1 Monat+ · 한달',
    'By City · 도시별': 'Nach Stadt · 도시별', 'Seoul · 서울': 'Seoul · 서울',
    'Incheon · 인천': 'Incheon · 인천', 'Busan · 부산': 'Busan · 부산',
    'Suwon · 수원': 'Suwon · 수원', 'Jeju · 제주도': 'Jeju · 제주도',
    'Gyeongju · 경주': 'Gyeongju · 경주', 'Other Cities': 'Andere Städte',
    'By Theme · 테마별': 'Nach Thema · 테마별', 'Food Tour · 음식 여행': 'Food-Tour · 음식 여행',
    'Events & Festivals · 이벤트': 'Veranstaltungen & Festivals · 이벤트', 'Sightseeing · 관광': 'Sightseeing · 관광',
    'Cross-Country · 장거리': 'Quer durchs Land · 장거리',
    '📋 Trip Planner · 여행 계획표': '📋 Reiseplaner · 여행 계획표',
    'Day-by-Day Itineraries': 'Tagesweise Reisepläne', 'City Travel Guides': 'Stadtreiseführer',
    'Themed Travel': 'Themenreisen', 'Bus': 'Bus', 'Subway': 'U-Bahn', 'Taxi': 'Taxi',
    'KTX High-speed Rail': 'KTX Hochgeschwindigkeitszug', 'Age': 'Alter', 'Bowing': 'Verbeugung',
    'Drinking': 'Trinken', 'Eating': 'Essen', 'Quiet': 'Ruhe', 'Shoes': 'Schuhe',
    'Tipping': 'Trinkgeld', 'Two Hands': 'Beide Hände',
    'International': 'International', 'Politics': 'Politik', 'Economy': 'Wirtschaft', 'Society': 'Gesellschaft',
    'Science': 'Wissenschaft', 'Culture': 'Kultur', 'Sports': 'Sport', 'Education': 'Bildung',
    'Environment': 'Umwelt',
    // ── Homepage Descriptions ─────────────────────────
    'Discover the beauty of Korea through language, culture, K-pop, travel, and cuisine — with free lessons designed for learners worldwide.': 'Entdecke die Schönheit Koreas durch Sprache, Kultur, K-Pop, Reisen und Küche — mit kostenlosen Lektionen für Lernende weltweit.',
    'Learn the Korean alphabet in just 2 hours. 한글 (Hangul) is remarkably logical — once you know the 24 basic letters, you can read anything.': 'Lerne das koreanische Alphabet in nur 2 Stunden. 한글 (Hangul) ist bemerkenswert logisch — wenn du die 24 Grundbuchstaben kennst, kannst du alles lesen.',
    'Learn Korean naturally through your favourite songs. Line-by-line breakdowns with vocabulary, grammar notes, and pronunciation guides.': 'Lerne Koreanisch natürlich durch deine Lieblingslieder. Zeilenweise Erklärungen mit Vokabular, Grammatiknotizen und Ausspracheführern.',
    'Pick up everyday Korean from your favourite dramas. Contextual vocabulary lists organised by show, genre, and proficiency level.': 'Lerne Alltagskoreanisch aus deinen Lieblingsdramas. Kontextuelle Vokabellisten nach Sendung, Genre und Niveau geordnet.',
    'From 김치 (kimchi) to 삼겹살 (samgyeopsal) — explore the rich vocabulary of Korean cuisine with pronunciation and cultural context.': 'Von 김치 (Kimchi) bis 삼겹살 (Samgyeopsal) — erkunde das reiche Vokabular der koreanischen Küche mit Aussprache und Kulturkontext.',
    'Whether you are just starting or aiming for fluency, we have a clear roadmap to take you there step by step.': 'Ob du gerade anfängst oder Fließendheit anstrebst, wir haben einen klaren Fahrplan, der dich Schritt für Schritt dorthin führt.',
    'Language is the gateway — immerse yourself in Korean pop culture, food, and beauty to supercharge your learning.': 'Sprache ist das Tor — tauche in koreanische Popkultur, Essen und Beauty ein, um dein Lernen zu beschleunigen.',
    'From BTS to BLACKPINK — the most common Korean words and phrases used by your favourite K-Pop artists, with pronunciation guides.': 'Von BTS bis BLACKPINK — die häufigsten koreanischen Wörter und Phrasen deiner K-Pop-Lieblingskünstler, mit Ausspracheführern.',
    'Korean dramas are packed with emotional vocabulary. Learn how characters express joy, sadness, anger, and love in authentic Korean.': 'K-Dramas sind vollgepackt mit emotionalem Vokabular. Lerne, wie Charaktere Freude, Trauer, Ärger und Liebe in authentischem Koreanisch ausdrücken.',
    'Essential phrases for ordering food, asking for the bill, and navigating a Korean restaurant menu with confidence.': 'Wichtige Phrasen zum Essen bestellen, die Rechnung verlangen und sicher durch eine koreanische Speisekarte navigieren.',
    'Explore the world of K-Beauty with essential vocabulary for skincare routines, cosmetics, and Korean beauty trends.': 'Erkunde die Welt der K-Beauty mit wichtigem Vokabular für Pflegeroutinen, Kosmetik und koreanische Schönheitstrends.',
    'Learn the language of every destination. From bustling Seoul to the serene shores of Jeju — your AI travel guide is ready.': 'Lerne die Sprache jedes Reiseziels. Vom belebten Seoul bis zu den ruhigen Ufern von Jeju — dein KI-Reiseführer ist bereit.',
    "South Korea's dazzling capital — from the ancient palaces of Gyeongbokgung to the neon streets of Gangnam and Hongdae.": 'Südkoreas glanzvolle Hauptstadt — von den alten Palästen des Gyeongbokgung bis zu den Neon-Straßen von Gangnam und Hongdae.',
    "Korea's vibrant port city with stunning beaches, fresh seafood markets, and a unique dialect worth discovering.": 'Koreas lebhafte Hafenstadt mit atemberaubenden Stränden, frischen Meeresfrüchtemärkten und einem einzigartigen Dialekt.',
    "Korea's paradise island — volcanic landscapes, pristine beaches, tangerine groves, and the famous haenyeo diving culture.": 'Koreas Paradiesinsel — vulkanische Landschaften, unberührte Strände, Mandarinenplantagen und die berühmte Haenyeo-Tauchkultur.',
    // ── Homepage Place Names & Quiz ───────────────────
    'Seoul': 'Seoul', 'Busan': 'Busan', 'Jeju Island': 'Insel Jeju',
    'Test Your Korean': 'Teste dein Koreanisch', 'Explore →': 'Entdecken →',
    // ── Homepage Cards & Labels ───────────────────────
    'K-Pop Lyrics Learning': 'K-Pop-Liedtexte lernen', 'K-Drama Vocabulary': 'K-Drama-Vokabular',
    'Korean Food Dictionary': 'Koreanisches Lebensmittelwörterbuch',
    'Master Korean Emotions Through K-Drama': 'Koreanische Gefühle durch K-Drama meistern',
    'Order Like a Local: Restaurant Korean': 'Wie ein Einheimischer bestellen: Koreanisch im Restaurant',
    'Beauty & Skincare Vocabulary in Korean': 'Beauty- & Pflege-Vokabular auf Koreanisch',
    'K-Pop Stars\' Korean Phrases You Need to Know': 'Koreanische Phrasen von K-Pop-Stars, die du kennen musst',
    'Read →': 'Lesen →', 'Hello / Good day': 'Hallo / Guten Tag',
    'annyeonghaseyo': 'an-nyeong-ha-se-yo',
    // ── Learning Path Checklist ───────────────────────
    '✓ Hangul Alphabet': '✓ Hangul-Alphabet', '✓ Basic Vowels & Consonants': '✓ Grundlegende Vokale & Konsonanten',
    '✓ Syllable Blocks': '✓ Silbenblöcke', '✓ Essential Vocabulary': '✓ Grundvokabular',
    '✓ Basic Greetings': '✓ Grundlegende Begrüßungen', '✓ Korean Grammar (SOV)': '✓ Koreanische Grammatik (SOV)',
    '✓ Particles & Conjugation': '✓ Partikel & Konjugation', '✓ Speech Levels': '✓ Sprachebenen',
    '✓ 300+ Vocabulary Words': '✓ 300+ Vokabeln', '✓ Real Dialogues': '✓ Echte Dialoge',
    '✓ Business Korean': '✓ Geschäftliches Koreanisch', '✓ Classical Korean': '✓ Klassisches Koreanisch',
    '✓ Essay Writing': '✓ Aufsätze schreiben', '✓ TOPIK Preparation': '✓ TOPIK-Vorbereitung',
    '✓ Idiomatic Expressions': '✓ Idiomatische Ausdrücke',
    // ── Homepage Eyebrow Labels ───────────────────────
    'Hangul Basics · 한글 기초': 'Hangul-Grundlagen · 한글 기초',
    'Korean Grammar · 문법': 'Koreanische Grammatik · 문법', 'Vocabulary · 어휘': 'Vokabular · 어휘',
    'Pronunciation · 발음': 'Aussprache · 발음',
    'Korean Food · 음식': 'Koreanisches Essen · 음식', 'K-Beauty · 뷰티': 'K-Beauty · 뷰티',
    'K-Drama · 드라마': 'K-Drama · 드라마', 'K-Pop Lyrics · 가사': 'K-Pop-Liedtexte · 가사',
    'TOPIK Prep · 토픽 준비': 'TOPIK-Vorbereitung · 토픽 준비',
    'Flashcards · 플래시카드': 'Lernkarten · 플래시카드',
    'Start Here · 여기서 시작': 'Hier starten · 여기서 시작',
    'Daily Vocabulary · 오늘의 단어': 'Tägliches Vokabular · 오늘의 단어',
    'Travel Guide · 여행': 'Reiseführer · 여행', 'Blog · 블로그': 'Blog · 블로그',
    'About Us · 소개': 'Über uns · 소개', 'Contact · 연락처': 'Kontakt · 연락처',
    'Seoul · 서울': 'Seoul · 서울', 'Busan · 부산': 'Busan · 부산', 'Jeju · 제주': 'Jeju · 제주',
    'Privacy': 'Datenschutz', 'Terms': 'Nutzungsbedingungen', 'Terms of Service': 'Nutzungsbedingungen',
    'K-FOOD · 한국 음식': 'K-FOOD · 한국 음식',
    // ── Food Page Stats ───────────────────────────────
    'Charcoal grill (best)': 'Holzkohlegrill (am besten)', 'Side dishes (free refill)': 'Beilagen (kostenlose Nachfüllung)',
    'Lettuce wrap style': 'Salatblatt-Wraps',
    // ── Lesson Header Meta ────────────────────────────
    'About this lesson': 'Über diese Lektion', 'Korean Grammar': 'Koreanische Grammatik',
    '✏️ Beginner · Lesson 1': '✏️ Anfänger · Lektion 1',
    '📐 Intermediate · Lesson 7': '📐 Mittelstufe · Lektion 7', '60 min read': '60 Min. lesen',
    'Alphabet': 'Alphabet', '📐 Intermediate · Lesson 5': '📐 Mittelstufe · Lektion 5',
    '🎯 26 Stages · 70 Steps': '🎯 26 Phasen · 70 Schritte',
    '📊 Beginner–Advanced': '📊 Anfänger–Fortgeschritten', '⏱️ ~90 min': '⏱️ ~90 Min.',
    '⚡ XP + Streak system': '⚡ XP + Streak-System',
    '📝 Advanced · Lesson 12': '📝 Fortgeschritten · Lektion 12', '✍️ Essay Structure Guide': '✍️ Aufsatzstruktur-Leitfaden',
    '📊 Advanced': '📊 Fortgeschritten', '🔖 Writing': '🔖 Schreiben', '🔗 Connective Grammar': '🔗 Verbindende Grammatik',
    '💼 Advanced · Lesson 13': '💼 Fortgeschritten · Lektion 13', '🏢 Workplace Expressions': '🏢 Ausdrücke am Arbeitsplatz',
    '🔖 Professional': '🔖 Professionell', '🤝 Business Etiquette': '🤝 Geschäftsetikette',
    '📜 Advanced · Lesson 14': '📜 Fortgeschritten · Lektion 14', '📜 Hanja (한자) Roots': '📜 Hanja (한자) Wurzeln',
    '🔖 History & Literature': '🔖 Geschichte & Literatur', '🏛️ Historical Korean Texts': '🏛️ Historische koreanische Texte',
    '💬 All Levels · 40 Dialogues': '💬 Alle Niveaus · 40 Dialoge',
    '💬 40 Full Dialogues': '💬 40 vollständige Dialoge', '📊 All Levels': '📊 Alle Niveaus',
    '🔖 Real-world Korean': '🔖 Koreanisch im Alltag', '🔊 Audio on Every Line': '🔊 Audio auf jeder Zeile',
    // ── Lesson Header — Shared Meta ───────────────────
    'Korean': 'Koreanisch', 'Expressing': 'Ausdrücken', 'Nouns': 'Nomen',
    '📊 Intermediate': '📊 Mittelstufe', '📊 Beginner–Intermediate': '📊 Anfänger–Mittelstufe',
    '🎯 6 Stages · 84 Steps': '🎯 6 Phasen · 84 Schritte',
    '🎯 5 Stages · 61 Steps': '🎯 5 Phasen · 61 Schritte',
    '🎯 6 Stages · 68 Steps': '🎯 6 Phasen · 68 Schritte',
    '⏱️ ~60–90 min': '⏱️ ~60–90 Min.', '⏱️ ~50 min': '⏱️ ~50 Min.', '⏱️ ~60 min': '⏱️ ~60 Min.',
    '⏱ 30 min': '⏱ 30 Min.', '⏱ 28 min': '⏱ 28 Min.', '⏱ 29 min': '⏱ 29 Min.',
    '🔊 Audio on every word': '🔊 Audio bei jedem Wort',
    '🔊 Audio on every phrase': '🔊 Audio bei jeder Phrase',
    '🔊 Audio on every form': '🔊 Audio bei jeder Form',
    '4 stages with listen-and-repeat audio and quizzes throughout': '4 Phasen mit Hören-und-Wiederholen-Audio und Quiz',
    // ── Lesson Header — Hangul ────────────────────────
    'Learn Hangul in 1 Hour:': 'Hangul in 1 Stunde lernen:',
    'Created in 1443 by King Sejong the Great': 'Im Jahr 1443 von König Sejong dem Großen erschaffen',
    'Phonetic alphabet — each symbol = one sound': 'Phonetisches Alphabet — jedes Symbol = ein Laut',
    '6 stages to cover every character': '6 Phasen für jeden Buchstaben',
    'Most learners finish in under 90 minutes': 'Die meisten Lernenden beenden es in unter 90 Minuten',
    // ── Lesson Header — Syllable Blocks ──────────────
    '🔷 Beginner · Lesson 2': '🔷 Anfänger · Lektion 2',
    'Korean Syllable Blocks:': 'Koreanische Silbenblöcke:',
    'Every syllable is a compact square block — not a horizontal letter string': 'Jede Silbe ist ein kompakter quadratischer Block — kein horizontaler Buchstabenstring',
    'Each block holds exactly 1 vowel plus up to 2 consonants': 'Jeder Block enthält genau 1 Vokal und bis zu 2 Konsonanten',
    '4 structural patterns: CV, V, CVC, VC — all follow the same rules': '4 Strukturmuster: CV, V, CVC, VC — alle folgen denselben Regeln',
    'Master the block structure and you can sound out any Korean word': 'Beherrsche die Blockstruktur und du kannst jedes koreanische Wort lesen',
    // ── Lesson Header — Pronunciation ────────────────
    '8 sound change rules — why Korean spelling and pronunciation differ': '8 Lautwandelregeln — warum sich koreanische Schreibung und Aussprache unterscheiden',
    'Batchim, liaison, assimilation, tensification, palatalization, and more': 'Batchim, Liaison, Assimilation, Tensifizierung, Palatalisierung und mehr',
    'Fix the 6 most common mistakes English speakers make': 'Die 6 häufigsten Fehler von Englischsprechern korrigieren',
    'Audio examples on every step — tap any word to hear it': 'Audio-Beispiele bei jedem Schritt — tippe auf ein Wort zum Anhören',
    // ── Lesson Header — Grammar ───────────────────────
    'Korean Grammar:': 'Koreanische Grammatik:',
    'SOV word order — the verb always comes last': 'SOV-Wortstellung — das Verb steht immer am Ende',
    'Particles replace rigid word-position rules': 'Partikel ersetzen starre Wortstellungsregeln',
    '26 stages: sentences to advanced patterns': '26 Phasen: von Sätzen zu fortgeschrittenen Mustern',
    'Most learners complete in under 90 minutes': 'Die meisten Lernenden beenden es in unter 90 Minuten',
    // ── Lesson Header — Nouns ────────────────────────
    '🏠 Beginner · Lesson 5': '🏠 Anfänger · Lektion 5', 'Common Korean': 'Häufiges Koreanisch',
    'Master people, family, place, time, and object nouns in Korean': 'Personen-, Familien-, Orts-, Zeit- und Objektnomen auf Koreanisch meistern',
    'Learn how Korean counters (개, 명, 잔) work with numbers': 'Lerne, wie koreanische Zählwörter (개, 명, 잔) mit Zahlen funktionieren',
    'Understand the possessive marker 의 and polite vs casual forms': 'Verstehe das Possessivmarker 의 und formelle vs. informelle Formen',
    // ── Lesson Header — Pronouns ─────────────────────
    '👥 Beginner · Lesson 4': '👥 Anfänger · Lektion 4',
    'Learn polite 저 vs casual 나, and why Korean often drops pronouns entirely': 'Lerne höfliches 저 vs. informelles 나 und warum Koreanisch oft Pronomen weglässt',
    'Understand why 당신 is rarely used and how to address people naturally': 'Verstehe, warum 당신 selten verwendet wird und wie man natürlich anredet',
    'Master 우리 (our/my), demonstratives (이것·그것·저것), and question words': '우리 (unser/mein), Demonstrativpronomen (이것·그것·저것) und Fragewörter meistern',
    // ── Lesson Header — Vocabulary ────────────────────
    '🗂 21 Categories': '🗂 21 Kategorien',
    '🔊 Audio on every card': '🔊 Audio auf jeder Karte',
    'Covers 500+ core Korean words across 21 categories': 'Umfasst 500+ koreanische Kernwörter in 21 Kategorien',
    'Bite-sized steps with instant audio — tap any card to hear it': 'Kleine Schritte mit sofortigem Audio — tippe auf eine Karte zum Anhören',
    'Quizzes after every category to lock in your memory': 'Quiz nach jeder Kategorie zum Einprägen',
    'Most learners finish each category in under 15 minutes': 'Die meisten Lernenden beenden jede Kategorie in unter 15 Minuten',
    // ── Hangul Page ───────────────────────────────────
    '✏️ Starter · Lesson 1': '✏️ Starter · Lektion 1', 'Hangul Alphabet:': 'Hangul-Alphabet:',
    '⏱ 45 min read': '⏱ 45 Min. lesen', '📊 Beginner': '📊 Anfänger',
    '🔖 Hangul Basics · 한글 기초': '🔖 Hangul-Grundlagen · 한글 기초',
    '🔡 Syllable Block Patterns': '🔡 Silbenblock-Muster',
    '📘 Common Compound Batchim Examples': '📘 Häufige zusammengesetzte Batchim-Beispiele',
    '👁 18,204 views': '👁 18.204 Aufrufe',
    'What is Hangul? (한글이란?)': 'Was ist Hangul? (한글이란?)',
    'Basic Vowels (기본 모음)': 'Grundlegende Vokale (기본 모음)', 'Hangul at a Glance': 'Hangul auf einen Blick',
    'Basic Consonants': 'Grundlegende Konsonanten', 'Basic Vowels': 'Grundlegende Vokale',
    'Double Consonants': 'Doppelkonsonanten', 'Compound Vowels': 'Zusammengesetzte Vokale', 'Fun Fact': 'Wissenswertes',
    'Why does ㅇ appear at the start?': 'Warum erscheint ㅇ am Anfang?',
    'Vowel Shape Mnemonics': 'Vokal-Form-Merkhilfen', 'About Hangul (한글)': 'Über Hangul (한글)',
    'Basic Vowels (모음)': 'Grundlegende Vokale (모음)',
    'Compound Vowels (복합 모음)': 'Zusammengesetzte Vokale (복합 모음)',
    'Basic Consonants (자음)': 'Grundlegende Konsonanten (자음)', 'Syllable Blocks (음절)': 'Silbenblöcke (음절)',
    'Tense (Double) Consonants — 쌍자음': 'Tense (Doppel-)Konsonanten — 쌍자음',
    'Compound Batchim (겹받침)': 'Zusammengesetztes Batchim (겹받침)',
    'Aspirated Consonants — 거센소리': 'Aspirierte Konsonanten — 거센소리', 'Quick Practice Quiz': 'Kurzes Übungsquiz',
    'Did you know?': 'Wusstest du?', 'Vowel Harmony': 'Vokalharmonie', 'Reading Practice': 'Leseübung',
    'The Tissue Test': 'Der Papiertest', '10 basic vowels': '10 Grundvokale',
    '11 compound vowels': '11 zusammengesetzte Vokale', '14 basic consonants': '14 Grundkonsonanten',
    '5 tense consonants': '5 tense Konsonanten', '5 aspirated consonants': '5 aspirierte Konsonanten',
    'October 9 is Hangul Day (한글날) in South Korea — a national holiday celebrating the invention of the alphabet in 1443.': 'Der 9. Oktober ist der Hangul-Tag (한글날) in Südkorea — ein Nationalfeiertag zur Feier der Erfindung des Alphabets im Jahr 1443.',
    'Structure': 'Struktur', 'Example': 'Beispiel', 'Reading': 'Lektüre', 'Meaning': 'Bedeutung',
    'Consonant + Vowel': 'Konsonant + Vokal', 'go (verb stem)': 'gehen (Verbstamm)',
    'Consonant + Vowel + Consonant': 'Konsonant + Vokal + Konsonant', 'Korean (prefix)': 'Koreanisch (Präfix)',
    'Silent ㅇ + Vowel': 'Stilles ㅇ + Vokal', 'ah! (exclamation)': 'ah! (Ausruf)',
    'Batchim': 'Batchim', 'Example Word': 'Beispielwort', 'Note': 'Hinweis', 'to read': 'lesen',
    'to sit': 'sitzen', 'life': 'Leben',
    'k (aspirated)': 'k (aspiriert)', 't (aspirated)': 't (aspiriert)',
    'p (aspirated)': 'p (aspiriert)', 'ch (aspirated)': 'ch (aspiriert)',
    '← Home': '← Startseite', 'Mark as Complete ✓': 'Als erledigt markieren ✓', 'Syllable Blocks →': 'Silbenblöcke →',
    // ── Grammar Page ──────────────────────────────────
    'Word Order — SOV Structure (어순)': 'Wortstellung — SOV-Struktur (어순)',
    'Korean Particles (조사)': 'Koreanische Partikel (조사)', 'Particle Practice': 'Partikel-Übung',
    'Speech Levels (존댓말 vs 반말)': 'Sprachebenen (존댓말 vs 반말)',
    'Present Tense (-아요/-어요)': 'Präsens (-아요/-어요)',
    'Past Tense (-았어요/-었어요)': 'Vergangenheit (-았어요/-었어요)',
    'Future Tense (-을 거예요/-ㄹ 거예요)': 'Zukunft (-을 거예요/-ㄹ 거예요)',
    'Making Sentences Negative (부정문)': 'Verneinung (부정문)',
    'Forming Questions (의문문)': 'Fragen bilden (의문문)',
    'WH- Question Words': 'W-Fragewörter',
    'Essential Sentence Patterns (문형)': 'Wichtige Satzmuster (문형)',
    'Connectors: 그리고, 그래서, 그렇지만, 그런데': 'Konnektoren: 그리고, 그래서, 그렇지만, 그런데',
    'And, With: -하고, -(이)랑': 'Und, Mit: -하고, -(이)랑',
    'To/From Someone: -한테, -한테서': 'An/Von jemandem: -한테, -한테서',
    'Telling Time (시간 말하기)': 'Uhrzeit sagen (시간 말하기)',
    'Counters (단위 명사)': 'Zählwörter (단위 명사)',
    'Present Progressive: -고 있어요': 'Verlaufsform: -고 있어요',
    'Particle': 'Partikel', 'Function': 'Funktion', 'Rule': 'Regel', 'Level': 'Stufe',
    'When to Use': 'Wann verwenden', 'Dictionary Form': 'Wörterbuchform', 'Stem': 'Stamm',
    'Conjugated': 'Konjugiert', 'Counter': 'Zählwort', 'Used for': 'Verwendet für',
    'Vowel': 'Vokal', 'Shape Mnemonic': 'Form-Merkhilfe', 'Mouth Position': 'Mundposition',
    'Time': 'Zeit', 'Register': 'Register', 'Used with': 'Verwendet mit',
    'Formal equivalent': 'Formelles Äquivalent', 'Korean · 한국어': 'Koreanisch · 한국어',
    'Translation · 번역': 'Übersetzung · 번역', 'Topic marker': 'Themamarker',
    'Subject marker': 'Subjektmarker', 'Object marker': 'Objektmarker',
    // ── Pronunciation Page ────────────────────────────
    '🔊 Beginner · Lesson 3': '🔊 Anfänger · Lektion 3', 'Pronunciation Guide:': 'Ausspracheführer:',
    '⏱ 50 min read': '⏱ 50 Min. lesen', '🔖 Pronunciation': '🔖 Aussprache',
    '👁 14,837 views': '👁 14.837 Aufrufe', 'sound change rules': 'Lautwandelregeln',
    'Batchim — Syllable-Final Consonants (받침)': 'Batchim — Silbenabschlusskonsonanten (받침)',
    '7 possible sounds': '7 mögliche Laute', 'Sound Group': 'Lautgruppe', 'Written As': 'Geschrieben als',
    'Pronounced As': 'Ausgesprochen als', 'Unreleased stops': 'Nicht gelöste Verschlusslaute',
    // ── Syllable Blocks Page ──────────────────────────
    'The ㅇ Placeholder Rule': 'Die ㅇ-Platzhalterregel',
    'Vertical vs Horizontal Vowels': 'Vertikale vs. horizontale Vokale',
    'Quick Visual Trick': 'Schneller visueller Trick', 'Building Your First Syllables': 'Deine ersten Silben bauen',
    'Adding Batchim — The Final Consonant': 'Batchim hinzufügen — der abschließende Konsonant',
    'Reading Real Korean Words': 'Echte koreanische Wörter lesen',
    'Practice & Summary': 'Übung & Zusammenfassung',
    '5 Rules for Korean Syllable Blocks': '5 Regeln für koreanische Silbenblöcke',
    '📝 Self-Test: Identify the Components': '📝 Selbsttest: Erkenne die Bestandteile',
    // ── Pronouns Page ─────────────────────────────────
    'Saying \'You\' in Korean': '„Du/Sie" auf Koreanisch sagen',
    'Third Person & We (그·그녀·우리)': 'Dritte Person & Wir (그·그녀·우리)',
    'Demonstrative Pronouns (이·그·저)': 'Demonstrativpronomen (이·그·저)',
    'Question Pronouns (의문대명사)': 'Fragewortpronomen (의문대명사)',
    'Pronouns Complete!': 'Pronomen abgeschlossen!',
    // ── Emotions Page ─────────────────────────────────
    '😊 Intermediate · Lesson 7': '😊 Mittelstufe · Lektion 7',
    'Core Emotions': 'Grundgefühle', 'Expressing Feelings': 'Gefühle ausdrücken',
    'Complex Emotions': 'Komplexe Gefühle', 'Emotional Phrases': 'Gefühlsphrasen',
    'Emotions in Korean (감정)': 'Gefühle auf Koreanisch (감정)',
    'Emotions Complete!': 'Gefühle abgeschlossen!',
    // ── Shopping Page ─────────────────────────────────
    '🛒 Intermediate · Lesson 8': '🛒 Mittelstufe · Lektion 8',
    'Shopping Vocabulary': 'Einkaufsvokabular', 'In the Store': 'Im Geschäft', 'Prices & Numbers': 'Preise & Zahlen',
    'Transactions': 'Transaktionen', 'Shopping in Korea (쇼핑)': 'Einkaufen in Korea (쇼핑)',
    'Shopping Complete!': 'Einkaufen abgeschlossen!',
    // ── Speech Levels Page ────────────────────────────
    '🗣️ Intermediate · Lesson 6': '🗣️ Mittelstufe · Lektion 6',
    '합쇼체 (Formal)': '합쇼체 (Formell)', '해요체 (Polite)': '해요체 (Höflich)',
    '반말 (Casual)': '반말 (Informell)', 'Choosing a Level': 'Eine Sprachebene wählen',
    'Korean Speech Levels Overview': 'Überblick über koreanische Sprachebenen',
    'Speech Levels Complete!': 'Sprachebenen abgeschlossen!',
    // ── Vocab Browser ───────────────────────────────────
    'Vocab Browser': 'Vokabular-Browser',
    'saved to flashcards': 'in Lernkarten gespeichert',
    'Loading vocabulary…': 'Vokabular wird geladen…',
    'No words match your search.': 'Keine Wörter entsprechen deiner Suche.',
    'Failed to load vocabulary.': 'Vokabular konnte nicht geladen werden.',
    'Search Korean, English, or romanization…': 'Auf Koreanisch, Englisch oder Romanisierung suchen…',
    '★ Add all in category': '★ Alle in der Kategorie hinzufügen',
    'Verbs': 'Verben',
    'Health': 'Gesundheit',
    'Media': 'Medien',
    'Proverbs': 'Sprichwörter',
    'Academic': 'Akademisch',
    // ── Progress system (streak / counters / resume) ────
    '✓ Correct!': '✓ Richtig!',
    '✗ Not quite — try again!': '✗ Fast — nochmal!',
    '{n}-day streak': '{n}-Tage-Serie',
    '{n} steps today': '{n} Schritte heute',
    'Continue': 'Fortsetzen',
    'Step {n} of {m}': 'Schritt {n} von {m}',
    'Steps completed': 'Abgeschlossene Schritte',
    'Words & phrases learned': 'Gelernte Wörter & Sätze',
    'Letters & syllables learned': 'Gelernte Buchstaben & Silben',
    'Best streak': 'Beste Serie',
    'Start Again': 'Neu starten',
    'Next Lesson →': 'Nächste Lektion →',
    'Next →': 'Weiter →',
    'Progress': 'Fortschritt',
    'Reset all progress': 'Gesamten Fortschritt zurücksetzen',
    '🔥 Daily streak + real progress tracking': '🔥 Tägliche Serie + echtes Fortschritts-Tracking'
  };
  if (window.LangManager) window.LangManager.register('de', DE);
})();
