'use strict';
(function() {
  const VI = {
    // ── Navigation & Global UI ─────────────────────────
    'Learn': 'Học', 'Quiz': 'Kiểm tra', 'K-Culture': 'K-Văn hóa', 'Travel': 'Du lịch', 'News': 'Tin tức',
    'Search...': 'Tìm kiếm...', 'Search lessons, vocabulary…': 'Tìm bài học, từ vựng…', 'Search lessons...': 'Tìm bài học...',
    'Loading lesson…': 'Đang tải bài học…', 'Previous': 'Trước', 'Next': 'Tiếp theo', '📚 Lesson 4 · vocabulary': '📚 Bài 4 · Từ vựng',
    'Search Results': 'Kết quả tìm kiếm', '← Back to Home': '← Về trang chủ',
    '🇰🇷 · Free · For Every Level': '🇰🇷 · Miễn phí · Cho mọi trình độ',
    'Learn Korean': 'Học tiếng Hàn', 'Start Learning': 'Bắt đầu học', 'Explore K-Culture': 'Khám phá K-Văn hóa',
    'Vocabulary Words': 'Từ vựng', 'Lessons': 'Bài học', 'Active Learners': 'Học viên đang học', '% Free': '% Miễn phí',
    'FEATURES': 'TÍNH NĂNG', 'Everything You Need to Learn Korean': 'Tất cả những gì bạn cần để học tiếng Hàn',
    'Start with 한글': 'Bắt đầu với 한글', 'Learn Hangul Now →': 'Học Hangul ngay →',
    'Hear It': 'Nghe', 'More Words': 'Thêm từ', 'Word of the Day': 'Từ của ngày',
    'STRUCTURED PATHS · 학습 경로': 'Lộ trình học · 학습 경로',
    'Choose Your Learning Path': 'Chọn lộ trình học của bạn',
    'Beginner': 'Người mới', 'Intermediate': 'Trung cấp', 'Advanced': 'Nâng cao',
    'Start Beginner Path →': 'Bắt đầu lộ trình người mới →', 'Start Intermediate Path →': 'Bắt đầu lộ trình trung cấp →',
    'Start Advanced Path →': 'Bắt đầu lộ trình nâng cao →', 'POPULAR': 'PHỔ BIẾN',
    'Beginner–Intermediate': 'Người mới–Trung cấp', 'Intermediate–Advanced': 'Trung cấp–Nâng cao',
    'Beg–Int': 'Mới–TC',
    // ── K-Culture & Home ──────────────────────────────
    'K-CULTURE': 'K-VĂN HÓA', 'K-CULTURE · 한국 문화': 'K-VĂN HÓA · 한국 문화',
    'Experience Korea Beyond Language': 'Trải nghiệm Hàn Quốc vượt ngôn ngữ',
    'Explore All K-Culture Content →': 'Khám phá toàn bộ nội dung K-Văn hóa →',
    'TRAVEL · 여행': 'DU LỊCH · 여행', 'Explore Korea': 'Khám phá Hàn Quốc',
    'View Full Travel Guide →': 'Xem hướng dẫn du lịch đầy đủ →',
    'PRACTICE · 연습': 'LUYỆN TẬP · 연습',
    '10 progressive levels · multiple choice · covers Hangul, Grammar & Vocabulary': '10 cấp độ · trắc nghiệm · bao gồm Hangul, Ngữ pháp & Từ vựng',
    'Choose a Level': 'Chọn cấp độ', 'questions': 'câu hỏi', '← All Levels': '← Tất cả cấp độ',
    'Try Again': 'Thử lại', 'Next Level': 'Cấp tiếp theo', 'All Levels': 'Tất cả cấp độ',
    'Next Level →': 'Cấp tiếp theo →',
    // ── Travel ────────────────────────────────────────
    '🇰🇷 · South Korea Travel Guide · 여행 안내': '🇰🇷 · Hướng dẫn du lịch Hàn Quốc · 여행 안내',
    'South Korea Travel Guide': 'Hướng dẫn du lịch Hàn Quốc',
    'Population': 'Dân số', 'UNESCO Sites': 'Di sản UNESCO',
    'Great to visit': 'Tuyệt vời để tham quan', 'Visa-free nations': 'Quốc gia miễn thị thực',
    'EXPLORE THE GUIDES · 가이드 탐색': 'KHÁM PHÁ HƯỚNG DẪN · 가이드 탐색',
    'Plan Your Perfect Korea Trip': 'Lên kế hoạch chuyến đi Hàn Quốc hoàn hảo',
    'TOP DESTINATIONS · 인기 여행지': 'ĐỊA ĐIỂM NỔI BẬT · 인기 여행지',
    'Where Will You Explore?': 'Bạn sẽ khám phá đâu?',
    'ESSENTIAL PHRASES · 필수 표현': 'CÂU HỮU ÍCH · 필수 표현',
    'Travel Korean Phrasebook': 'Sổ tay tiếng Hàn du lịch',
    'TRANSPORTATION · 교통': 'PHƯƠNG TIỆN · 교통', 'Getting Around Korea': 'Di chuyển ở Hàn Quốc',
    'FOOD TOUR · 음식 여행': 'TOUR ẨM THỰC · 음식 여행', 'Regional Korean Specialties': 'Đặc sản vùng miền Hàn Quốc',
    'CULTURAL ETIQUETTE · 예절': 'VĂN HÓA ỨNG XỬ · 예절', 'Korean Cultural Tips': 'Mẹo văn hóa Hàn Quốc',
    'TRAVEL APPS · 여행 앱': 'ỨNG DỤNG DU LỊCH · 여행 앱', 'Essential Apps for Korea Travel': 'Ứng dụng cần thiết khi du lịch Hàn Quốc',
    'READY TO LEARN?': 'SẴN SÀNG HỌC CHƯA?', 'Start Speaking Korean Today': 'Bắt đầu nói tiếng Hàn ngay hôm nay',
    'Start Learning Korean →': 'Bắt đầu học tiếng Hàn →', 'Plan Your Trip': 'Lên kế hoạch chuyến đi',
    // ── News ──────────────────────────────────────────
    '📰 · Korean News · 한국 뉴스': '📰 · Tin tức Hàn Quốc · 한국 뉴스',
    'TODAY\'S KOREA · 오늘의 한국': 'HÀN QUỐC HÔM NAY · 오늘의 한국',
    'All 전체': 'Tất cả 전체', 'LATEST · 최신 기사': 'MỚI NHẤT · 최신 기사',
    'FEATURED · 주목 기사': 'NỔI BẬT · 주목 기사', 'ARTICLES · 기사 목록': 'BÀI VIẾT · 기사 목록',
    'Today\'s Korean News': 'Tin tức Hàn Quốc hôm nay', 'Admin ⚙️': 'Admin ⚙️',
    '더 보기 — Load More': 'Tải thêm', 'All articles loaded': 'Đã tải hết bài viết',
    'THIS WEEK\'S TOP STORIES · 이번 주 인기 뉴스': 'TIN NỔI BẬT TUẦN NÀY · 이번 주 인기 뉴스',
    'Most Read This Week': 'Đọc nhiều nhất tuần này',
    'VOCABULARY SPOTLIGHT · 핵심 어휘': 'TỪ VỰNG NỔI BẬT · 핵심 어휘',
    'Key News Vocabulary': 'Từ vựng tin tức quan trọng', 'Full Vocabulary Lists →': 'Danh sách từ vựng đầy đủ →',
    'K-Pop': 'K-Pop', 'K-Drama': 'K-Drama', 'K-Beauty': 'K-Beauty', 'All': 'Tất cả', 'Level:': 'Cấp độ:',
    // ── Footer & Company ──────────────────────────────
    'Learn · 학습': 'Học · 학습', 'K-Culture · 문화': 'K-Văn hóa · 문화',
    'Company · 회사': 'Công ty · 회사', 'Explore': 'Khám phá', 'Company': 'Công ty',
    'Hangul Alphabet': 'Bảng chữ cái Hangul', 'Grammar': 'Ngữ pháp', 'Vocabulary': 'Từ vựng',
    'Travel Guide': 'Hướng dẫn du lịch', 'Korean News': 'Tin tức Hàn Quốc', 'About Us': 'Về chúng tôi',
    'Contact': 'Liên hệ', 'Privacy Policy': 'Chính sách bảo mật', 'Terms of Use': 'Điều khoản sử dụng',
    'Made with ❤️ for Korean learners worldwide.': 'Làm với ❤️ cho người học tiếng Hàn trên toàn thế giới.',
    '🇰🇷 학습을 즐기세요! (Enjoy your learning!)': '🇰🇷 학습을 즐기세요! (Chúc bạn học vui!)',
    'Home': 'Trang chủ', 'Hangul': 'Hangul',
    'A free Korean language learning platform — combining language study with K-culture, travel guides, and real-world practice. For learners of every level, worldwide.': 'Nền tảng học tiếng Hàn miễn phí — kết hợp học ngôn ngữ với K-văn hóa, hướng dẫn du lịch và thực hành thực tế. Dành cho mọi trình độ trên toàn thế giới.',
    'A free Korean language learning platform for learners of every level, worldwide.': 'Nền tảng học tiếng Hàn miễn phí cho mọi trình độ trên toàn thế giới.',
    '© 2026 한국어 학교. Made with ❤️ for Korean learners worldwide.': '© 2026 한국어 학교. Làm với ❤️ cho người học tiếng Hàn trên toàn thế giới.',
    // ── Sidebar Dividers ──────────────────────────────
    'Getting Started': 'Bắt đầu', 'Tools': 'Công cụ',
    'CATEGORIES · 카테고리': 'DANH MỤC · 카테고리', 'DEEP DIVES · 심층 탐구': 'CHUYÊN SÂU · 심층 탐구',
    // ── Learn Sidebar ─────────────────────────────────
    'Introduction': 'Giới thiệu', 'Syllable Blocks': 'Khối âm tiết', 'Pronunciation Guide': 'Hướng dẫn phát âm',
    'Vocab': 'Từ vựng', 'Greetings': 'Lời chào', 'Numbers': 'Số', 'Family': 'Gia đình',
    'Food & Drink': 'Thức ăn & Đồ uống', 'Colors': 'Màu sắc', 'Days & Time': 'Ngày & Giờ', 'Places': 'Địa điểm',
    'Emotions': 'Cảm xúc', 'Body Parts': 'Bộ phận cơ thể', 'Shopping': 'Mua sắm', 'Weather': 'Thời tiết',
    'Verbs & Actions': 'Động từ & Hành động', 'Adjectives': 'Tính từ', 'Workplace': 'Nơi làm việc',
    'Health & Medicine': 'Sức khỏe & Y tế', 'Media & K-Culture': 'Truyền thông & K-Văn hóa',
    'Proverbs & Idioms': 'Tục ngữ & Thành ngữ', 'Academic Korean': 'Tiếng Hàn học thuật',
    'News & Society': 'Tin tức & Xã hội', 'Konglish': 'Konglish', 'Pronouns': 'Đại từ',
    'Common Nouns': 'Danh từ thông dụng', 'Sentence Structure': 'Cấu trúc câu', 'Korean Particles': 'Trợ từ tiếng Hàn',
    'Verb Conjugation': 'Chia động từ', 'Question Forms': 'Câu hỏi', 'Connectors': 'Liên từ',
    'And, With': 'Và, Cùng', 'To/From Someone': 'Đến/Từ ai đó', 'Telling Time': 'Nói giờ',
    'Counters': 'Đơn vị đếm', 'Present Progressive': 'Hiện tại tiếp diễn', 'Self Introduction': 'Tự giới thiệu',
    'Dates and Months': 'Ngày và tháng', 'Degree Adverbs': 'Trạng từ mức độ',
    'Nominalizer -는 것': 'Danh từ hóa -는 것', 'Comparatives': 'So sánh',
    'Still, Already': 'Vẫn, Đã', 'Someone, Something': 'Ai đó, Cái gì đó',
    'Imperative -(으)세요': 'Mệnh lệnh -(으)세요', 'Don\'t: -지 마세요': 'Đừng: -지 마세요',
    'Method: -(으)로': 'Phương tiện: -(으)로', 'Good/Poor At': 'Giỏi/Kém về',
    '-도 Advanced Uses': 'Cách dùng nâng cao của -도', 'Formal vs Informal': 'Trang trọng vs Thông thường',
    'Expressing Emotions': 'Diễn đạt cảm xúc', 'Shopping Phrases': 'Cụm từ mua sắm', 'Writing Essays': 'Viết luận',
    'Business Korean': 'Tiếng Hàn thương mại', 'Classical Korean': 'Tiếng Hàn cổ điển', 'Korean Dialogues': 'Hội thoại tiếng Hàn',
    'Flashcards': 'Thẻ ghi nhớ',
    // ── Culture Sidebar ───────────────────────────────
    'K-Movie': 'K-Điện ảnh', 'K-Food': 'K-Ẩm thực', 'K-Fashion': 'K-Thời trang',
    'Korean Thing': 'Chuyện Hàn Quốc', 'K-Gaming': 'K-Gaming', 'K-Sports': 'K-Thể thao',
    'K-Pop, K-Drama, food, beauty, fashion, gaming, sports & traditions.': 'K-Pop, K-Drama, ẩm thực, làm đẹp, thời trang, gaming, thể thao & truyền thống.',
    'K-Pop History': 'Lịch sử K-Pop', 'Agencies': 'Công ty quản lý', 'Generations': 'Thế hệ', 'Genres': 'Thể loại',
    'Variety Shows': 'Chương trình giải trí', 'Film & Acting': 'Điện ảnh & Diễn xuất', 'Idol Phrases': 'Câu nói của idol',
    'Fan Slang': 'Tiếng lóng fan', 'Fan Chants': 'Fanchant', 'Drama History': 'Lịch sử K-Drama',
    'Drama Genres': 'Thể loại phim', 'Must-Watch Dramas': 'Phim cần xem', 'K-Drama Tropes': 'Mô-típ K-Drama',
    'Speech Levels': 'Cấp độ nói', 'Dialogue Practice': 'Luyện hội thoại',
    'Fan Culture & Slang': 'Văn hóa & Tiếng lóng fan', 'Movie History': 'Lịch sử điện ảnh',
    'Movie Genres': 'Thể loại phim', 'Must-Watch Films': 'Phim cần xem', 'Directors': 'Đạo diễn',
    'Iconic Lines': 'Câu thoại kinh điển', 'Fan Culture': 'Văn hóa fan',
    'K-Food Goes Global': 'K-Ẩm thực vươn ra thế giới', 'Foods That Went Global': 'Món ăn nổi tiếng toàn cầu',
    'K-Food Timeline': 'Lịch sử K-Ẩm thực', 'Essential Dishes': 'Món ăn cơ bản',
    'World-Famous Chefs': 'Đầu bếp nổi tiếng thế giới', 'Ordering & Dining': 'Gọi món & Ăn uống',
    'Street Food': 'Ẩm thực đường phố', 'Food Culture & Drinking': 'Văn hóa ẩm thực & Uống rượu',
    'Ramyeon Guide': 'Hướng dẫn mì Ramyeon', 'Mandu Guide': 'Hướng dẫn Mandu',
    'Chicken Guide': 'Hướng dẫn gà rán', 'K-BBQ Guide': 'Hướng dẫn K-BBQ', 'Kimchi Guide': 'Hướng dẫn Kimchi',
    'K-Beauty Goes Global': 'K-Beauty vươn ra thế giới', 'K-Beauty Timeline': 'Lịch sử K-Beauty',
    'Iconic Brands': 'Thương hiệu nổi tiếng', 'Beauty Vocabulary': 'Từ vựng làm đẹp', '10-Step Skincare': 'Quy trình chăm sóc da 10 bước',
    'Key Ingredients': 'Thành phần chính', 'Beauty Trends': 'Xu hướng làm đẹp', 'Makeup Philosophy': 'Triết lý trang điểm',
    'Skin Clinic Culture': 'Văn hóa phòng khám thẩm mỹ', 'K-Beauty Dialogue': 'Hội thoại K-Beauty',
    'K-Fashion Global': 'K-Thời trang toàn cầu', 'Fashion Icons': 'Biểu tượng thời trang',
    'Fashion Timeline': 'Lịch sử thời trang', 'Style Aesthetics': 'Phong cách thẩm mỹ', 'Idol Fashion': 'Thời trang idol',
    'Seoul Fashion Week': 'Tuần lễ thời trang Seoul', 'Fashion Vocabulary': 'Từ vựng thời trang',
    'Fashion Districts': 'Khu thời trang', 'Shopping Dialogue': 'Hội thoại mua sắm',
    'Hanbok & Traditional Fashion': 'Hanbok & Thời trang truyền thống', 'Rice Obsession': 'Văn hóa gạo',
    'Youth Protection Laws': 'Luật bảo vệ trẻ em', 'Fast Delivery Culture': 'Văn hóa giao hàng nhanh',
    'Invasive Species Crisis': 'Khủng hoảng sinh vật xâm lấn', 'Table Call Culture': 'Văn hóa gọi nhân viên tại bàn',
    'Public Transport': 'Giao thông công cộng', 'Jjimjilbang': 'Jjimjilbang', 'Plastic Surgery Culture': 'Văn hóa phẫu thuật thẩm mỹ',
    'Outdoor Drinking': 'Uống rượu ngoài trời', 'Jeonse Housing': 'Nhà ở Jeonse',
    'Traditions & Holidays': 'Truyền thống & Lễ tết', '100 Korean Proverbs': '100 tục ngữ Hàn Quốc',
    'K-Gaming Stats': 'Thống kê K-Gaming', 'Gaming Timeline': 'Lịch sử gaming',
    'Gaming Legends': 'Huyền thoại gaming', 'Iconic Games': 'Game huyền thoại', 'Streaming Culture': 'Văn hóa streaming',
    'PC Bang Culture': 'Văn hóa PC Bang', 'PC방 Culture': 'Văn hóa PC방', 'Esports Leagues': 'Giải đấu esports',
    'Gamer Slang': 'Tiếng lóng game', 'Gaming Vocabulary': 'Từ vựng gaming', 'Sports Overview': 'Tổng quan thể thao',
    'Football Heroes': 'Anh hùng bóng đá', 'Baseball Heroes': 'Anh hùng bóng chày', 'Marathon Legends': 'Huyền thoại marathon',
    'Individual Legends': 'Huyền thoại cá nhân', 'Traditional Sports': 'Thể thao truyền thống', 'Cheer Chants': 'Hô cổ vũ',
    // ── Travel Sidebar ────────────────────────────────
    'Travel Guide · 여행 안내': 'Hướng dẫn du lịch · 여행 안내', 'South Korea': 'Hàn Quốc',
    'By Days · 일수별': 'Theo ngày · 일수별', '1 Day Trip · 당일치기': 'Đi về trong ngày · 당일치기',
    '2 Days · 1박 2일': '2 ngày · 1박 2일', '3 Days · 2박 3일': '3 ngày · 2박 3일',
    '5 Days · 4박 5일': '5 ngày · 4박 5일', '1 Week · 일주일': '1 tuần · 일주일',
    '10 Days': '10 ngày', '2 Weeks · 2주': '2 tuần · 2주', '1 Month+ · 한달': '1 tháng+ · 한달',
    'By City · 도시별': 'Theo thành phố · 도시별', 'Seoul · 서울': 'Seoul · 서울',
    'Incheon · 인천': 'Incheon · 인천', 'Busan · 부산': 'Busan · 부산',
    'Suwon · 수원': 'Suwon · 수원', 'Jeju · 제주도': 'Jeju · 제주도',
    'Gyeongju · 경주': 'Gyeongju · 경주', 'Other Cities': 'Thành phố khác',
    'By Theme · 테마별': 'Theo chủ đề · 테마별', 'Food Tour · 음식 여행': 'Tour ẩm thực · 음식 여행',
    'Events & Festivals · 이벤트': 'Sự kiện & Lễ hội · 이벤트', 'Sightseeing · 관광': 'Tham quan · 관광',
    'Cross-Country · 장거리': 'Xuyên quốc gia · 장거리',
    '📋 Trip Planner · 여행 계획표': '📋 Lên kế hoạch du lịch · 여행 계획표',
    'Day-by-Day Itineraries': 'Lịch trình từng ngày', 'City Travel Guides': 'Hướng dẫn du lịch thành phố',
    'Themed Travel': 'Du lịch theo chủ đề', 'Bus': 'Xe buýt', 'Subway': 'Tàu điện ngầm', 'Taxi': 'Taxi',
    'KTX High-speed Rail': 'Tàu cao tốc KTX', 'Age': 'Tuổi', 'Bowing': 'Cúi chào',
    'Drinking': 'Uống rượu', 'Eating': 'Ăn uống', 'Quiet': 'Im lặng', 'Shoes': 'Giày',
    'Tipping': 'Tiền tip', 'Two Hands': 'Hai tay',
    // ── News Filter Categories ─────────────────────────
    'International': 'Quốc tế', 'Politics': 'Chính trị', 'Economy': 'Kinh tế', 'Society': 'Xã hội',
    'Science': 'Khoa học', 'Culture': 'Văn hóa', 'Sports': 'Thể thao', 'Education': 'Giáo dục',
    'Environment': 'Môi trường',
    // ── Homepage Descriptions ─────────────────────────
    'Discover the beauty of Korea through language, culture, K-pop, travel, and cuisine — with free lessons designed for learners worldwide.': 'Khám phá vẻ đẹp của Hàn Quốc qua ngôn ngữ, văn hóa, K-pop, du lịch và ẩm thực — với các bài học miễn phí dành cho người học trên toàn thế giới.',
    'Learn the Korean alphabet in just 2 hours. 한글 (Hangul) is remarkably logical — once you know the 24 basic letters, you can read anything.': 'Học bảng chữ cái tiếng Hàn chỉ trong 2 giờ. 한글 (Hangul) rất có hệ thống — một khi biết 24 chữ cái cơ bản, bạn có thể đọc bất cứ thứ gì.',
    'Learn Korean naturally through your favourite songs. Line-by-line breakdowns with vocabulary, grammar notes, and pronunciation guides.': 'Học tiếng Hàn tự nhiên qua các bài hát yêu thích. Phân tích từng dòng kèm từ vựng, ghi chú ngữ pháp và hướng dẫn phát âm.',
    'Pick up everyday Korean from your favourite dramas. Contextual vocabulary lists organised by show, genre, and proficiency level.': 'Học tiếng Hàn hàng ngày từ các bộ phim yêu thích. Danh sách từ vựng theo ngữ cảnh được sắp xếp theo phim, thể loại và trình độ.',
    'From 김치 (kimchi) to 삼겹살 (samgyeopsal) — explore the rich vocabulary of Korean cuisine with pronunciation and cultural context.': 'Từ 김치 (kimchi) đến 삼겹살 (samgyeopsal) — khám phá từ vựng phong phú về ẩm thực Hàn Quốc kèm phát âm và bối cảnh văn hóa.',
    'Whether you are just starting or aiming for fluency, we have a clear roadmap to take you there step by step.': 'Dù bạn mới bắt đầu hay muốn đạt trình độ lưu loát, chúng tôi có lộ trình rõ ràng để đưa bạn từng bước.',
    'Language is the gateway — immerse yourself in Korean pop culture, food, and beauty to supercharge your learning.': 'Ngôn ngữ là cánh cổng — hãy đắm chìm vào văn hóa đại chúng, ẩm thực và làm đẹp Hàn Quốc để thúc đẩy việc học.',
    'From BTS to BLACKPINK — the most common Korean words and phrases used by your favourite K-Pop artists, with pronunciation guides.': 'Từ BTS đến BLACKPINK — những từ và cụm từ tiếng Hàn phổ biến nhất của nghệ sĩ K-Pop yêu thích, kèm hướng dẫn phát âm.',
    'Korean dramas are packed with emotional vocabulary. Learn how characters express joy, sadness, anger, and love in authentic Korean.': 'K-Drama chứa đầy từ vựng cảm xúc. Học cách nhân vật bày tỏ niềm vui, nỗi buồn, tức giận và tình yêu bằng tiếng Hàn chính xác.',
    'Essential phrases for ordering food, asking for the bill, and navigating a Korean restaurant menu with confidence.': 'Cụm từ cần thiết để gọi món, hỏi hóa đơn và duyệt thực đơn nhà hàng Hàn Quốc một cách tự tin.',
    'Explore the world of K-Beauty with essential vocabulary for skincare routines, cosmetics, and Korean beauty trends.': 'Khám phá thế giới K-Beauty với từ vựng cần thiết về quy trình chăm sóc da, mỹ phẩm và xu hướng làm đẹp Hàn Quốc.',
    'Learn the language of every destination. From bustling Seoul to the serene shores of Jeju — your AI travel guide is ready.': 'Học ngôn ngữ của từng điểm đến. Từ Seoul nhộn nhịp đến bờ biển yên bình của Jeju — hướng dẫn du lịch AI của bạn đã sẵn sàng.',
    "South Korea's dazzling capital — from the ancient palaces of Gyeongbokgung to the neon streets of Gangnam and Hongdae.": 'Thủ đô rực rỡ của Hàn Quốc — từ cung điện cổ Gyeongbokgung đến những con phố neon ở Gangnam và Hongdae.',
    "Korea's vibrant port city with stunning beaches, fresh seafood markets, and a unique dialect worth discovering.": 'Thành phố cảng sầm uất của Hàn Quốc với bãi biển tuyệt đẹp, chợ hải sản tươi và phương ngữ độc đáo đáng khám phá.',
    "Korea's paradise island — volcanic landscapes, pristine beaches, tangerine groves, and the famous haenyeo diving culture.": 'Hòn đảo thiên đường của Hàn Quốc — địa hình núi lửa, bãi biển trong xanh, vườn quýt và văn hóa lặn biển haenyeo nổi tiếng.',
    // ── Homepage Place Names & Quiz ───────────────────
    'Seoul': 'Seoul', 'Busan': 'Busan', 'Jeju Island': 'Đảo Jeju',
    'Test Your Korean': 'Kiểm tra tiếng Hàn', 'Explore →': 'Khám phá →',
    // ── Homepage Cards & Labels ───────────────────────
    'K-Pop Lyrics Learning': 'Học qua lời K-Pop', 'K-Drama Vocabulary': 'Từ vựng K-Drama',
    'Korean Food Dictionary': 'Từ điển ẩm thực Hàn Quốc',
    'Master Korean Emotions Through K-Drama': 'Nắm vững cảm xúc tiếng Hàn qua K-Drama',
    'Order Like a Local: Restaurant Korean': 'Gọi món như người địa phương: Tiếng Hàn tại nhà hàng',
    'Beauty & Skincare Vocabulary in Korean': 'Từ vựng làm đẹp & chăm sóc da bằng tiếng Hàn',
    'K-Pop Stars\' Korean Phrases You Need to Know': 'Câu tiếng Hàn của ngôi sao K-Pop bạn cần biết',
    'Read →': 'Đọc →', 'Hello / Good day': 'Xin chào / Chào buổi sáng',
    'annyeonghaseyo': 'an-nyeong-ha-se-yo',
    // ── Learning Path Checklist ───────────────────────
    '✓ Hangul Alphabet': '✓ Bảng chữ cái Hangul', '✓ Basic Vowels & Consonants': '✓ Nguyên âm & Phụ âm cơ bản',
    '✓ Syllable Blocks': '✓ Khối âm tiết', '✓ Essential Vocabulary': '✓ Từ vựng cần thiết',
    '✓ Basic Greetings': '✓ Lời chào cơ bản', '✓ Korean Grammar (SOV)': '✓ Ngữ pháp tiếng Hàn (SOV)',
    '✓ Particles & Conjugation': '✓ Trợ từ & Chia động từ', '✓ Speech Levels': '✓ Cấp độ nói',
    '✓ 300+ Vocabulary Words': '✓ 300+ từ vựng', '✓ Real Dialogues': '✓ Hội thoại thực tế',
    '✓ Business Korean': '✓ Tiếng Hàn thương mại', '✓ Classical Korean': '✓ Tiếng Hàn cổ điển',
    '✓ Essay Writing': '✓ Viết luận', '✓ TOPIK Preparation': '✓ Ôn thi TOPIK',
    '✓ Idiomatic Expressions': '✓ Thành ngữ',
    // ── Homepage Eyebrow Labels ───────────────────────
    'Hangul Basics · 한글 기초': 'Hangul cơ bản · 한글 기초',
    'Korean Grammar · 문법': 'Ngữ pháp tiếng Hàn · 문법', 'Vocabulary · 어휘': 'Từ vựng · 어휘',
    'Pronunciation · 발음': 'Phát âm · 발음', 'Korean News · 뉴스': 'Tin tức Hàn Quốc · 뉴스',
    'Korean Food · 음식': 'Ẩm thực Hàn Quốc · 음식', 'K-Beauty · 뷰티': 'K-Beauty · 뷰티',
    'K-Drama · 드라마': 'K-Drama · 드라마', 'K-Pop Lyrics · 가사': 'Lời K-Pop · 가사',
    'TOPIK Prep · 토픽 준비': 'Ôn thi TOPIK · 토픽 준비',
    'Flashcards · 플래시카드': 'Thẻ ghi nhớ · 플래시카드',
    'Start Here · 여기서 시작': 'Bắt đầu ở đây · 여기서 시작',
    'Daily Vocabulary · 오늘의 단어': 'Từ vựng hàng ngày · 오늘의 단어',
    'Travel Guide · 여행': 'Hướng dẫn du lịch · 여행', 'Blog · 블로그': 'Blog · 블로그',
    'About Us · 소개': 'Về chúng tôi · 소개', 'Contact · 연락처': 'Liên hệ · 연락처',
    'Seoul · 서울': 'Seoul · 서울', 'Busan · 부산': 'Busan · 부산', 'Jeju · 제주': 'Jeju · 제주',
    'Privacy': 'Bảo mật', 'Terms': 'Điều khoản', 'Terms of Service': 'Điều khoản dịch vụ',
    'K-FOOD · 한국 음식': 'K-ẨM THỰC · 한국 음식',
    // ── Food Page Stats ───────────────────────────────
    'Charcoal grill (best)': 'Nướng than (ngon nhất)', 'Side dishes (free refill)': 'Món phụ (thêm miễn phí)',
    'Lettuce wrap style': 'Cuộn rau diếp',
    // ── Lesson Header Meta ────────────────────────────
    'About this lesson': 'Về bài học này', 'Korean Grammar': 'Ngữ pháp tiếng Hàn',
    '✏️ Beginner · Lesson 1': '✏️ Người mới · Bài 1',
    '📐 Intermediate · Lesson 7': '📐 Trung cấp · Bài 7', '60 min read': '60 phút đọc',
    'Alphabet': 'Bảng chữ cái', '📐 Intermediate · Lesson 5': '📐 Trung cấp · Bài 5',
    '🎯 26 Stages · 70 Steps': '🎯 26 giai đoạn · 70 bước',
    '📊 Beginner–Advanced': '📊 Người mới–Nâng cao', '⏱️ ~90 min': '⏱️ ~90 phút',
    '⚡ XP + Streak system': '⚡ Hệ thống XP + Chuỗi',
    '📝 Advanced · Lesson 12': '📝 Nâng cao · Bài 12', '✍️ Essay Structure Guide': '✍️ Hướng dẫn cấu trúc luận văn',
    '📊 Advanced': '📊 Nâng cao', '🔖 Writing': '🔖 Viết', '🔗 Connective Grammar': '🔗 Ngữ pháp liên kết',
    '💼 Advanced · Lesson 13': '💼 Nâng cao · Bài 13', '🏢 Workplace Expressions': '🏢 Cụm từ nơi làm việc',
    '🔖 Professional': '🔖 Chuyên nghiệp', '🤝 Business Etiquette': '🤝 Văn hóa kinh doanh',
    '📜 Advanced · Lesson 14': '📜 Nâng cao · Bài 14', '📜 Hanja (한자) Roots': '📜 Chữ Hán (한자) gốc',
    '🔖 History & Literature': '🔖 Lịch sử & Văn học', '🏛️ Historical Korean Texts': '🏛️ Văn bản lịch sử Hàn Quốc',
    '💬 All Levels · 40 Dialogues': '💬 Mọi trình độ · 40 hội thoại',
    '💬 40 Full Dialogues': '💬 40 hội thoại đầy đủ', '📊 All Levels': '📊 Mọi trình độ',
    '🔖 Real-world Korean': '🔖 Tiếng Hàn thực tế', '🔊 Audio on Every Line': '🔊 Âm thanh trên mỗi dòng',
    // ── Lesson Header — Shared Meta ───────────────────
    'Korean': 'Tiếng Hàn', 'Expressing': 'Diễn đạt', 'Nouns': 'Danh từ',
    '📊 Intermediate': '📊 Trung cấp', '📊 Beginner–Intermediate': '📊 Người mới–Trung cấp',
    '🎯 6 Stages · 84 Steps': '🎯 6 giai đoạn · 84 bước',
    '🎯 5 Stages · 61 Steps': '🎯 5 giai đoạn · 61 bước',
    '🎯 6 Stages · 68 Steps': '🎯 6 giai đoạn · 68 bước',
    '⏱️ ~60–90 min': '⏱️ ~60–90 phút', '⏱️ ~50 min': '⏱️ ~50 phút', '⏱️ ~60 min': '⏱️ ~60 phút',
    '⏱ 30 min': '⏱ 30 phút', '⏱ 28 min': '⏱ 28 phút', '⏱ 29 min': '⏱ 29 phút',
    '🔊 Audio on every word': '🔊 Âm thanh trên mỗi từ',
    '🔊 Audio on every phrase': '🔊 Âm thanh trên mỗi cụm từ',
    '🔊 Audio on every form': '🔊 Âm thanh trên mỗi dạng',
    '4 stages with listen-and-repeat audio and quizzes throughout': '4 giai đoạn với âm thanh nghe-nhắc lại và kiểm tra xuyên suốt',
    // ── Lesson Header — Hangul ────────────────────────
    'Learn Hangul in 1 Hour:': 'Học Hangul trong 1 giờ:',
    'Created in 1443 by King Sejong the Great': 'Được tạo ra năm 1443 bởi vua Sejong Đại đế',
    'Phonetic alphabet — each symbol = one sound': 'Bảng chữ cái ngữ âm — mỗi ký hiệu = một âm',
    '6 stages to cover every character': '6 giai đoạn bao gồm tất cả ký tự',
    'Most learners finish in under 90 minutes': 'Hầu hết người học hoàn thành trong dưới 90 phút',
    // ── Lesson Header — Syllable Blocks ──────────────
    '🔷 Beginner · Lesson 2': '🔷 Người mới · Bài 2',
    'Korean Syllable Blocks:': 'Khối âm tiết tiếng Hàn:',
    'Every syllable is a compact square block — not a horizontal letter string': 'Mỗi âm tiết là một khối vuông gọn — không phải chuỗi chữ cái ngang',
    'Each block holds exactly 1 vowel plus up to 2 consonants': 'Mỗi khối chứa đúng 1 nguyên âm và tối đa 2 phụ âm',
    '4 structural patterns: CV, V, CVC, VC — all follow the same rules': '4 mẫu cấu trúc: CV, V, CVC, VC — tất cả theo cùng quy tắc',
    'Master the block structure and you can sound out any Korean word': 'Nắm vững cấu trúc khối và bạn có thể đọc bất kỳ từ tiếng Hàn nào',
    // ── Lesson Header — Pronunciation ────────────────
    '8 sound change rules — why Korean spelling and pronunciation differ': '8 quy tắc biến âm — tại sao cách viết và phát âm tiếng Hàn khác nhau',
    'Batchim, liaison, assimilation, tensification, palatalization, and more': 'Batchim, liên âm, đồng hóa, âm căng, khẩu âm hóa và nhiều hơn',
    'Fix the 6 most common mistakes English speakers make': 'Sửa 6 lỗi phổ biến nhất của người nói tiếng Anh',
    'Audio examples on every step — tap any word to hear it': 'Ví dụ âm thanh ở mỗi bước — chạm vào từ bất kỳ để nghe',
    // ── Lesson Header — Grammar ───────────────────────
    'Korean Grammar:': 'Ngữ pháp tiếng Hàn:',
    'SOV word order — the verb always comes last': 'Trật tự từ SOV — động từ luôn đứng cuối',
    'Particles replace rigid word-position rules': 'Trợ từ thay thế quy tắc vị trí từ cứng nhắc',
    '26 stages: sentences to advanced patterns': '26 giai đoạn: từ câu đến mẫu nâng cao',
    'Most learners complete in under 90 minutes': 'Hầu hết người học hoàn thành trong dưới 90 phút',
    // ── Lesson Header — Nouns ────────────────────────
    '🏠 Beginner · Lesson 5': '🏠 Người mới · Bài 5', 'Common Korean': 'Tiếng Hàn thông dụng',
    'Master people, family, place, time, and object nouns in Korean': 'Nắm vững danh từ về người, gia đình, địa điểm, thời gian và đồ vật',
    'Learn how Korean counters (개, 명, 잔) work with numbers': 'Tìm hiểu cách đơn vị đếm tiếng Hàn (개, 명, 잔) hoạt động với số',
    'Understand the possessive marker 의 and polite vs casual forms': 'Hiểu trợ từ sở hữu 의 và dạng lịch sự vs thông thường',
    // ── Lesson Header — Pronouns ─────────────────────
    '👥 Beginner · Lesson 4': '👥 Người mới · Bài 4',
    'Learn polite 저 vs casual 나, and why Korean often drops pronouns entirely': 'Học 저 lịch sự vs 나 thông thường, và tại sao tiếng Hàn thường bỏ đại từ',
    'Understand why 당신 is rarely used and how to address people naturally': 'Hiểu tại sao 당신 ít được dùng và cách xưng hô tự nhiên',
    'Master 우리 (our/my), demonstratives (이것·그것·저것), and question words': 'Nắm vững 우리 (của chúng ta/của tôi), chỉ thị từ (이것·그것·저것) và từ hỏi',
    // ── Lesson Header — Vocabulary ────────────────────
    '🗂 21 Categories': '🗂 21 danh mục',
    '🔊 Audio on every card': '🔊 Âm thanh trên mỗi thẻ',
    'Covers 500+ core Korean words across 21 categories': 'Bao gồm 500+ từ tiếng Hàn cốt lõi trong 21 danh mục',
    'Bite-sized steps with instant audio — tap any card to hear it': 'Bước nhỏ với âm thanh tức thì — chạm vào thẻ bất kỳ để nghe',
    'Quizzes after every category to lock in your memory': 'Kiểm tra sau mỗi danh mục để củng cố trí nhớ',
    'Most learners finish each category in under 15 minutes': 'Hầu hết người học hoàn thành mỗi danh mục trong dưới 15 phút',
    // ── Hangul Page ───────────────────────────────────
    '✏️ Starter · Lesson 1': '✏️ Khởi đầu · Bài 1', 'Hangul Alphabet:': 'Bảng chữ cái Hangul:',
    '⏱ 45 min read': '⏱ 45 phút đọc', '📊 Beginner': '📊 Người mới',
    '🔖 Hangul Basics · 한글 기초': '🔖 Hangul cơ bản · 한글 기초',
    '🔡 Syllable Block Patterns': '🔡 Mẫu khối âm tiết',
    '📘 Common Compound Batchim Examples': '📘 Ví dụ Batchim kép thông dụng',
    '👁 18,204 views': '👁 18.204 lượt xem',
    'What is Hangul? (한글이란?)': 'Hangul là gì? (한글이란?)',
    'Basic Vowels (기본 모음)': 'Nguyên âm cơ bản (기본 모음)', 'Hangul at a Glance': 'Hangul trong nháy mắt',
    'Basic Consonants': 'Phụ âm cơ bản', 'Basic Vowels': 'Nguyên âm cơ bản',
    'Double Consonants': 'Phụ âm đôi', 'Compound Vowels': 'Nguyên âm kép', 'Fun Fact': 'Điều thú vị',
    'Why does ㅇ appear at the start?': 'Tại sao ㅇ xuất hiện ở đầu?',
    'Vowel Shape Mnemonics': 'Gợi nhớ hình dạng nguyên âm', 'About Hangul (한글)': 'Về Hangul (한글)',
    'Basic Vowels (모음)': 'Nguyên âm cơ bản (모음)',
    'Compound Vowels (복합 모음)': 'Nguyên âm kép (복합 모음)',
    'Basic Consonants (자음)': 'Phụ âm cơ bản (자음)', 'Syllable Blocks (음절)': 'Khối âm tiết (음절)',
    'Tense (Double) Consonants — 쌍자음': 'Phụ âm căng (đôi) — 쌍자음',
    'Compound Batchim (겹받침)': 'Batchim kép (겹받침)',
    'Aspirated Consonants — 거센소리': 'Phụ âm bật hơi — 거센소리', 'Quick Practice Quiz': 'Kiểm tra nhanh',
    'Did you know?': 'Bạn có biết không?', 'Vowel Harmony': 'Hòa âm nguyên âm', 'Reading Practice': 'Luyện đọc',
    'The Tissue Test': 'Bài kiểm tra khăn giấy', '10 basic vowels': '10 nguyên âm cơ bản',
    '11 compound vowels': '11 nguyên âm kép', '14 basic consonants': '14 phụ âm cơ bản',
    '5 tense consonants': '5 phụ âm căng', '5 aspirated consonants': '5 phụ âm bật hơi',
    'October 9 is Hangul Day (한글날) in South Korea — a national holiday celebrating the invention of the alphabet in 1443.': 'Ngày 9 tháng 10 là Ngày Hangul (한글날) ở Hàn Quốc — ngày lễ quốc gia kỷ niệm sự ra đời của bảng chữ cái năm 1443.',
    'Structure': 'Cấu trúc', 'Example': 'Ví dụ', 'Reading': 'Đọc', 'Meaning': 'Nghĩa',
    'Consonant + Vowel': 'Phụ âm + Nguyên âm', 'go (verb stem)': 'đi (gốc động từ)',
    'Consonant + Vowel + Consonant': 'Phụ âm + Nguyên âm + Phụ âm', 'Korean (prefix)': 'Tiếng Hàn (tiền tố)',
    'Silent ㅇ + Vowel': 'ㅇ câm + Nguyên âm', 'ah! (exclamation)': 'à! (thán từ)',
    'Batchim': 'Batchim', 'Example Word': 'Từ ví dụ', 'Note': 'Ghi chú', 'to read': 'đọc',
    'to sit': 'ngồi', 'life': 'cuộc sống',
    'k (aspirated)': 'k (bật hơi)', 't (aspirated)': 't (bật hơi)',
    'p (aspirated)': 'p (bật hơi)', 'ch (aspirated)': 'ch (bật hơi)',
    '← Home': '← Trang chủ', 'Mark as Complete ✓': 'Đánh dấu hoàn thành ✓', 'Syllable Blocks →': 'Khối âm tiết →',
    // ── Grammar Page ──────────────────────────────────
    'Word Order — SOV Structure (어순)': 'Trật tự từ — Cấu trúc SOV (어순)',
    'Korean Particles (조사)': 'Trợ từ tiếng Hàn (조사)', 'Particle Practice': 'Luyện trợ từ',
    'Speech Levels (존댓말 vs 반말)': 'Cấp độ nói (존댓말 vs 반말)',
    'Present Tense (-아요/-어요)': 'Thì hiện tại (-아요/-어요)',
    'Past Tense (-았어요/-었어요)': 'Thì quá khứ (-았어요/-었어요)',
    'Future Tense (-을 거예요/-ㄹ 거예요)': 'Thì tương lai (-을 거예요/-ㄹ 거예요)',
    'Making Sentences Negative (부정문)': 'Câu phủ định (부정문)',
    'Forming Questions (의문문)': 'Đặt câu hỏi (의문문)',
    'WH- Question Words': 'Từ hỏi WH-',
    'Essential Sentence Patterns (문형)': 'Mẫu câu cơ bản (문형)',
    'Connectors: 그리고, 그래서, 그렇지만, 그런데': 'Liên từ: 그리고, 그래서, 그렇지만, 그런데',
    'And, With: -하고, -(이)랑': 'Và, Cùng: -하고, -(이)랑',
    'To/From Someone: -한테, -한테서': 'Đến/Từ ai đó: -한테, -한테서',
    'Telling Time (시간 말하기)': 'Nói giờ (시간 말하기)',
    'Counters (단위 명사)': 'Đơn vị đếm (단위 명사)',
    'Present Progressive: -고 있어요': 'Hiện tại tiếp diễn: -고 있어요',
    'Particle': 'Trợ từ', 'Function': 'Chức năng', 'Rule': 'Quy tắc', 'Level': 'Cấp độ',
    'When to Use': 'Khi nào dùng', 'Dictionary Form': 'Dạng từ điển', 'Stem': 'Gốc',
    'Conjugated': 'Đã chia', 'Counter': 'Đơn vị đếm', 'Used for': 'Dùng cho',
    'Vowel': 'Nguyên âm', 'Shape Mnemonic': 'Gợi nhớ hình dạng', 'Mouth Position': 'Vị trí miệng',
    'Time': 'Thời gian', 'Register': 'Mức ngôn ngữ', 'Used with': 'Dùng với',
    'Formal equivalent': 'Tương đương trang trọng', 'Korean · 한국어': 'Tiếng Hàn · 한국어',
    'Translation · 번역': 'Dịch nghĩa · 번역', 'Topic marker': 'Trợ từ chủ đề',
    'Subject marker': 'Trợ từ chủ thể', 'Object marker': 'Trợ từ tân ngữ',
    // ── Pronunciation Page ────────────────────────────
    '🔊 Beginner · Lesson 3': '🔊 Người mới · Bài 3', 'Pronunciation Guide:': 'Hướng dẫn phát âm:',
    '⏱ 50 min read': '⏱ 50 phút đọc', '🔖 Pronunciation': '🔖 Phát âm',
    '👁 14,837 views': '👁 14.837 lượt xem', 'sound change rules': 'quy tắc biến âm',
    'Batchim — Syllable-Final Consonants (받침)': 'Batchim — Phụ âm cuối âm tiết (받침)',
    '7 possible sounds': '7 âm có thể', 'Sound Group': 'Nhóm âm', 'Written As': 'Viết là',
    'Pronounced As': 'Phát âm là', 'Unreleased stops': 'Âm tắc không bật',
    // ── Syllable Blocks Page ──────────────────────────
    'The ㅇ Placeholder Rule': 'Quy tắc chỗ giữ ㅇ',
    'Vertical vs Horizontal Vowels': 'Nguyên âm dọc vs ngang',
    'Quick Visual Trick': 'Mẹo nhìn nhanh', 'Building Your First Syllables': 'Xây dựng âm tiết đầu tiên',
    'Adding Batchim — The Final Consonant': 'Thêm Batchim — Phụ âm cuối',
    'Reading Real Korean Words': 'Đọc từ tiếng Hàn thực tế',
    'Practice & Summary': 'Luyện tập & Tóm tắt',
    '5 Rules for Korean Syllable Blocks': '5 quy tắc cho khối âm tiết tiếng Hàn',
    '📝 Self-Test: Identify the Components': '📝 Tự kiểm tra: Xác định các thành phần',
    // ── Pronouns Page ─────────────────────────────────
    'Saying \'You\' in Korean': 'Cách nói "bạn" trong tiếng Hàn',
    'Third Person & We (그·그녀·우리)': 'Ngôi thứ ba & Chúng ta (그·그녀·우리)',
    'Demonstrative Pronouns (이·그·저)': 'Đại từ chỉ thị (이·그·저)',
    'Question Pronouns (의문대명사)': 'Đại từ hỏi (의문대명사)',
    'Pronouns Complete!': 'Hoàn thành đại từ!',
    // ── Emotions Page ─────────────────────────────────
    '😊 Intermediate · Lesson 7': '😊 Trung cấp · Bài 7',
    'Core Emotions': 'Cảm xúc cơ bản', 'Expressing Feelings': 'Diễn đạt cảm xúc',
    'Complex Emotions': 'Cảm xúc phức tạp', 'Emotional Phrases': 'Cụm từ cảm xúc',
    'Emotions in Korean (감정)': 'Cảm xúc trong tiếng Hàn (감정)',
    'Emotions Complete!': 'Hoàn thành cảm xúc!',
    // ── Shopping Page ─────────────────────────────────
    '🛒 Intermediate · Lesson 8': '🛒 Trung cấp · Bài 8',
    'Shopping Vocabulary': 'Từ vựng mua sắm', 'In the Store': 'Trong cửa hàng', 'Prices & Numbers': 'Giá cả & Số',
    'Transactions': 'Giao dịch', 'Shopping in Korea (쇼핑)': 'Mua sắm ở Hàn Quốc (쇼핑)',
    'Shopping Complete!': 'Hoàn thành mua sắm!',
    // ── Speech Levels Page ────────────────────────────
    '🗣️ Intermediate · Lesson 6': '🗣️ Trung cấp · Bài 6',
    '합쇼체 (Formal)': '합쇼체 (Trang trọng)', '해요체 (Polite)': '해요체 (Lịch sự)',
    '반말 (Casual)': '반말 (Thông thường)', 'Choosing a Level': 'Chọn cấp độ',
    'Korean Speech Levels Overview': 'Tổng quan cấp độ nói tiếng Hàn',
    'Speech Levels Complete!': 'Hoàn thành cấp độ nói!',
    // ── Vocab Browser ───────────────────────────────────
    'Vocab Browser': 'Tra cứu từ vựng',
    'saved to flashcards': 'đã lưu vào thẻ ghi nhớ',
    'Loading vocabulary…': 'Đang tải từ vựng…',
    'No words match your search.': 'Không có từ nào khớp với tìm kiếm.',
    'Failed to load vocabulary.': 'Không tải được từ vựng.',
    'Search Korean, English, or romanization…': 'Tìm tiếng Hàn, tiếng Anh hoặc phiên âm…',
    '★ Add all in category': '★ Thêm tất cả trong danh mục',
    'Verbs': 'Động từ',
    'Health': 'Sức khỏe',
    'Media': 'Truyền thông',
    'Proverbs': 'Tục ngữ',
    'Academic': 'Học thuật',
    // ── Progress system (streak / counters / resume) ────
    '✓ Correct!': '✓ Đúng rồi!',
    '✗ Not quite — try again!': '✗ Chưa đúng — thử lại!',
    '{n}-day streak': 'Chuỗi {n} ngày',
    '{n} steps today': '{n} bước hôm nay',
    'Continue': 'Tiếp tục',
    'Step {n} of {m}': 'Bước {n} / {m}',
    'Steps completed': 'Số bước đã hoàn thành',
    'Words & phrases learned': 'Từ & cụm từ đã học',
    'Letters & syllables learned': 'Chữ cái & âm tiết đã học',
    'Best streak': 'Chuỗi dài nhất',
    'Start Again': 'Bắt đầu lại',
    'Next Lesson →': 'Bài học tiếp →',
    'Next →': 'Tiếp →',
    'Progress': 'Tiến độ',
    'Reset all progress': 'Đặt lại toàn bộ tiến độ',
    '🔥 Daily streak + real progress tracking': '🔥 Chuỗi học mỗi ngày + theo dõi tiến độ thực'
  };
  if (window.LangManager) window.LangManager.register('vi', VI);
})();
