'use strict';
(function() {
  const ID = {
    // ── Navigation & Global UI ─────────────────────────
    'Learn': 'Belajar', 'Quiz': 'Kuis', 'K-Culture': 'K-Budaya', 'Travel': 'Wisata', 'News': 'Berita',
    'Search...': 'Cari...', 'Search lessons, vocabulary…': 'Cari pelajaran, kosakata…',
    '🇰🇷 · Free · For Every Level': '🇰🇷 · Gratis · Untuk Semua Level',
    'Learn Korean': 'Belajar Bahasa Korea', 'Start Learning': 'Mulai Belajar', 'Explore K-Culture': 'Jelajahi K-Budaya',
    'Vocabulary Words': 'Kosakata', 'Lessons': 'Pelajaran', 'Active Learners': 'Pembelajar Aktif', '% Free': '% Gratis',
    'FEATURES': 'FITUR', 'Everything You Need to Learn Korean': 'Semua yang Anda Butuhkan untuk Belajar Bahasa Korea',
    'Start with 한글': 'Mulai dengan 한글', 'Learn Hangul Now →': 'Belajar Hangul Sekarang →',
    'Hear It': 'Dengarkan', 'More Words': 'Kata Lainnya', 'Word of the Day': 'Kata Hari Ini',
    'STRUCTURED PATHS · 학습 경로': 'JALUR TERSTRUKTUR · 학습 경로',
    'Choose Your Learning Path': 'Pilih Jalur Belajar Anda',
    'Beginner': 'Pemula', 'Intermediate': 'Menengah', 'Advanced': 'Mahir',
    'Start Beginner Path →': 'Mulai Jalur Pemula →', 'Start Intermediate Path →': 'Mulai Jalur Menengah →',
    'Start Advanced Path →': 'Mulai Jalur Mahir →', 'POPULAR': 'POPULER',
    'Beginner–Intermediate': 'Pemula–Menengah', 'Intermediate–Advanced': 'Menengah–Mahir',
    'Beg–Int': 'Pmla–Mngh',
    // ── K-Culture & Home ──────────────────────────────
    'K-CULTURE': 'K-BUDAYA', 'K-CULTURE · 한국 문화': 'K-BUDAYA · 한국 문화',
    'Experience Korea Beyond Language': 'Rasakan Korea Melampaui Bahasa',
    'Explore All K-Culture Content →': 'Jelajahi Semua Konten K-Budaya →',
    'TRAVEL · 여행': 'WISATA · 여행', 'Explore Korea': 'Jelajahi Korea',
    'View Full Travel Guide →': 'Lihat Panduan Wisata Lengkap →',
    'PRACTICE · 연습': 'LATIHAN · 연습',
    '10 progressive levels · multiple choice · covers Hangul, Grammar & Vocabulary': '10 level bertahap · pilihan ganda · mencakup Hangul, Tata Bahasa & Kosakata',
    'Choose a Level': 'Pilih Level', 'questions': 'pertanyaan', '← All Levels': '← Semua Level',
    'Try Again': 'Coba Lagi', 'Next Level': 'Level Berikutnya', 'All Levels': 'Semua Level',
    'Next Level →': 'Level Berikutnya →',
    // ── Travel ────────────────────────────────────────
    '🇰🇷 · South Korea Travel Guide · 여행 안내': '🇰🇷 · Panduan Wisata Korea Selatan · 여행 안내',
    'South Korea Travel Guide': 'Panduan Wisata Korea Selatan',
    'Population': 'Populasi', 'UNESCO Sites': 'Situs UNESCO',
    'Great to visit': 'Bagus untuk dikunjungi', 'Visa-free nations': 'Negara bebas visa',
    'EXPLORE THE GUIDES · 가이드 탐색': 'JELAJAHI PANDUAN · 가이드 탐색',
    'Plan Your Perfect Korea Trip': 'Rencanakan Perjalanan Korea Sempurna Anda',
    'TOP DESTINATIONS · 인기 여행지': 'DESTINASI TERPOPULER · 인기 여행지',
    'Where Will You Explore?': 'Ke Mana Anda Akan Menjelajah?',
    'ESSENTIAL PHRASES · 필수 표현': 'FRASA PENTING · 필수 표현',
    'Travel Korean Phrasebook': 'Buku Frasa Bahasa Korea untuk Wisata',
    'TRANSPORTATION · 교통': 'TRANSPORTASI · 교통', 'Getting Around Korea': 'Bepergian di Korea',
    'FOOD TOUR · 음식 여행': 'WISATA KULINER · 음식 여행', 'Regional Korean Specialties': 'Kekhasan Kuliner Daerah Korea',
    'CULTURAL ETIQUETTE · 예절': 'ETIKA BUDAYA · 예절', 'Korean Cultural Tips': 'Tips Budaya Korea',
    'TRAVEL APPS · 여행 앱': 'APLIKASI WISATA · 여행 앱', 'Essential Apps for Korea Travel': 'Aplikasi Penting untuk Wisata Korea',
    'READY TO LEARN?': 'SIAP UNTUK BELAJAR?', 'Start Speaking Korean Today': 'Mulai Berbicara Bahasa Korea Hari Ini',
    'Start Learning Korean →': 'Mulai Belajar Bahasa Korea →', 'Plan Your Trip': 'Rencanakan Perjalanan Anda',
    'K-Pop': 'K-Pop', 'K-Drama': 'K-Drama', 'K-Beauty': 'K-Beauty', 'All': 'Semua',
    // ── Footer & Company ──────────────────────────────
    'Learn · 학습': 'Belajar · 학습', 'K-Culture · 문화': 'K-Budaya · 문화',
    'Company · 회사': 'Perusahaan · 회사', 'Explore': 'Jelajahi', 'Company': 'Perusahaan',
    'Hangul Alphabet': 'Alfabet Hangul', 'Grammar': 'Tata Bahasa', 'Vocabulary': 'Kosakata',
    'Travel Guide': 'Panduan Wisata', 'Korean News': 'Berita Korea', 'About Us': 'Tentang Kami',
    'Contact': 'Kontak', 'Privacy Policy': 'Kebijakan Privasi', 'Terms of Use': 'Ketentuan Penggunaan',
    'Made with ❤️ for Korean learners worldwide.': 'Dibuat dengan ❤️ untuk pembelajar bahasa Korea di seluruh dunia.',
    '🇰🇷 학습을 즐기세요! (Enjoy your learning!)': '🇰🇷 학습을 즐기세요! (Selamat belajar!)',
    'Home': 'Beranda', 'Hangul': 'Hangul',
    'A free Korean language learning platform — combining language study with K-culture, travel guides, and real-world practice. For learners of every level, worldwide.': 'Platform belajar bahasa Korea gratis — menggabungkan pembelajaran bahasa dengan K-budaya, panduan wisata, dan praktik dunia nyata. Untuk pembelajar semua level, di seluruh dunia.',
    'A free Korean language learning platform for learners of every level, worldwide.': 'Platform belajar bahasa Korea gratis untuk pembelajar semua level, di seluruh dunia.',
    '© 2026 한국어 학교. Made with ❤️ for Korean learners worldwide.': '© 2026 한국어 학교. Dibuat dengan ❤️ untuk pembelajar bahasa Korea di seluruh dunia.',
    // ── Sidebar Dividers ──────────────────────────────
    'Getting Started': 'Memulai', 'Tools': 'Alat Bantu',
    'CATEGORIES · 카테고리': 'KATEGORI · 카테고리', 'DEEP DIVES · 심층 탐구': 'PEMBAHASAN MENDALAM · 심층 탐구',
    // ── Learn Sidebar ─────────────────────────────────
    'Introduction': 'Pengantar', 'Syllable Blocks': 'Blok Suku Kata', 'Pronunciation Guide': 'Panduan Pelafalan',
    'Vocab': 'Kosakata', 'Greetings': 'Salam', 'Numbers': 'Angka', 'Family': 'Keluarga',
    'Food & Drink': 'Makanan & Minuman', 'Colors': 'Warna', 'Days & Time': 'Hari & Waktu', 'Places': 'Tempat',
    'Emotions': 'Emosi', 'Body Parts': 'Bagian Tubuh', 'Shopping': 'Belanja', 'Weather': 'Cuaca',
    'Verbs & Actions': 'Kata Kerja & Aksi', 'Adjectives': 'Kata Sifat', 'Workplace': 'Tempat Kerja',
    'Health & Medicine': 'Kesehatan & Obat-obatan', 'Media & K-Culture': 'Media & K-Budaya',
    'Proverbs & Idioms': 'Peribahasa & Idiom', 'Academic Korean': 'Bahasa Korea Akademik',
    'News & Society': 'Berita & Masyarakat', 'Konglish': 'Konglish', 'Pronouns': 'Kata Ganti',
    'Common Nouns': 'Kata Benda Umum', 'Sentence Structure': 'Struktur Kalimat', 'Korean Particles': 'Partikel Bahasa Korea',
    'Verb Conjugation': 'Konjugasi Kata Kerja', 'Question Forms': 'Bentuk Pertanyaan', 'Connectors': 'Kata Sambung',
    'And, With': 'Dan, Dengan', 'To/From Someone': 'Kepada/Dari Seseorang', 'Telling Time': 'Menyebutkan Waktu',
    'Counters': 'Kata Bantu Bilangan', 'Present Progressive': 'Present Progressive', 'Self Introduction': 'Perkenalan Diri',
    'Dates and Months': 'Tanggal dan Bulan', 'Degree Adverbs': 'Kata Keterangan Derajat',
    'Nominalizer -는 것': 'Nominalisasi -는 것', 'Comparatives': 'Perbandingan',
    'Still, Already': 'Masih, Sudah', 'Someone, Something': 'Seseorang, Sesuatu',
    'Imperative -(으)세요': 'Perintah -(으)세요', 'Don\'t: -지 마세요': 'Jangan: -지 마세요',
    'Method: -(으)로': 'Cara: -(으)로', 'Good/Poor At': 'Mahir/Kurang Mahir',
    '-도 Advanced Uses': 'Penggunaan Lanjutan -도', 'Formal vs Informal': 'Formal vs Informal',
    'Expressing Emotions': 'Mengungkapkan Emosi', 'Shopping Phrases': 'Frasa Belanja', 'Writing Essays': 'Menulis Esai',
    'Business Korean': 'Bahasa Korea Bisnis', 'Classical Korean': 'Bahasa Korea Klasik', 'Korean Dialogues': 'Dialog Bahasa Korea',
    'Flashcards': 'Kartu Hafalan',
    // ── Culture Sidebar ───────────────────────────────
    'K-Movie': 'K-Film', 'K-Food': 'K-Kuliner', 'K-Fashion': 'K-Fashion',
    'Korean Thing': 'Hal-hal Korea', 'K-Gaming': 'K-Gaming', 'K-Sports': 'K-Olahraga',
    'K-Pop, K-Drama, food, beauty, fashion, gaming, sports & traditions.': 'K-Pop, K-Drama, kuliner, kecantikan, fashion, gaming, olahraga & tradisi.',
    'K-Pop History': 'Sejarah K-Pop', 'Agencies': 'Agensi', 'Generations': 'Generasi', 'Genres': 'Genre',
    'Variety Shows': 'Acara Variety', 'Film & Acting': 'Film & Akting', 'Idol Phrases': 'Frasa Idola',
    'Fan Slang': 'Bahasa Gaul Fan', 'Fan Chants': 'Yel-yel Fan', 'Drama History': 'Sejarah K-Drama',
    'Drama Genres': 'Genre Drama', 'Must-Watch Dramas': 'Drama Wajib Tonton', 'K-Drama Tropes': 'Trope K-Drama',
    'Speech Levels': 'Tingkat Kesopanan Bahasa', 'Dialogue Practice': 'Latihan Dialog',
    'Fan Culture & Slang': 'Budaya & Bahasa Gaul Fan', 'Movie History': 'Sejarah Film',
    'Movie Genres': 'Genre Film', 'Must-Watch Films': 'Film Wajib Tonton', 'Directors': 'Sutradara',
    'Iconic Lines': 'Dialog Ikonik', 'Fan Culture': 'Budaya Fan',
    'K-Food Goes Global': 'K-Kuliner Mendunia', 'Foods That Went Global': 'Makanan yang Mendunia',
    'K-Food Timeline': 'Garis Waktu K-Kuliner', 'Essential Dishes': 'Hidangan Penting',
    'World-Famous Chefs': 'Koki Terkenal Dunia', 'Ordering & Dining': 'Memesan & Bersantap',
    'Street Food': 'Jajanan Kaki Lima', 'Food Culture & Drinking': 'Budaya Kuliner & Minum',
    'Ramyeon Guide': 'Panduan Ramyeon', 'Mandu Guide': 'Panduan Mandu',
    'Chicken Guide': 'Panduan Ayam Goreng', 'K-BBQ Guide': 'Panduan K-BBQ', 'Kimchi Guide': 'Panduan Kimchi',
    'K-Beauty Goes Global': 'K-Beauty Mendunia', 'K-Beauty Timeline': 'Garis Waktu K-Beauty',
    'Iconic Brands': 'Merek Ikonik', 'Beauty Vocabulary': 'Kosakata Kecantikan', '10-Step Skincare': 'Perawatan Kulit 10 Langkah',
    'Key Ingredients': 'Bahan Utama', 'Beauty Trends': 'Tren Kecantikan', 'Makeup Philosophy': 'Filosofi Makeup',
    'Skin Clinic Culture': 'Budaya Klinik Kecantikan', 'K-Beauty Dialogue': 'Dialog K-Beauty',
    'K-Fashion Global': 'K-Fashion Mendunia', 'Fashion Icons': 'Ikon Fashion',
    'Fashion Timeline': 'Garis Waktu Fashion', 'Style Aesthetics': 'Estetika Gaya', 'Idol Fashion': 'Fashion Idola',
    'Seoul Fashion Week': 'Seoul Fashion Week', 'Fashion Vocabulary': 'Kosakata Fashion',
    'Fashion Districts': 'Distrik Fashion', 'Shopping Dialogue': 'Dialog Belanja',
    'Hanbok & Traditional Fashion': 'Hanbok & Fashion Tradisional', 'Rice Obsession': 'Budaya Nasi',
    'Youth Protection Laws': 'Undang-undang Perlindungan Anak', 'Fast Delivery Culture': 'Budaya Pengiriman Cepat',
    'Invasive Species Crisis': 'Krisis Spesies Invasif', 'Table Call Culture': 'Budaya Memanggil Pelayan di Meja',
    'Public Transport': 'Transportasi Umum', 'Jjimjilbang': 'Jjimjilbang', 'Plastic Surgery Culture': 'Budaya Operasi Plastik',
    'Outdoor Drinking': 'Minum di Luar Ruangan', 'Jeonse Housing': 'Perumahan Jeonse',
    'Traditions & Holidays': 'Tradisi & Hari Libur', '100 Korean Proverbs': '100 Peribahasa Korea',
    'K-Gaming Stats': 'Statistik K-Gaming', 'Gaming Timeline': 'Garis Waktu Gaming',
    'Gaming Legends': 'Legenda Gaming', 'Iconic Games': 'Game Ikonik', 'Streaming Culture': 'Budaya Streaming',
    'PC Bang Culture': 'Budaya PC Bang', 'PC방 Culture': 'Budaya PC방', 'Esports Leagues': 'Liga Esports',
    'Gamer Slang': 'Bahasa Gaul Gamer', 'Gaming Vocabulary': 'Kosakata Gaming', 'Sports Overview': 'Ikhtisar Olahraga',
    'Football Heroes': 'Pahlawan Sepak Bola', 'Baseball Heroes': 'Pahlawan Bisbol', 'Marathon Legends': 'Legenda Maraton',
    'Individual Legends': 'Legenda Individu', 'Traditional Sports': 'Olahraga Tradisional', 'Cheer Chants': 'Yel-yel Sorak',
    // ── Travel Sidebar ────────────────────────────────
    'Travel Guide · 여행 안내': 'Panduan Wisata · 여행 안내', 'South Korea': 'Korea Selatan',
    'By Days · 일수별': 'Berdasarkan Hari · 일수별', '1 Day Trip · 당일치기': 'Wisata Sehari · 당일치기',
    '2 Days · 1박 2일': '2 Hari · 1박 2일', '3 Days · 2박 3일': '3 Hari · 2박 3일',
    '5 Days · 4박 5일': '5 Hari · 4박 5일', '1 Week · 일주일': '1 Minggu · 일주일',
    '10 Days': '10 Hari', '2 Weeks · 2주': '2 Minggu · 2주', '1 Month+ · 한달': '1 Bulan+ · 한달',
    'By City · 도시별': 'Berdasarkan Kota · 도시별', 'Seoul · 서울': 'Seoul · 서울',
    'Incheon · 인천': 'Incheon · 인천', 'Busan · 부산': 'Busan · 부산',
    'Suwon · 수원': 'Suwon · 수원', 'Jeju · 제주도': 'Jeju · 제주도',
    'Gyeongju · 경주': 'Gyeongju · 경주', 'Other Cities': 'Kota Lainnya',
    'By Theme · 테마별': 'Berdasarkan Tema · 테마별', 'Food Tour · 음식 여행': 'Wisata Kuliner · 음식 여행',
    'Events & Festivals · 이벤트': 'Acara & Festival · 이벤트', 'Sightseeing · 관광': 'Wisata · 관광',
    'Cross-Country · 장거리': 'Lintas Negara · 장거리',
    '📋 Trip Planner · 여행 계획표': '📋 Perencana Perjalanan · 여행 계획표',
    'Day-by-Day Itineraries': 'Itinerari Harian', 'City Travel Guides': 'Panduan Wisata Kota',
    'Themed Travel': 'Wisata Bertema', 'Bus': 'Bus', 'Subway': 'Kereta Bawah Tanah', 'Taxi': 'Taksi',
    'KTX High-speed Rail': 'Kereta Cepat KTX', 'Age': 'Usia', 'Bowing': 'Membungkuk',
    'Drinking': 'Minum', 'Eating': 'Makan', 'Quiet': 'Diam', 'Shoes': 'Sepatu',
    'Tipping': 'Memberi Tip', 'Two Hands': 'Dua Tangan',
    'International': 'Internasional', 'Politics': 'Politik', 'Economy': 'Ekonomi', 'Society': 'Masyarakat',
    'Science': 'Sains', 'Culture': 'Budaya', 'Sports': 'Olahraga', 'Education': 'Pendidikan',
    'Environment': 'Lingkungan',
    // ── Homepage Descriptions ─────────────────────────
    'Discover the beauty of Korea through language, culture, K-pop, travel, and cuisine — with free lessons designed for learners worldwide.': 'Temukan keindahan Korea lewat bahasa, budaya, K-pop, wisata, dan kuliner — dengan pelajaran gratis yang dirancang untuk pembelajar di seluruh dunia.',
    'Learn the Korean alphabet in just 2 hours. 한글 (Hangul) is remarkably logical — once you know the 24 basic letters, you can read anything.': 'Pelajari alfabet Korea hanya dalam 2 jam. 한글 (Hangul) sangat logis — begitu Anda tahu 24 huruf dasarnya, Anda bisa membaca apa saja.',
    'Learn Korean naturally through your favourite songs. Line-by-line breakdowns with vocabulary, grammar notes, and pronunciation guides.': 'Belajar bahasa Korea secara alami lewat lagu favorit Anda. Pembahasan baris per baris dengan kosakata, catatan tata bahasa, dan panduan pelafalan.',
    'Pick up everyday Korean from your favourite dramas. Contextual vocabulary lists organised by show, genre, and proficiency level.': 'Pelajari bahasa Korea sehari-hari dari drama favorit Anda. Daftar kosakata kontekstual yang disusun berdasarkan judul, genre, dan level kemahiran.',
    'From 김치 (kimchi) to 삼겹살 (samgyeopsal) — explore the rich vocabulary of Korean cuisine with pronunciation and cultural context.': 'Dari 김치 (kimchi) hingga 삼겹살 (samgyeopsal) — jelajahi kosakata kaya kuliner Korea lengkap dengan pelafalan dan konteks budaya.',
    'Whether you are just starting or aiming for fluency, we have a clear roadmap to take you there step by step.': 'Baik Anda baru memulai atau ingin mencapai kefasihan, kami punya peta jalan yang jelas untuk membawa Anda ke sana langkah demi langkah.',
    'Language is the gateway — immerse yourself in Korean pop culture, food, and beauty to supercharge your learning.': 'Bahasa adalah gerbangnya — benamkan diri Anda dalam budaya pop, kuliner, dan kecantikan Korea untuk mempercepat pembelajaran Anda.',
    'From BTS to BLACKPINK — the most common Korean words and phrases used by your favourite K-Pop artists, with pronunciation guides.': 'Dari BTS hingga BLACKPINK — kata dan frasa Korea paling umum yang digunakan oleh artis K-Pop favorit Anda, lengkap dengan panduan pelafalan.',
    'Korean dramas are packed with emotional vocabulary. Learn how characters express joy, sadness, anger, and love in authentic Korean.': 'Drama Korea penuh dengan kosakata emosional. Pelajari cara karakter mengungkapkan kebahagiaan, kesedihan, kemarahan, dan cinta dalam bahasa Korea yang otentik.',
    'Essential phrases for ordering food, asking for the bill, and navigating a Korean restaurant menu with confidence.': 'Frasa penting untuk memesan makanan, meminta tagihan, dan memahami menu restoran Korea dengan percaya diri.',
    'Explore the world of K-Beauty with essential vocabulary for skincare routines, cosmetics, and Korean beauty trends.': 'Jelajahi dunia K-Beauty dengan kosakata penting untuk rutinitas perawatan kulit, kosmetik, dan tren kecantikan Korea.',
    'Learn the language of every destination. From bustling Seoul to the serene shores of Jeju — your AI travel guide is ready.': 'Pelajari bahasa setiap destinasi. Dari Seoul yang ramai hingga pantai tenang Jeju — panduan wisata AI Anda sudah siap.',
    "South Korea's dazzling capital — from the ancient palaces of Gyeongbokgung to the neon streets of Gangnam and Hongdae.": 'Ibu kota Korea Selatan yang memukau — dari istana kuno Gyeongbokgung hingga jalanan neon Gangnam dan Hongdae.',
    "Korea's vibrant port city with stunning beaches, fresh seafood markets, and a unique dialect worth discovering.": 'Kota pelabuhan Korea yang dinamis dengan pantai indah, pasar makanan laut segar, dan dialek unik yang layak dijelajahi.',
    "Korea's paradise island — volcanic landscapes, pristine beaches, tangerine groves, and the famous haenyeo diving culture.": 'Pulau surga Korea — lanskap vulkanik, pantai murni, kebun jeruk keprok, dan budaya penyelaman haenyeo yang terkenal.',
    // ── Homepage Place Names & Quiz ───────────────────
    'Seoul': 'Seoul', 'Busan': 'Busan', 'Jeju Island': 'Pulau Jeju',
    'Test Your Korean': 'Uji Bahasa Korea Anda', 'Explore →': 'Jelajahi →',
    // ── Homepage Cards & Labels ───────────────────────
    'K-Pop Lyrics Learning': 'Belajar Lewat Lirik K-Pop', 'K-Drama Vocabulary': 'Kosakata K-Drama',
    'Korean Food Dictionary': 'Kamus Kuliner Korea',
    'Master Korean Emotions Through K-Drama': 'Kuasai Emosi Bahasa Korea Lewat K-Drama',
    'Order Like a Local: Restaurant Korean': 'Memesan Seperti Warga Lokal: Bahasa Korea di Restoran',
    'Beauty & Skincare Vocabulary in Korean': 'Kosakata Kecantikan & Perawatan Kulit dalam Bahasa Korea',
    'K-Pop Stars\' Korean Phrases You Need to Know': 'Frasa Bahasa Korea Bintang K-Pop yang Perlu Anda Tahu',
    'Read →': 'Baca →', 'Hello / Good day': 'Halo / Selamat siang',
    'annyeonghaseyo': 'an-nyeong-ha-se-yo',
    // ── Learning Path Checklist ───────────────────────
    '✓ Hangul Alphabet': '✓ Alfabet Hangul', '✓ Basic Vowels & Consonants': '✓ Vokal & Konsonan Dasar',
    '✓ Syllable Blocks': '✓ Blok Suku Kata', '✓ Essential Vocabulary': '✓ Kosakata Penting',
    '✓ Basic Greetings': '✓ Salam Dasar', '✓ Korean Grammar (SOV)': '✓ Tata Bahasa Korea (SOV)',
    '✓ Particles & Conjugation': '✓ Partikel & Konjugasi', '✓ Speech Levels': '✓ Tingkat Kesopanan Bahasa',
    '✓ 300+ Vocabulary Words': '✓ 300+ Kosakata', '✓ Real Dialogues': '✓ Dialog Nyata',
    '✓ Business Korean': '✓ Bahasa Korea Bisnis', '✓ Classical Korean': '✓ Bahasa Korea Klasik',
    '✓ Essay Writing': '✓ Menulis Esai', '✓ TOPIK Preparation': '✓ Persiapan TOPIK',
    '✓ Idiomatic Expressions': '✓ Ungkapan Idiomatik',
    // ── Homepage Eyebrow Labels ───────────────────────
    'Hangul Basics · 한글 기초': 'Dasar-dasar Hangul · 한글 기초',
    'Korean Grammar · 문법': 'Tata Bahasa Korea · 문법', 'Vocabulary · 어휘': 'Kosakata · 어휘',
    'Pronunciation · 발음': 'Pelafalan · 발음',
    'Korean Food · 음식': 'Kuliner Korea · 음식', 'K-Beauty · 뷰티': 'K-Beauty · 뷰티',
    'K-Drama · 드라마': 'K-Drama · 드라마', 'K-Pop Lyrics · 가사': 'Lirik K-Pop · 가사',
    'TOPIK Prep · 토픽 준비': 'Persiapan TOPIK · 토픽 준비',
    'Flashcards · 플래시카드': 'Kartu Hafalan · 플래시카드',
    'Start Here · 여기서 시작': 'Mulai di Sini · 여기서 시작',
    'Daily Vocabulary · 오늘의 단어': 'Kosakata Harian · 오늘의 단어',
    'Travel Guide · 여행': 'Panduan Wisata · 여행', 'Blog · 블로그': 'Blog · 블로그',
    'About Us · 소개': 'Tentang Kami · 소개', 'Contact · 연락처': 'Kontak · 연락처',
    'Seoul · 서울': 'Seoul · 서울', 'Busan · 부산': 'Busan · 부산', 'Jeju · 제주': 'Jeju · 제주',
    'Privacy': 'Privasi', 'Terms': 'Ketentuan', 'Terms of Service': 'Ketentuan Layanan',
    'K-FOOD · 한국 음식': 'K-KULINER · 한국 음식',
    // ── Food Page Stats ───────────────────────────────
    'Charcoal grill (best)': 'Panggang arang (terbaik)', 'Side dishes (free refill)': 'Lauk pendamping (isi ulang gratis)',
    'Lettuce wrap style': 'Gaya bungkus selada',
    // ── Lesson Header Meta ────────────────────────────
    'About this lesson': 'Tentang pelajaran ini', 'Korean Grammar': 'Tata Bahasa Korea',
    '✏️ Beginner · Lesson 1': '✏️ Pemula · Pelajaran 1',
    '📐 Intermediate · Lesson 7': '📐 Menengah · Pelajaran 7', '60 min read': '60 menit membaca',
    'Alphabet': 'Alfabet', '📐 Intermediate · Lesson 5': '📐 Menengah · Pelajaran 5',
    '🎯 26 Stages · 70 Steps': '🎯 26 Tahap · 70 Langkah',
    '📊 Beginner–Advanced': '📊 Pemula–Mahir', '⏱️ ~90 min': '⏱️ ~90 menit',
    '⚡ XP + Streak system': '⚡ Sistem XP + Beruntun',
    '📝 Advanced · Lesson 12': '📝 Mahir · Pelajaran 12', '✍️ Essay Structure Guide': '✍️ Panduan Struktur Esai',
    '📊 Advanced': '📊 Mahir', '🔖 Writing': '🔖 Menulis', '🔗 Connective Grammar': '🔗 Tata Bahasa Penghubung',
    '💼 Advanced · Lesson 13': '💼 Mahir · Pelajaran 13', '🏢 Workplace Expressions': '🏢 Ungkapan Tempat Kerja',
    '🔖 Professional': '🔖 Profesional', '🤝 Business Etiquette': '🤝 Etika Bisnis',
    '📜 Advanced · Lesson 14': '📜 Mahir · Pelajaran 14', '📜 Hanja (한자) Roots': '📜 Akar Kata Hanja (한자)',
    '🔖 History & Literature': '🔖 Sejarah & Sastra', '🏛️ Historical Korean Texts': '🏛️ Teks Sejarah Korea',
    '💬 All Levels · 40 Dialogues': '💬 Semua Level · 40 Dialog',
    '💬 40 Full Dialogues': '💬 40 Dialog Lengkap', '📊 All Levels': '📊 Semua Level',
    '🔖 Real-world Korean': '🔖 Bahasa Korea Dunia Nyata', '🔊 Audio on Every Line': '🔊 Audio di Setiap Baris',
    // ── Lesson Header — Shared Meta ───────────────────
    'Korean': 'Bahasa Korea', 'Expressing': 'Mengungkapkan', 'Nouns': 'Kata Benda',
    '📊 Intermediate': '📊 Menengah', '📊 Beginner–Intermediate': '📊 Pemula–Menengah',
    '🎯 6 Stages · 84 Steps': '🎯 6 Tahap · 84 Langkah',
    '🎯 5 Stages · 61 Steps': '🎯 5 Tahap · 61 Langkah',
    '🎯 6 Stages · 68 Steps': '🎯 6 Tahap · 68 Langkah',
    '⏱️ ~60–90 min': '⏱️ ~60–90 menit', '⏱️ ~50 min': '⏱️ ~50 menit', '⏱️ ~60 min': '⏱️ ~60 menit',
    '⏱ 30 min': '⏱ 30 menit', '⏱ 28 min': '⏱ 28 menit', '⏱ 29 min': '⏱ 29 menit',
    '🔊 Audio on every word': '🔊 Audio di setiap kata',
    '🔊 Audio on every phrase': '🔊 Audio di setiap frasa',
    '🔊 Audio on every form': '🔊 Audio di setiap bentuk',
    '4 stages with listen-and-repeat audio and quizzes throughout': '4 tahap dengan audio dengar-dan-ulangi serta kuis di sepanjang pelajaran',
    // ── Lesson Header — Hangul ────────────────────────
    'Learn Hangul in 1 Hour:': 'Belajar Hangul dalam 1 Jam:',
    'Created in 1443 by King Sejong the Great': 'Diciptakan pada 1443 oleh Raja Sejong yang Agung',
    'Phonetic alphabet — each symbol = one sound': 'Alfabet fonetik — setiap simbol = satu bunyi',
    '6 stages to cover every character': '6 tahap untuk mencakup semua karakter',
    'Most learners finish in under 90 minutes': 'Sebagian besar pembelajar selesai dalam kurang dari 90 menit',
    // ── Lesson Header — Syllable Blocks ──────────────
    '🔷 Beginner · Lesson 2': '🔷 Pemula · Pelajaran 2',
    'Korean Syllable Blocks:': 'Blok Suku Kata Korea:',
    'Every syllable is a compact square block — not a horizontal letter string': 'Setiap suku kata adalah blok kotak yang ringkas — bukan deretan huruf horizontal',
    'Each block holds exactly 1 vowel plus up to 2 consonants': 'Setiap blok berisi tepat 1 vokal ditambah hingga 2 konsonan',
    '4 structural patterns: CV, V, CVC, VC — all follow the same rules': '4 pola struktur: CV, V, CVC, VC — semua mengikuti aturan yang sama',
    'Master the block structure and you can sound out any Korean word': 'Kuasai struktur blok dan Anda bisa mengeja kata Korea apa pun',
    // ── Lesson Header — Pronunciation ────────────────
    '8 sound change rules — why Korean spelling and pronunciation differ': '8 aturan perubahan bunyi — mengapa ejaan dan pelafalan Korea berbeda',
    'Batchim, liaison, assimilation, tensification, palatalization, and more': 'Batchim, liaison, asimilasi, tensifikasi, palatalisasi, dan lainnya',
    'Fix the 6 most common mistakes English speakers make': 'Perbaiki 6 kesalahan paling umum yang dibuat penutur bahasa Inggris',
    'Audio examples on every step — tap any word to hear it': 'Contoh audio di setiap langkah — ketuk kata apa pun untuk mendengarnya',
    // ── Lesson Header — Grammar ───────────────────────
    'Korean Grammar:': 'Tata Bahasa Korea:',
    'SOV word order — the verb always comes last': 'Urutan kata SOV — kata kerja selalu di akhir',
    'Particles replace rigid word-position rules': 'Partikel menggantikan aturan posisi kata yang kaku',
    '26 stages: sentences to advanced patterns': '26 tahap: dari kalimat hingga pola tingkat lanjut',
    'Most learners complete in under 90 minutes': 'Sebagian besar pembelajar selesai dalam kurang dari 90 menit',
    // ── Lesson Header — Nouns ────────────────────────
    '🏠 Beginner · Lesson 5': '🏠 Pemula · Pelajaran 5', 'Common Korean': 'Bahasa Korea Umum',
    'Master people, family, place, time, and object nouns in Korean': 'Kuasai kata benda orang, keluarga, tempat, waktu, dan objek dalam bahasa Korea',
    'Learn how Korean counters (개, 명, 잔) work with numbers': 'Pelajari cara kata bantu bilangan Korea (개, 명, 잔) bekerja dengan angka',
    'Understand the possessive marker 의 and polite vs casual forms': 'Pahami penanda kepemilikan 의 dan bentuk sopan vs santai',
    // ── Lesson Header — Pronouns ─────────────────────
    '👥 Beginner · Lesson 4': '👥 Pemula · Pelajaran 4',
    'Learn polite 저 vs casual 나, and why Korean often drops pronouns entirely': 'Pelajari 저 yang sopan vs 나 yang santai, dan mengapa bahasa Korea sering menghilangkan kata ganti sepenuhnya',
    'Understand why 당신 is rarely used and how to address people naturally': 'Pahami mengapa 당신 jarang digunakan dan cara menyapa orang secara alami',
    'Master 우리 (our/my), demonstratives (이것·그것·저것), and question words': 'Kuasai 우리 (kami/saya), kata tunjuk (이것·그것·저것), dan kata tanya',
    // ── Lesson Header — Vocabulary ────────────────────
    '🗂 21 Categories': '🗂 21 Kategori',
    '🔊 Audio on every card': '🔊 Audio di setiap kartu',
    'Covers 500+ core Korean words across 21 categories': 'Mencakup 500+ kata inti bahasa Korea dalam 21 kategori',
    'Bite-sized steps with instant audio — tap any card to hear it': 'Langkah-langkah singkat dengan audio instan — ketuk kartu apa pun untuk mendengarnya',
    'Quizzes after every category to lock in your memory': 'Kuis setelah setiap kategori untuk mengunci ingatan Anda',
    'Most learners finish each category in under 15 minutes': 'Sebagian besar pembelajar menyelesaikan setiap kategori dalam kurang dari 15 menit',
    // ── Hangul Page ───────────────────────────────────
    '✏️ Starter · Lesson 1': '✏️ Pemula · Pelajaran 1', 'Hangul Alphabet:': 'Alfabet Hangul:',
    '⏱ 45 min read': '⏱ 45 menit membaca', '📊 Beginner': '📊 Pemula',
    '🔖 Hangul Basics · 한글 기초': '🔖 Dasar-dasar Hangul · 한글 기초',
    '🔡 Syllable Block Patterns': '🔡 Pola Blok Suku Kata',
    '📘 Common Compound Batchim Examples': '📘 Contoh Batchim Ganda Umum',
    '👁 18,204 views': '👁 18.204 dilihat',
    'What is Hangul? (한글이란?)': 'Apa itu Hangul? (한글이란?)',
    'Basic Vowels (기본 모음)': 'Vokal Dasar (기본 모음)', 'Hangul at a Glance': 'Hangul Sekilas',
    'Basic Consonants': 'Konsonan Dasar', 'Basic Vowels': 'Vokal Dasar',
    'Double Consonants': 'Konsonan Ganda', 'Compound Vowels': 'Vokal Majemuk', 'Fun Fact': 'Fakta Menarik',
    'Why does ㅇ appear at the start?': 'Mengapa ㅇ muncul di awal?',
    'Vowel Shape Mnemonics': 'Mnemonik Bentuk Vokal', 'About Hangul (한글)': 'Tentang Hangul (한글)',
    'Basic Vowels (모음)': 'Vokal Dasar (모음)',
    'Compound Vowels (복합 모음)': 'Vokal Majemuk (복합 모음)',
    'Basic Consonants (자음)': 'Konsonan Dasar (자음)', 'Syllable Blocks (음절)': 'Blok Suku Kata (음절)',
    'Tense (Double) Consonants — 쌍자음': 'Konsonan Tegang (Ganda) — 쌍자음',
    'Compound Batchim (겹받침)': 'Batchim Ganda (겹받침)',
    'Aspirated Consonants — 거센소리': 'Konsonan Aspirasi — 거센소리', 'Quick Practice Quiz': 'Kuis Latihan Cepat',
    'Did you know?': 'Tahukah Anda?', 'Vowel Harmony': 'Harmoni Vokal', 'Reading Practice': 'Latihan Membaca',
    'The Tissue Test': 'Tes Tisu', '10 basic vowels': '10 vokal dasar',
    '11 compound vowels': '11 vokal majemuk', '14 basic consonants': '14 konsonan dasar',
    '5 tense consonants': '5 konsonan tegang', '5 aspirated consonants': '5 konsonan aspirasi',
    'October 9 is Hangul Day (한글날) in South Korea — a national holiday celebrating the invention of the alphabet in 1443.': '9 Oktober adalah Hari Hangul (한글날) di Korea Selatan — hari libur nasional untuk merayakan penciptaan alfabet pada tahun 1443.',
    'Structure': 'Struktur', 'Example': 'Contoh', 'Reading': 'Bacaan', 'Meaning': 'Arti',
    'Consonant + Vowel': 'Konsonan + Vokal', 'go (verb stem)': 'pergi (akar kata kerja)',
    'Consonant + Vowel + Consonant': 'Konsonan + Vokal + Konsonan', 'Korean (prefix)': 'Korea (awalan)',
    'Silent ㅇ + Vowel': 'ㅇ diam + Vokal', 'ah! (exclamation)': 'ah! (seruan)',
    'Batchim': 'Batchim', 'Example Word': 'Contoh Kata', 'Note': 'Catatan', 'to read': 'membaca',
    'to sit': 'duduk', 'life': 'kehidupan',
    'k (aspirated)': 'k (aspirasi)', 't (aspirated)': 't (aspirasi)',
    'p (aspirated)': 'p (aspirasi)', 'ch (aspirated)': 'ch (aspirasi)',
    '← Home': '← Beranda', 'Mark as Complete ✓': 'Tandai Selesai ✓', 'Syllable Blocks →': 'Blok Suku Kata →',
    // ── Grammar Page ──────────────────────────────────
    'Word Order — SOV Structure (어순)': 'Urutan Kata — Struktur SOV (어순)',
    'Korean Particles (조사)': 'Partikel Bahasa Korea (조사)', 'Particle Practice': 'Latihan Partikel',
    'Speech Levels (존댓말 vs 반말)': 'Tingkat Kesopanan Bahasa (존댓말 vs 반말)',
    'Present Tense (-아요/-어요)': 'Bentuk Waktu Sekarang (-아요/-어요)',
    'Past Tense (-았어요/-었어요)': 'Bentuk Waktu Lampau (-았어요/-었어요)',
    'Future Tense (-을 거예요/-ㄹ 거예요)': 'Bentuk Waktu Depan (-을 거예요/-ㄹ 거예요)',
    'Making Sentences Negative (부정문)': 'Membuat Kalimat Negatif (부정문)',
    'Forming Questions (의문문)': 'Membentuk Pertanyaan (의문문)',
    'WH- Question Words': 'Kata Tanya WH-',
    'Essential Sentence Patterns (문형)': 'Pola Kalimat Penting (문형)',
    'Connectors: 그리고, 그래서, 그렇지만, 그런데': 'Kata Sambung: 그리고, 그래서, 그렇지만, 그런데',
    'And, With: -하고, -(이)랑': 'Dan, Dengan: -하고, -(이)랑',
    'To/From Someone: -한테, -한테서': 'Kepada/Dari Seseorang: -한테, -한테서',
    'Telling Time (시간 말하기)': 'Menyebutkan Waktu (시간 말하기)',
    'Counters (단위 명사)': 'Kata Bantu Bilangan (단위 명사)',
    'Present Progressive: -고 있어요': 'Present Progressive: -고 있어요',
    'Particle': 'Partikel', 'Function': 'Fungsi', 'Rule': 'Aturan', 'Level': 'Level',
    'When to Use': 'Kapan Digunakan', 'Dictionary Form': 'Bentuk Kamus', 'Stem': 'Akar Kata',
    'Conjugated': 'Terkonjugasi', 'Counter': 'Kata Bantu Bilangan', 'Used for': 'Digunakan untuk',
    'Vowel': 'Vokal', 'Shape Mnemonic': 'Mnemonik Bentuk', 'Mouth Position': 'Posisi Mulut',
    'Time': 'Waktu', 'Register': 'Ragam Bahasa', 'Used with': 'Digunakan dengan',
    'Formal equivalent': 'Padanan Formal', 'Korean · 한국어': 'Bahasa Korea · 한국어',
    'Translation · 번역': 'Terjemahan · 번역', 'Topic marker': 'Penanda Topik',
    'Subject marker': 'Penanda Subjek', 'Object marker': 'Penanda Objek',
    // ── Pronunciation Page ────────────────────────────
    '🔊 Beginner · Lesson 3': '🔊 Pemula · Pelajaran 3', 'Pronunciation Guide:': 'Panduan Pelafalan:',
    '⏱ 50 min read': '⏱ 50 menit membaca', '🔖 Pronunciation': '🔖 Pelafalan',
    '👁 14,837 views': '👁 14.837 dilihat', 'sound change rules': 'aturan perubahan bunyi',
    'Batchim — Syllable-Final Consonants (받침)': 'Batchim — Konsonan Akhir Suku Kata (받침)',
    '7 possible sounds': '7 kemungkinan bunyi', 'Sound Group': 'Kelompok Bunyi', 'Written As': 'Ditulis Sebagai',
    'Pronounced As': 'Dilafalkan Sebagai', 'Unreleased stops': 'Bunyi Tertahan',
    // ── Syllable Blocks Page ──────────────────────────
    'The ㅇ Placeholder Rule': 'Aturan ㅇ Penanda Tempat',
    'Vertical vs Horizontal Vowels': 'Vokal Vertikal vs Horizontal',
    'Quick Visual Trick': 'Trik Visual Cepat', 'Building Your First Syllables': 'Membangun Suku Kata Pertama Anda',
    'Adding Batchim — The Final Consonant': 'Menambahkan Batchim — Konsonan Akhir',
    'Reading Real Korean Words': 'Membaca Kata Korea Nyata',
    'Practice & Summary': 'Latihan & Ringkasan',
    '5 Rules for Korean Syllable Blocks': '5 Aturan untuk Blok Suku Kata Korea',
    '📝 Self-Test: Identify the Components': '📝 Uji Mandiri: Identifikasi Komponen',
    // ── Pronouns Page ─────────────────────────────────
    'Saying \'You\' in Korean': 'Mengucapkan "Kamu" dalam Bahasa Korea',
    'Third Person & We (그·그녀·우리)': 'Orang Ketiga & Kami (그·그녀·우리)',
    'Demonstrative Pronouns (이·그·저)': 'Kata Ganti Penunjuk (이·그·저)',
    'Question Pronouns (의문대명사)': 'Kata Ganti Tanya (의문대명사)',
    'Pronouns Complete!': 'Kata Ganti Selesai!',
    // ── Emotions Page ─────────────────────────────────
    '😊 Intermediate · Lesson 7': '😊 Menengah · Pelajaran 7',
    'Core Emotions': 'Emosi Inti', 'Expressing Feelings': 'Mengungkapkan Perasaan',
    'Complex Emotions': 'Emosi Kompleks', 'Emotional Phrases': 'Frasa Emosional',
    'Emotions in Korean (감정)': 'Emosi dalam Bahasa Korea (감정)',
    'Emotions Complete!': 'Emosi Selesai!',
    // ── Shopping Page ─────────────────────────────────
    '🛒 Intermediate · Lesson 8': '🛒 Menengah · Pelajaran 8',
    'Shopping Vocabulary': 'Kosakata Belanja', 'In the Store': 'Di Toko', 'Prices & Numbers': 'Harga & Angka',
    'Transactions': 'Transaksi', 'Shopping in Korea (쇼핑)': 'Belanja di Korea (쇼핑)',
    'Shopping Complete!': 'Belanja Selesai!',
    // ── Speech Levels Page ────────────────────────────
    '🗣️ Intermediate · Lesson 6': '🗣️ Menengah · Pelajaran 6',
    '합쇼체 (Formal)': '합쇼체 (Formal)', '해요체 (Polite)': '해요체 (Sopan)',
    '반말 (Casual)': '반말 (Santai)', 'Choosing a Level': 'Memilih Level',
    'Korean Speech Levels Overview': 'Ikhtisar Tingkat Kesopanan Bahasa Korea',
    'Speech Levels Complete!': 'Tingkat Kesopanan Bahasa Selesai!',
    // ── Vocab Browser ───────────────────────────────────
    'Vocab Browser': 'Penjelajah Kosakata',
    'saved to flashcards': 'disimpan ke kartu hafalan',
    'Loading vocabulary…': 'Memuat kosakata…',
    'Search Results': 'Hasil Pencarian', '← Back to Home': '← Kembali ke Beranda',
    'No words match your search.': 'Tidak ada kata yang cocok dengan pencarian Anda.',
    'Failed to load vocabulary.': 'Gagal memuat kosakata.',
    'Search Korean, English, or romanization…': 'Cari bahasa Korea, Inggris, atau romanisasi…',
    '★ Add all in category': '★ Tambahkan semua dalam kategori',
    'Verbs': 'Kata Kerja',
    'Health': 'Kesehatan',
    'Media': 'Media',
    'Proverbs': 'Peribahasa',
    'Academic': 'Akademik',
    // ── Progress system (streak / counters / resume) ────
    '✓ Correct!': '✓ Benar!',
    '✗ Not quite — try again!': '✗ Belum tepat — coba lagi!',
    '{n}-day streak': 'Beruntun {n} hari',
    '{n} steps today': '{n} langkah hari ini',
    'Continue': 'Lanjutkan',
    'Step {n} of {m}': 'Langkah {n} dari {m}',
    'Steps completed': 'Langkah selesai',
    'Words & phrases learned': 'Kata & frasa yang dipelajari',
    'Letters & syllables learned': 'Huruf & suku kata yang dipelajari',
    'Best streak': 'Beruntun terbaik',
    'Start Again': 'Mulai Lagi',
    'Next Lesson →': 'Pelajaran Berikutnya →',
    'Next →': 'Lanjut →',
    'Progress': 'Kemajuan',
    'Reset all progress': 'Atur ulang semua kemajuan',
    '🔥 Daily streak + real progress tracking': '🔥 Beruntun harian + pelacakan kemajuan nyata'
  };
  if (window.LangManager) window.LangManager.register('id', ID);
})();
