'use strict';
(function() {
  const ZH_TW = {
    // ── Navigation & Global UI ─────────────────────────
    'Learn': '學習', 'Quiz': '測驗', 'K-Culture': 'K文化', 'Travel': '旅遊',
    'Search...': '搜尋...', 'Search lessons, vocabulary…': '搜尋課程、單字…',
    '🇰🇷 · Free · For Every Level': '🇰🇷 · 免費 · 適合各程度',
    'Learn Korean': '學韓語', 'Start Learning': '開始學習', 'Explore K-Culture': '探索K文化',
    'Vocabulary Words': '詞彙量', 'Lessons': '課程數', 'Active Learners': '學習人數', '% Free': '% 免費',
    'FEATURES': '功能特色', 'Everything You Need to Learn Korean': '學韓語所需的一切',
    'Start with 한글': '從韓文字母開始', 'Learn Hangul Now →': '立即學韓文字母 →',
    'Hear It': '聽發音', 'More Words': '更多單字', 'Word of the Day': '每日單字',
    'STRUCTURED PATHS · 학습 경로': '系統化學習路徑 · 학습 경로',
    'Choose Your Learning Path': '選擇你的學習路徑',
    'Beginner': '初級', 'Intermediate': '中級', 'Advanced': '高級',
    'Start Beginner Path →': '開始初級路徑 →', 'Start Intermediate Path →': '開始中級路徑 →',
    'Start Advanced Path →': '開始高級路徑 →', 'POPULAR': '熱門',
    'Beginner–Intermediate': '初級～中級', 'Intermediate–Advanced': '中級～高級',
    'Beg–Int': '初中級',
    // ── K-Culture & Home ──────────────────────────────
    'K-CULTURE': 'K文化', 'K-CULTURE · 한국 문화': 'K文化 · 한국 문화',
    'Experience Korea Beyond Language': '超越語言，體驗韓國',
    'Explore All K-Culture Content →': '查看所有K文化內容 →',
    'TRAVEL · 여행': '旅遊 · 여행', 'Explore Korea': '探索韓國',
    'View Full Travel Guide →': '查看完整旅遊指南 →',
    'PRACTICE · 연습': '練習 · 연습',
    '10 progressive levels · multiple choice · covers Hangul, Grammar & Vocabulary': '10個進階關卡 · 選擇題 · 涵蓋韓文字母、文法與詞彙',
    'Choose a Level': '選擇關卡', 'questions': '題', '← All Levels': '← 所有關卡',
    'Try Again': '再試一次', 'Next Level': '下一關', 'All Levels': '全部關卡',
    'Next Level →': '下一關 →',
    // ── Travel ────────────────────────────────────────
    '🇰🇷 · South Korea Travel Guide · 여행 안내': '🇰🇷 · 韓國旅遊指南 · 여행 안내',
    'South Korea Travel Guide': '韓國旅遊指南',
    'Population': '人口', 'UNESCO Sites': '聯合國教科文組織遺址',
    'Great to visit': '適合造訪', 'Visa-free nations': '免簽國家',
    'EXPLORE THE GUIDES · 가이드 탐색': '探索指南 · 가이드 탐색',
    'Plan Your Perfect Korea Trip': '規劃你的完美韓國之旅',
    'TOP DESTINATIONS · 인기 여행지': '熱門目的地 · 인기 여행지',
    'Where Will You Explore?': '你想探索哪裡？',
    'ESSENTIAL PHRASES · 필수 표현': '必備旅遊短語 · 필수 표현',
    'Travel Korean Phrasebook': '旅遊韓語短語集',
    'TRANSPORTATION · 교통': '交通 · 교통', 'Getting Around Korea': '韓國交通方式',
    'FOOD TOUR · 음식 여행': '美食之旅 · 음식 여행', 'Regional Korean Specialties': '韓國各地特色料理',
    'CULTURAL ETIQUETTE · 예절': '文化禮儀 · 예절', 'Korean Cultural Tips': '韓國文化小提示',
    'TRAVEL APPS · 여행 앱': '旅遊App · 여행 앱', 'Essential Apps for Korea Travel': '韓國旅遊必備App',
    'READY TO LEARN?': '準備好學習了嗎？', 'Start Speaking Korean Today': '今天就開始說韓語',
    'Start Learning Korean →': '開始學韓語 →', 'Plan Your Trip': '規劃你的旅程',
    'K-Pop': 'K-Pop', 'K-Drama': '韓劇', 'K-Beauty': 'K-Beauty', 'All': '全部',
    // ── Footer & Company ──────────────────────────────
    'Learn · 학습': '學習 · 학습', 'K-Culture · 문화': 'K文化 · 문화',
    'Company · 회사': '關於 · 회사', 'Explore': '探索', 'Company': '公司',
    'Hangul Alphabet': '韓文字母', 'Grammar': '文法', 'Vocabulary': '詞彙',
    'Travel Guide': '旅遊指南', 'About Us': '關於我們',
    'Contact': '聯絡我們', 'Privacy Policy': '隱私政策', 'Terms of Use': '使用條款',
    'Made with ❤️ for Korean learners worldwide.': '為全球韓語學習者用心製作 ❤️',
    '🇰🇷 학습을 즐기세요! (Enjoy your learning!)': '🇰🇷 학습을 즐기세요！（享受你的學習！）',
    'Home': '首頁', 'Hangul': '韓文字母',
    'A free Korean language learning platform — combining language study with K-culture, travel guides, and real-world practice. For learners of every level, worldwide.': '免費韓語學習平台 — 結合語言學習、K文化、旅遊指南與實際練習，適合全球各程度的學習者。',
    'A free Korean language learning platform for learners of every level, worldwide.': '免費韓語學習平台，適合全球各程度的學習者。',
    '© 2026 한국어 학교. Made with ❤️ for Korean learners worldwide.': '© 2026 한국어 학교. 為全球韓語學習者用心製作 ❤️',
    // ── Sidebar Dividers ──────────────────────────────
    'Getting Started': '入門', 'Tools': '工具',
    'CATEGORIES · 카테고리': '分類 · 카테고리', 'DEEP DIVES · 심층 탐구': '深度探索 · 심층 탐구',
    // ── Learn Sidebar ─────────────────────────────────
    'Introduction': '介紹', 'Syllable Blocks': '音節積木', 'Pronunciation Guide': '發音指南',
    'Vocab': '詞彙', 'Greetings': '問候語', 'Numbers': '數字', 'Family': '家族',
    'Food & Drink': '飲食', 'Colors': '顏色', 'Days & Time': '星期與時間', 'Places': '地點',
    'Emotions': '情緒', 'Body Parts': '身體部位', 'Shopping': '購物', 'Weather': '天氣',
    'Verbs & Actions': '動詞與動作', 'Adjectives': '形容詞', 'Workplace': '職場',
    'Health & Medicine': '健康與醫療', 'Media & K-Culture': '媒體與K文化',
    'Proverbs & Idioms': '諺語與慣用語', 'Academic Korean': '學術韓語',
    'News & Society': '新聞與社會', 'Konglish': '韓式英語', 'Pronouns': '代名詞',
    'Common Nouns': '常用名詞', 'Sentence Structure': '句子結構', 'Korean Particles': '韓語助詞',
    'Verb Conjugation': '動詞變化', 'Question Forms': '疑問句型', 'Connectors': '連接詞',
    'And, With': '和、一起', 'To/From Someone': '給某人／來自某人', 'Telling Time': '說時間',
    'Counters': '數量詞', 'Present Progressive': '現在進行式', 'Self Introduction': '自我介紹',
    'Dates and Months': '日期與月份', 'Degree Adverbs': '程度副詞',
    'Nominalizer -는 것': '名詞化 -는 것', 'Comparatives': '比較級',
    'Still, Already': '還、已經', 'Someone, Something': '某人、某事',
    'Imperative -(으)세요': '命令句 -(으)세요', 'Don\'t: -지 마세요': '不要：-지 마세요',
    'Method: -(으)로': '方法：-(으)로', 'Good/Poor At': '擅長／不擅長',
    '-도 Advanced Uses': '도（進階用法）', 'Formal vs Informal': '正式 vs 非正式',
    'Expressing Emotions': '表達情緒', 'Shopping Phrases': '購物短語', 'Writing Essays': '寫作文',
    'Business Korean': '商務韓語', 'Classical Korean': '古典韓語', 'Korean Dialogues': '韓語對話',
    'Flashcards': '字卡',
    // ── Culture Sidebar ───────────────────────────────
    'K-Movie': '韓國電影', 'K-Food': '韓食', 'K-Fashion': 'K-Fashion',
    'Korean Thing': '韓國特有文化', 'K-Gaming': 'K-電競', 'K-Sports': 'K-運動',
    'K-Pop, K-Drama, food, beauty, fashion, gaming, sports & traditions.': 'K-Pop、韓劇、美食、美妝、時尚、電競、運動與傳統文化。',
    'K-Pop History': 'K-Pop歷史', 'Agencies': '經紀公司', 'Generations': '世代', 'Genres': '曲風',
    'Variety Shows': '綜藝節目', 'Film & Acting': '電影與表演', 'Idol Phrases': '偶像常用語',
    'Fan Slang': '粉絲用語', 'Fan Chants': '粉絲應援口號', 'Drama History': '韓劇歷史',
    'Drama Genres': '韓劇類型', 'Must-Watch Dramas': '必看韓劇', 'K-Drama Tropes': '韓劇套路',
    'Speech Levels': '敬語等級', 'Dialogue Practice': '對話練習',
    'Fan Culture & Slang': '粉絲文化與用語', 'Movie History': '電影歷史',
    'Movie Genres': '電影類型', 'Must-Watch Films': '必看電影', 'Directors': '導演',
    'Iconic Lines': '經典台詞', 'Fan Culture': '粉絲文化',
    'K-Food Goes Global': '韓食走向世界', 'Foods That Went Global': '走向世界的韓食',
    'K-Food Timeline': '韓食發展史', 'Essential Dishes': '必吃料理',
    'World-Famous Chefs': '世界知名主廚', 'Ordering & Dining': '點餐與用餐',
    'Street Food': '街頭美食', 'Food Culture & Drinking': '飲食文化與飲酒文化',
    'Ramyeon Guide': '韓國拉麵指南', 'Mandu Guide': '韓式餃子指南',
    'Chicken Guide': '炸雞指南', 'K-BBQ Guide': '韓式烤肉指南', 'Kimchi Guide': '泡菜指南',
    'K-Beauty Goes Global': 'K-Beauty走向世界', 'K-Beauty Timeline': 'K-Beauty發展史',
    'Iconic Brands': '代表品牌', 'Beauty Vocabulary': '美妝詞彙', '10-Step Skincare': '10步驟護膚',
    'Key Ingredients': '關鍵成分', 'Beauty Trends': '美妝趨勢', 'Makeup Philosophy': '妝容哲學',
    'Skin Clinic Culture': '醫美文化', 'K-Beauty Dialogue': 'K-Beauty對話',
    'K-Fashion Global': 'K-Fashion走向世界', 'Fashion Icons': '時尚指標',
    'Fashion Timeline': '時尚發展史', 'Style Aesthetics': '風格美學', 'Idol Fashion': '偶像時尚',
    'Seoul Fashion Week': '首爾時裝週', 'Fashion Vocabulary': '時尚詞彙',
    'Fashion Districts': '時尚商圈', 'Shopping Dialogue': '購物對話',
    'Hanbok & Traditional Fashion': '韓服與傳統服飾', 'Rice Obsession': '韓國人的白飯情結',
    'Youth Protection Laws': '青少年保護法', 'Fast Delivery Culture': '超速外送文化',
    'Invasive Species Crisis': '入侵物種危機', 'Table Call Culture': '桌邊呼叫文化',
    'Public Transport': '大眾交通', 'Jjimjilbang': '汗蒸幕', 'Plastic Surgery Culture': '整形文化',
    'Outdoor Drinking': '戶外飲酒', 'Jeonse Housing': '전세住宅制度',
    'Traditions & Holidays': '傳統與節日', '100 Korean Proverbs': '韓國諺語100句',
    'K-Gaming Stats': 'K-電競數據', 'Gaming Timeline': '電競發展史',
    'Gaming Legends': '電競傳奇人物', 'Iconic Games': '經典遊戲', 'Streaming Culture': '直播文化',
    'PC Bang Culture': 'PC房文化', 'PC방 Culture': 'PC房文化', 'Esports Leagues': '電競聯賽',
    'Gamer Slang': '玩家用語', 'Gaming Vocabulary': '遊戲詞彙', 'Sports Overview': '運動概覽',
    'Football Heroes': '足球英雄', 'Baseball Heroes': '棒球英雄', 'Marathon Legends': '馬拉松傳奇',
    'Individual Legends': '個人傳奇', 'Traditional Sports': '傳統運動', 'Cheer Chants': '應援口號',
    // ── Travel Sidebar ────────────────────────────────
    'Travel Guide · 여행 안내': '旅遊指南 · 여행 안내', 'South Korea': '韓國',
    'By Days · 일수별': '依天數 · 일수별', '1 Day Trip · 당일치기': '一日遊 · 당일치기',
    '2 Days · 1박 2일': '兩天一夜 · 1박 2일', '3 Days · 2박 3일': '三天兩夜 · 2박 3일',
    '5 Days · 4박 5일': '五天四夜 · 4박 5일', '1 Week · 일주일': '一週 · 일주일',
    '10 Days': '十天', '2 Weeks · 2주': '兩週 · 2주', '1 Month+ · 한달': '一個月以上 · 한달',
    'By City · 도시별': '依城市 · 도시별', 'Seoul · 서울': '首爾 · 서울',
    'Incheon · 인천': '仁川 · 인천', 'Busan · 부산': '釜山 · 부산',
    'Suwon · 수원': '水原 · 수원', 'Jeju · 제주도': '濟州島 · 제주도',
    'Gyeongju · 경주': '慶州 · 경주', 'Other Cities': '其他城市',
    'By Theme · 테마별': '依主題 · 테마별', 'Food Tour · 음식 여행': '美食之旅 · 음식 여행',
    'Events & Festivals · 이벤트': '活動與節慶 · 이벤트', 'Sightseeing · 관광': '觀光 · 관광',
    'Cross-Country · 장거리': '長距離行程 · 장거리',
    '📋 Trip Planner · 여행 계획표': '📋 旅程規劃 · 여행 계획표',
    'Day-by-Day Itineraries': '逐日行程', 'City Travel Guides': '城市旅遊指南',
    'Themed Travel': '主題旅遊', 'Bus': '公車', 'Subway': '地鐵', 'Taxi': '計程車',
    'KTX High-speed Rail': 'KTX高速鐵路', 'Age': '年齡', 'Bowing': '鞠躬禮',
    'Drinking': '飲酒', 'Eating': '飲食', 'Quiet': '保持安靜', 'Shoes': '鞋子',
    'Tipping': '小費', 'Two Hands': '雙手',
    'International': '國際', 'Politics': '政治', 'Economy': '經濟', 'Society': '社會',
    'Science': '科學', 'Culture': '文化', 'Sports': '運動', 'Education': '教育',
    'Environment': '環境',
    // ── Homepage Descriptions (hero, bento, cards, travel) ─
    'Discover the beauty of Korea through language, culture, K-pop, travel, and cuisine — with free lessons designed for learners worldwide.': '透過語言、文化、K-Pop、旅遊與美食發現韓國之美 — 為全球學習者打造的免費課程。',
    'Learn the Korean alphabet in just 2 hours. 한글 (Hangul) is remarkably logical — once you know the 24 basic letters, you can read anything.': '只需2小時學會韓語字母。한글（韓文字母）邏輯性極強 — 一旦掌握24個基本字母，你就能閱讀任何東西。',
    'Learn Korean naturally through your favourite songs. Line-by-line breakdowns with vocabulary, grammar notes, and pronunciation guides.': '透過你最喜歡的歌曲自然學習韓語。逐行拆解，附詞彙、文法筆記和發音指南。',
    'Pick up everyday Korean from your favourite dramas. Contextual vocabulary lists organised by show, genre, and proficiency level.': '從你最喜歡的韓劇中汲取日常韓語。按劇集、類型和程度整理的情境詞彙列表。',
    'From 김치 (kimchi) to 삼겹살 (samgyeopsal) — explore the rich vocabulary of Korean cuisine with pronunciation and cultural context.': '從김치（泡菜）到삼겹살（五花肉） — 探索韓國料理的豐富詞彙，附發音和文化背景。',
    'Whether you are just starting or aiming for fluency, we have a clear roadmap to take you there step by step.': '無論你是剛開始還是追求流利，我們有清晰的路線圖帶你一步步達成目標。',
    'Language is the gateway — immerse yourself in Korean pop culture, food, and beauty to supercharge your learning.': '語言是入口 — 深入韓國流行文化、美食和美妝，讓你的學習事半功倍。',
    'From BTS to BLACKPINK — the most common Korean words and phrases used by your favourite K-Pop artists, with pronunciation guides.': '從BTS到BLACKPINK — 你最喜歡的K-Pop藝人最常用的韓語單字和短語，附發音指南。',
    'Korean dramas are packed with emotional vocabulary. Learn how characters express joy, sadness, anger, and love in authentic Korean.': '韓劇充滿豐富的情感詞彙。學習劇中角色如何用道地韓語表達喜悅、悲傷、憤怒與愛意。',
    'Essential phrases for ordering food, asking for the bill, and navigating a Korean restaurant menu with confidence.': '在韓國餐廳點餐、要帳單及看懂菜單的必備短語，讓你自信開口不再尷尬。',
    'Explore the world of K-Beauty with essential vocabulary for skincare routines, cosmetics, and Korean beauty trends.': '探索K-Beauty世界，學習護膚程序、化妝品與韓國美妝趨勢的必備詞彙。',
    'Learn the language of every destination. From bustling Seoul to the serene shores of Jeju — your AI travel guide is ready.': '學習每個目的地的語言。從繁華的首爾到寧靜的濟州島海岸 — 你的旅遊指南隨時候命。',
    "South Korea's dazzling capital — from the ancient palaces of Gyeongbokgung to the neon streets of Gangnam and Hongdae.": '韓國璀璨的首都 — 從景福宮的古老宮殿到江南與弘大的霓虹街道。',
    "Korea's vibrant port city with stunning beaches, fresh seafood markets, and a unique dialect worth discovering.": '韓國充滿活力的港口城市，有壯麗的海灘、新鮮的海鮮市場，以及值得探索的獨特方言。',
    "Korea's paradise island — volcanic landscapes, pristine beaches, tangerine groves, and the famous haenyeo diving culture.": '韓國的天堂島嶼 — 火山地貌、純淨海灘、橘子園，以及著名的海女潛水文化。',
    // ── Homepage Place Names & Quiz ───────────────────
    'Seoul': '首爾', 'Busan': '釜山', 'Jeju Island': '濟州島',
    'Test Your Korean': '測試你的韓語', 'Explore →': '探索 →',
    // ── Homepage Cards & Labels ───────────────────────
    'K-Pop Lyrics Learning': 'K-Pop歌詞學習', 'K-Drama Vocabulary': '韓劇詞彙',
    'Korean Food Dictionary': '韓食辭典',
    'Master Korean Emotions Through K-Drama': '透過韓劇掌握韓語情緒表達',
    'Order Like a Local: Restaurant Korean': '像當地人一樣點餐：餐廳韓語',
    'Beauty & Skincare Vocabulary in Korean': '韓語美妝與護膚詞彙',
    'K-Pop Stars\' Korean Phrases You Need to Know': '你必須知道的K-Pop明星韓語短語',
    'Read →': '閱讀 →', 'Hello / Good day': '你好 / 美好的一天',
    'annyeonghaseyo': 'ㄢ ㄋㄧㄥ ㄏㄚ ㄙㄝ ㄧㄠ',
    // ── Learning Path Checklist ───────────────────────
    '✓ Hangul Alphabet': '✓ 韓文字母', '✓ Basic Vowels & Consonants': '✓ 基本母音與子音',
    '✓ Syllable Blocks': '✓ 音節積木', '✓ Essential Vocabulary': '✓ 基本詞彙',
    '✓ Basic Greetings': '✓ 基本問候語', '✓ Korean Grammar (SOV)': '✓ 韓語文法（SOV）',
    '✓ Particles & Conjugation': '✓ 助詞與動詞變化', '✓ Speech Levels': '✓ 敬語等級',
    '✓ 300+ Vocabulary Words': '✓ 300個以上詞彙', '✓ Real Dialogues': '✓ 真實對話',
    '✓ Business Korean': '✓ 商務韓語', '✓ Classical Korean': '✓ 古典韓語',
    '✓ Essay Writing': '✓ 寫作文', '✓ TOPIK Preparation': '✓ TOPIK備考',
    '✓ Idiomatic Expressions': '✓ 慣用表達',
    // ── Homepage Eyebrow Labels ───────────────────────
    'Hangul Basics · 한글 기초': '韓文字母基礎 · 한글 기초',
    'Korean Grammar · 문법': '韓語文法 · 문법', 'Vocabulary · 어휘': '詞彙 · 어휘',
    'Pronunciation · 발음': '發音 · 발음',
    'Korean Food · 음식': '韓食 · 음식', 'K-Beauty · 뷰티': 'K-Beauty · 뷰티',
    'K-Drama · 드라마': '韓劇 · 드라마', 'K-Pop Lyrics · 가사': 'K-Pop歌詞 · 가사',
    'TOPIK Prep · 토픽 준비': 'TOPIK備考 · 토픽 준비',
    'Flashcards · 플래시카드': '字卡 · 플래시카드',
    'Start Here · 여기서 시작': '從這裡開始 · 여기서 시작',
    'Daily Vocabulary · 오늘의 단어': '每日詞彙 · 오늘의 단어',
    'Travel Guide · 여행': '旅遊指南 · 여행', 'Blog · 블로그': '部落格 · 블로그',
    'About Us · 소개': '關於我們 · 소개', 'Contact · 연락처': '聯絡我們 · 연락처',
    'Seoul · 서울': '首爾 · 서울', 'Busan · 부산': '釜山 · 부산', 'Jeju · 제주': '濟州 · 제주',
    'Privacy': '隱私', 'Terms': '條款', 'Terms of Service': '服務條款',
    'K-FOOD · 한국 음식': '韓食 · 한국 음식',
    // ── Food Page Stats ───────────────────────────────
    'Charcoal grill (best)': '炭火烤爐（最佳）', 'Side dishes (free refill)': '小菜（免費續加）',
    'Lettuce wrap style': '生菜包肉吃法',
    // ── Lesson Header Meta ────────────────────────────
    'About this lesson': '關於本課', 'Korean Grammar': '韓語文法',
    '✏️ Beginner · Lesson 1': '✏️ 初級 · 第1課',
    '📐 Intermediate · Lesson 7': '📐 中級 · 第7課', '60 min read': '60分鐘閱讀',
    'Alphabet': '字母', '📐 Intermediate · Lesson 5': '📐 中級 · 第5課',
    '🎯 26 Stages · 70 Steps': '🎯 26個階段 · 70個步驟',
    '📊 Beginner–Advanced': '📊 初級～高級', '⏱️ ~90 min': '⏱️ 約90分鐘',
    '⚡ XP + Streak system': '⚡ XP + 連續學習系統',
    '📝 Advanced · Lesson 12': '📝 高級 · 第12課', '✍️ Essay Structure Guide': '✍️ 作文結構指南',
    '📊 Advanced': '📊 高級', '🔖 Writing': '🔖 寫作', '🔗 Connective Grammar': '🔗 連接文法',
    '💼 Advanced · Lesson 13': '💼 高級 · 第13課', '🏢 Workplace Expressions': '🏢 職場表達',
    '🔖 Professional': '🔖 專業', '🤝 Business Etiquette': '🤝 商務禮儀',
    '📜 Advanced · Lesson 14': '📜 高級 · 第14課', '📜 Hanja (한자) Roots': '📜 漢字（한자）語源',
    '🔖 History & Literature': '🔖 歷史與文學', '🏛️ Historical Korean Texts': '🏛️ 韓國古典文獻',
    '💬 All Levels · 40 Dialogues': '💬 所有級別 · 40段對話',
    '💬 40 Full Dialogues': '💬 40段完整對話', '📊 All Levels': '📊 所有級別',
    '🔖 Real-world Korean': '🔖 實用韓語', '🔊 Audio on Every Line': '🔊 每行都有音檔',
    // ── Lesson Header — Shared Meta ───────────────────
    'Korean': '韓語', 'Expressing': '表達', 'Nouns': '名詞',
    '📊 Intermediate': '📊 中級', '📊 Beginner–Intermediate': '📊 初級～中級',
    '🎯 6 Stages · 84 Steps': '🎯 6個階段 · 84個步驟',
    '🎯 5 Stages · 61 Steps': '🎯 5個階段 · 61個步驟',
    '🎯 6 Stages · 68 Steps': '🎯 6個階段 · 68個步驟',
    '⏱️ ~60–90 min': '⏱️ 約60–90分鐘', '⏱️ ~50 min': '⏱️ 約50分鐘', '⏱️ ~60 min': '⏱️ 約60分鐘',
    '⏱ 30 min': '⏱ 30分鐘', '⏱ 28 min': '⏱ 28分鐘', '⏱ 29 min': '⏱ 29分鐘',
    '🔊 Audio on every word': '🔊 每個單字都有音頻',
    '🔊 Audio on every phrase': '🔊 每個短語都有音頻',
    '🔊 Audio on every form': '🔊 每種形式都有音頻',
    '4 stages with listen-and-repeat audio and quizzes throughout': '4個階段，全程搭配跟讀音頻與測驗',
    // ── Lesson Header — Hangul ────────────────────────
    'Learn Hangul in 1 Hour:': '1小時學會韓文字母：',
    'Created in 1443 by King Sejong the Great': '由世宗大王於1443年創制',
    'Phonetic alphabet — each symbol = one sound': '表音字母 — 每個符號代表一個音',
    '6 stages to cover every character': '6個階段，涵蓋所有字母',
    'Most learners finish in under 90 minutes': '大多數學習者在90分鐘內完成',
    // ── Lesson Header — Syllable Blocks ──────────────
    '🔷 Beginner · Lesson 2': '🔷 初級 · 第2課',
    'Korean Syllable Blocks:': '韓語音節積木：',
    'Every syllable is a compact square block — not a horizontal letter string': '每個音節都是緊湊的方塊 — 而非橫向的字母串',
    'Each block holds exactly 1 vowel plus up to 2 consonants': '每個方塊包含恰好1個母音和最多2個子音',
    '4 structural patterns: CV, V, CVC, VC — all follow the same rules': '4種結構模式：CV、V、CVC、VC — 全部遵循相同規則',
    'Master the block structure and you can sound out any Korean word': '掌握積木結構，你就能拼讀任何韓語單字',
    // ── Lesson Header — Pronunciation ────────────────
    '8 sound change rules — why Korean spelling and pronunciation differ': '8種發音變化規則 — 解釋韓語拼寫與發音的差異',
    'Batchim, liaison, assimilation, tensification, palatalization, and more': '收音、連音、同化、激音化、口蓋音化等更多規則',
    'Fix the 6 most common mistakes English speakers make': '糾正英語母語者最常犯的6個錯誤',
    'Audio examples on every step — tap any word to hear it': '每個步驟都有音頻示例 — 點擊任何單字即可收聽',
    // ── Lesson Header — Grammar ───────────────────────
    'Korean Grammar:': '韓語文法：',
    'SOV word order — the verb always comes last': 'SOV語序 — 動詞永遠在最後',
    'Particles replace rigid word-position rules': '助詞取代固定詞序規則',
    '26 stages: sentences to advanced patterns': '26個階段：從句子到進階句型',
    'Most learners complete in under 90 minutes': '大多數學習者在90分鐘內完成',
    // ── Lesson Header — Nouns ────────────────────────
    '🏠 Beginner · Lesson 5': '🏠 初級 · 第5課', 'Common Korean': '常見韓語',
    'Master people, family, place, time, and object nouns in Korean': '掌握韓語中的人物、家族、地點、時間和物品名詞',
    'Learn how Korean counters (개, 명, 잔) work with numbers': '學習韓語量詞（개、명、잔）如何與數字搭配使用',
    'Understand the possessive marker 의 and polite vs casual forms': '理解所有格助詞의，以及敬語與非敬語形式的差別',
    // ── Lesson Header — Pronouns ─────────────────────
    '👥 Beginner · Lesson 4': '👥 初級 · 第4課',
    'Learn polite 저 vs casual 나, and why Korean often drops pronouns entirely': '學習敬語的저與非敬語的나，以及韓語為何常省略代名詞',
    'Understand why 당신 is rarely used and how to address people naturally': '理解為何당신很少使用，以及如何自然稱呼他人',
    'Master 우리 (our/my), demonstratives (이것·그것·저것), and question words': '掌握우리（我們／我的）、指示詞（이것·그것·저것）和疑問詞',
    // ── Lesson Header — Vocabulary ────────────────────
    '🗂 21 Categories': '🗂 21個分類',
    '🔊 Audio on every card': '🔊 每張卡片都有音檔',
    'Covers 500+ core Korean words across 21 categories': '涵蓋21個分類的500+核心韓語單字',
    'Bite-sized steps with instant audio — tap any card to hear it': '單步驟即時音檔 — 點擊任何卡片即可收聽',
    'Quizzes after every category to lock in your memory': '每個分類後有測驗以鞏固記憶',
    'Most learners finish each category in under 15 minutes': '大多數學習者每個分類可在15分鐘內完成',
    // ── Hangul Page ───────────────────────────────────
    '✏️ Starter · Lesson 1': '✏️ 入門 · 第1課', 'Hangul Alphabet:': '韓文字母：',
    '⏱ 45 min read': '⏱ 45分鐘閱讀', '📊 Beginner': '📊 初級',
    '🔖 Hangul Basics · 한글 기초': '🔖 韓文字母基礎 · 한글 기초',
    '🔡 Syllable Block Patterns': '🔡 音節積木規律',
    '📘 Common Compound Batchim Examples': '📘 常見複合收音範例',
    '👁 18,204 views': '👁 18,204 次瀏覽',
    'What is Hangul? (한글이란?)': '什麼是韓文字母？（한글이란？）',
    'Basic Vowels (기본 모음)': '基本母音（기본 모음）', 'Hangul at a Glance': '韓文字母概覽',
    'Basic Consonants': '基本子音', 'Basic Vowels': '基本母音',
    'Double Consonants': '雙重子音', 'Compound Vowels': '複合母音', 'Fun Fact': '趣味知識',
    'Why does ㅇ appear at the start?': '為什麼ㅇ會出現在字首？',
    'Vowel Shape Mnemonics': '母音形狀記憶法', 'About Hangul (한글)': '關於韓文字母（한글）',
    'Basic Vowels (모음)': '基本母音（모음）',
    'Compound Vowels (복합 모음)': '複合母音（복합 모음）',
    'Basic Consonants (자음)': '基本子音（자음）', 'Syllable Blocks (음절)': '音節積木（음절）',
    'Tense (Double) Consonants — 쌍자음': '緊音（雙重子音） — 쌍자음',
    'Compound Batchim (겹받침)': '複合收音（겹받침）',
    'Aspirated Consonants — 거센소리': '送氣音 — 거센소리', 'Quick Practice Quiz': '快速練習測驗',
    'Did you know?': '你知道嗎？', 'Vowel Harmony': '母音和諧', 'Reading Practice': '閱讀練習',
    'The Tissue Test': '衛生紙測試', '10 basic vowels': '10個基本母音',
    '11 compound vowels': '11個複合母音', '14 basic consonants': '14個基本子音',
    '5 tense consonants': '5個緊音', '5 aspirated consonants': '5個送氣音',
    'October 9 is Hangul Day (한글날) in South Korea — a national holiday celebrating the invention of the alphabet in 1443.': '10月9日是韓國的韓文字母日（한글날）— 紀念1443年韓文字母創制的國定假日。',
    'ㅏ and ㅗ are "bright" vowels that pair with -아요 in conjugation. All other vowels are "dark" and pair with -어요. This pattern is consistent throughout the language.': 'ㅏ和ㅗ是「明亮」母音，動詞變化時搭配-아요。其他母音都是「暗沉」母音，搭配-어요。這個規律貫穿整個語言。',
    '한국어 = 한(han) + 국(guk) + 어(eo) = "Korean language". Each syllable block is exactly one beat when spoken aloud. Try tapping the rhythm as you read!': '한국어 = 한(han) + 국(guk) + 어(eo) = 「韓語」。每個音節積木說出來剛好是一拍。試著邊讀邊打節拍！',
    'Hold a tissue in front of your mouth. For aspirated consonants (ㅋㅌㅍㅊ), the tissue should flutter. For regular consonants (ㄱㄷㅂㅈ), it stays still. This is a great way to feel the difference!': '在嘴前拿一張衛生紙。對送氣音（ㅋㅌㅍㅊ），衛生紙會飄動；對一般子音（ㄱㄷㅂㅈ），衛生紙不動。這是感受差異的好方法！',
    'Structure': '結構', 'Example': '例子', 'Reading': '讀法', 'Meaning': '意思',
    'Consonant + Vowel': '子音 + 母音', 'go (verb stem)': '去（動詞詞幹）',
    'Consonant + Vowel + Consonant': '子音 + 母音 + 子音', 'Korean (prefix)': '韓國（前綴）',
    'Silent ㅇ + Vowel': '無音ㅇ + 母音', 'ah! (exclamation)': '啊！（感嘆詞）',
    'Batchim': '收音', 'Example Word': '例字', 'Note': '備注', 'to read': '閱讀',
    'Pronounce ㄱ; ㄹ carries to next syllable before vowel': '發ㄱ音；ㄹ在母音前連音到下一音節',
    'to sit': '坐', 'Pronounce ㄴ; ㅈ carries to next syllable before vowel': '發ㄴ音；ㅈ在母音前連音到下一音節',
    'life': '人生', 'Pronounce ㅁ; ㄹ carries to next syllable before vowel': '發ㅁ音；ㄹ在母音前連音到下一音節',
    'k (aspirated)': 'k（送氣）', 't (aspirated)': 't（送氣）',
    'p (aspirated)': 'p（送氣）', 'ch (aspirated)': 'ch（送氣）',
    '← Home': '← 首頁', 'Mark as Complete ✓': '標記為完成 ✓', 'Syllable Blocks →': '音節積木 →',
    // ── Grammar Page ──────────────────────────────────
    'Word Order — SOV Structure (어순)': '語序 — SOV結構（어순）',
    'Korean Particles (조사)': '韓語助詞（조사）', 'Particle Practice': '助詞練習',
    'Speech Levels (존댓말 vs 반말)': '敬語等級（존댓말 vs 반말）',
    'Present Tense (-아요/-어요)': '現在式（-아요/-어요）',
    'Past Tense (-았어요/-었어요)': '過去式（-았어요/-었어요）',
    'Future Tense (-을 거예요/-ㄹ 거예요)': '未來式（-을 거예요/-ㄹ 거예요）',
    'Making Sentences Negative (부정문)': '否定句的構成（부정문）',
    'Forming Questions (의문문)': '疑問句的構成（의문문）',
    'WH- Question Words': 'WH疑問詞',
    'Essential Sentence Patterns (문형)': '必備句型（문형）',
    'Connectors: 그리고, 그래서, 그렇지만, 그런데': '連接詞：그리고、그래서、그렇지만、그런데',
    'And, With: -하고, -(이)랑': '和、一起：-하고、-(이)랑',
    'To/From Someone: -한테, -한테서': '給某人／來自某人：-한테、-한테서',
    'Telling Time (시간 말하기)': '說時間（시간 말하기）',
    'Counters (단위 명사)': '數量詞（단위 명사）',
    'Present Progressive: -고 있어요': '現在進行式：-고 있어요',
    'Particle': '助詞', 'Function': '功能', 'Rule': '規則', 'Level': '等級',
    'When to Use': '使用時機', 'Dictionary Form': '原形', 'Stem': '詞幹',
    'Conjugated': '變化形', 'Counter': '數量詞（助數詞）', 'Used for': '用於',
    'Vowel': '母音', 'Shape Mnemonic': '形狀記憶法', 'Mouth Position': '嘴型',
    'Time': '時間', 'Register': '敬語程度', 'Used with': '搭配對象',
    'Formal equivalent': '正式對應表達', 'Korean · 한국어': '韓語 · 한국어',
    'Translation · 번역': '翻譯 · 번역', 'Topic marker': '主題助詞',
    'Subject marker': '主語助詞', 'Object marker': '受詞助詞',
    // ── Pronunciation Page ────────────────────────────
    '🔊 Beginner · Lesson 3': '🔊 初級 · 第3課', 'Pronunciation Guide:': '發音指南：',
    '⏱ 50 min read': '⏱ 50分鐘閱讀', '🔖 Pronunciation': '🔖 發音',
    '👁 14,837 views': '👁 14,837 次瀏覽', 'sound change rules': '音變規則',
    'Batchim — Syllable-Final Consonants (받침)': '收音 — 音節末子音（받침）',
    '7 possible sounds': '7種可能的音', 'Sound Group': '音群', 'Written As': '書寫形式',
    'Pronounced As': '發音形式', 'Unreleased stops': '未釋放塞音',
    // ── Syllable Blocks Page ──────────────────────────
    'ㅇ (silent) + Vowel + Final': 'ㅇ（無音）+ 母音 + 尾音', 'inside / no': '裡面 / 不是',
    'The ㅇ Placeholder Rule': 'ㅇ佔位符規則',
    'Vertical vs Horizontal Vowels': '縱型母音 vs 橫型母音',
    'Quick Visual Trick': '快速視覺技巧', 'Building Your First Syllables': '建構你的第一個音節',
    'With vowel ㅏ (a)': '使用母音ㅏ（a）', 'With vowel ㅗ (o)': '使用母音ㅗ（o）',
    'Adding Batchim — The Final Consonant': '加上收音 — 尾音子音',
    '🔷 Batchim Progressions': '🔷 收音變化', 'Add ㄱ at the bottom of 가': '在가的下方加ㄱ',
    'Add ㄴ at the bottom of 나': '在나的下方加ㄴ',
    'Add ㄴ at the bottom of 사 — mountain!': '在사的下方加ㄴ — 山！',
    'Add ㅁ at the bottom of 보 — spring!': '在보的下方加ㅁ — 春！',
    'Here are 12 everyday Korean words built with batchim:': '以下是12個含有收音的日常韓語單字：',
    'Reading Real Korean Words': '閱讀真實的韓語單字',
    '🇰🇷 한국 — Korea': '🇰🇷 한국 — 韓國', '👤 사람 — Person': '👤 사람 — 人',
    '🏫 학교 — School': '🏫 학교 — 學校', '👋 안녕 — Hello / Peace': '👋 안녕 — 你好 / 和平',
    '🙏 감사 — Gratitude / Thank you': '🙏 감사 — 感謝 / 謝謝',
    '❤️ 사랑 — Love': '❤️ 사랑 — 愛', '🎵 음악 — Music': '🎵 음악 — 音樂',
    '🤝 친구 — Friend': '🤝 친구 — 朋友', '👨‍👩‍👧 가족 — Family': '👨‍👩‍👧 가족 — 家族',
    '🌊 바다 — Sea / Ocean': '🌊 바다 — 海洋', 'Practice & Summary': '練習與總結',
    '5 Rules for Korean Syllable Blocks': '韓語音節積木的5個規則',
    '📝 Self-Test: Identify the Components': '📝 自我測試：識別各成分',
    // ── Pronouns Page ─────────────────────────────────
    'Saying \'You\' in Korean': '韓語中如何說「你」',
    'Third Person & We (그·그녀·우리)': '第三人稱與我們（그·그녀·우리）',
    'Demonstrative Pronouns (이·그·저)': '指示代名詞（이·그·저）',
    'Question Pronouns (의문대명사)': '疑問代名詞（의문대명사）',
    'Which pronoun is the polite form of \'I\'?': '哪個代名詞是「我」的敬語形式？',
    'Why do Koreans rarely say 당신 in conversation?': '為什麼韓國人在對話中很少說당신？',
    '우리 엄마 literally means \'our mom\' but is used to mean…': '우리 엄마字面意思是「我們的媽媽」，但實際用來表示…',
    'Which form of \'we\' is more humble and polite, used toward seniors?': '哪種「我們」更謙遜有禮，用於對長輩說話？',
    'Which demonstrative refers to something far from BOTH the speaker AND the listener?': '哪個指示詞指離說話者和聽話者都很遠的東西？',
    '저것 is the formal version. What is the casual version?': '저것是正式版本。那非正式版本是什麼？',
    'Which question pronoun means \'who\'?': '哪個疑問代名詞表示「誰」？',
    'Pronouns Complete!': '代名詞 完成！',
    // ── Emotions Page ─────────────────────────────────
    '😊 Intermediate · Lesson 7': '😊 中級 · 第7課',
    'Learn how Korean emotion adjectives conjugate directly — no \'am/is/are\' needed': '學習韓語情緒形容詞如何直接變化 — 不需要be動詞',
    'Discover culturally unique Korean emotion words like 그립다, 뿌듯하다, and 설레다': '探索韓語文化獨特的情緒詞彙，如그립다、뿌듯하다和설레다',
    'Master key emotion phrases: 보고 싶어요, 감동받았어요, 괜찮아요': '掌握關鍵情緒短語：보고 싶어요、감동받았어요、괜찮아요',
    '4 stages covering vocabulary, in-store phrases, prices, and payment': '4個階段涵蓋詞彙、店內短語、價格與付款',
    'Core Emotions': '核心情緒', 'Expressing Feelings': '表達感受',
    'Complex Emotions': '複雜情緒', 'Emotional Phrases': '情緒短語',
    'Emotions in Korean (감정)': '韓語中的情緒（감정）',
    'Conjugating Emotion Adjectives': '情緒形容詞的變化',
    'More Feeling Words (감정 어휘)': '更多情緒詞彙（감정 어휘）',
    '기분 — Mood & Feeling': '기분 — 心情與感受', 'Deeper Emotions (깊은 감정)': '深層情緒（깊은 감정）',
    'Common Emotional Sentence Patterns': '常見情緒句型',
    'Which word means \'to be happy\'?': '哪個單字表示「高興」？',
    'Which word means \'to be tired\'?': '哪個單字表示「疲累」？',
    '기분이 좋아요 means…': '기분이 좋아요的意思是…', '그립다 means…': '그립다的意思是…',
    '뿌듯하다 means…': '뿌듯하다的意思是…', '보고 싶어요 means…': '보고 싶어요的意思是…',
    'Emotions Complete!': '情緒 完成！',
    // ── Shopping Page ─────────────────────────────────
    '🛒 Intermediate · Lesson 8': '🛒 中級 · 第8課',
    'Learn Korean store vocabulary — 가게, 시장, 백화점, 편의점': '學習韓語商店詞彙 — 가게、시장、백화점、편의점',
    'Master the two most useful phrases: 얼마예요? and 이거 주세요': '掌握兩個最實用的短語：얼마예요?和이거 주세요',
    'Understand prices in 원 (won) and how to bargain at traditional markets': '了解以원（韓元）表示的價格，以及如何在傳統市場議價',
    'Shopping Vocabulary': '購物詞彙', 'In the Store': '在店裡', 'Prices & Numbers': '價格與數字',
    'Transactions': '交易結算', 'Shopping in Korea (쇼핑)': '在韓國購物（쇼핑）',
    'Shopping Item Words (쇼핑 물건)': '購物物品詞彙（쇼핑 물건）',
    'Key Shopping Phrases (쇼핑 표현)': '關鍵購物短語（쇼핑 표현）',
    'Asking About Availability (있어요? / 없어요)': '詢問有無（있어요? / 없어요）',
    'Korean Money & Prices (원)': '韓國貨幣與價格（원）',
    'Payment Methods (결제 방법)': '付款方式（결제 방법）',
    'Which word means \'market\' (traditional outdoor market)?': '哪個單字表示「市場」（傳統戶外市場）？',
    'How do you ask \'How much is it?\' in Korean?': '韓語中如何詢問「多少錢？」？',
    '없어요 means…': '없어요的意思是…', '비싸다 means…': '비싸다的意思是…',
    'Which word means \'change\' (money returned to you after paying)?': '哪個單字表示「找錢」（付款後退還的零錢）？',
    'How do you say \'I\'ll pay by card\'?': '「我用卡付款」怎麼說？', 'Shopping Complete!': '購物 完成！',
    // ── Speech Levels Page ────────────────────────────
    '🗣️ Intermediate · Lesson 6': '🗣️ 中級 · 第6課',
    'Learn the 4 Korean speech levels: formal 합쇼체, polite 해요체, casual 반말, written 문어체': '學習韓語4種敬語等級：正式합쇼체、禮貌해요체、隨意반말、書面문어체',
    'Understand when to use each level — who you\'re talking to and why it matters': '了解何時使用各等級 — 對誰說話，以及為什麼重要',
    'Compare the same phrases across all levels side by side': '並排比較同一短語在所有等級的差異',
    '합쇼체 (Formal)': '합쇼체（正式）', '해요체 (Polite)': '해요체（禮貌）',
    '반말 (Casual)': '반말（隨意）', 'Choosing a Level': '選擇等級',
    'Korean Speech Levels Overview': '韓語敬語等級概覽',
    '합쇼체 — The Formal Register': '합쇼체 — 正式體',
    '합쇼체 Verb Endings (-ㅂ니다/-습니다)': '합쇼체動詞語尾（-ㅂ니다/-습니다）',
    '해요체 — Everyday Polite Speech': '해요체 — 日常禮貌用語',
    '-아요 / -어요 Pattern': '-아요 / -어요規律',
    '반말 — Casual Speech': '반말 — 隨意說話',
    'When to Use 반말 (and When NOT to)': '何時使用반말（以及何時不用）',
    '문어체 — Written/Formal Style': '문어체 — 書面／正式風格',
    'Speech Level Comparison Chart': '敬語等級對照表',
    'Mixing Speech Levels — A Common Mistake': '混用敬語等級 — 常見錯誤',
    '합쇼체 is best described as…': '합쇼체最適合描述為…',
    '해요체 is best described as…': '해요체最適合描述為…',
    'Which form of \'I go\' is 해요체 (everyday polite)?': '「我去」的해요체（日常禮貌）是哪個？',
    'Which greeting is 반말 (casual)?': '哪個問候語是반말（隨意）？',
    'You\'re talking to a stranger your same age on the street. Which level should you use?': '你在街上和同齡陌生人說話，應該使用哪個等級？',
    '감사합니다 is the ___ form of \'thank you\'': '감사합니다是「謝謝」的___形式',
    'In a job interview in Korea, which speech level should you use?': '在韓國的求職面試中，應使用哪種敬語等級？',
    'Speech Levels Complete!': '敬語等級 完成！',

    // ── Vocab Browser ───────────────────────────────────
    'Vocab Browser': '單字瀏覽器',
    'saved to flashcards': '個字卡已儲存',
    'Loading vocabulary…': '載入中…',
    'No words match your search.': '找不到符合的單字。',
    'Failed to load vocabulary.': '載入詞彙失敗。',
    'Search Korean, English, or romanization…': '搜尋韓語、英語或羅馬拼音…',
    '★ Add all in category': '★ 全部加入此分類',
    'Verbs': '動詞',
    'Health': '健康',
    'Media': '媒體',
    'Proverbs': '諺語',
    'Academic': '學術',
    // ── Progress system (streak / counters / resume) ────
    '✓ Correct!': '✓ 正確！',
    '✗ Not quite — try again!': '✗ 差一點 — 再試試！',
    '{n}-day streak': '連續學習 {n} 天',
    '{n} steps today': '今天 {n} 個步驟',
    'Continue': '繼續學習',
    'Step {n} of {m}': '第 {n} / {m} 步',
    'Steps completed': '已完成步驟',
    'Words & phrases learned': '已學單字與片語',
    'Letters & syllables learned': '已學字母與音節',
    'Best streak': '最長連續紀錄',
    'Start Again': '再試一次',
    'Next Lesson →': '下一課 →',
    'Next →': '下一步 →',
    'Progress': '進度',
    'Reset all progress': '重設所有進度',
    '🔥 Daily streak + real progress tracking': '🔥 每日連續學習 + 真實進度追蹤'
  };
  if (window.LangManager) window.LangManager.register('zh-tw', ZH_TW);

/* ── Quiz Traditional Chinese (Taiwan) Translations ─── */
window.QUIZ_ZH_TW = {
  'What sound does ㅏ make?': { qzh: 'ㅏ發什麼音？' },
  'What sound does ㅓ make?': { qzh: 'ㅓ發什麼音？' },
  'What sound does ㅗ make?': { qzh: 'ㅗ發什麼音？' },
  'What sound does ㅜ make?': { qzh: 'ㅜ發什麼音？' },
  'What sound does ㅡ make?': { qzh: 'ㅡ發什麼音？' },
  'What sound does ㅣ make?': { qzh: 'ㅣ發什麼音？' },
  'What sound does ㅑ make?': { qzh: 'ㅑ發什麼音？' },
  'What sound does ㅕ make?': { qzh: 'ㅕ發什麼音？' },
  'What sound does ㅛ make?': { qzh: 'ㅛ發什麼音？' },
  'What sound does ㅠ make?': { qzh: 'ㅠ發什麼音？' },
  'Which vowel makes the sound "a"?': { qzh: '哪個母音發「a」的音？' },
  'Which vowel makes the sound "eo"?': { qzh: '哪個母音發「eo」的音？' },
  'What sound does ㅐ make?': { qzh: 'ㅐ發什麼音？' },
  'What sound does ㅔ make?': { qzh: 'ㅔ發什麼音？' },
  'What sound does ㅘ make?': { qzh: 'ㅘ發什麼音？' },
  'What sound does ㅝ make?': { qzh: 'ㅝ發什麼音？' },
  'What sound does ㅟ make?': { qzh: 'ㅟ發什麼音？' },
  'What sound does ㅢ make?': { qzh: 'ㅢ發什麼音？' },
  'Which vowel is formed by combining ㅗ + ㅏ?': { qzh: 'ㅗ＋ㅏ組合而成的母音是哪個？' },
  'Which vowel is formed by combining ㅜ + ㅣ?': { qzh: 'ㅜ＋ㅣ組合而成的母音是哪個？' },
  'What sound does ㄱ make?': { qzh: 'ㄱ發什麼音？' },
  'What sound does ㄴ make?': { qzh: 'ㄴ發什麼音？' },
  'What sound does ㄷ make?': { qzh: 'ㄷ發什麼音？' },
  'What sound does ㄹ make?': { qzh: 'ㄹ發什麼音？' },
  'What sound does ㅁ make?': { qzh: 'ㅁ發什麼音？' },
  'What sound does ㅂ make?': { qzh: 'ㅂ發什麼音？' },
  'What sound does ㅅ make?': { qzh: 'ㅅ發什麼音？' },
  'What sound does ㅇ make at the START of a syllable?': { qzh: 'ㅇ在音節開頭發什麼音？' },
  'What sound does ㅇ make at the END of a syllable?': { qzh: 'ㅇ在音節結尾發什麼音？' },
  'What sound does ㅈ make?': { qzh: 'ㅈ發什麼音？' },
  'Which is the tensed (double) version of ㄱ?': { qzh: 'ㄱ的緊音（雙重）版本是哪個？' },
  'Which is the tensed (double) version of ㄷ?': { qzh: 'ㄷ的緊音版本是哪個？' },
  'Which is the tensed (double) version of ㅂ?': { qzh: 'ㅂ的緊音版本是哪個？' },
  'Which is the aspirated version of ㄱ?': { qzh: 'ㄱ的送氣音版本是哪個？' },
  'Which is the aspirated version of ㄷ?': { qzh: 'ㄷ的送氣音版本是哪個？' },
  'Which is the aspirated version of ㅂ?': { qzh: 'ㅂ的送氣音版本是哪個？' },
  'What sound does ㄲ make?': { qzh: 'ㄲ發什麼音？' },
  'What sound does ㅋ make?': { qzh: 'ㅋ發什麼音？' },
  'What sound does ㅎ make?': { qzh: 'ㅎ發什麼音？' },
  'The compound batchim ㄳ is made of which two consonants?': { qzh: '複合收音ㄳ由哪兩個子音組成？' },
  '안녕하세요 is read as?': { qzh: '안녕하세요怎麼讀？' },
  'Which word means "love"?': { qzh: '哪個單字表示「愛」？' },
  '감사합니다 is read as?': { qzh: '감사합니다怎麼讀？' },
  'Which word means "school"?': { qzh: '哪個單字表示「學校」？' },
  'What does 물 mean?': { qzh: '물是什麼意思？', choiceszh: ['水', '牛奶', '飯', '食物'] },
  'What does 밥 mean?': { qzh: '밥是什麼意思？', choiceszh: ['飯', '魚', '麵包', '麵'] },
  'Which word means "person / people"?': { qzh: '哪個單字表示「人」？' },
  '한국 is the Korean word for?': { qzh: '한국是什麼意思？', choiceszh: ['韓國', '日本', '中國', '美國'] },
  'What does 집 mean?': { qzh: '집是什麼意思？', choiceszh: ['家', '街道', '城市', '大樓'] },
  'Which word means "friend"?': { qzh: '哪個單字表示「朋友」？' },
  'What does 하늘 mean?': { qzh: '하늘是什麼意思？', choiceszh: ['天空', '太陽', '星星', '月亮'] },
  'Which word means "sea / ocean"?': { qzh: '哪個單字表示「海洋」？' },
  '화이팅 / 파이팅 is an expression meaning?': { qzh: '화이팅／파이팅是什麼意思？', choiceszh: ['加油！', '我愛你！', '好吃！', '謝謝！'] },
  'What does 맛있어요 mean?': { qzh: '맛있어요是什麼意思？', choiceszh: ['好吃', '肚子餓', '吃飽了', '辣'] },
  'Which word means "heart / mind"?': { qzh: '哪個單字表示「心」？' },
  'In Hangul syllable blocks, 받침 refers to?': { qzh: '韓文音節積木中，받침指的是什麼？', choiceszh: ['尾音（最後的子音）', '初音（開頭的子音）', '母音', '音節界線'] },
  'What does 영어 mean?': { qzh: '영어是什麼意思？', choiceszh: ['英語', '韓語', '日語', '中文'] },
  'Which word means "tree"?': { qzh: '哪個單字表示「樹」？' },
  'Which word means "to be happy"?': { qzh: '哪個單字表示「高興」？' },
  'Which word means "to be tired"?': { qzh: '哪個單字表示「疲累」？' },
  'Which word means "market" (traditional outdoor market)?': { qzh: '哪個單字表示「市場」（傳統戶外市場）？' },
  "How do you ask 'How much is it?' in Korean?": { qzh: '韓語中如何詢問「多少錢？」？' },
  "How do you say 'I'll pay by card'?": { qzh: '「我用卡付款」怎麼說？' },
  "Which pronoun is the polite form of 'I'?": { qzh: '哪個代名詞是「我」的敬語形式？' },
  'Which demonstrative refers to something far from BOTH the speaker AND the listener?': { qzh: '哪個指示詞指離說話者和聽話者都很遠的東西？' },
  "Which question pronoun means 'who'?": { qzh: '哪個疑問代名詞表示「誰」？' },
  '합쇼체 is best described as…': { qzh: '합쇼체最適合描述為…' },
  '해요체 is best described as…': { qzh: '해요체最適合描述為…' },
  "Which form of 'I go' is 해요체 (everyday polite)?": { qzh: '「我去」的해요체（日常禮貌）是哪個？' },
  'Which greeting is 반말 (casual)?': { qzh: '哪個問候語是반말（隨意）？' },
  "You're talking to a stranger your same age on the street. Which level should you use?": { qzh: '你在街上和同齡陌生人說話，應該使用哪個等級？' },
  "감사합니다 is the ___ form of 'thank you'": { qzh: '감사합니다是「謝謝」的___形式' },
  'In a job interview in Korea, which speech level should you use?': { qzh: '在韓國的求職面試中，應使用哪種敬語等級？' },
};

})();
